<?php
    /**
     * 试题分析及与之对应的评价 
     */

    $clsq_all['fields'] = isset($clsq_all['fields']) ? $clsq_all['fields'] : array();
    $clsq_all['desc_data'] = isset($clsq_all['desc_data']) ? $clsq_all['desc_data'] : array();
?>

<?php if (count($clsq_all['flash_data']['data'])) {?>
    <?php 
        $flash_data = array();
        foreach ($clsq_all['flash_data']['data'] as $key => $item)
        {
            $flash_data[] = array('name' => $key, 'data' => array_values($item));
        }
        
        $max_score = $clsq_all['max_score'];
        if ($max_score > 0) {
            $max_score = ceil($max_score) + 1;
        }
    ?>

    <div id="flash_container_clsq_<?=$t_subject_id?>"  class="cls_row indent_25"></div>
    <script type="text/javascript">
    $(function () {
        //试题分析及与之对应的评价 曲线图
        $('#flash_container_clsq_<?=$t_subject_id?>').highcharts({
            chart: {
                height: '1000',
                type: 'line',
                inverted: true
            },
            title: {
                text: '试题得分折线图'
            },
            plotOptions: {
                line: {
                    dataLabels: {
                        enabled: false
                    },
                    enableMouseTracking: false  //关闭动画特效,使其在pdf中线条不会变粗
                }
            },
            xAxis: {
                categories: eval("("+'<?php echo json_encode($clsq_all['flash_data']['field']); ?>'+")"),
                labels: {
                    rotation : 0.5,//坐标旋转角度 为0：表示横放置
                    align : 'right'
                }
            },
            yAxis:[{
                title:'',
                <?php if($max_score > 0) {?>
                    max:<?=$max_score?>, // 定义Y轴 最大值  
                    min:0 // 定义最小值 
                <?php } else {?>
                    tickPositions: [0]
                <?php } ?>
                },
                {
                title:'',
                <?php if($max_score > 0) {?>
                    max:<?=$max_score?>, // 定义Y轴 最大值  
                    min:0, // 定义最小值
                <?php } else {?>
                    tickPositions: [0],
                <?php }?>
                opposite:true
            }],
            tooltip: {
                valueSuffix: ''
            },
            legend: {
                layout: 'vertical',
                align: 'right',
                verticalAlign: 'middle',
                borderWidth: 0
            },
            colors: ['#4F81BD','#F15A24','#8CC63F','#93489B','#FBB03B','#00A99D','#4C5260','#959FB1','#90B9EA','#F7AA8E','#B9E881','#DE98E5','#F5CB8E','#67D8CE','#A0B7F2'],
            series: eval("("+'<?php echo json_encode($flash_data); ?>'+")")
        });
    });
    </script>
<?php } ?>

<?php if (count($clsq_all['desc_data'])) {?>
    <table class="mb10 cls_row table_header indent_25" id="table_clsq_ss_1">
        <tr>
            <?php foreach ($clsq_all['fields'] as $val) {?>
            <th width="20%"><?=$val?></th>
            <?php }?>
        </tr>
    </table>

    <?php $auto_key  = 0;?>
    <?php foreach ($clsq_all['desc_data'] as $item) {?>
        <?php $auto_key++;?>
        <table class=" cls_row cls_table indent_25" <?php if (!$no_paging) {?>ref_title_id="table_clsq_ss_1"<?php }?>>
            <tr <?php echo $auto_key%2==0 ? 'class="bgc"' : '';?>>
                    <th width="20%"><?=$item['id'];?></th>
                    <td width="20%"><?=$item['difficulty'];?></td>
                    <td width="20%"><?=$item['full_score'];?></td>
                    <td width="20%" <?php if ($item['test_score'] != $item['expect_score']) {?>style="color:<?=$item['test_score'] > $item['expect_score'] ? 'green' : 'red'?>"<?php }?>><?=$item['test_score'];?></td>
                    <td width="20%"><?=$item['expect_score'];?></td>
            </tr>
        </table>
   <?php } ?>
<?php } ?>