<?php $this->load->view('common/header');?>
<div id="body">   
  <form name="Frm_info" method="POST" action="<?=site_url('admin/knowledge/update')?>">
  <input type="hidden" name="id" value="<?=$row['id']?>" />
  <input type="hidden" name="pid" value="<?=$row['pid']?>" />
  <div class="space">
    <div class="subtitle">编辑知识点</div>
    <table class="maintable" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="16%" class="altbg1">知识点名称</td>        
        <td>
            <input type="text" name="knowledge_name" class="txtbox" value="<?=$row['knowledge_name']?>">
        </td>
      </tr>
      <tr>
        <td width="16%" class="altbg1">所属学科</td>
        <td>
          <?php if($row['pid']): ?>
          <input type="hidden" name="subject_id" value="<?=$parent['subject_id']?>" />
          <?=$subjects[$parent['subject_id']]?>
          <?php else: ?>
            <input type="hidden" name="old_subject_id" value="<?=$row['subject_id']?>" />
            <select name="subject_id">
                <option value="0">--学科--</option>
                <?php foreach($subjects as $k => $v): ?>
                <option value="<?=$k?>"<?=$k==$row['subject_id']?' selected':''?>><?=$v?></option>
                <?php endforeach; ?>
            </select>
          <?php endif; ?>
        </td>
      </tr>
    </table>
  </div>
  <center> 
    <input type="submit" name="dosubmit" value=" 提交 " class="btn" />
    &nbsp;&nbsp;
    <input type="button" name="" value=" 返回 " onclick="history.go(-1);" class="btn" />
  </center>   
  </form>
</div>
<?php $this->load->view('common/footer');?>