<?php $this->load->view('common/header');?>

<script>
var cloze_type = <?=$question['p_type']?>
</script>
<?php 
    static_global(array('js/jquery/plugin/validate/jquery.validate.min.js', 
                        'js/jquery/plugin/validate/additional-methods.min.js',
                        
                        'js/jquery/plugin/blockUi.js',
                        'js/jquery/plugin/jquery.json-2.4.min.js',
                        		
                        'js/jquery/plugin/validate/messages_zh.js',
                        'js/third_party/ueditor/ueditor.config.question.js',
                        'js/third_party/ueditor/ueditor.all.min.js',
                        'js/third_party/ueditor/lang/zh-cn/zh-cn.js'));

    static_js(array('admin/question/question.js', 
    				'admin/question/question_validate.js',
                    'admin/question/pic_delete.js'));
?>

<script>
var is_question_mode = 1;//用于区分知识点选择框中的认知过程
var is_group  = false;
var knowledge_ids = [<?=trim($question['knowledge'],',')?>];
var knowledge_know_process = eval("("+'<?php echo json_encode($know_processes); ?>'+")");

var ajax_url_knowledge = '<?=site_url('admin/common/knowledge_all')?>';
var ajax_url_knowledge_select = '<?=site_url('admin/common/knowledge_select')?>';
var ajax_url_knowledge_init = '<?=site_url('admin/common/knowledge_init')?>';
</script>

<script>
$(document).ready(function(){
    $('input:radio[name=qtype]').unbind('click').click(function(){
        toggle_qtype();
    });
    toggle_qtype();
});

//解决ueditor编辑器放table里在360兼容模式下显示不了。
$(function() {
	//题目编辑器
	var editor = UE.getEditor('question_title');
	window.question_editor = editor;

	//选项编辑器
	$("textarea[name='option[]']").each(function(i,item){
		$(this).attr('id','option_'+i);
		UE.getEditor('option_'+i,{
			enterTag:'<br>',
			initialFrameWidth:720,
			initialFrameHeight:60			
		});
	});
});
</script>
<style>
.height_light {
    border:1px solid #f00;
    padding:2px 0 2px 0;
    margin:2px 0 2px 0;
}
.div_option{
    border-bottom:1px solid #CCCCFF;
    padding:5px;
}
</style>
<div id="body">
  <form name="Frm_info" class="validate" id="question_form" method="POST" action="<?=site_url('admin/question_external/update_cloze_question')?>" enctype="multipart/form-data" onsubmit="return false;">
  <input type="hidden" name="act" id="act" value="<?=$act?>" />
  <?php if($act == 'edit'):?>
  <input type="hidden" name="ques_id" value="<?=$question['ques_id']?>" />
  <?php endif;?>
  <input type="hidden" name="parent_id" value="<?=$question['parent_id']?>" />  
  <div class="space">
    <div class="subtitle"><?=$act=='add'?'添加':'编辑'?>完形填空试题</div> 
    <table class="maintable" id="table_basic" border="0" cellspacing="0" cellpadding="0">
        <tr>
            <td colspan="2" class="altbg2" style="text-align: center;">
                题目信息 [<font class="font_4">选填</font>]
            </td>
        </tr>
        <tr style="display: none;">
        	<td>
        		<input type="hidden" name="subject_id" id="subject_id" value="<?php echo $question['subject_id'];?>"/>
        	</td>
        </tr>
        <tr>
            <td class="altbg1">知识点</td>
            <td>
             <div style="position:absolute;top:-1000px;left:200px;"><input type="checkbox" name="knowledge_id[]" value="" /></div>
             <div id="knowledge_list"></div>
             <input type="hidden" name="knowledge_ids" id="knowledge_ids" value="<?=trim($question['knowledge'],',')?>" />
             <button id="knowledge_select" class="btn2" type="button">点击选择</button><font color="red">*</font>
             <label for="knowledge_id[]" class="error" style="display:none"></label>
            </td>
        </tr>
        <tr>
            <td class="altbg1" width="10%">序号</td>
            <td>
            <input type="text" name="sort" id="sort" value="<?=$question['sort']?>" size="2" maxlength="2">
            </td>
        </tr>
        <tr style="display: none;">
            <td class="altbg1" width="10%">题目</td>
            <td>
				<script id="question_title" name="title" type="text/plain" style="width:700px;height:320px;"><?=$question['title']?></script>                
                <div id="input_answer_notice">
                填空题说明：<br/>
                1, 在需要设置填空项的地方，输入【中文括号加数字】，例如：（1），（2）。<br/>
                2, 多个填空项，请按数字顺序填写；只有一个填空项，可以不填写数字。
                </div> 
            </td>
        </tr>
        <?php $this->load->view('question/options');?>
    </table>
  </div>
  <center> 
    <input type="submit" name="dosubmit" value=" 提交 " class="btn" />
    &nbsp;&nbsp;
    <input type="button" name="back" value=" 返回 " onclick="history.go(-1);" class="btn" />
  </center>   
  </form>
</div>
<?php $this->load->view('common/footer');?>