<?php $this->load->view('common/header', array('load_dialog_css' => true));?>

<?php static_global(array('js/datepicker/wdatepicker.js','js/jquery/plugin/blockUi.js'));?>
<?php static_js(array('admin/question/question.js', 'admin/question/question_list.js', 'admin/exam_rule/exam_rule.js'));?>

<?php $this->load->view('recycle/recycle.phtml');?>

<script language="javascript">
var class_ids = [<?=implode(',',$search['class_id'])?>];
var skill_ids = [<?=implode(',',$search['skill_id'])?>];
var knowledge_ids = [<?php echo $search['knowledge_ids'];?>];
var method_tactic_ids = [<?php echo $search['method_tactic_ids'];?>];

var ajax_url_class = '<?=site_url('admin/common/question_class')?>';
var ajax_url_skill = '<?=site_url('admin/common/skill')?>';
var ajax_url_knowledge = '<?=site_url('admin/common/knowledge')?>';
var ajax_url_knowledge_select = '<?=site_url('admin/common/knowledge_select')?>';
var ajax_url_knowledge_init = '<?=site_url('admin/common/knowledge_init')?>';

var ajax_url_method_tactic = '<?=site_url('admin/common/method_tactic_all')?>';
var ajax_url_method_tactic_select = '<?=site_url('admin/common/method_tactic_select')?>';
var ajax_url_method_tactic_init = '<?=site_url('admin/common/method_tactic_init')?>';

function check_form(form) {
    if (checkbox_check('ids[]')) {
        var op = $('#batch_op').val();
        if (op == '') {
            alert('请选择操作类型');
            return false;
        } else if (op == 'relate') {
            var relate_ques_id = parseInt($('#relate_ques_id').val());
            if (isNaN(relate_ques_id)) {
                alert('请填写被关联试题ID.');
                return false;
            }
        }
        var action = $('#batch_op').find('option[value='+op+']').attr('op');
        form.action = action;
        return true;
    }
    return false;
}

$(document).ready(function(){
    $('.ques_title').dblclick(function(){
        $(this).find('div').first().toggleClass('line_18');
    });

    $('.ques_handle_td').click(function(e){
        var is_hidden = true;
        $(this).find('div[class=ques_handle] > a').each(function(){
            if ($(this).css('display') == 'none')
            {
            	is_hidden = false;
                return;
            }
        });
        
        is_hidden && $(this).find('div').first().toggleClass('line_18');
    });
    
    $('#start_grade,#end_grade').change(function(){
        //set_question_class();
        //联动类型
        set_question_class_checkbox();
    });
    $('#subject_id').change(function(){
        set_skill();
        set_knowledge_cascade(0, 'knowledge_pid');

        //联动类型
        set_question_class_checkbox();
    });
    set_question_class_checkbox();

    $('#knowledge_pid').change(function(){
        set_knowledge_cascade($(this).val(), 'knowledge_id');
    });
    $('#batch_op').change(function(){
        set_batch_option();
    });

    $('#knowledge_select').click(function(){
        knowledge_select();
    });

    // 对已选择的知识点操作，调整隐藏项knowledge_ids的值
    $('#knowledge_list').on('click', 'input:checkbox', function(){
        var objs = $('#knowledge_list').find('input:checkbox');
        var ids = '';
        for (var i=0; i<objs.length; i++) {
            if (objs[i].checked) {
                ids += (ids ? ',' : '') + objs[i].value;
            }
        }
        $('#knowledge_ids').val(ids);
    });

    //方法策略
    $('#method_tactic_select').click(function(){
    	method_tactic_select();
    });
    // 对已选择的方法策略操作，调整隐藏项knowledge_ids的值
    $('#method_tactic_list').on('click', 'input:checkbox', function(){
        var objs = $('#method_tactic_list').find('input:checkbox');
        var ids = '';
        for (var i=0; i<objs.length; i++) {
            if (objs[i].checked) {
                ids += (ids ? ',' : '') + objs[i].value;
            }
        }
        $('#method_tactic_ids').val(ids);
    });

    $('#subject_id').change(function(){
    	var subject_id = $('#subject_id').val();
    	if (subject_id == 11)
    	{
    		$("#subject_id_list input[name='subject_str[]']").removeAttr('disabled');
    	    $('#subject_id_list').show();
    	}
    	else
    	{
    		$('#subject_id_list').hide();
    		$("#subject_id_list input[name='subject_str[]']").attr('disabled', 'disabled');
    	}
    });

    set_batch_option();
    init_knowledge();
    init_method_tactic();
});

function set_knowledge_cascade(pid, target) {
    var subject_id = $('#subject_id').val();
    if (subject_id == '') return;
    if (pid.length == 0) {
        $('#'+target)[0].length = 1;
        return;
    }
    $.post(
        ajax_url_knowledge,
        {subject_id:subject_id, pid:pid},
        function(data){
            var target_obj = $('#'+target)[0];
            if (document.all) {
                target_obj.fireEvent("onchange")
            } else {
                var evt = document.createEvent("HTMLEvents");
                evt.initEvent('change', true, true);
                target_obj.dispatchEvent(evt)
            }

            var str = '<option value="">=请选择=</option>';
            for (var i=0; i<data.length; i++) {
                str += '<option value="'+data[i]['id']+'">'+data[i]['knowledge_name']+'('+data[i]['ques_num']+')</option>';
            }
            $('#'+target).html(str);
        },
        'json'
    );
}

function set_batch_option() {
    var op = $('#batch_op').val();
    if (op == 'relate') {
        $('#batch_extend').show();
    } else {
        $('#batch_extend').hide();
    }
}

//年级跟类型联动
function set_question_class_option() {
    var start_grade = $('#start_grade').val();
    var end_grade = $('#end_grade').val();
    if ( !start_grade ) return;
    $.post(
        ajax_url_class,
        {grade_id:grade_id},
        function(data){
            if (typeof(class_id) == 'undefined') class_id = 0;
            var str = '';
            for (var i=0; i<data.length; i++) {
                var selected = js_class_id==data[i]['class_id'] ? ' selected' : '';
                str += '<option value="'+data[i]['class_id']+'"'+selected+'>'+data[i]['class_name']+'</option>';
            }
            $('#class_id')[0].length = 1;
            $('#class_id').append(str);
        },
        'json'
    );
}

function set_disable(ques_id, status)
{
	if (!ques_id) return;

	if (!confirm('您确定要执行操作？'))
	{
	    return;
	}

	$.getJSON('/admin/question_external/set_ques_status',{ques_id:ques_id,'status':status},function(data){
	    if (data.status == true)
	    {
	        $('#set_ques_status_'+ques_id).attr('onclick',"set_disable("+ques_id+", "+Math.abs(status - 2)+");");
	        $('#set_ques_status_'+ques_id).html(((status == 2) ? "解禁" : "禁用"));
		}
	});
}

<?/*?>
var group_type_list = <?=json_encode($group_type_list);?>;
function change_group_type(pid)
{
	var html2 = '<select name="group_type_id"><option>-请选择-</option>';
    var group_type_pid = $('#group_type_pid').val();
    for(var i = 0; i < group_type_list.length; i++)
    {
        if (group_type_list[i]['id'] == pid)
        {
        	var children = group_type_list[i]['childlist'];
        	for(var j = 0; j < children.length; j++)
            {
        			html2 += '<option value="' + children[j]['id'] + '">' + children[j]['group_type_name'] + '</option>';
            }
        }
    }
    html2 += '</select>';
    $('#group_type_sel2').html(html2);
}

function set_group_type()
{
    var group_type_pid = '<?=$search['group_type_pid']?>';
    var group_type_id = '<?=$search['group_type_id']?>';
    var html1 = '<select name="group_type_pid" onchange="change_group_type($(this).val());"><option>-请选择-</option>';
    var html2 = '<select name="group_type_id"><option>-请选择-</option>';
    for(var i = 0; i < group_type_list.length; i++)
    {
        if (group_type_list[i]['id'] == group_type_pid)
        {
        	html1 += '<option value="' + group_type_pid + '" selected>' + group_type_list[i]['group_type_name'] + '</option>';
        	var children = group_type_list[i]['childlist'];
        	for(var j = 0; j < children.length; j++)
            {
        		if (children[j]['id'] == group_type_id)
                {
        			html2 += '<option value="' + group_type_id + '" selected>' + children[j]['group_type_name'] + '</option>';
                }
        		else
        		{
        			html2 += '<option value="' + children[j]['id'] + '">' + children[j]['group_type_name'] + '</option>';
        		}
            }
        }
        else
        {
        	html1 += '<option value="' + group_type_list[i]['id'] + '">' + group_type_list[i]['group_type_name'] + '</option>'
        }
    }

    html1 += '</select">';
    html2 += '</select>';


    $('#group_type_sel').html(html1);
    $('#group_type_sel2').html(html2);
}
<?*/?>
</script>

<style>
<!--
.maintable tr.has_skill td{
	color:#6F5D23;
}
.ques_handle_td .line_18{ overflow:hidden; text-overflow:ellipsis; white-space:nowrap;}
.ques_handle {width:180px;}
.ques_handle a {width:auto;}
textarea {width:195px;}
-->
</style>


<div id="body">
  <form name="frm_cpuser_list" action="<?=site_url('admin/question_external/batch_delete')?>" method="POST" onsubmit="return check_form(this)">
  <div class="space">
    <div class="subtitle">
    <?php if($mode=='trash'):?>
    试题回收站
    <?php else:?>
    <?php if ($priv_manage) {?>
        <?php if(empty($relate_ques_id)):?>
            <?php if ($is_english_admin) {?>
                <a class="menu" href="<?=site_url('admin/question_external/addSentence')?>">添加连词成句</a>
                <a class="menu" href="<?=site_url('admin/question_external/add/?type=7')?>">添加翻译题</a>
                <a class="menu" href="<?=site_url('admin/question_external/add_diction')?>">添加选词填空</a>
                <a class="menu" href="<?=site_url('admin/question_external/add_match')?>">添加匹配题</a>
                <a class="menu" href="<?=site_url('admin/question_external/add_cloze')?>">添加完形填空</a>
                <a class="menu" href="<?=site_url('admin/question_external/add_blank')?>">添加阅读填空</a>
                <a class="menu" href="<?=site_url('admin/question_external/add_correct')?>">添加改错</a>
                <a class="menu" href="<?=site_url('admin/question_external/add_listening')?>">添加听力</a>
            <?php }?>
            <a class="menu" href="<?=site_url('admin/question_external/add_group')?>">添加题组</a>
            <a class="menu" href="<?=site_url('admin/question_external/add')?>">添加试题</a>
        <?php else:?>
            <a class="menu" href="<?=site_url('admin/question_external/add_group/'.$relate_ques_id)?>">添加关联题组</a>
            <a class="menu" href="<?=site_url('admin/question_external/add/'.$relate_ques_id)?>">添加关联试题</a>
        <?php endif;?>
    <?php } ?>
    试题管理<?php /*?>(<font color="red">注:列表中 标注 <font color="#6F5D23">颜色</font> 的有关联技能的试题</font>)<?php */?>
    <?php endif;?>
    </div>
    <table class="maintable" border="0" cellspacing="0" cellpadding="0">
      <tr class="altbg1">
        <td width="50">&nbsp;&nbsp;ID</td>
        <td width="400">题目（双击展开/收缩）</td>
        <td width="60">题型</td>
        <td width="80">考试方式</td>
        <td width="50">学科</td>
        <td width="140">类型</td>
        <td width="120">年级</td>
        <td width="120">录入时间</td>
        <td width="80">录入人员</td>
        <td width="195">操作（单击空白展开/收缩）</td>
      </tr>
      <?php if($list):?>
      <?php foreach($list as $val):?>
      <?php
      		$q_type = '';
		?>
      <tr>
        <td><?php if ($priv_manage) {?><input type="checkbox" name="ids[]" value="<?=$val['ques_id']?>" /><?php } ?><?=$val['ques_id']?></td>
        <td title="双击展开" class="ques_title">
            <div class="line_18" style="width: 400px;">
                <?=strip_tags($val['title'])?>
            </div>
        </td>
        <td>
          <?=$val['qtype']?>
          <?php $q_type = $val['qtype'];?>
        </td>
        <td>
        <?php $test_way = C('test_way')?>
        <?php if ($val['test_way'] < 3) {?>
            <?=$test_way[$val['test_way']]?>
        <?php } else {?>
            <?=implode(' ', $test_way)?>
        <?php }?>
        </td>
        <td><?=$val['subject_name']?></td>
        <td><?=$val['class_name']?></td>
        <td>[<?=$val['start_grade']?>] - [<?=$val['end_grade']?>]</td>
        <td><?=$val['addtime']?></td>
        <td><?=$val['realname']?></td>
        <td class="ques_handle_td">
        <div class="ques_handle line_18">
          <?php if($val['is_parent']):?>

        <!-- 有编辑权限 -->
              <?php if ($val['has_edit_power']) {?>

            <!--  正在考或者考过-->
    	          <?php if ($val['be_tested']) {?>

        	          <font style="color:#999;text-decoration:line-through;" title="该试题已经被考生考过 或者 正在被考中,因此无法操作">管理</font>


        	          <font style="color:#999;text-decoration:line-through;" title="该试题已经被考生考过 或者 正在被考中,因此无法编辑">编辑</font>
        	      <!--不在回收站  -->

        	          <?php if($mode!='trash'):?>

        	          <font style="color:#999;text-decoration:line-through;" title="该试题已经被考生考过 或者 正在被考中,因此无法操作">复制</font>

        	          <?php endif;?>


        	          <?php if ($val['is_delete'] == 0) {?>

    	              <a href="javascript:void(0);" onclick="set_disable('<?=$val['ques_id']?>','2');" id="set_ques_status_<?=$val['ques_id']?>">禁用</a>

    	              <?php } elseif($val['is_delete'] == 2) {?>

    	              <a href="javascript:void(0);" onclick="set_disable('<?=$val['ques_id']?>','0');" id="set_ques_status_<?=$val['ques_id']?>">解禁</a>

    	              <?php }?>

        	      <?php } else {?>

                    <!-- 未考过 -->
        	           <?php if ($val['type'] == 4) {?>
            	           <a href="<?=site_url('admin/question_external/cloze/'.$val['ques_id'])?>">管理</a>
            	           <a href="<?=site_url('admin/question_external/edit_cloze/'.$val['ques_id'])?>">编辑</a>
            	          <?php if($mode!='trash'):?>
            	          <a href="<?=site_url('admin/question_external/add_cloze/?copy='.$val['ques_id'])?>">复制</a>
            	          <?php endif;?>

            	       <?php } elseif ($val['type'] == 5) {?>
            	           <a href="<?=site_url('admin/question_external/match/'.$val['ques_id'])?>">管理</a>
            	           <a href="<?=site_url('admin/question_external/edit_match/'.$val['ques_id'])?>">编辑</a>
            	          <?php if($mode!='trash'):?>
            	          <a href="<?=site_url('admin/question_external/add_match/?copy='.$val['ques_id'])?>">复制</a>
            	          <?php endif;?>

            	      <?php } elseif ($val['type'] == 6) {?>

            	           <a href="<?=site_url('admin/question_external/diction/'.$val['ques_id'])?>">管理</a>
            	           <a href="<?=site_url('admin/question_external/edit_diction/'.$val['ques_id'])?>">编辑</a>
            	          <?php if($mode!='trash'):?>
            	          <a href="<?=site_url('admin/question_external/add_diction/?copy='.$val['ques_id'])?>">复制</a>
            	          <?php endif;?>

            	      <?php } elseif ($val['type'] == 8) {?>

                           <a href="<?=site_url('admin/question_external/blank/'.$val['ques_id'])?>">管理</a>
                           <a href="<?=site_url('admin/question_external/edit_blank/'.$val['ques_id'])?>">编辑</a>

                          <?php if($mode!='trash'):?>

                          <a href="<?=site_url('admin/question_external/add_blank/?copy='.$val['ques_id'])?>">复制</a>
                          <?php endif;?>
                     <?php } elseif ($val['type'] == 12) {?>

                           <a href="<?=site_url('admin/question_external/listening/'.$val['ques_id'])?>">管理</a>
                           <a href="<?=site_url('admin/question_external/edit_listening/'.$val['ques_id'])?>">编辑</a>

                          <?php if($mode!='trash'):?>

                          <a href="<?=site_url('admin/question_external/add_listening/?copy='.$val['ques_id'])?>">复制</a>
                          <?php endif;?>

                       <?php } elseif ($val['type'] == 13) {?>

                           <a href="<?=site_url('admin/question_external/correct/'.$val['ques_id'])?>">管理</a>
                           <a href="<?=site_url('admin/question_external/edit_correct/'.$val['ques_id'])?>">编辑</a>

                          <?php if($mode!='trash'):?>

                          <a href="<?=site_url('admin/question_external/add_correct/?copy='.$val['ques_id'])?>">复制</a>
                          <?php endif;?>

        	           <?php } else {?>

            	          <a href="<?=site_url('admin/question_external/group/'.$val['ques_id'])?>">管理</a>
            	          <a href="<?=site_url('admin/question_external/edit_group/'.$val['ques_id'])?>">编辑</a>

            	          <?php if($mode!='trash'):?>

            	          <a href="<?=site_url('admin/question_external/add_group/?copy='.$val['ques_id'])?>">复制</a>

            	          <?php endif;?>
        	          <?php }?>
    	          <?php } ?>
	          <?php }?>

	         <!--end  -->

	          <a href="<?=site_url('admin/question_external/preview/'.$val['ques_id'])?>" target="_blank">预览</a>

          <?php else:?>

	          <a href="<?=site_url('admin/question_external/preview/'.$val['ques_id'])?>" target="_blank">预览</a>
	          <?php if ($val['has_edit_power']) {?>
    	          <?php if ($val['be_tested']) {?>
    	          <font style="color:#999;text-decoration:line-through;" title="该试题已经被考生考过 或者 正在被考中,因此无法编辑">编辑</font>
    	          <?php if($mode!='trash'):?>
    	          <font style="color:#999;text-decoration:line-through;" title="该试题已经被考生考过 或者 正在被考中,因此无法操作">复制</font>
    	          <?php endif;?>
    	          <?php if ($val['is_delete'] == 0) {?>
	              <a href="javascript:void(0);" onclick="set_disable('<?=$val['ques_id']?>','2');" id="set_ques_status_<?=$val['ques_id']?>">禁用</a>
	              <?php } elseif($val['is_delete'] == 2) {?>
	              <a href="javascript:void(0);" onclick="set_disable('<?=$val['ques_id']?>','0');" id="set_ques_status_<?=$val['ques_id']?>">解禁</a>
	              <?php }?>
    	          <?php } else {?>
    	          <a href="<?=site_url('admin/question_external/edit/'.$val['ques_id'])?>">编辑</a>
    	          <?php if($mode!='trash'):?>
    	          <a href="<?=site_url('admin/question_external/add/?type='.$val['type'].'&copy='.$val['ques_id'])?>">复制</a>
    	          <?php endif;?>
    	          <?php } ?>
	          <?php } ?>

          <?php endif;?>


          <?php if ($val['has_edit_power']) {?>
          <?php if($mode=='trash'):?>
测试题为真题
	          <a href="<?=site_url('admin/question_external/restore/'.$val['ques_id'])?>" onclick="return confirm('您确定要还原么？');">还原</a>
	          <?php if ($val['be_tested']) {?>
	          <font style="color:#999;text-decoration:line-through;" title="该试题已经被考生考过 或者 正在被考中,因此无法操作">移除</font>
	          <?php } else {?>
	          <a href="<?=site_url('admin/question_external/remove/'.$val['ques_id'])?>" onclick="return confirm('您确定要彻底删除么？');">移除</a>
	          <?php } ?>

          <?php else:?>

	          <?php if($priv_delete):?>
		          <?php if (!$val['be_tested']) {?>
		          <?php $remove_id = $val['ques_id'];?>
		          <a class="a_delete" rel="<?php echo $remove_id;?>" id="a_delete_<?php echo $remove_id;?>" href="###">删除</a>
		          <div class="delete_box display_none" id="delete_box_<?php echo $remove_id;?>">
		        			<textarea title="请输入 删除原因" placeholder="请输入 删除原因" name="note" id="txt_reason_<?php echo $remove_id;?>"></textarea>
		        			<input type="button" value="保存" class="btn btn_submit_delete" delete_id="<?php echo $remove_id;?>" post_url="<?=site_url('admin/question_external/delete/'.$remove_id)?>" rel="<?php echo $remove_id;?>" id="btn_submit_<?php echo $remove_id;?>" style="margin-top:4px;"/>
		        			<input type="button" rel="<?php echo $remove_id;?>" id="btn_cancle_<?php echo $remove_id;?>" value="取消" class="btn btn_cancle_delete" />
				  </div>
		          <?php } ?>

	          <?php endif;?>
          <?php endif;?>

          <?php if($val['group_id']):?>
	          <?php if ($val['be_tested']) {?>
	          <font style="color:#999;text-decoration:line-through;" title="该试题已经被考生考过 或者 正在被考中,因此无法关联组">关联组</font>
	          <?php } else {?>
	          <a href="<?=site_url('admin/relate_group/group/'.$val['group_id'])?>">关联组[<?=$val['group_id']?>]</a>
	          <?php }?>
          <?php endif;?>
          <!-- 设置考过的原创题目为真题 -->

                  	        <?php if ($val['be_tested_1']):?>

        	          <?php $remove_id=$val['ques_id'];?>
        	          		          <a class="a_original" rel="<?php echo $remove_id;?>" id="a_original_<?php echo $remove_id;?>" href="###">

        	          		      <?php if($val['is_original']==1):?>
        	          		          设置真题
        	          		          <?php else:?>
        	          		           设置原创
        	          		           <?php endif;?>
        	          		          </a>

		          <div class="original_box display_none" id="original_box_<?php echo $remove_id;?>">

		        			    <?php if($val['is_original']==1):?>

		        			   <label for="exam_year">年份：</label>
                <input type="text"  id="related_<?php echo $remove_id;?>"  class="txtbox1" name="exam_year" onclick="WdatePicker({dateFmt:'yyyy'});" value="<?php echo $val['exam_year'] ?>" readonly/>
            <?php else:?>

        	       <input type="text" id="related_<?php echo $remove_id;?>" class="txtbox2" name="related" value="<?php echo $val['related']; ?>"/>
                <span>真题路径必须为已录入的真题</span>

        	<?php endif;?>
                  <input type="hidden"  id="is_original_<?php echo $remove_id;?>"  class="txtbox2" name="exam_year" value="<?php echo $val['is_original'] ?>" readonly/>
		        			<input type="button" value="保存" class="btn btn_submit_original" delete_id="<?php echo $remove_id;?>" post_url="<?=site_url('admin/question_external/update_original/'.$remove_id)?>" rel="<?php echo $remove_id;?>" id="btn_submit_<?php echo $remove_id;?>" style="margin-top:4px;"/>

		        			<input type="button" rel="<?php echo $remove_id;?>" id="btn_cancle_<?php echo $remove_id;?>" value="取消" class="btn btn_cancle_original" />
				  </div>


        	          <?php endif;?>


                      <?php if($val['is_original']==1):?>

               <?php $remove_id = $val['ques_id'];?>


		          <a class="a_check" rel="<?php echo $remove_id;?>" id="a_check_<?php echo $remove_id;?>" href="###">
		          <?php if($val['check']==0):?>
		          审核
		          <?php else:?>
		          取消审核
		           <?php endif;?>
		          </a>

		          <div class="check_box display_none" id="check_box_<?php echo $remove_id;?>">


		        	        			   <input type="hidden"  id="check_<?php echo $remove_id;?>"  class="txtbox2" name="check"  value="<?php echo $val['check'];?>"  />

		        			<input type="button" value="<?php if($val['check']==0):?>审核<?php else:?>取消审核
		           <?php endif;?>" class="btn btn_submit_check" check_id="<?php echo $remove_id;?>" post_url="<?=site_url('admin/question_external/check/'.$remove_id)?>" rel="<?php echo $remove_id;?>" id="btn_submit_check_<?php echo $remove_id;?>" style="margin-top:4px;"/>

		        			<input type="button" rel="<?php echo $remove_id;?>" id="btn_cancle_check_<?php echo $remove_id;?>" value="取消" class="btn btn_cancle_check" />

				  </div>
                  <?php endif;?>
          <?php } ?>
          </div>
        </td>
      </tr>
      <?php if($mode == 'trash'):?>
	      <?php $recycles = $val['recycle'];?>
	      <?php if (count($recycles)) {?>
	      <tr>
	      	  <td><strong>删除原因:</strong></td>
	      	  <td colspan="9">
	      	  		<ul class="recycle">
	      	  			<?php foreach ($recycles as $k=>$recycle) {?>
	      	  			<li><?php echo $k+1;?>、<?php echo $recycle['reason'] . '  <font color="red">' . $recycle['ctime'] . '</font>';?></li>
	      	  			<?php }?>
	      	  		</ul>
	      	  </td>
	      </tr>
	      <?php }?>
      <?php endif;?>

      <?php endforeach; ?>
      <?php else: ?>
      <tr>
        <td colspan="10">暂无记录！</td>
      </tr>
      <?php endif; ?>
      <tr class="altbg1">
        <td colspan="3">
          <?php if ($priv_manage) {?>
          <button type="button" class="btn2" onclick="checkbox_checked('ids[]');">全选</button>
          <?php if($mode=='trash'):?>
          <select name="batch_op" id="batch_op">
           <option value="">-选择操作-</option>
           <option value="restore" op="<?=site_url('admin/question_external/batch_restore')?>">批量还原</option>
           <option value="remove" op="<?=site_url('admin/question_external/batch_remove')?>">批量移除</option>
          </select>
          <?php else:?>
          <select name="batch_op" id="batch_op">
           <option value="">-选择操作-</option>
           <option value="relate" op="<?=site_url('admin/question_external/batch_relate')?>">关联试题</option>
           <option value="unrelate" op="<?=site_url('admin/question_external/batch_unrelate')?>">取消关联</option>
          <option value="shenhe" op="<?=site_url('admin/question_external/batch_shenhe')?>">批量审核</option>
          <option value="unshenhe" op="<?=site_url('admin/question_external/batch_unshenhe')?>">取消审核</option>
          </select>
          <span style="display:none;" id="batch_extend">
          关联试题ID:
          <input type="text" class="txtbox5" name="relate_ques_id" id="relate_ques_id" />
          </span>
          <?php endif;?>
          <?php } ?>
        </td>
        <td colspan="7" style="text-align:right"><?=$pagination?></td>
      </tr>
    </table>
    <center><input type="submit" name="dosubmit" value=" 提交操作 " class="btn" /></center>
  </div>
  </form>
  <script>
  function test()
  {
       	 var start_grade = parseInt($('#start_grade').val());
 	    var end_grade = parseInt($('#end_grade').val());
  	    var begin_time =$('#begin_time').val();
    	  var end_time = $('#end_time').val();
    	  var start_difficulty =$('#start_difficulty').val();
    	  var end_difficulty = $('#end_difficulty').val();

 	    if (isNaN(start_grade) || isNaN(end_grade) || start_grade > end_grade) {
 	        alert('年级段选择错误，开始年级不能大于结束年级！');
 	        return false;
            }

 	   else if(!duibi(begin_time, end_time))
            {
                alert('开始时间不能大于结束时间！');
 	        return false;
            }


  	  else if (isNaN(start_difficulty )  ) {

	       alert('难度系数填写错误，不是数字！');
	       return false;
        }

   	 else if (isNaN(end_difficulty  ) ) {

	       alert('难度系数填写错误，不是数字！');
	       return false;
        }

   	 else  if ( Number(start_difficulty)>100||Number(start_difficulty)<0)
	    {
	    	   alert('难易度填写错误，范围应为[0-100]！');
	       return false;
	    }

   	 else  if ( Number(end_difficulty)>100||Number(end_difficulty)<0)
	    {
	    	   alert('难易度填写错误，范围应为[0-100]！');
	       return false;
	    }

   	 else  if (start_difficulty!=''&&Number(start_difficulty)  > Number(end_difficulty)&&end_difficulty!='' ) {

	 	       alert('难度系数填写错误，开始区间大于结束区间！');
	 	       return false;
	         }
   	 else
   	 {

                $('#search_form').submit();
   	 }


 }

  function duibi(a, b) {
	    var arr = a.split("-");
	    var starttime = new Date(arr[0], arr[1], arr[2]);
	    var starttimes = starttime.getTime();

	    var arrs = b.split("-");
	    var lktime = new Date(arrs[0], arrs[1], arrs[2]);
	    var lktimes = lktime.getTime();

	    if (starttimes > lktimes) {

	       // alert('开始时间大于离开时间，请检查');
	        return false;
	    }
	    else
	        return true;

	}	</script>
  <div class="space">
    <form method="get" name="search_form" class="validate" id="search_form" action="<?=site_url('admin/question_external/index/'.$mode)?>" onsubmit="return test();">
        <div class="space">
            <div class="subtitle">搜索试题</div>
            <table class="maintable" border="0" cellspacing="0" cellpadding="0">
                <tr>
                    <td class="altbg1" width="15%">试题ID</td>
                    <td>
                    	<input type="text" value="<?php echo isset($search['ques_id']) ? $search['ques_id'] : '';?>" name="ques_id"/>
                    	<font color="red">*注：根据试题ID搜索时，其他条件将失效</font>
                    </td>
                </tr>
                <tr>
                    <td class="altbg1">录入时间</td>
                    <td>
                        <input type="text" id="begin_time" name="begin_time" class="txtbox4" value="<?=$search['begin_time']?>" onclick="WdatePicker({dateFmt:'yyyy-MM-dd',startDate:'2013-09-01'});"> -
                        <input type="text" id="end_time" name="end_time" class="txtbox4" value="<?=$search['end_time']?>" onclick="WdatePicker({dateFmt:'yyyy-MM-dd',startDate:'2013-09-01'});">
                    </td>
                </tr>
                <tr>
                    <td class="altbg1">题型</td>
                    <td>
                      <select name="qtype">
                        <option value="">-请选择-</option>
                        <?php foreach($qtypes as $k => $v):?>
                        <option value="<?=$k?>" <?=$search['type']===$k?'selected':''?>><?=$v?></option>
                        <?php endforeach;?>
                      </select>
                    </td>
                </tr>
                <tr>
                    <td class="altbg1">考试方式</td>
                    <td>
                      <select name="test_way">
                        <option value="">-请选择-</option>
                        <?php $test_way = C('test_way')?>
                        <?php foreach($test_way as $k => $v):?>
                        <option value="<?=$k?>" <?=$search['test_way'] === $k ? 'selected' : '' ?>><?=$v?></option>
                        <?php endforeach;?>
                      </select>
                    </td>
                </tr>
                <tr>
                    <td class="altbg1">审核状态</td>
                    <td>
                    <select name="check">
                        <option value="">-请选择-</option>

                        <option value="0" <?=$search['check']===0?'selected':''?>>未审</option>
                     <option value="1" <?=$search['check']===1?'selected':''?>>已审</option>
                      </select>
                    </td>
                </tr>

                <tr>
                    <td class="altbg1">标签</td>
                    <td>
                    <SELECT name="tags">
                    <option value="">-请选择-</option>
                    <?php foreach ($q_tags as $k => $q_tag) {?>
                        <?php foreach ($q_tag as $key => $item) {?>
                            <option value="<?=$k?>-<?=$key?>" <?=$search['tags']===$k.'-'.$key?'selected':''?>><?=$item?></option>
                        <?php }?>
                    <?php }?>
                    </SELECT>
                    </td>
                </tr>
                <tr>
                    <td class="altbg1">学科</td>
                    <td>
                      <select name="subject_id" id="subject_id">
                        <option value="">--请选择--</option>
                        <?php foreach($subjects as $key => $val): ?>
                        <option value="<?=$key?>"<?=$key==$search['subject_id']?' selected="selected" ':''?>><?=$val?></option>
                        <?php endforeach; ?>
                      </select>

                      <?php $subject_ids = explode(',', $search['subject_id_str']);?>
                      <span id="subject_id_list" <?if ($search['subject_id'] != 11): ?> style="display: none;" <?php endif;?>>
                          <?php foreach($all_subjects as $key => $val): ?>
                              <?php if ($key != 11):?>
                                <input type="checkbox" name="subject_str[]" value="<?=$key?>" <? echo in_array($key, $subject_ids) ? 'checked': '';?>><?=$val?>
                              <?php endif;?>
                          <?php endforeach; ?>
                      </span>
                    </td>
                </tr>
                <tr>
                    <td class="altbg1">知识点</td>
                    <td>
		             <div id="knowledge_list"></div>
		             <input type="hidden" name="knowledge_ids" id="knowledge_ids" value="<?php echo $search['knowledge_ids'];?>" />
		             <button id="knowledge_select" class="btn2" type="button">点击选择</button>
                    </td>
                </tr>
                <tr>
                    <td class="altbg1">认知过程</td>
                    <td>
                    	<div id="kp_box">
                    		<?php $search_kp = is_array($search['know_process']) ? $search['know_process'] : array();?>
			             	<?php foreach ($know_processes as $k=>$v) {?>
			             	<input type="checkbox" name="know_process[]" value="<?php echo $k;?>" id="kp_<?php echo $k;?>" <?php echo in_array($k, $search_kp) ? 'checked="checked"' : '';?>/><label for="kp_<?php echo $k;?>"><?php echo $v;?></label>
			             	<?php } ?>
                    	</div>
                    </td>
                </tr>
                <tr>
                    <td class="altbg1">方法策略：</td>
                    <td>
		             <div id="method_tactic_list"></div>
		             <input type="hidden" name="method_tactic_ids" id="method_tactic_ids" value="<?php echo $search['method_tactic_ids'];?>" />
		             <button id="method_tactic_select" class="btn2" type="button">点击选择</button>
                    </td>
                </tr>

                <tr style="display:none;">
                    <td class="altbg1">技能</td>
                    <td>
                      <span id="skill_list"></span>
                    </td>
                </tr>
                <tr>
                    <td class="altbg1">年级</td>
                    <td>
                      <select name="start_grade" id="start_grade">
                        <option value="0">--请选择--</option>
                        <?php foreach($grades as $key => $val): ?>
                        <option value="<?=$key?>"<?=$key==$search['start_grade']?' selected="selected" ':''?>><?=$val?></option>
                        <?php endforeach; ?>
                      </select>
                      -
                      <select name="end_grade" id="end_grade">
                        <option value="0">--请选择--</option>
                        <?php foreach($grades as $key => $val): ?>
                        <option value="<?=$key?>"<?=$key==$search['end_grade']?' selected="selected" ':''?>><?=$val?></option>
                        <?php endforeach; ?>
                      </select>

                    </td>
                </tr>
                <tr>
                    <td class="altbg1">类型</td>
                    <td>
                    	<input type="hidden" value="<?php echo implode('_', $search['class_id']);?>" id="search_class_id"/>
                      <div id="class_list"></div>
                      <div style="display:none;" id="hidden_class_list">
		                <?php foreach($grades as $key => $val):?>
		                <div id="grade<?=$key?>_class" <?php if(empty($relate_class[$key])):?>style="display:none;"<?php endif;?>>
			                <?php $class_list = isset($all_grade_class[$key])?$all_grade_class[$key]:array();?>
			                <?php $class_list_ids = array();?>
			                <?php foreach($class_list as $cid => $class):?>
			                <?php $class_list_ids[$cid] = $class['class_name'];?>
			                <?php if($key>=11 && in_array($cid,array(2,3))):?>
							<span class="subject_type_box">
							<?php $subject_type_ids = array();?>
			                <?php foreach(array_filter($subject_types) as $k => $v):?>
			                <?php $subject_type_ids[$k] = $v;?>
			                <?php endforeach;?>
			                <?php echo json_encode($subject_type_ids);?>
			                </span>
			                <?php endif;?>
			                <?php endforeach;?>
			                <span class="class_id_box"><?php echo json_encode($class_list_ids);?></span>
		                </div>
		                <?php endforeach;?>
                    </td>
                </tr>
                <tr>
                    <td class="altbg1">文理科:</td>
                    <td>
                      <div id="subject_type_list">
                        <?php /* foreach(array_filter($subject_types) as $k=>$val):?>
                        <input type="checkbox" class="subject_type <?=($search['subject_type'] != '' && $search['subject_type'] == $k) ? 'checked':''?>" name="subject_type" id="subject_type<?=$k?>" value="<?=$k?>" <?=($search['subject_type'] != '' && $search['subject_type'] == $k) ? 'checked':''?>/><label for="subject_type<?=$k?>"><?=$val?></label>
                        <?php endforeach; */?>
                      </div>
                      <input type="hidden" value="<?php echo $search['subject_type'];?>" id="search_subject_type"/>
                    </td>
                </tr>
                <tr>
                    <td class="altbg1">难易度</td>
                    <td>
                        <input type="text" name="start_difficulty" id="start_difficulty" class="txtbox4" value="<?=$search['start_difficulty']?>"/> -
                        <input type="text" name="end_difficulty" id="end_difficulty" class="txtbox4" value="<?=$search['end_difficulty']?>" /> <span style="color:red">请按难易度数值区间搜索，范围为[0-100]</span>
                    </td>
                </tr>
                <tr>
                    <td class="altbg1">关键字</td>
                    <td><input type="text" name="keyword" value="<?=$search['keyword']?>" class="txtbox" /></td>
                </tr>
            </table>
            <center>
                <input type="submit" value=" 搜索 " class="btn" /> 
                <input type="button" value="重置 " class="btn" onclick="window.location.href='/admin/question_external/index/<?php echo $mode;?>'"/>
            </center>
        </div>
    </form>
  </div>
</div>
<?php $this->load->view('common/footer', array('load_dialog_js' => true));?>

