  <div class="space">
  <div class="subtitle"><span class="menu" style="padding-top:5px;"><a href="javascript://" class="close"><img src="<?=__HTML_URL__?>images/no.gif" /></a></span>知识点选择</div> 
    <div style="max-height:300px;_height:300px;overflow:auto;">
    <table class="maintable" border="0" cellspacing="0" cellpadding="0" style="margin-bottom:0px;width:780px;">
        <?php if($list):?>
        <?php foreach($list as $parent):?>
        <tbody id="range_parent_<?=$parent['id']?>">
        <tr>
            <td colspan="3" class="altbg2" style="text-align: center;">
                <input type="hidden" name="pid" value="<?=$parent['id']?>" />  
                <?php $subject = C('subject');?>        
                <span class="pname font_4"><?=$subject[$parent['subject_id']] . '->' .              
                $parent['knowledge_name']?>(<?=$parent['ques_num']?>[<?=$parent['relate_ques_num']?>])</span>
                [<a href="javascript://" class="expand">收起</a>]
                <input type="checkbox" name="knowledge_parent<?=$parent['id']?>" id="knowledge_parent<?=$parent['id']?>" onclick="allchecked('','range_parent_<?=$parent['id']?>',this)" /><label for="knowledge_parent<?=$parent['id']?>">全选/取消</label>
            </td>
        </tr>
        <?php foreach($parent['children'] as $key => $val):?>
        <?php $td_index = $key%3;?>
        <?php if($td_index == 0):?><tr><?php endif;?>
            <td<?php if($key+1==count($parent['children']) && $td_index<2):?> colspan="<?=(3-$td_index)?>"<?php endif;?>><input type="checkbox" name="knowledge_ids" id="knowledge_<?=$val['id']?>" value="<?=$val['id']?>" <?=strpos($knowledge_ids, ','.$val['id'].',')!==false?' checked':''?>/><label for="knowledge_<?=$val['id']?>"><?=$val['knowledge_name']?>(<?=$val['ques_num']?>[<?=$val['relate_ques_num']?>])</label></td>
        <?php if($td_index==2 OR $key+1==count($parent['children'])):?></tr><?php endif;?>
        <?php endforeach;?>
        </tbody>
        <?php endforeach;?>
        <?php else:?>
        <tr>
            <td colspan="3" style="text-align: center;color:#f00">
                暂无知识点
            </td>
        </tr>
        <?php endif;?>
    </table>
    </div>
    <table class="maintable" border="0" cellspacing="0" cellpadding="0">
        <tr>
            <td style="background:#A6CBE7;text-align: center;color:#f00">
                <input type="button" id="knowledge_confirm" value=" 确定 " class="btn" />
                <input type="button" value=" 取消 " class="btn close" />
            </td>
        </tr>
    </table>
  </div>
  <script>
    $(document).ready(function(){
        $('#knowledge_confirm').click(function(){
            var selected = [];
            var item = [];
            var index = 0;
            var checkbox = $('input:checked[name=knowledge_ids]');
            for (var i=0; i<checkbox.length; i++) {
                if (checkbox[i].checked == true) {
                    var pid = $(checkbox[i]).parent().parent().parent().find('input[name=pid]').val();
                    var pname = $(checkbox[i]).parent().parent().parent().find('span.pname').text();                    
                    if (typeof(selected[pid])=='undefined') {
                        selected[pid] = [pname,[]];
                        index = 0;
                    }                     
                    var kid = checkbox[i].value;
                    var kname = $(checkbox[i]).parent().find('label').html();
                    item = [kid,kname];
                    selected[pid][1][index++] = item;
                } 
            }
            if (selected.length == 0) {
                alert('请选择知识点');
                return;
            }
            var string = '';
            var knowledge_ids = '';
            for (pid in selected) {
                if (pid != 'indexof') {                   
                    var parent = selected[pid];
                    string += '<div><span class="font_4" pkid="'+pid+'">'+parent[0]+'</span>：';
                    for (i=0; i<parent[1].length; i++) {
                        string += '<input type="checkbox" name="knowledge_id[]" id="knowledge'+parent[1][i][0]+'" value="'+parent[1][i][0]+'" checked /><label for="knowledge'+parent[1][i][0]+'">'+parent[1][i][1]+'</label>';
                        knowledge_ids += (knowledge_ids?',':'') + parent[1][i][0];
                    }
                    string += '</div><hr/>';
                }                  
            }
            $('#knowledge_list').html(string);
            $('#knowledge_ids').val(knowledge_ids);            
            $.unblockUI();
            // 试题规则编辑页面
            if ($('#knowledge_rule_list').length) {                
                reset_knowledge_rule_list();
            }
        });
        $('.expand').click(function(){
            if ($(this).html() == '展开') {
                $(this).html('收起');
                $(this).parent().parent().siblings().show();
            } else {
                $(this).html('展开');
                $(this).parent().parent().siblings().hide();
            }
            
        });
    });
  </script>