<?php $this->load->view('common/profile_header', array('topmenu' => 'profile', 'submenu' => 'awards'));?>
<?php static_global(array('js/datepicker/wdatepicker.js','js/jquery/plugin/blockUi.js'));
 static_js('schools.js');?>
   
<style>
.height_light {
    border:1px solid #f00;
    padding:2px;
    margin:2px;
}
.score_rank_td div{
	line-height:30px;
	height:30px;
	padding-top:6px;
}
</style>
<?php
// 初始化公共数据
$grades        = C('grades');
$grades_year = array();
for ($year = date('Y'), $i = 0, $n = $student['grade_id'] - 3; $i <= $n; $i++, $year--)
{
    $grades_year[$year] = $year . '年';
}
$subject_list  = C('subject');
$awards_levels = C('awards_level');
?>
<script type="text/javascript">
    function addItem(type)
    {
        var string = $('#'+type).find('span').html();
        string += '<input type="button" value="删除" onclick="delItem($(this))" />';
        $('#'+type).parent().append('<div class="cls_'+type+'">'+string+'</div>');
    }

    function delItem(obj)
    {
      	obj.parent().remove();
    }

    function check_awards(form) {
        // 检查排名
        var current_grade = parseInt(form.grade_id.value);

        var start_grade = current_grade-2 > 0 ? current_grade-2 : 1;
        var needed_grade_num = current_grade - start_grade;


        var needed_grades = [];

        var arr_grade_id = get_inputs('input','score_rank[grade_id][]');
        var arr_ranking  = get_inputs('input','score_rank[ranking][]');
        var arr_totalnum = get_inputs('input','score_rank[totalnum][]');
        var err = '';
        var not_complete = false;
        var ranking_err = false;
        var outof_grade = false;
        for (var i=0; i<arr_grade_id.length; i++) {
            var grade_id = parseInt(arr_grade_id[i].value);
            var ranking  = parseInt(arr_ranking[i].value);
            var totalnum = parseInt(arr_totalnum[i].value);
            // 都没填的跳过
            if (!arr_ranking[i].value.trim() && ! arr_totalnum[i].value.trim()) {
                continue;
            }
            // 填写不完整的，提示
            if (isNaN(ranking) || isNaN(totalnum)) {
                not_complete = true;
                $(arr_grade_id[i]).parent().parent().addClass('height_light');
                $(arr_grade_id[i]).parent().children().bind('blur',function(){
                    check_item($(this).parent().parent(), 'ranking');
                });
                continue;
            }
            // 排名比总数大的
            if (ranking > totalnum) {
                ranking_err = true;
                $(arr_grade_id[i]).parent().parent().addClass('height_light');
                $(arr_grade_id[i]).parent().children().bind('blur',function(){
                    check_item($(this).parent().parent(), 'ranking');
                });
                continue;
            }
            // 大于当前年级
            if (grade_id > current_grade) {
                outof_grade = true;
                $(arr_grade_id[i]).parent().parent().addClass('height_light');
                $(arr_grade_id[i]).parent().children().bind('blur',function(){
                    check_item($(this).parent().parent(), 'ranking');
                });
                continue;
            }
            if (grade_id >= start_grade && grade_id<=current_grade) {
                needed_grades.push(grade_id);
            }
        }

        // 检查竞赛成绩
        for (var typeid=1; typeid<=2; typeid++) {
            var arr_subject = get_inputs('input','awards_subject['+typeid+'][]');
            var arr_awards  = get_inputs('select','awards_awards['+typeid+'][]');
            var arr_grade   = get_inputs('select','awards_grade['+typeid+'][]');
            for (i=0; i<arr_subject.length; i++) {
                var subject = parseInt(arr_subject[i].value);
                var awards  = parseInt(arr_awards[i].value);
                var grade   = parseInt(arr_grade[i].value);
                // 没填的跳过
                if (! awards && ! grade) {
                    continue;
                }
                // 填写不完整的
                if (! awards || ! grade) {
                    not_complete = true;
                    $(arr_subject[i]).parent().parent().addClass('height_light');
                    $(arr_subject[i]).parent().children().bind('blur',function(){
                        check_item($(this).parent().parent(), 'awards');
                    });
                    continue;
                }
            }
        }

        // 其他成绩
        var arr_other_name = get_inputs('input','awards_other[name][]');

        var arr_other_desc = get_inputs('textarea','awards_other[desc][]');
        for (i=0; i<arr_other_name.length; i++) {
            var other_name = arr_other_name[i].value.trim();
            var other_desc = arr_other_desc[i].value.trim();
            if ( ! other_name && ! other_desc) continue;
            if ( ! other_name || ! other_desc) {
                not_complete = true;
                $(arr_other_name[i]).parent().parent().addClass('height_light');
                $(arr_other_name[i]).parent().children().bind('blur',function(){
                    check_item($(this).parent().parent(), 'other');
                });
                continue;
            }
        }




        var falg = 0;
        $("input[name='subject_in[]']:checkbox").each(function () {
            if ($(this).prop("checked"))
            {
                 falg += 1;
            }
        });
        if (falg > 3){
          alert("目前已经确定参加选考科目:最多只能选三项");return false;
        }




        var falg1 = 0;
        $("input[name='subject_not[]']:checkbox").each(function () {
            if ($(this).prop("checked"))
            {
                 falg1 += 1;
            }
        });
        if (falg1 > 4){
          alert("目前已经确定不参加选考科目:最多只能选四项");return false;
        }




        var xuekao_xuankao_subject_id = get_inputs('select','subject_first[subject_id][]');
        var xuekao_xuankao_fenshu = get_inputs('input','subject_first[fenshu][]');
        var xuekao_xuankao_shijian = get_inputs('input','subject_first[shijian][]');
        var wanzheng=0;
        var fenshus = [];
        var subjects = [];
        for (i=0; i<xuekao_xuankao_subject_id.length; i++) {

            var subject_id = xuekao_xuankao_subject_id[i].value.trim();

            var fenshu = xuekao_xuankao_fenshu[i].value.trim();

            var shijian = xuekao_xuankao_shijian[i].value.trim();

            if ( !subject_id && !fenshu && !shijian) continue;

            if ( ! subject_id || ! fenshu || ! shijian) {
                alert('第一次参加的选考科目及成绩:不完整');return false;
            }
            else
            {
                wanzheng +=1;
                fenshus.push(fenshu);

            }

        }


        if (wanzheng > 3){
            alert("第一次参加的选考科目及成绩:最多只能选三项");
            return false;
          }

        var grade_id=<?php echo $student['grade_id'];?>

        if( (parseInt(grade_id)==11||parseInt(grade_id)==12) &&wanzheng==0 )
        {
        	 alert("高二高三第一次参加的选考科目及成绩:必填一项");
             return false;
        }
        var xuekao_xuankaofenshu =[100,97,94,91,88,85,82,79,76,73,70,67,64,61,58,55,52,49,46,43,40];


        if(wanzheng>0){


        	for (i=0; i<wanzheng; i++) {
            	if($.inArray(parseInt(fenshus[i]),xuekao_xuankaofenshu)<0)
            	{
          		  alert("第一次参加的选考科目及成绩:输入成绩有误，成绩集合为:100,97,94,91,88,85,82,79,76,73,70,67,64,61,58,55,52,49,46,43,40");
          		  return false;
            	}
        	}


               $("select[name='subject_first[subject_id][]']").each(function(i){$(this).attr("xh",i);});

               var chongfu_subject=1;
                $("select[name='subject_first[subject_id][]']").each(function () {
                    var val = $(this).find('option:selected').val();
                    var xh = $(this).attr("xh");
               	 $("#TbData select[name='subject_first[subject_id][]']").each(function(){
                  	  if(val==$(this).find('option:selected').val()&&val!=0&&xh!= $(this).attr("xh"))
                      {
                    		chongfu_subject=0;
                      }
                  });
                });
                if(!chongfu_subject)
                {
                	alert('第一次参加的选考科目:学科重复 ');return false;
                }

        }




        var xuekao_xuankao_subject_id2 = get_inputs('select','subject_two[subject_id][]');
        var xuekao_xuankao_fenshu2 = get_inputs('input','subject_two[fenshu][]');
        var xuekao_xuankao_shijian2 = get_inputs('input','subject_two[shijian][]');
        var wanzheng2=0;
        for (i=0; i<xuekao_xuankao_subject_id2.length; i++) {

            var subject_id2 = xuekao_xuankao_subject_id2[i].value.trim();

            var fenshu2 = xuekao_xuankao_fenshu2[i].value.trim();

            var shijian2 = xuekao_xuankao_shijian2[i].value.trim();

            if ( !subject_id2 && !fenshu2 && !shijian2) continue;

            if ( ! subject_id2 || ! fenshu2 || ! shijian2) {
                alert('第二次参加的选考科目及成绩:不完整 ');return false;
            }
            else
            {
                wanzheng2 +=1;
            }

        }
        if (wanzheng2 > 3){
            alert("第二次参加的选考科目及成绩:最多只能选三项");
            return false;
          }

        if(wanzheng2>0){


        	for (i=0; i<wanzheng2; i++) {
            	if($.inArray(parseInt(fenshus2[i]),xuekao_xuankaofenshu)<0)
            	{
           		  alert("第二次参加的选考科目及成绩:输入成绩有误，成绩集合为:100,97,94,91,88,85,82,79,76,73,70,67,64,61,58,55,52,49,46,43,40");return false;
            	}
        	}


               $("select[name='subject_two[subject_id][]']").each(function(i){$(this).attr("xh_1",i);});

               var chongfu_subject_1=1;
                $("select[name='subject_two[subject_id][]']").each(function () {
                	var val = $(this).find('option:selected').val();
                	var  xh_1 = $(this).attr("xh_1");

               	 $("#TbData_1 select[name='subject_two[subject_id][]']").each(function(){

                  	  if(val==$(this).find('option:selected').val()&&val!=0&&xh_1 != $(this).attr("xh_1"))
                      {
                    		chongfu_subject_1=0;
                      }
                  });
                });

                if(!chongfu_subject_1)
                {
                	alert('第二次参加的选考科目:学科重复 ');
                	return false;
                }

        }



        var xuekao_xuankao_subject_id3 = get_inputs('select','subject_finish[subject_id][]');
        var xuekao_xuankao_rank = get_inputs('select','subject_finish[rank][]');

        var wanzheng3=0;
        for (i=0; i<xuekao_xuankao_subject_id3.length; i++) {

            var subject_id3 = xuekao_xuankao_subject_id3[i].value.trim();

            var rank = xuekao_xuankao_rank[i].value.trim();


            if ( !subject_id3 && !rank) continue;

            if ( ! subject_id3 || ! rank ) {
                alert('已经参加的学科科目及成绩:不完整 ');return false;
            }
            else
            {
                wanzheng3 +=1;
            }

        }

        if(wanzheng3>0){


            var chongfu_subject_2 = 1;

             $("select[name='subject_finish[subject_id][]']").each(function(i){$(this).attr("xh_2",i);});

             var chongfu_subject_1=1;
              $("select[name='subject_finish[subject_id][]']").each(function () {
            	  var val = $(this).find('option:selected').val();
            	  var xh_2 = $(this).attr("xh_2");

             	 $("#TbData_2 select[name='subject_finish[subject_id][]']").each(function(){

                	  if(val==$(this).find('option:selected').val()&&val!=0&&xh_2!=$(this).attr("xh_2"))
                    {
                  		chongfu_subject_2=0;
                    }

              	  });
              });
              if(!chongfu_subject_2)
              {
              	alert('已经参加的学科科目及成绩 :学科重复 ');return false;
              }

      }



        if (not_complete === true) {
            err += "- 数据没有填写完整。\n";
        }
        if (ranking_err === true) {
            err += "- 排名不能比总人数大。\n";
        }
        if (outof_grade === true) {
            err += "- 您选择的年级大于您就读的年级。\n";
        }


        if (needed_grades.length < needed_grade_num) {
            err += "- 请至少填写最近两年成绩排名！\n";
        }
        if (err) {
            alert(err);
            return false;
        }
        return true;

    }

    function check_item($div, type) {
        var items = $div.find('span').children();//('select,input,textarea');
        var check = false;
        switch(type) {
            case 'ranking' :
                var grade_id = parseInt($div.find('select').val());
                var ranking  = parseInt($div.find('input[name*=ranking]').val());
                var totalnum = parseInt($div.find('input[name*=totalnum]').val());
                if ( ! grade_id && ! ranking && ! totalnum) {
                    check = true;
                    break;
                }
                if (grade_id && ranking && totalnum) {
                    if (ranking <= totalnum) {
                        check = true;
                        break;
                    }
                }
                break;
            case 'awards' :
                var subject = parseInt($div.find('select[name*=_subject]').val());
                var awards  = parseInt($div.find('select[name*=_awards]').val());
                var grade   = parseInt($div.find('select[name*=_grade]').val());
                if ( ! subject && ! awards && ! grade) {
                    check = true;
                    break;
                }
                if (subject && awards && grade) {
                    check = true;
                    break;
                }
                break;
            case 'other' :
                var name = $div.find('input[name*=name]').val().trim();
                var desc = $div.find('textarea').val().trim();
                if ( ! name && ! desc) {
                    check = true;
                    break;
                }
                if (name && desc) {
                    check = true;
                    break;
                }
                break;
            default :
                return;
        }
        if (check == true) {
            $div.removeClass('height_light');
        }
    }

    function get_inputs(type, name, parent) {
        if(parent) {
            var objs=parent.getElementsByTagName(type);
        } else {
            var objs=document.getElementsByTagName(type);
        }
        var result = [];
        for (var i=0; i<objs.length; i++) {
            if (objs[i].name == name) {
                result.push(objs[i]);
            }
        }
        return result;
    }

</script>
<div id="body">
  <form method="POST" name="form_awards" id="form_awards" action="<?=site_url('student/profile/awards_save')?>" onsubmit="return check_awards(this);">
  <input type="hidden" name="uid" value="<?=$uid?>">
  <input type="hidden" name="grade_id" value="<?=$student['grade_id']?>">
  <div class="space">
    <table class="maintable" id="table_awards" border="0" cellspacing="0" cellpadding="0" >
      <tr>
        <td colspan="2" class="altbg2" style="text-align: left;">
          <span class="altbg2-bg">成绩排名</span>
          <i class="altbg2-r"></i>
        </td>
      </tr>
      <tr><td colspan="2" class="altgb4">请填写最近两年成绩排名,小升初必填 </td></tr>
      <tr>
        <td width="16%" class="altbg1" style="border-bottom:2px solid #045eab;">排名 <span style="color:#f00;position:relative;top:3px;"> * </span></td>
        <td style="border-bottom:2px solid #045eab;" class="score_rank_td">
            <?php if($score_ranks): ?>
            <?php $auto_key = 0;?>
            <?php foreach($score_ranks as $k => $rank): ?>
            <?php $auto_key++;?>
            <div>
              <span>
                <? if ($student['grade_id'] == 6) { ?>
                <input type="hidden" name="score_rank[grade_id][]" value="<?=$rank['grade_id']?>"/> <?=$grades[$rank['grade_id']]?>
                <? } else { ?>
                <select class="ie_select" name="score_rank[grade_id][]">
                  <option value="0">--年级--</option>
                    <?php foreach($grades as $kk => $v) { ?>
                    <option value="<?=$kk?>"<?php if($rank['grade_id']==$kk) echo ' selected="selected"';?>><?=$v?></option>
                    <?php } ?>
                </select>
                <? } ?>
			                排名：<input type="text" name="score_rank[ranking][]" class="txtbox5" value="<?=$rank['ranking']?>"> /
			                人数：<input type="text" name="score_rank[totalnum][]" class="txtbox5" value="<?=$rank['totalnum']?>">
              </span>
              <?php /* if ($auto_key = 1) {?>
              <input type="button" value="添加" onclick="addItem('score_rank_div')" />
              <?php } else { ?>
              <input type="button" value="删除" onclick="delItem($(this))" />
              <?php } */ ?>
            </div>
            <?php endforeach; ?>
            <?php endif;?>
            <?if(!$score_ranks){?>
            <?php for ($i = 1; $i <= 3; $i++) {?>
            <div <?php echo $i == 1 ? 'id="score_rank_div" style="display:none;"' : '';?>>
              <span>
                <? if ($student['grade_id'] == 6) { ?>
                <input type="hidden" name="score_rank[grade_id][]" value="<?=(6 - $i + 1 + 1)?>"/> <?=$grades[6 - $i + 1 + 1]?>
                <? } else { ?>
                <select class="ie_select" name="score_rank[grade_id][]">
                  <option value="0">--年级--</option>
                    <?php foreach($grades as $k => $v)  { ?>
                    <option value="<?=$k?>"><?=$v?></option>
                    <?php } ?>
                </select>
                <? } ?>
                <input type="hidden" name="score_rank[id][]" value="" />
			                排名：<input type="text" name="score_rank[ranking][]" class="txtbox5" value=""> /
			                人数：<input type="text" name="score_rank[totalnum][]" class="txtbox5" value="">
              </span>
              <?php /* if ($score_ranks) {?>
              <input type="button" value="删除" onclick="delItem($(this))" <?php echo $i == 1 ? 'style="display:none;"' : '';?>/>
              <input type="button" style="display:none;" value="添加" onclick="addItem('score_rank_div')" />
              <?php } else {?>
              <input type="button" <?php if ($i == 1) {echo 'style="display:none;"';}?> value="添加" onclick="addItem('score_rank_div')" />
              <?php } */ ?>
            </div>
            <?php  } ?>
        <?}?>
        </td>
      </tr>
      <tr><td style="border:none;"></td></tr>
      <tr>
         <td colspan="2" class="altbg2" style="text-align: left;">
          <span class="altbg2-bg">竞赛获奖</span>
          <i class="altbg2-r"></i>
        </td>
      </tr>
      <tr><td colspan="2" class="altgb4">竞赛获奖成绩,小升初选填 </td></tr>
      <?php foreach(C('awards_type') as $type_id => $type_name):?>
      <tr>
        <td class="altbg1"><?=$type_name?>成绩</td>
        <td class="score_rank_td">
            <?php if(isset($awards_list[$type_id])):?>
            <?php $auto_key = 0;?>
            <?php foreach($awards_list[$type_id] as $val):?>
            <?php $auto_key++;?>
            <div>
               <span>
                <? if ($student['grade_id'] <= 6) { ?>
                  <input type="hidden" name="awards_subject[<?=$type_id?>][]" value="2"/> 数学
                <? } else { ?>
                <select name="awards_subject[<?=$type_id?>][]">
                    <option value="0">--学科--</option>
                    <?php foreach($subject_list as $k => $v): ?>
                    <option value="<?=$k?>"<?php if($val['subject']==$k) echo ' selected="selected"';?>><?=$v?></option>
                    <?php endforeach; ?>
                </select>
                <? } ?>
                <select name="awards_awards[<?=$type_id?>][]">
                    <option value="0">--奖项--</option>
                    <?php foreach($awards_levels[$type_id] as $k => $v): ?>
                    <option value="<?=$k?>"<?php if($val['awards']==$k) echo ' selected="selected"';?>><?=$v?></option>
                    <?php endforeach; ?>
                </select>
                <select name="awards_grade[<?=$type_id?>][]">
                    <option value="0">--获奖年份--</option>
                    <?php foreach($grades_year as $k => $v) { ?>
                    <option value="<?=$k?>"<?php if($val['grade']==$k) echo ' selected="selected"';?>><?=$v?></option>
                    <?php } ?>
                </select>
                <input type="hidden" name="awards_ids[<?=$type_id?>][]" value="<?=$val['id']?>" />
               </span>

              <?php if ($auto_key == 1) {?>
              <input type="button" value="添加" onclick="addItem('awards_<?=$type_id?>')" />
              <?php } else { ?>
              <input type="button" value="删除" onclick="delItem($(this))" />
              <?php } ?>
            </div>
            <?php endforeach;?>
            <?php endif;?>

            <?php for ($i = 1; $i <= 2; $i++) {?>
            <div <?php echo $i == 1 ? 'id="awards_' . $type_id . '" style="display:none;"' : '';?>>
               <span>
                <? if ($student['grade_id'] <= 6) { ?>
                  <input type="hidden" name="awards_subject[<?=$type_id?>][]" value="2"/> 数学
                <? } else { ?>
                <select name="awards_subject[<?=$type_id?>][]">
                    <option value="0">--学科--</option>
                    <?php foreach($subject_list as $k => $v): ?>
                    <option value="<?=$k?>"><?=$v?></option>
                    <?php endforeach; ?>
                </select>
                <? } ?>
                <select name="awards_awards[<?=$type_id?>][]">
                    <option value="0">--奖项--</option>
                    <?php foreach($awards_levels[$type_id] as $k => $v): ?>
                    <option value="<?=$k?>"><?=$v?></option>
                    <?php endforeach; ?>
                </select>
                <select name="awards_grade[<?=$type_id?>][]">
                    <option value="0">--获奖年份--</option>
                    <?php foreach($grades_year as $k => $v): ?>
                    <option value="<?=$k?>"><?=$v?></option>
                    <?php endforeach; ?>
                </select>
                <input type="hidden" name="awards_ids[<?=$type_id?>][]" value="" />
               </span>
               <?php if (isset($awards_list[$type_id])) {?>
               <input type="button" value="删除" onclick="delItem($(this))" <?php echo $i == 1 ? 'style="display:none;"' : '';?>/>
               <input type="button" style="display:none;" value="添加" onclick="addItem('awards_<?=$type_id?>')" />
               <?php } else {?>
               <input type="button" <?php if ($i == 1) {echo 'style="display:none;"';}?> value="添加" onclick="addItem('awards_<?=$type_id?>')" />
               <?php }?>
            </div>
            <?php } ?>
        </td>
      </tr>
      <?php endforeach;?>
      <tr>
        <td class="altbg1" style="border-bottom:2px solid #045eab;">其他竞赛奖项</td>
        <td style="border-bottom:2px solid #045eab;">
           <?php if(isset($awards_list[0])):?>
           <?php $auto_key = 0;?>
           <?php foreach($awards_list[0] as $val):?>
           <?php $auto_key++;?>
           <div>
            <span>
                <input type="hidden" name="awards_other[id][]" value="<?=$val['id']?>" />
                <p class="pHonor clearfix"><span class="pHonorname fl_l">名称</span><input type="text" name="awards_other[name][]" class="txtbox2 fl_l" value="<?=$val['other_name']?>"></p>
               <p class="clearfix"><span class="pHonorname fl_l">获奖情况</span><textarea class="fl_l" name="awards_other[desc][]" rows="3" cols="50"><?=$val['other_desc']?></textarea>
               </p>
            </span>
            <?php if ($auto_key == 1) {?>
            <input type="button" value="添加" onclick="addItem('awards_other')" />
            <?php } else { ?>
            <input type="button" value="删除" onclick="delItem($(this))" />
            <?php } ?>
           </div>
           <?php endforeach; ?>
           <?php endif; ?>

           <?php for ($i = 1; $i <= 2; $i++) {?>
           <div <?php echo $i == 1 ? 'id="awards_other" style="display:none;"' : '';?>>
            <span>
                <input type="hidden" name="awards_other[id][]" value="" />
                <p class="pHonor clearfix"><span class="pHonorname fl_l">名称</span><input type="text" name="awards_other[name][]" class="txtbox2 fl_l" value=""></p>
                <p class="clearfix"><span class="pHonorname fl_l">获奖情况</span><textarea class="pHonorINput" name="awards_other[desc][]" rows="3" cols="50"></textarea>
                </p>
            </span>
            <?php if (isset($awards_list[0])) {?>
            <input type="button" value="删除" onclick="delItem($(this))" <?php echo $i == 1 ? 'style="display:none;"' : '';?>/>
            <input type="button" style="display:none;" value="添加" onclick="addItem('awards_other')" />
            <?php } else {?>
            <input type="button" <?php if ($i == 1) {echo 'style="display:none;"';}?> value="添加" onclick="addItem('awards_other')" />
            <?php }?>
           </div>
           <?php } ?>
        </td>
      </tr>
      <tr>
        <td colspan="2" class="altbg2" style="text-align: left;">
          <span class="altbg2-bg">升学志愿</span>
          <i class="altbg2-r"></i>
        </td>
      </tr>
      <tr><td colspan="2" class="altgb4">升学志愿，小升初必填</td></tr>
      <tr>
          <td class="altbg1">第一志愿<span style="color:#f00;position:relative;top:3px;"> * </span></td>
           <td>
           <input class="txtbox" id="school_select0" name="volunteer[a]" type="text" value="<?if($volunteer[a]){?><?=$volunteer[a]?><?}?>"/>
               <input id="school_id0" name="school_id[a]" type="hidden" value="<?=$school_id[a]?>"/>
           </td>
      </tr>
      <tr>
          <td class="altbg1">第二志愿</td>
          <td>
              <input class="txtbox" id="school_select1" name="volunteer[b]" type="text"  value="<?if($volunteer[b]){?><?=$volunteer[b]?><?}?>"/>
              <input id="school_id1" name="school_id[b]" type="hidden" value="<?=$school_id[b]?>"/>
          </td>
      </tr>
      <tr>
          <td class="altbg1" style="border-bottom:2px solid #045eab;">第三志愿</td>
          <td style="border-bottom:2px solid #045eab;">
             <input class="txtbox" id="school_select2" name="volunteer[c]" type="text"  value="<?if($volunteer[c]){?><?=$volunteer[c]?><?}?>"/>
               <input id="school_id2" name="school_id[c]" type="hidden" value="<?=$school_id[c]?>"/>
      </td>
      </tr>
      <tr><td style="border:none;"></td>
        </tr>
<? if (false) { ?>
 <tr><td style="border:none;height:10px;"></td></tr>

       <tr>
        <td colspan="2" class="altbg3" style="text-align: left;">
            	学考选考
        </td>
      </tr>

            <tr>
        <td width="16%" class="altbg1" style="border-bottom:2px solid #045eab;">是否在实验班<span style="color:#f00;position:relative;top:3px;"> * </span></td>
        <td style="border-bottom:2px solid #045eab;" class="score_rank_td">


            <div>
              <span>
                <input type="radio" name ="is_in_class" value="1" <?php if($xuekao_xuankao['is_in_class']==1): ?>checked<?php endif;?>>是
                &nbsp;
               <input type="radio" name ="is_in_class"  value="0" <?php if($xuekao_xuankao['is_in_class']==0): ?>checked<?php endif;?>>否
              </span>

            </div>


        </td>
      </tr>
      <tr><td style="border:none;"></td></tr>


            <tr>
        <td width="16%" class="altbg1" style="border-bottom:2px solid #045eab;">你参加走班教学的科目<span style="color:#f00;position:relative;top:3px;">  </span></td>
        <td style="border-bottom:2px solid #045eab;" class="score_rank_td">


            <?php
                $subject_class = unserialize($xuekao_xuankao['subject_class']);
            ?>
            <div>
              <span>
              <?php foreach ($subjects as $k => $v):?>

                <input type="checkbox" name ="subject_class[]"
                 <?php if( !empty($subject_class)&&in_array($k, $subject_class)&&is_array($subject_class)): ?>checked<?php endif;?> value="<?php echo $k;?>"


                 >
                 <?php echo $v;?>
               <?php endforeach;?>


            </div>



        </td>
      </tr>
      <tr><td style="border:none;"></td></tr>


  <tr>
        <td width="16%" class="altbg1" style="border-bottom:2px solid #045eab;">

目前已经确定参加选考科目

        <span style="color:#f00;position:relative;top:3px;">  </span></td>
        <td style="border-bottom:2px solid #045eab;" class="score_rank_td">


            <?php
                $subject_in = unserialize($xuekao_xuankao['subject_in']);
            ?>
            <div>
              <span >
              <?php foreach ($subjects as $k => $v):?>

                <input type="checkbox" name ="subject_in[]"  <?php if( !empty($subject_in)&&in_array($k, $subject_in)&&is_array($subject_in)): ?>checked<?php endif;?> value="<?php echo $k;?>"><?php echo $v;?>
               <?php endforeach;?>
</span><span style="color:#f00;position:relative;top:3px;">
可多选，最多选三项。可为空。</span>
            </div>



        </td>
      </tr>
      <tr><td style="border:none;"></td></tr>

  <tr>
        <td width="16%" class="altbg1" style="border-bottom:2px solid #045eab;">



目前已经确定不参加选考科目

        <span style="color:#f00;position:relative;top:3px;"> </span></td>
        <td style="border-bottom:2px solid #045eab;" class="score_rank_td">


            <?php
                $subject_not = unserialize($xuekao_xuankao['subject_not']);
            ?>
            <div>
              <span>
              <?php foreach ($subjects as $k => $v):?>

                <input type="checkbox" name ="subject_not[]"  <?php if( !empty($subject_not)&&in_array($k, $subject_not)&&is_array($subject_not)): ?>checked<?php endif;?> value="<?php echo $k;?>" ><?php echo $v;?>
               <?php endforeach;?>
</span>
<span style="color:#f00;position:relative;top:3px;">
可多选，最多选四项。可为空。</span>
            </div>



        </td>
      </tr>
      <tr><td style="border:none;"></td></tr>


      <tr>
        <td width="16%" class="altbg1" style="border-bottom:2px solid #045eab;">第一次参加的选考科目及成绩
        <span style="color:#f00;position:relative;top:3px;">         (分数集合为【100,97,94,91,88,85,82,79,76,73,70,67,64,61,58,55,52,49,46,43,40】)</span></td>
        <td style="border-bottom:2px solid #045eab;" class="score_rank_td" id="TbData">
            <?php
            $subject_first = unserialize($xuekao_xuankao[subject_first]);

            if(!empty($subject_first['subject_id'])): ?>
            <?php $auto_key = 0;
            ?>
            <?php foreach($subject_first['subject_id'] as $k => $rank): ?>
            <?php

            $auto_key++;?>
            <div>
              <span>
                <select class="ie_select" name="subject_first[subject_id][]">
                  <option value="">--学科--</option>
                    <?php foreach($subjects as $kk => $v): ?>
                    <option value="<?=$kk?>"<?php if($rank==$kk) echo ' selected="selected"';?>><?=$v?></option>
                    <?php endforeach; ?>
                </select>
			                分数<input type="text" name="subject_first[fenshu][]" class="txtbox5" value="<?=$subject_first['fenshu'][$k]?>">

时间
<input type="text" onclick="WdatePicker({dateFmt:'yyyy-MM-dd',startDate:'%y-%M-%d %h:%m:%s'});" value="<?=$subject_first['shijian'][$k]?>" class="txtbox4" name="subject_first[shijian][]" >


              </span>
              <?php if ($auto_key == 1) {?>
              <input type="button" value="添加" onclick="addItem('subject_first')" />
              <?php } else { ?>
              <input type="button" value="删除" onclick="delItem($(this))" />
              <?php } ?>
            </div>
            <?php endforeach; ?>
            <?php endif;?>

            <?php for ($i = 1; $i <= 2; $i++) {?>
            <div <?php echo $i == 1 ? 'id="subject_first" style="display:none;"' : '';?>>
              <span>
                <select class="ie_select" name="subject_first[subject_id][]">
                  <option value="">--学科--</option>
                    <?php foreach($subjects as $k => $v): ?>
                    <option value="<?=$k?>"><?=$v?></option>
                    <?php endforeach; ?>
                </select>

			            分数  <input type="text" name="subject_first[fenshu][]" class="txtbox5" value="">
			           时间  <input type="text" onclick="WdatePicker({dateFmt:'yyyy-MM-dd',startDate:'%y-%M-%d %h:%m:%s'});" value="" class="txtbox4" name="subject_first[shijian][]" >


              </span>
              <?php if (!empty($subject_first['subject_id'])) {?>
              <input type="button" value="删除" onclick="delItem($(this))" <?php echo $i == 1 ? 'style="display:none;"' : '';?>/>
              <input type="button" style="display:none;" value="添加" onclick="addItem('subject_first')" />
              <?php } else {?>
              <input type="button" <?php if ($i == 1) {echo 'style="display:none;"';}?> value="添加" onclick="addItem('subject_first')" />
              <?php }?>
               <span style="color:#f00;position:relative;top:3px;">
            可多选，最多三项。此项在学生为高二和高三年级的时候为必填项。</span>
            </div>
            <?php  } ?>


        </td>
      </tr>
      <tr><td style="border:none;"></td></tr>



            <tr>
        <td width="16%" class="altbg1" style="border-bottom:2px solid #045eab;">第二次参加的选考科目及成绩<span style="color:#f00;position:relative;top:3px;">         (分数集合为【100,97,94,91,88,85,82,79,76,73,70,67,64,61,58,55,52,49,46,43,40】) </span></td>
        <td style="border-bottom:2px solid #045eab;" class="score_rank_td" id="TbData_1">
            <?php
            $subject_two = unserialize($xuekao_xuankao[subject_two]);
            if(!empty($subject_two['subject_id'])): ?>
            <?php $auto_key = 0;
            ?>
            <?php foreach($subject_two[subject_id] as $k => $rank): ?>

            <?php

            $auto_key++;?>
            <div>
              <span>
                <select class="ie_select" name="subject_two[subject_id][]">
                  <option value="">--学科--</option>
                    <?php foreach($subjects as $kk => $v): ?>
                    <option value="<?=$kk?>"<?php if($rank==$kk) echo ' selected="selected"';?>><?=$v?></option>
                    <?php endforeach; ?>
                </select>
			                 分数<input type="text" name="subject_two[fenshu][]" class="txtbox5" value="<?=$subject_two['fenshu'][$k]?>">
			                  时间<input type="text" onclick="WdatePicker({dateFmt:'yyyy-MM-dd',startDate:'%y-%M-%d %h:%m:%s'});" value="<?=$subject_two['shijian'][$k]?>" class="txtbox4" name="subject_two[shijian][]" >
              </span>
              <?php if ($auto_key == 1) {?>
              <input type="button" value="添加" onclick="addItem('subject_two')" />
              <?php } else { ?>
              <input type="button" value="删除" onclick="delItem($(this))" />
              <?php } ?>
            </div>

            <?php endforeach; ?>
            <?php endif;?>

            <?php for ($i = 1; $i <= 2; $i++) {?>
            <div <?php echo $i == 1 ? 'id="subject_two" style="display:none;"' : '';?>>
              <span>
                <select class="ie_select" name="subject_two[subject_id][]">
                  <option value="">--学科--</option>
                    <?php foreach($subjects as $k => $v): ?>
                    <option value="<?=$k?>"><?=$v?></option>
                    <?php endforeach; ?>
                </select>
                <input type="hidden" name="subject_two[id][]" value="" />
			               分数 <input type="text" name="subject_two[fenshu][]" class="txtbox5" value="">
			             时间 <input type="text" onclick="WdatePicker({dateFmt:'yyyy-MM-dd',startDate:'%y-%M-%d %h:%m:%s'});"  class="txtbox4" name="subject_two[shijian][]" >
              </span>
              <?php if (!empty($subject_two['subject_id'])) {?>
              <input type="button" value="删除" onclick="delItem($(this))" <?php echo $i == 1 ? 'style="display:none;"' : '';?>/>
              <input type="button" style="display:none;" value="添加" onclick="addItem('subject_two')" />
              <?php } else {?>
              <input type="button" <?php if ($i == 1) {echo 'style="display:none;"';}?> value="添加" onclick="addItem('subject_two')" />
              <?php }?>
               <span style="color:#f00;position:relative;top:3px;">
            可多选，最多三项</span>
            </div>
            <?php  } ?>
        </td>
      </tr>
      <tr><td style="border:none;"></td></tr>



            <tr>
        <td width="16%" class="altbg1" style="border-bottom:2px solid #045eab;">已经参加的学科科目及成绩<span style="color:#f00;position:relative;top:3px;">  </span></td>
        <td style="border-bottom:2px solid #045eab;" class="score_rank_td" id="TbData_2">
            <?php
            $subject_finish = unserialize($xuekao_xuankao[subject_finish]);

             if(!empty($subject_finish[subject_id])): ?>
            <?php $auto_key = 0;

            ?>
            <?php foreach($subject_finish[subject_id] as $k => $rank): ?>
            <?php

            $auto_key++;?>
            <div>
              <span>
                <select class="ie_select" name="subject_finish[subject_id][]">
                  <option value="">--学科--</option>
                    <?php foreach($subjects as $kk => $v): ?>
                    <option value="<?=$kk?>"<?php if($rank==$kk) echo ' selected="selected"';?>><?=$v?></option>
                    <?php endforeach; ?>
                </select>


                <select class="ie_select" name="subject_finish[rank][]">
                  <option value="">--成绩等级--</option>
                    <?php foreach($ranks as $kk => $v): ?>
                    <option value="<?=$kk?>"<?php if($subject_finish[rank][$k]==$kk) echo ' selected="selected"';?>><?=$v?></option>
                    <?php endforeach; ?>
                </select>

              </span>
              <?php if ($auto_key == 1) {?>
              <input type="button" value="添加" onclick="addItem('subject_finish')" />
              <?php } else { ?>
              <input type="button" value="删除" onclick="delItem($(this))" />
              <?php } ?>
            </div>

            <?php endforeach; ?>
            <?php endif;?>

            <?php for ($i = 1; $i <= 2; $i++) {?>
            <div <?php echo $i == 1 ? 'id="subject_finish" style="display:none;"' : '';?>>
              <span>
                <select class="ie_select" name="subject_finish[subject_id][]">
                  <option value="">--学科--</option>
                    <?php foreach($subjects as $k => $v): ?>
                    <option value="<?=$k?>"><?=$v?></option>
                    <?php endforeach; ?>
                </select>
                <select class="ie_select" name="subject_finish[rank][]">
                  <option value="">--成绩等级--</option>
                    <?php foreach($ranks as $kk => $v): ?>
                    <option value="<?=$kk?>"><?=$v?></option>
                    <?php endforeach; ?>
                </select>
              </span>
              <?php if (!empty($subject_finish[subject_id])) {?>
              <input type="button" value="删除" onclick="delItem($(this))" <?php echo $i == 1 ? 'style="display:none;"' : '';?>/>
              <input type="button" style="display:none;" value="添加" onclick="addItem('subject_finish')" />
              <?php } else {?>
              <input type="button" <?php if ($i == 1) {echo 'style="display:none;"';}?> value="添加" onclick="addItem('subject_finish')" />
              <?php }?>
            </div>
            <?php  } ?>
        </td>
      </tr>
      <tr><td style="border:none;"></td></tr>

<? }// comment now  ?>

    </table>
    <center style="margin-bottom:20px;">
  <?php if($uid OR $this->session->userdata('complete')):?>
    <input type="submit" name="dosubmit" value=" 保存修改  " class="btn" />
  <?php else: ?>
    <input type="button" value=" 上一步 " onclick="location='<?=site_url('student/profile/base')?>'" class="btn" />
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <input type="submit" name="dosubmit"  value=" 下一步 " class="btn" />
  <?php endif; ?>
  </center>
  </div>
  </form>
</div>

<div id="scroll_s">
<style type="text/css">
table.pop_dialog_table {
    border-collapse: collapse;
    margin: auto;
    table-layout: fixed;
    background: rgba(0, 0, 0, .45);
    border-radius: 7px;
    background-color: #8b8b8b\9 ;
    width: 650px;
}

table.pop_dialog_table em {
    font-style: normal
}

td.pop_topleft, td.pop_topright, td.pop_bottomleft, td.pop_bottomright {
    height: 10px;
    overflow: hidden;
    padding: 0 !important;
    width: 10px !important
}

td.pop_content {
    background-color: #FFF;
    padding: 0
}

td.pop_content.morpadding_bluebg {
    padding: 10px;
    background-color: #d2d9e6
}

td.pop_content h2 {
    background: #3777bc
    border: 1px solid #005eac;
    color: #FFF;
    font-size: 14px;
    font-weight: 700;
    margin: 0;
    *zoom: 1
}

td.pop_content h2 span {
    display: block;
    padding: 4px 10px 5px
}

td.pop_content h2 a.floatright {
    float: right
}

td.pop_content .dialog_content {
    background: #fff;
    border: 1px solid #005eac;
    border-top-width: 0
}

td.pop_content .dialog_body p {
    color: #333
}

td.pop_content .dialog_body a, td.pop_content .dialog_body a:visited {
    color: #005eac;
    font-size: 12px;

}

td.pop_content .dialog_content.borderblue {
    border: 1px #8598c0 solid
}

td.pop_content .dialog_body {
    padding: 10px;
    position: relative;
    zoom: 1
}

td.pop_content .no_padding {
    padding: 0
}

td.pop_content .dialog_buttons input {
    line-height: 16px;
    background-color: #005eac !important;
    background-image: none !important;
    border-color: #b8d4e8 #124680 #124680 #b8d4e8 !important;
    border-style: solid;
    border-width: 1px;
    color: #fff
}

td.pop_content .dialog_buttons input.gray {
    border: 1px solid;
    border-color: #fff #848484 #848484 #fff !important;
    background: #f0f0f0 !important;
    color: #333 !important
}

td.pop_content .share_popup {
    padding: 0
}

td.pop_content .dialog_summary {
    background: #f2f2f2;
    padding: 8px 10px;
    border-bottom: 1px solid #ccc
}

td.pop_content .dialog_summary p.centertext {
    margin: 30px;
    text-align: center;
    line-height: 20px
}

td.pop_content .dialog_summary ul.classlist {
    list-style: none
}

td.pop_content .dialog_summary ul.classlist li {
    list-style: none;
    height: 25px;
    line-height: 25px
}

td.pop_content .dialog_summary ul.classlist li input.floatleft {
    background: 0;
    float: left;
    vertical-align: middle;
    margin-right: 5px;
    margin-top: 7px
}

td.pop_content .dialog_summary ul.classlist li .gray {
    color: #b4b4b4
}

td.pop_content .dialog_summary.higher {
    height: 100px;
    padding: 10px
}

td.pop_content .dialog_buttons {
    background: #f0f5f8;
    padding: 8px;
    text-align: right;
    border-top: 1px solid #ccc
}

td.pop_content .dialog_buttons.alignleft {
    text-align: left
}

td.pop_content .dialog_buttons input {
    margin-left: 5px;
    padding: 2px 15px;
    _padding: 2px 10px
}

td.pop_content .dialog_buttons_left_msg {
    float: left
}

td.pop_content .loading {
    padding: 10px;
    font-size: 14px;
    font-weight: 700;
    background: #f7f7f7
}

td.pop_content input, td.pop_content select {
    vertical-align: middle
}

td.pop_content p {
    margin-bottom: 1ex
}

.dialogtips {
    padding: 4px;
    background-color: #feffcf;
    position: absolute;
    top: 0;
    left: 0;
    width: 370px
}

* html .dialogtips {
    left: auto;
    right: 0
}
 #school_select0{
     /*position: relative;*/
 }
 #school_select1{
     /*position: relative;*/
 } 
#school_select2{
     /*position: relative;*/
 }
 .pop_dialog_table{
     position: absolute;
     z-index: 30;
     bottom: -10px;
 }
.contextual_dialog .generic_dialog_popup {
    width: 360px
}

.contextual_dialog .contextual_arrow, .contextual_dialog .contextual_arrow_rev {
    background-image: url(http://a.xnimg.cn/img/minifeed_dialog_triangle.gif);
    background-repeat: no-repeat;
    height: 12px;
    position: relative;
    top: 1px
}

.contextual_dialog .contextual_arrow_rev {
    background-image: url(http://a.xnimg.cn/img/minifeed_dialog_triangle_rev.gif)
}

.contextual_dialog .contextual_arrow span, .contextual_dialog .contextual_arrow_rev span {
    display: none
}

.contextual_dialog h2 {
    color: #000;
    padding-bottom: 4px
}

.contextual_dialog .contextual_dialog_content {
    background-color: #f0f0f0;
    border: 1px solid #b7b7b7;
    border-bottom: 2px solid #005eac;
    line-height: 15px;
    padding: 8px 10px 10px
}

.contextual_dialog .dialog_buttons {
    padding-top: 10px
}

.contextual_dialog .dialog_buttons input {
    margin-right: 10px
}

.errorDialog td.pop_content h2 {
    background: #ffebe8;
    border: 0;
    border-bottom: 1px solid #AAA;
    color: #333
}

.errorDialog td.pop_content h2 span {
    padding: 6px 10px 7px
}

.errorDialog td.pop_content {
    border: 1px solid #ee7c90
}

.errorDialog td.pop_content .dialog_content {
    border: 0
}

.errorDialog td.pop_content .dialog_content .dialog_body {
    padding: 15px
}

ul.square_bullets {
    color: #005eac;
    list-style-image: none;
    list-style-position: outside;
    list-style-type: square;
    padding-left: 20px
}

.share-intro p {
    table-layout: fixed;
    word-wrap: break-word;
    word-break: break-all;
    overflow: hidden
}

.share_popup .tabs {
    padding-top: 15px;
    border-bottom: 1px solid #898989
}

.share_popup .toggle_tabs {
    list-style: none;
    width: 360px;
    margin: 0 auto
}

.share_popup .toggle_tabs li {
    float: left;
    background: #f1f1f1 url(http://a.xnimg.cn/img/toggle_tab_bg.gif) repeat-x 0 1px
}

.share_popup .toggle_tabs li a {
    border: solid #898989;
    border-width: 1px;
    border-left: 0;
    padding: 3px 15px;
    display: block;
    color: #333;
    margin-bottom: -1px
}

.share_popup .toggle_tabs li a.selected {
    color: #fff !important;
    background: #6d84b4;
    border-color: #005eac;
    text-decoration: none
}

.share_popup .toggle_tabs li.first a {
    border: 1px solid #898989
}

.share_popup .toggle_tabs li.first a.selected {
    border-color: #005eac #5973a9
}

.share_popup .toggle_tabs li.middle a {
    border: 1px solid #898989;
    border-left: 0
}

.share_popup .toggle_tabs li.middle a.selected {
    border-color: #005eac #5973a9
}

td.pop_content h2 a {
    float: right;
    padding: 6px 10px;
    color: #fff;
    font-weight: 400;
    font-size: 12px
}

td.pop_content h2 a.close-button {
    position: absolute;
    top: 10px;
    right: 6px;
    padding: 6px 10px;
    color: #fff;
    font-weight: 400;
    font-size: 12px
}

td.pop_content h2 a:hover {
    color: #fff
}

.share_popup .share_header {
    position: relative
}

#popShare .poplogin {
    width: 500px;
    margin: 0 auto
}

.share_popup .title-share {
    position: absolute;
    left: 10px;
    top: 16px;
    padding-left: 20px;
    font-size: 14px;
    font-weight: bolder;
    background: url(http://a.xnimg.cn/img/newsfeed/share.gif) no-repeat left center
}

.share_send, .share_post {
    background: #f7f7f7 none repeat scroll 0;
    padding-top: 15px
}

.share-preview {
    background: #f7f7f7
}

.share_fields {
    padding-bottom: 10px
}

.composer_fields dt {
    float: left;
    margin: 0;
    padding: 0 10px 0 20pt;
    text-align: right;
    width: 65px
}

.composer_fields dd {
    float: left;
    margin: 0 0 10px;
    width: 300px;
    overflow: hidden;
    word-wrap: break-word;
    word-break: break-all
}

.composer_fields dd#dd_privacy_field {
    margin: 0
}

.composer_fields textarea {
    height: 50px;
    margin: 0;
    overflow: auto
}

.composer_fields label {
    color: #666;
    font-weight: 700;
    padding-top: 4px;
    display: block
}

.attachment_stage {
    background-color: #f0f0f0;
    border-bottom: 1px solid #ccc;
    border-top: 1px solid #ccc
}

.s-message .share-footer {
    display: block;
    height: 23px;
    line-height: 23px;
    float: right;
    _margin-top: 3px;
    margin-bottom: -10px;
    *margin-bottom: 0;
    _margin-bottom: -3px;
    padding-left: 0
}

.s-message .share-footer span {
    color: #888;
    _margin-top: 4px;
    display: block;
    float: left
}

.s-message a.m-editor-emo {
    display: block;
    width: 30px;
    height: 23px;
    line-height: 23px;
    padding-left: 25px;
    background-image: url(http://a.xnimg.cn/imgpro/minieditor/action_btn.png);
    background-position: 0 -23px;
    background-repeat: no-repeat;
    outline: 0;
    margin-bottom: -10px;
    *margin-bottom: 0;
    _margin-bottom: -3px;
    float: left
}

.attachment_stage_area {
    overflow: hidden;
    padding: 8px 3px 7px 8px
}

.message-fields .share-title, .message-fields .share-description {
    word-wrap: break-word;
    word-break: break-all;
    line-height: 16px !important;
    zoom: 1
}

.share-body h3 {
    font-weight: normal
}

.share-title {
    font-weight: 700;
    color: #555;
    word-wrap: break-word;
    word-break: break-all;
    line-height: 16px !important;
    zoom: 1;
    overflow: hidden
}

.music-summary {
    margin-top: 5px
}

.share_info.share-with-pic {
    margin-left: 115px
}

.share_thumb {
    border: 1px solid #ccc;
    float: left;
    margin-right: 5px
}

.share_thumb img {
    border: 3px solid #fff
}

.share-description {
    line-height: 18px;
    color: gray
}

.share-description span {
    color: #333
}

.share-description a {
    margin-right: 3px
}

.share_buttons {
    text-align: center;
    padding: 0 60px 10px 0
}

.share_buttons input {
    margin: 0 5px
}

.share_popup div.tokenizer, .share_popup input.inputtext, .share_popup textarea {
    width: 295px;
    border: 1px solid #8496ba
}

.share_popup input.inputtext, .share_popup textarea {
    padding: 5px 0 5px 3px
}

.share-popup-abstract .share-popup-figure {
    float: left;
    margin-right: 10px;
    _display: inline
}

.share-popup-abstract .share-abs-title {
    color: #005dac !important;
    font-weight: bolder
}

.share-popup-abstract .share-abs-content {
    color: #808080 !important
}

.share-success {
    width: 410px;
    padding: 10px 0
}

.share-success-tip {
    width: 100px;
    font-size: 14px;
    text-align: center;
    display: inline-block;
    *display: inline;
    *zoom: 1;
    vertical-align: middle
}

.share-success-more {
    width: 300px;
    text-align: center;
    font-size: 12px;
    border-left: 1px solid #cee1ee;
    display: inline-block;
    *display: inline;
    *zoom: 1;
    vertical-align: middle
}

.share-success-more p {
    margin-top: 10px
}

td.pop_content .dialog_body h1.general {
    font-size: 15px;
    margin-bottom: 15px
}

td.pop_content .dialog_body p.altbox {
    color: #999;
    margin-bottom: 15px;
    padding-bottom: 3px;
    border-bottom: 1px #e0e0e0 solid
}

td.pop_content .dialog_body p.namefilter {
    margin-bottom: 15px
}

td.pop_content .dialog_body p.namefilter label {
    color: #999;
    font-weight: 700
}

td.pop_content .dialog_body p.namefilter .inputtext {
    width: 200px
}

td.pop_content .dialog_body #list-results .selector {
    height: 200px;
    margin-bottom: 15px
}

table.pop_dialog_table.w515 {
    width: 515px
}

#univlist, #searchSchoolList, #highSchoolList {
    position: absolute;
    width: 606px;
    z-index: 9999
}

#univlist_provinces {
    border-bottom: 1px solid #005eac
}

#univlist p label {
    font-weight: lighter;
    color: #333
}

#univlist p .input-text {
    width: 190px;
    background: #fff url(http://a.xnimg.cn/imgpro/bg/cs_navtop.png?timestamp=091222) no-repeat scroll left -175px
}

#univlist_provinces td {
    vertical-align: middle;
    color: #808080;
    text-align: center;
    font-size: 13px
}

#univlist_provinces a {
    font-size: 12px;
    display: block;
    text-decoration: none
}

#univlist_provinces td.activetab a {
    background: #005eac;
    color: #fff
}

#univlist_provinces:after {
    content: ".";
    display: block;
    height: 0;
    clear: both;
    visibility: hidden
}

#univlist_provinces {
    *zoom: 1
}

#univlist_univs {
    list-style: none;
    padding: 5px 10px;
    border: 1px solid #d8dfea;
    background: #fff
}

#univlist_univs:after {
    content: ".";
    display: block;
    height: 0;
    line-height: 0;
    clear: both;
    visibility: hidden
}

#univlist_univs {
    *zoom: 1
}

#univlist_univs li {
    float: left;
    width: 140px;
    border-bottom: 1px solid #f4f4f4;
    line-height: 23px
}

#univlist_univs li.univ {
    width: 112px
}

#univlist_univs li a:hover {
    background: #005eac;
    color: #fff;
    text-decoration: none
}

#searchlist_school {
    list-style: none;
    padding: 5px 10px;
    border: 1px solid #d8dfea;
    background: #fff
}

#searchlist_school:after {
    content: ".";
    display: block;
    height: 0;
    line-height: 0;
    clear: both;
    visibility: hidden
}

#searchlist_school {
    *zoom: 1
}

#searchlist_school li {
    float: left;
    width: 140px;
    border-bottom: 1px solid #f4f4f4;
    line-height: 23px
}

#searchlist_school li.univ {
    width: 112px
}

#searchlist_school li a:hover {
    background: #005eac;
    color: #fff;
    text-decoration: none
}

#univlist .operation a {
    margin-right: 180px
}

#uniList {
    width: 612px
}

.popup-wrapper {
    border: 10px solid #d8dfea;
    position: absolute;
    z-index: 9999;
    overflow: hidden
}

.popup-wrapper iframe {
    position: absolute;
    top: 0;
    left: 0;
    z-index: -1;
    filter: mask();
    width: 3000px;
    height: 3000px;
    display: hidden
}

.popup-content {
    border: 1px solid #005eac;
    background: #f7f7f7;
    padding: 6px;
    overflow: hidden;
    zoom: 1
}

#popup-country {
    font: 13px sans-serif;
    list-style: none;
    overflow: hidden;
    zoom: 1;
    /*margin-left: -36px;*/
}

#popup-country li {
    float: left;
    line-height: 26px !important;
    padding: 0 4px 0 5px;
    background: url(http://a.xnimg.cn/img/popup_country_separator.gif) no-repeat right 50%;
    _border: 0
}

* html #popup-country li {
    background-position: 0 40%
}

#popup-country li a {
    word-break: keep-all;
    _line-height: 26px
}

#popup-country li#c_0, #popup-country li#c_13 {
    background: 0
}

#popup-country li a {
    display: block;
    cursor: pointer
}

#popup-country li.active a {
    font-weight: bold;
    color: #000
}

#popup-country li.active a:hover {
    text-decoration: none
}

#popup-province, #popup-province-hs,#popup-area {
    list-style: none;
    overflow: hidden;
    zoom: 1;
    border: 1px solid #c3c3c3;
    background: #FFF;
    padding: 3px;
	margin-top: 5px;
}

#popup-province li, #popup-province-hs li,#popup-area li{
    font-size: 12px;
    float: left;
    padding-right:10px;
    text-align: center;
    _border: 0
}

#popup-province li a, #popup-province-hs li a, #popup-area li a {
    height: 18px;
    line-height: 18px
}

li.active a, li.active a {
    background: #005eac;
    color: #fff !important
}

#popup-province li.active a:hover, #popup-province-hs li.active a:hover, #popup-area li.active a:hover{
    text-decoration: none
}

#popup-province li a, #popup-province-hs li a, #popup-area li a {
    display: block;
    cursor: pointer
}

#popup-province li#p_0_3, #popup-province li#p_0_20, #popup-province li#p_0_26, #popup-province li#p_0_9 {
    width: 44px
}

#popup-province-hs li#hsp_0_5, #popup-province-hs li#hsp_0_8, #popup-province-hs li#hsp_0_22, #popup-province-hs li#hsp_0_25 {
    width: 44px
}

#popup-unis, #popup-unis-hs {
    list-style: none;
    overflow-x: hidden;
    overflow-y: auto;
    height: 200px;
    zoom: 1;
    border: 1px solid #c3c3c3;
    background: #FFF;
    padding: 10px 0 10px 10px;
    margin: 5px 0
}

#popup-unis li, #popup-unis-hs li {
    float: left;
    width: 160px;
    padding: 4px 12px;
    background: url(http://a.xnimg.cn/img/school_list_dot.gif) no-repeat 0 9px
}

#popup-unis li a:hover, #popup-unis-hs li a:hover {
    background: #005eac;
    color: #FFF;
    text-decoration: none;
	cursor: pointer
}

* html #popup-unis li {
    height: 1.3em
}

#uniList .canbutton {
    float: right
}

.module-popupcity {
    background-color: #fff;
    padding: 3px 8px;
    border: 1px solid #c3c3c3;
    overflow: hidden;
    zoom: 1;
    margin: 5px 0
}

.module-popupcity li {
    list-style: none;
    margin-right: 5px;
    height: 18px;
    display: inline-block;
    *display: inline;
    zoom: 1;
    word-break: keep-all;
    line-height: 18px
}

.module-popupcity li.active {
    _border: 0
}

.module-qulist {
    background-color: #fff;
    overflow: hidden;
    zoom: 1;
    padding: 3px 8px;
    border: 1px #c3c3c3 solid;
    margin-bottom: 5px
}

.module-qulist li {
    display: inline-block;
    list-style: none;
    margin-right: 5px;
    float: left;
    word-break: keep-all;
    height: 18px;
    line-height: 18px;
    _border: 0
}

.module-qulist li a {
    white-space: nowrap
}

.module-schoollist {
    background-color: #fff;
    height: 200px;
    padding: 5px;
    overflow-y: scroll;
    overflow-x: hidden;
    border: 1px #c3c3c3 solid;
    margin-bottom: 5px
}

.module-schoollist li {
    float: left;
    list-style: none;
    display: block;
    width: 170px;
    padding-top: 4px;
    padding-bottom: 4px;
    overflow: hidden;
    padding-left: 10px;
    margin-right: 5px;
    background: url(http://a.xnimg.cn/img/school_list_dot.gif) left 10px no-repeat
}

.module-schoollist li.active {
    _border: 0
}

#scroll_s {
    display: none;
    position : absolute;
    top : 550px;
    left : 60px;
}
</style>
<script type="text/javascript">
var _school_id = '';
$(function(){
    //
    $(document).on('click', 'li[id^=c_]', function(){
        $('li[id^=c_]').removeClass('active');
        $(this).addClass('active');
        _depth_1_selected  = $(this).attr('id').split('_')[1];
        region_city(_depth_1_selected, null, null, 7, 1);
    });
    //
    $(document).on('click', 'li[id^=p_]', function(){
        $('li[id^=p_]').removeClass('active');
        $(this).addClass('active');
        _depth_2_selected  = $(this).attr('id').split('_')[1];
        region_area(_depth_2_selected, null, 7, 1);
    });
    $(document).on('click', 'li[id^=a_]', function(){
        $('li[id^=a_]').removeClass('active');
        $(this).addClass('active');
        _depth_3_selected  = $(this).attr('id').split('_')[1];
        _depth_2_selected  = $('li[id^=p_][class="active"]').attr('id').split('_')[1];
        show_school(_depth_3_selected,_depth_2_selected, 7, 1);
    });
    
    //搜索学校
    $('#school_search_input').keyup(function(){
        keywords = $(this).val();
        $('li[id^=u_]').find('a').each(function(i, item) {
            if ($(this).html().indexOf(keywords)<0)
            {
                $(this).parent().hide();
            }
            else
            {
                $(this).parent().show();
            }
        });
    });
    
    //点击学校，返回id,name，关闭层
    $(document).on('click', 'li[id^=u_]', function(){
        var school_id = $(this).attr('id').split('_')[1];
        $('#'+_school_id).val($(this).find('a').html());
       
        $('#'+_school_id).next().val(school_id);
        
        $('#scroll_s').hide();
    });

    $('input[name^="volunteer"]').blur(function(){
        _school_id = $(this).attr('id');
    });

});
</script>
<table class="pop_dialog_table">
<tbody>
<tr>
    <td class="pop_topleft"></td>
    <td class="pop_border"></td>
    <td class="pop_topright"></td>
</tr>
<tr>
<td class="pop_border"></td>
<td class="pop_content"><h2><span>选择学校</span><a style="display:none;" class="close-button" href="#nogo"
                                                onclick="return false;">关闭</a></h2>

<div class="dialog_content">
<div class="dialog_body">
<div id="univlist" style="position: static;">
<div><p id="filter_univ"><label for="school_search_input">搜索 : </label><input class="input-text" id="school_search_input" name="school_search_input" type="text" autocomplete="off">

</p>
<ul id="popup-country"></ul>
<ul id="popup-province"></ul>
<ul id="popup-area"></ul>
<ul id="popup-unis"></ul>
</div>
</div>
</div>
<div class="dialog_buttons"><input type="button" class=" input-submit" value="关闭" dialog="1"></div>
</div>
</td>
<td class="pop_border"></td>
</tr>
<tr>
    <td class="pop_bottomleft"></td>
    <td class="pop_border"></td>
    <td class="pop_bottomright"></td>
</tr>
</tbody>
</table>
</div>
<script type="text/javascript">
$('document').ready(function (){
    $("#school_select0").click(function(){
       
        $("#scroll_s").css("display","block");
        var school_id0 = parseInt($('#school_id0').val());
        var school_area0 = '<?php if (isset($student['area'])) echo intval($student['area']);?>';
        var school_province0 = '<?php if (isset($student['area'])) echo intval($student['city']);?>';
        var school_country0 = '<?php if (isset($student['area'])) echo intval($student['province']);?>';

        if(school_country0 > 0)
        {
            region_province(0,school_country0,school_province0,school_area0, 7, 1);
        }
        else
        {
            region_province(0,0,0,0, 7, 1);//初始化弹出层
        }
    });
    $(".input-submit").click(function(){
        $("#scroll_s").css("display","none");
    });

     $("#school_select1").click(function(){
       
        $("#scroll_s").css("display","block");
        var school_id1 = parseInt($('#school_id1').val());
        var school_area1 = '<?php if (isset($student['area'])) echo intval($student['area']);?>';
        var school_province1 = '<?php if (isset($student['area'])) echo intval($student['city']);?>';
        var school_country1 = '<?php if (isset($student['area'])) echo intval($student['province']);?>';

        if(school_country1 > 0)
        {
            region_province(0,school_country1,school_province1,school_area1, 7, 1);
        }
        else
        {
            region_province(0,0,0,0, 7, 1);//初始化弹出层
        }
    });
    $(".input-submit").click(function(){
        $("#scroll_s").css("display","none");
    });

     $("#school_select2").click(function(){
       
        $("#scroll_s").css("display","block");
        var school_id2 = parseInt($('#school_id2').val());
        var school_area2 = '<?php if (isset($student['area'])) echo intval($student['area']);?>';
        var school_province2 = '<?php if (isset($student['area'])) echo intval($student['city']);?>';
        var school_country2 = '<?php if (isset($student['area'])) echo intval($student['province']);?>';

        if(school_country2 > 0)
        {
            region_province(0,school_country2,school_province2,school_area2,7, 1);
        }
        else
        {
            region_province(0,0,0,0,7,1);//初始化弹出层
        }
    });
    $(".input-submit").click(function(){
        $("#scroll_s").css("display","none");
    });
});
</script>


<?php $this->load->view('common/profile_footer');?>
