<?php $this->load->view('common/profile_header', array('topmenu' => 'profile', 'submenu' => 'base'));?>
<?php
    // 根路径
    echo "<script>root_url = '".rtrim(site_url(''),'/')."';</script>";
    static_js('schools.js');
    static_global(array('js/datepicker/wdatepicker.js'));
    $vc = C('virtual_currency');
?>
<?php 
    static_global(array('js/common/address.js', 
                    'js/common/region.js'));
?>
<style type="text/css">
div.cls_item_div_ul_list {
    margin:4px 0px 0px 4px;
    padding:4px;
    border-width:1px 0px 1px 0px;
    border-style:solid;
    border-color:black;
    height:300px;
    overflow-y:auto;
}
div.cls_item_div_ul_list ul {
    list-style-type:none;
}

div.cls_item_div_ul_list ul li {
    float:left;
    width:25%;
    cursor:pointer;
}
</style>
<script tyle="text/javascript">
function check_base(form)
{
    var uid = form.uid.value;
    var action = form.action.value;

<? 
    /*
    if (form.school_id.value == '0' || form.school_id.value == '')
    {
        alert('请选择您的所在学校！');
        return false;
    }
     */
?>

    if ((jQuery("#selProvinces option").size() > 1 && form.sb_addr_provid.value == '0')
        || (jQuery("#selCities option").size() > 1 && form.sb_addr_cityid.value == '0')
        || (jQuery("#selAreas option").size() > 1 && form.sb_addr_areaid.value == '0'))
    {
        alert('请选择您的家庭地址所在省市区！');
        return false;
    }
    if (!form.sb_addr_desc.value.trim())
    {
        alert('请填写您家庭地址！');
        form.sb_addr_desc.focus();
        return false;
    }

    var prov = jQuery("#selProvinces option:selected").text();
    var city = jQuery("#selCities option:selected").text();
    var area = jQuery("#selAreas option:selected").text();
    if (prov == city)
    {
        form.address.value = city + area + ' ' + form.sb_addr_desc.value;
    }
    else
    {
        form.address.value = prov + city + area + ' ' + form.sb_addr_desc.value;
    }
    if (!is_zipcode(form.zipcode.value.trim()))
    {
        alert('请填写邮编！');
        form.zipcode.focus();
        return false;
    }

    if (form.no_tiid.checked == false)
    {
        if (form.ti_name.value == '')
        {
            alert('请填写培训学校');
            return false;
        }
        if (form.cors_name.value == '')
        {
            alert('请填写培训课程');
            return false;
        }
        if (form.sbc_teachers.value == '')
        {
            alert('请填写授课老师');
            return false;
        }
    }

    if (fnGetCheckBoxValues('body', 'sbs_stunumtype[]') == '')
    {
        alert('请选择可接受的授课模式');
        return false;
    }

    if (fnGetCheckBoxValues('body', 'sbclassid_classid[]') == '')
    {
        alert('请选择希望辅导难度');
        return false;
    }

    return true;
}

function fnSetTIIDNameClick()
{
    var ti_name = jQuery('#id_ti_name_defined').get(0).value;
    if (ti_name.length < 1)
    {
        alert('请输入自定义培训机构名称(省市区与家庭住址相同)');
        return;
    }
    fnSetTIIDName('', ti_name);
}

function fnSetTIIDName(ti_id, ti_name)
{
    if (ti_id != jQuery('#id_sbc_tiid').get(0).value)
    {
        jQuery('#id_sbc_corsid').get(0).value = '';
        jQuery('#id_cors_cmid').get(0).value = '';
        jQuery('#id_cors_name').get(0).value = '';
    }
    jQuery('#id_sbc_tiid').attr('value', ti_id);
    jQuery('#id_ti_name').attr('value', ti_name);
    fnCloseDialog('id_sbc_tiid_dlg');
}

function fnSetTIListDiv(ti_list)
{
    var str = '';
    for (var i = 0; i < ti_list.length; i++)
    {
        str += '<li onclick="fnSetTIIDName(' + ti_list[i]['ti_id'] + ', jQuery(this).text())">' + ti_list[i]['ti_name'] + '</li>';
    }
<? /*
    for (var i = 0; i < 100; i++)
    {
        str += '<li>' + '这是的是安是的分服是安是但' + '</li>';
    }
 */ ?>

    $("#id_ti_list > ul").html(str);
}

function fnSetCORSIDNameClick()
{
    var cors_name = jQuery('#id_cors_name_defined').get(0).value;
    if (cors_name.length < 1)
    {
        alert('请输入自定义培训课程名称');
        return;
    }
    var cors_cmid = jQuery('#id_cors_cmid_1').get(0).checked ? 1 : 2;
    fnSetCORSIDName('', cors_name, cors_cmid);
}

function fnSetCORSIDName(cors_id, cors_name, cors_cmid)
{
    jQuery('#id_sbc_corsid').get(0).value = cors_id;
    jQuery('#id_cors_name').get(0).value = cors_name;
    jQuery('#id_cors_cmid').get(0).value = cors_cmid;
    fnCloseDialog('id_sbc_corsid_dlg');
}

function fnSetCORSListDiv(cors_list)
{
    var str = '';
    for (var i = 0; i < cors_list.length; i++)
    {
        str += '<li onclick="fnSetCORSIDName(' + cors_list[i]['cors_id'] + ', jQuery(this).text(), ' + cors_list[i]['cors_cmid'] + ')">' + cors_list[i]['cors_name'] + '</li>';
    }
<? /*
    for (var i = 0; i < 100; i++)
    {
        str += '<li>' + '课程课程安是的分服是安是但' + '</li>';
    }
 */ ?>

    $("#id_cors_list > ul").html(str);
}


function fnSetCTeacherClick()
{
    var cteachers = jQuery('#id_sbc_teachers_defined').get(0).value;
    if (cteachers .length < 1)
    {
        alert('请输入自定义授课教师名称');
        return;
    }
    fnSetCTeacher(cteachers);
}

function fnSetCTeacher(cteachers)
{
    jQuery('#id_sbc_teachers').get(0).value = cteachers;
    fnCloseDialog('id_sbc_teachers_dlg');
}

function fnSetCTeacherListDiv(ct_list)
{
    var str = '';
    for (var i = 0; i < ct_list.length; i++)
    {
        str += '<li onclick="fnSetCTeacher(jQuery(this).text())">' + ct_list[i]['ct_name'] + '</li>';
    }
<? /*
    for (var i = 0; i < 100; i++)
    {
        str += '<li>' + '教师教师是安是但' + '</li>';
    }
 */?>

    $("#id_cteacher_list > ul").html(str);
}


function fnShowDlg1()
{
    var ti_id = jQuery('#id_sbc_tiid').attr('value');
    var ti_name = jQuery('#id_ti_name').attr('value');

    if (ti_id == '')
    {
        jQuery('#id_ti_name_defined').get(0).value = ti_name;
    }
    fnShowDialog('id_sbc_tiid_dlg');
}

function fnShowDlg2()
{
    if (jQuery('#id_ti_name').attr('value').length < 1)
    {
        alert('请先填写培训机构');
        return;
    }
    var tiid = jQuery('#id_sbc_tiid').attr('value');
    jQuery("#id_cors_tiid").get(0).value = tiid;
    if (tiid == '')
    {
        jQuery('#id_cors_list > ul').html('');
        jQuery("#id_qry_cors_cmid").attr('disabled', 'disabled');
        jQuery("#id_qry_cors_name").attr('disabled', 'disabled');
        jQuery("#id_qry_cors_btn").attr('disabled', 'disabled');

    }
    else
    {
        jQuery("#id_qry_cors_cmid").removeAttr('disabled');
        jQuery("#id_qry_cors_name").removeAttr('disabled');
        jQuery("#id_qry_cors_btn").removeAttr('disabled');
    }
    var cors_id = jQuery("#id_sbc_corsid").attr('value');
    if (cors_id == '')
    {
        jQuery("#id_cors_name_defined").get(0).value = jQuery("#id_cors_name").get(0).value;
        if (jQuery("#id_cors_cmid").attr('value') == 1)
        {
            jQuery("#id_cors_cmid_1").get(0).checked =  true;
        }
        else
        {
            jQuery("#id_cors_cmid_1").get(0).checked =  false;
        }
    }
    fnShowDialog('id_sbc_corsid_dlg');
}

function fnShowDlg3()
{
    if (jQuery('#id_ti_name').get(0).value.length < 1)
    {
        alert('请先填写培训机构');
        return;
    }
    if (jQuery('#id_cors_name').get(0).value.length < 1)
    {
        alert('请先填写培训课程');
        return;
    }

    var cors_id = jQuery('#id_sbc_corsid').get(0).value;
    jQuery('#id_cteacher_cors_id').get(0).value = cors_id;
    if (cors_id == '')
    {
        jQuery('#id_cteacher_list > ul').html('');
        jQuery('#id_sbc_teachers_defined').get(0).value = jQuery('#id_sbc_teachers').get(0).value;
        jQuery('#id_cteacher_cors_id').attr('disabled', 'disabled');
        jQuery('#id_qry_cteacher_name').attr('disabled', 'disabled');
        jQuery('#id_qry_cteacher_btn').attr('disabled', 'disabled');
    }
    else
    {
        jQuery('#id_sbc_teachers_defined').get(0).value = jQuery('#id_sbc_teachers').get(0).value;
        jQuery('#id_cteacher_cors_id').removeAttr('disabled');
        jQuery('#id_qry_cteacher_name').removeAttr('disabled');
        jQuery('#id_qry_cteacher_btn').removeAttr('disabled');
    }
    fnShowDialog('id_sbc_teachers_dlg');
}

function fnOnCheckBoxNOTIChanged()
{
    var bChecked = jQuery('#id_checkbox_noti').get(0).checked;
    if (bChecked)
    {
        jQuery('#id_ti_name').attr('disabled', 'disabled');
        jQuery('#id_cors_name').attr('disabled', 'disabled');
        jQuery('#id_sbc_teachers').attr('disabled', 'disabled');
    }
    else
    {
        jQuery('#id_ti_name').removeAttr('disabled', 'disabled');
        jQuery('#id_cors_name').removeAttr('disabled', 'disabled');
        jQuery('#id_sbc_teachers').removeAttr('disabled', 'disabled');
    }
}

$(function() {
<? if (!isset($student['sbc_uid'])) { ?>
    jQuery('#id_checkbox_noti').get(0).checked = true;
    fnOnCheckBoxNOTIChanged();
<? } ?>
});
</script>
<div id="body">
  <form method="POST" name="form_base" action="<?=site_url('student/profile/base_save')?>" enctype="multipart/form-data" onsubmit="return check_base(this);">
  <input type="hidden" name="uid" value="<?=$uid?>">
  <input type="hidden" name="action" value="<?=$action?>">

      <div class="space">
          <table class="maintable" id="table_basic" border="0" cellspacing="0" cellpadding="0">
              <tr><td style="border:none;height:10px;"></td></tr>
      <tr>
        <td colspan="2" class="altbg2" style="text-align: left;">
            <span class="altbg2-bg">家庭住址</span>
          	<i class="altbg2-r"></i>
        </td>
      </tr>
<? /*
        <tr>
            <td class="altbg1">年级</td>
            <td>
              <select name="grade_id" id="select_grade_id">
                <option value="0">--请选择--</option>
<?php $grade_list = array_reverse(C('grades'), true);
                foreach($grade_list as $key => $val): ?>
                <option value="<?=$key?>"<?=$key==$student['grade_id']?' selected="selected"':''?>><?=$val?></option>
                <?php endforeach; ?>
              </select>
              <span style="color:#f00">*</span>
            </td>
        </tr>
        <tr>
            <td class="altbg1">所在学校</td>
            <td>
                <input type="hidden" name="grade_id" id="select_grade_id" value="<?=$student['grade_id']?>"/>
                <input class="txtbox" id="school_select" name="school_name" type="text" value="<?=$student['school_name']?>"/>
                <input id="school_id" name="school_id" type="hidden" value="<?=$student['school_id']?>"/>
              <span style="color:#f00">*</span><span style="color:#f00;display:none" id="_school_select"></span>
            </td>
        </tr>
 */?>
        <tr>
            <td class="altbg1">家庭地址</td>
            <td>
              <select name="sb_addr_provid" id="selProvinces" onchange="region.changed(this, 2, 'selCities');region.changed(document.getElementById('selCities'), 2, 'selAreas');">
                <option value="0">--请选择省--</option>
                <? foreach($province_list as $val) { ?>
                <option value="<?=$val['region_id']?>"<?=$val['region_id']==$student['sb_addr_provid']?' selected="selected"':''?>><?=$val['region_name']?></option>
                <? } ?>
              </select>
              <select name="sb_addr_cityid" id="selCities" onchange="region.changed(this, 3, 'selAreas')">
                <option value="0">--请选择市--</option>
                <? foreach($city_list as $val) { ?>
                <option value="<?=$val['region_id']?>"<?=$val['region_id']==$student['sb_addr_cityid']?' selected="selected"':''?>><?=$val['region_name']?></option>
                <? } ?>
              </select>
              <select name="sb_addr_areaid" id="selAreas">
                <option value="0">--请选择区县--</option>
                <? foreach($area_list as $val) { ?>
                <option value="<?=$val['region_id']?>"<?=$val['region_id']==$student['sb_addr_areaid']?' selected="selected"':''?>><?=$val['region_name']?></option>
                <? } ?>
              </select>
              <input type="text" id="sb_addr_desc" name="sb_addr_desc" value="<?=$student['sb_addr_desc']?>" class="txtbox" />
              <input type="hidden" id="address" name="address" value="<?=$student['address']?>" class="txtbox" />
               <span style="color:#f00">*</span>
            </td>
        </tr>
      <tr>
        <td class="altbg1">邮编</td>
        <td>
          <input type="text" id="zipcode" name="zipcode" value="<?=$student['zipcode']?>" class="txtbox" />
           <span style="color:#f00">*</span>
        </td>
      </tr>

      <tr><td style="border:none;height:10px;"></td></tr>
      <tr>
        <td colspan="2" class="altbg2" style="text-align: left;">
            <span class="altbg2-bg">课外培训</span>
          	<i class="altbg2-r"></i>
        </td>
      </tr>
      <tr>
        <td class="altbg1">参加的培训机构</td>
        <td>
              培训机构
              <input type="hidden" id="id_sbc_tiid" name="sbc_tiid" value="<?=$student['sbc_tiid']?>"/>
              <input type="text" id="id_ti_name" name="ti_name" value="<?=Func::echo_s($student['ti_name'])?>" class="txtbox" readonly="readonly" style="background:lightyellow" onclick="fnShowDlg1()"/>
              培训课程
              <input type="hidden" id="id_sbc_corsid" name="sbc_corsid" value="<?=$student['sbc_corsid']?>"/> 
              <input type="hidden" id="id_cors_cmid" name="cors_cmid" value="<?=$student['cors_cmid']?>"/>
              <input type="text" id="id_cors_name" name="cors_name" value="<?=Func::echo_s($student['cors_name'])?>" class="txtbox" readonly="readonly" style="background:lightyellow" onclick="fnShowDlg2()"/>
              授课教师
              <input type="text" id="id_sbc_teachers" name="sbc_teachers" value="<?=Func::echo_s($student['sbc_teachers'])?>" class="txtbox" readonly="readonly" style="background:lightyellow" onclick="fnShowDlg3()"/>

              <label><input type="checkbox" name='no_tiid' id="id_checkbox_noti" onchange="fnOnCheckBoxNOTIChanged()" <? if ($student['no_tiid']) echo('checked="checked"'); ?> value="1"/>暂无</label>
               <span style="color:#f00">*</span>
        </td>
      </tr>
      <tr>
        <td class="altbg1">可接受的授课模式</td>
        <td>
            <? foreach ($stunumtype_list as $v) { ?>
            <label><input type="checkbox" name="sbs_stunumtype[]" value="<?=$v['csnt_id']?>" <? if (in_array($v['csnt_id'], $student['sbs_stunumtype'])) echo("checked='checked'"); ?>/> <?=Func::echo_s($v['csnt_name'])?><? if ($v['csnt_memo']) { ?>(<?=Func::echo_s($v['csnt_memo'])?>)<? } ?></label>
            <? } ?>
           <span style="color:#f00">*</span>
        </td>
      </tr>
      <tr>
        <td class="altbg1">希望辅导难度</td>
        <td>
            <? foreach ($class_list as $v) { ?>
            <label><input type="checkbox" name="sbclassid_classid[]" value="<?=$v['class_id']?>" <? if (in_array($v['class_id'], $student['sbclassid_classid'])) echo("checked='checked'"); ?>/> <?=Func::echo_s($v['class_name'])?></label>
            <? } ?>
           <span style="color:#f00">*</span>
        </td>
      </tr>

        <tr><td style="border:none;height:10px;"></td></tr>
        <tr>
          <td colspan="2" style="text-align:center;border:none;">
             <center>
                <?php if($uid OR $this->session->userdata('complete')) { ?>
                  <input type="submit" name="dosubmit"  value=" 保存修改  " class="btn"/>
                <?php } else { ?>
                <input type="button" value=" 上一步 " onclick="location='<?=site_url('student/profile/basic')?>'" class="btn" />
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <input type="submit" name="dosubmit" value=" 下一步 " class="btn"/>
                <?php } ?>
              </center>
          </td>
        </tr>
        <tr><td style="border:none;height:10px;"></td></tr>
    </table>
  </div>
  </form>
</div>
<div id="id_sbc_tiid_dlg" style="display:none;width:800px">
  <div class="cls_title">选择或输入培训机构</div>
  <div class="cls_box" style="margin:5px">
     <div>
      <select name="ti_typeid" class="cls_field">
        <option value="">--请选择培训机构类型--</option>
        <? foreach ($tit_list as $val) { ?>
        <option value="<?=$val['tit_id']?>" <?=$val['tit_id'] == $student['ti_typeid'] ? ' selected="selected"' : ''?>><?=Func::echo_s($val['tit_name'])?></option>
        <? } ?>
      </select>
      <select name="ti_provid" id="id_ti_provid" onchange="region.changed(this, 2, 'id_ti_cityid');region.changed(document.getElementById('id_ti_cityid'), 2, 'id_ti_areaid');" class="cls_field">
      <option value="0">--请选择省--</option>
      <? foreach($province_list as $val) { ?>
      <option value="<?=$val['region_id']?>"<?=$val['region_id']==$student['ti_provid']?' selected="selected"':''?>><?=$val['region_name']?></option>
      <? } ?>
    </select>
    <select name="ti_cityid" id="id_ti_cityid" onchange="region.changed(this, 3, 'id_ti_areaid')" class="cls_field">
      <option value="0">--请选择市--</option>
      <? foreach($city_list as $val) { ?>
      <option value="<?=$val['region_id']?>"<?=$val['region_id']==$student['ti_cityid']?' selected="selected"':''?>><?=$val['region_name']?></option>
      <? } ?>
    </select>
    <select name="ti_areaid" id="id_ti_areaid" class="cls_field">
      <option value="0">--请选择区县--</option>
      <? foreach($area_list as $val) { ?>
      <option value="<?=$val['region_id']?>"<?=$val['region_id']==$student['ti_areaid']?' selected="selected"':''?>><?=$val['region_name']?></option>
      <? } ?>
    </select>
    <input type="text" name="ti_name" class='cls_field txtbox'/> <button type="button" onclick="ajax_baseFetchTIList(fnGetFormData('id_sbc_tiid_dlg'))">查询</button>
    </div>
    <div id="id_ti_list" class='cls_item_div_ul_list'>
      <ul>
      </ul>
    </div>
    <div style="clear:both">以上没有我要找的培训机构，自己输入<input type="text" id="id_ti_name_defined" name="ti_name_defined" value="" class="txtbox"/></div>
  </div>
  <div class="cls_dialog_buttons">
    <button type="button" onclick="fnSetTIIDNameClick()">确  定</button>
    <button type="button" onclick="fnCloseDialog('id_sbc_tiid_dlg')">取  消</button>
  </div>
</div>

<div id="id_sbc_corsid_dlg" style="display:none;width:800px">
  <div class="cls_title">选择或输入培训课程</div>
  <div class="cls_box" style="margin:5px">
     <div id='id_sbc_corsid_dlg_qry_div'>
      <input type="hidden" name="cors_tiid" id="id_cors_tiid" value="" class='cls_field'/>
      <select name="cors_cmid" id="id_qry_cors_cmid" class='cls_field'>
        <option value="">--请选择授课模式--</option>
        <? foreach ($cm_list as $val) { ?>
        <option value="<?=$val['cm_id']?>" <?=$val['cm_id'] == $student['cors_cmid'] ? ' selected="selected"' : ''?>><?=Func::echo_s($val['cm_name'])?></option>
        <? } ?>
      </select>
    <input type="text" name="cors_name" id="id_qry_cors_name" class='cls_field txtbox'/> <button type="button" id="id_qry_cors_btn" onclick='ajax_baseFetchCORSList(fnGetFormData("id_sbc_corsid_dlg_qry_div"))'>查询</button>
    </div>
    <div id="id_cors_list" class='cls_item_div_ul_list'>
       <ul>
       </ul>
    </div>
    <div style="clear:both">以上没有我要找的培训课程，自己输入<input type="text" id="id_cors_name_defined" class="txtbox"/><label><input type="checkbox" name="cors_cmid_1" id="id_cors_cmid_1"/>一对一课程</label></div>
  </div>
  <div class="cls_dialog_buttons">
    <button type="button" onclick="fnSetCORSIDNameClick()">确  定</button>
    <button type="button" onclick="fnCloseDialog('id_sbc_corsid_dlg')">取  消</button>
  </div>
</div>

<div id="id_sbc_teachers_dlg" style="display:none;width:800px">
  <div class="cls_title">选择或输入授课教师</div>
  <div class="cls_box" style="margin:5px">
     <div id='id_sbc_teachers_dlg_qry_div'>
    <input type="hidden" name="cors_id" id="id_cteacher_cors_id" class="cls_field"/>
    <input type="text" name="cteacher_name" id='id_qry_cteacher_name' class='cls_field txtbox'/> <button type="button" id='id_qry_cteacher_btn' onclick='ajax_baseFetchCTeacherList(fnGetFormData("id_sbc_teachers_dlg_qry_div"))'>查询</button>
    </div>
    <div id="id_cteacher_list" class='cls_item_div_ul_list'>
        <ul>
        </ul>
    </div>
    <div style="clear:both">以上没有我要找的授课老师, 自己输入<input type="text" id="id_sbc_teachers_defined" class="txtbox"/></div>
  </div>
  <div class="cls_dialog_buttons">
    <button type="button" onclick="fnSetCTeacherClick()">确  定</button>
    <button type="button" onclick="fnCloseDialog('id_sbc_teachers_dlg')">取  消</button>
  </div>
</div>
<?php $this->load->view('common/profile_footer');?>
