<?php echo $this->load->view('common/header.phtml', array('render_simple' => false, 'page_title' => '系统当前时间段没有找到相应的考试'));?>
<style>
body{background:#fff;}
*{padding:0;margin:0;}
.cls_notice{
    margin: 100px auto 0;
    padding: 50px;
    background-color: #ffc;
    border: 1px solid #dedede;
	font-size:14px;
	font-family: "微软雅黑";
	text-align: center;
	overflow: hidden;
}
h1{
	font-size:20px;
	margin-bottom:10px;
}
.cls_notice_pos{
    width: 750px;
    margin: 0 auto;
}
.cls_notice_ico{
    background: url("/source/images/zeming/exam/notice.png") no-repeat;
    _background:none;
    _filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(enabled=true,src='/source/images/zeming/exam/notice.png',sizingMethod='scale');
    width: 146px;
    height: 130px;
    margin-right: 30px;
}
.fl_l {
	display: inline-block;
	float: left;
	padding-top: 30px;
}
.cls_copyright{
    text-align: center;
    margin-top: 20px;
	position: relative;
}
.cls_copyright_main {
    margin-left: 16px;
}
.cls_copyright_tm{
    font-size: 10px;
    position: absolute;
    font-style: normal;
    font-family:tahoma;
}
</style>
<script>
	function close_window()
	{
		window.open('','_self');
		window.close();
	}
</script>
</head>
<body>
	<div class="cls_notice">
		<div class="cls_notice_pos">
			<i class="cls_notice_ico fl_l"></i>
			<div class="fl_l">
			    <h1>系统当前时间段没有找到相应的考试</h1>
			    <p>
			    	您可以：
					<a href="###" id="btn_close" onclick="close_window();">关闭窗口</a>&nbsp;
					<a href="javascript:window.location.reload();">刷新页面</a>（<span class="tip">也可按 F5 键 进行手动刷新</span>）&nbsp;
				</p>
			</div>
		</div>
	</div>
	<?php echo $this->load->view('common/copyright');?>
</body>
</html>