<?php echo $this->load->view('common/header');?>
<?php static_global('js/flexigrid/css/flexigrid.css', 'css'); ?>
<?php static_global('js/flexigrid/js/flexigrid.js'); ?>

<?php static_global('css/third_party/zebra_dialog/flat/zebra_dialog.css', 'css');?>

<script language="javascript">
$(function(){
    fnInitGrid('#id_grid');
});
function check_form(form) {                      
    if (checkbox_check('id[]')) {
        var op = $('#batch_op').val();
        if (op == '') {
            alert('请选择操作类型');
            return false;
        } else {
            var notice = '';
            if (op == 'remove') {
              notice = '移除之后无法再恢复，';
            }
            if (confirm(notice + '您确定要执行该操作么？')) {
                var action = $('#batch_op').find('option[value='+op+']').attr('op');

                form.action = action;
                return true;
            }
        }
    }
    return false;
}

$(document).ready(function(){
    set_batch_option();
    $('.ques_title').find('div').dblclick(function(){
        $(this).toggleClass('line_18');
    });
    $('#batch_op').change(function(){
        set_batch_option();
    });
});

function set_batch_option() {
    var op = $('#batch_op').val();
    if (op == 'relate') {
        $('#batch_extend').show();
    } else {
        $('#batch_extend').hide();
    }
}

</script>

<?php 
  $current_module_url = site_url('admin/invigilate');
  
  $order = $search['order'];

  if ($search['order_type'] == 'asc') 
  {
	$order_type_url = $order_url . '&order_type=desc&order=' . $order;
	$order_type_str = '&nbsp;↑&nbsp;';
  } 
  else 
  {
	$order_type_url = $order_url . '&order_type=asc&order=' . $order;
	$order_type_str = '&nbsp;↓&nbsp;';
  }
?>
<?php $this->load->view('recycle/recycle.phtml');?>
<div id="body">
  <form name="frm_invigilator_list" action="<?php echo $current_module_url . '/index/';?>" method="POST" onsubmit="return check_form(this)">
    <div class="space">
      <div class="subtitle">
监考老师管理


        <?php if ($priv_manage): ?>
          <a class="menu" href="<?php echo $current_module_url . '/add'; ?>">新增监考人员</a>
        <?php endif ?>
<a href="javascript:void(0)" onclick="fnShowDialog('id_qry_dlg')" style="float:right">查询</a>
      </div>

      <table class="" id="id_grid" border="0" cellspacing="0" cellpadding="0">
        <tbody>
          <tr class="cls_title">
            <td width="40">ID</td>
            <td width="200">
              <a href="<?php echo $order == 'email' ? $order_type_url : $order_url . '&order_type=asc&order=email';?>">邮箱帐号<?php echo $order == 'email' ? $order_type_str : '';?></a>
            </td>
            <td width="80">
              <a href="<?php echo $order == 'name' ? $order_type_url : $order_url . '&order_type=asc&order=name';?>">姓名<?php echo $order == 'name' ? $order_type_str : '';?></a>
            </td>
            <td width="160">
              <a href="<?php echo $order == 'memo' ? $order_type_url : $order_url . '&order_type=asc&order=memo';?>">所在单位<?php echo $order == 'memo' ? $order_type_str : '';?></a>
            </td>
            <td width="90">
              <span>手机号码</span>
            </td>
            <td width="120">
              <a href="<?php echo $order == 'time' ? $order_type_url : $order_url . '&order_type=asc&order=time';?>">创建时间<?php echo $order == 'time' ? $order_type_str : '';?></a>
            </td>
            <td width="40">状态</td>
            <td width="200">操作</td>
          </tr>
          <?php if (!count($list)) {?>
            <tr>  
                <td colspan="7" align="center">暂无记录.</td>
            </tr>
            <?php } else { ?>
              <?php
              foreach ($list as $k => $item) {
                    $email = $item['invigilator_email'];
                    $name = $item['invigilator_name'];
                    $memo = $item['invigilator_memo'];
                    $flag = $item['invigilator_flag'];
                    $ctime = $item['invigilator_addtime'];
                    $id = $item['invigilator_id'];
                    $cellphone = $item['cellphone'];
              ?>
                <tr>
                  <td><input type="checkbox" name="id[]" value="<?php echo $id;?>"><?php echo $id;?></td>
                  <td><?php echo $email; ?></td>
                  <td><?php echo $name; ?></td> 
                  <td><?php echo $memo; ?></td>
                  <td><?php echo $cellphone; ?></td>
                  <td><?php echo date('Y-m-d H:i:s', $ctime); ?></td> 
                  <td>
                      <?php if ($flag === '0') {?>
                      <img src="<?php echo __HTML_URL__;?>images/no.gif" title="已禁用">
                      <?php } elseif ($flag === '1') {?>
                      <img src="<?php echo __HTML_URL__;?>images/yes.gif" title="已启用">
                      <?php } else {?>
                      <font color="red">已删除</font>
                      <?php }?>
                  </td> 
                  <td>
                      <?php if ($priv_manage) {?>
                        <a href="<?php echo $current_module_url . '/edit/' . $id;?>">编辑</a> | 
                        <a href="###" i_name="<?php echo $name;?>" class="reset_password" rel="<?php echo $id;?>">重置密码</a> |
                        <?php if ($flag == 1): ?>
      				            <?php $remove_id = $id;?>
        		              <a href="javascript:void(0)" onclick="fnShowDialog('delete_box_<?php echo $remove_id;?>')">删除</a>
                        <?php else: ?>
                          <a href="<?php echo $current_module_url . '/do_action/?act=3&id=' . $id;?>" onclick="return confirm('确定要还原该 监考人员的帐号吗？');">还原</a>
                        <?php endif ?>              
                      <?php } ?>
                  </td>
                </tr>
            <?php }?>
            <tr class="altbg1">
              <td colspan="2">
                <?php if ($priv_manage) {?>
                  <button type="button" class="btn2" onclick="checkbox_checked('id[]');">全选</button>
                  <select name="batch_op" id="batch_op">
                    <option value="">-选择操作-</option>
                    <option value="">暂无！</option>
                  </select>
                <?php } ?>
              </td>
              <td colspan="8" style="text-align:right"><?=$pagination?></td>
            </tr> 
          <?php  } ?>
        </tbody>
      </table>
      <center>
      	  <input type="submit" name="dosubmit" value=" 提交操作 " class="btn" />
      </center>
    </div>
  </form>



              <?php
              if ($list) { foreach ($list as $k => $item) {
                    $name = $item['invigilator_name'];
                    $flag = $item['invigilator_flag'];
                    $id = $item['invigilator_id'];
              ?>


                        <?php if ($flag == 1) {  ?>
      				            <?php $remove_id = $id;?>
            		          <div id="delete_box_<?php echo $remove_id;?>" style="display:none;">
                                      <div class="cls_title">请输入删除(<?=$name?>)原因</div>
                                      <div class="space" style="margin:5px">
            		        			<textarea title="请输入 删除原因" placeholder="请输入 删除原因" name="note" id="txt_reason_<?php echo $remove_id;?>"></textarea>
<div class="cls_dialog_buttons" align="center">
            		        			<input type="button" value="保存" class="btn btn_submit_delete" delete_id="<?php echo $remove_id;?>" post_url="<?php echo $current_module_url . '/do_action/?act=2&id=' . $id;?>" rel="<?php echo $remove_id;?>" id="btn_submit_<?php echo $remove_id;?>" style="margin-top:5px"/>
            		        			<input type="button" value="取消" class="btn" onclick="fnCloseDialog('delete_box_<?=$remove_id?>')"/>
</div>
</div>
            				      </div>
                        <?php } ?>
                    <? } } ?>




<div id="id_qry_dlg" style="display:none">
        <div class="cls_title">搜索监考人员信息</div>
  <form method="get" name="search_form" action="<?php echo $current_module_url . '/index/'?>">
    <div class="space" style="margin:5px">
        <table class="maintable" border="0" cellspacing="0" cellpadding="0">
            <tr>
                <td class="altbg1">电子邮箱</td>
                <td>
                  <input type="text" class="" name="email" value="<?php echo isset($search['email']) ? $search['email'] : '';?>" placeholder="请输入 电子邮箱"/>
                </td>
            </tr>
            <tr>
                <td class="altbg1">关键字(姓名)</td>
                <td>
                  <input type="text" name="name" value="<?php echo isset($search['name']) ? $search['name'] : '';?>" placeholder="请输入 姓名"/>
                </td>
            </tr>              
        </table>
        <center>
            <input type="submit" value=" 搜索 " class="btn" /> 
            <input type="button" value="重置 " class="btn" onclick="window.location.href='<?php echo $current_module_url . '/index';?>'"/>
        </center>
    </div>
  </form>
</div>
</div>

<script type="text/javascript">
  $(document).ready(function () {

      //重置密码
      $('a.reset_password').unbind('click').bind('click', function () {
            var uid = $(this).attr('rel'),
            	uname = $(this).attr('i_name');
			new $.Zebra_Dialog('', {
			    'source':  {'ajax': '<?php echo $current_module_url . '/load_reset_password/';?>' + uid},
			    'type':     '',
			    width: 890,
			    'title': '修改 监考老师 (<font color="red" style="font-size:16px;">' + uname + '</font>) 的密码'
			});
			
			setTimeout(function () {
				$('div.ZebraDialog_Buttons').hide();
			}, 500);
	});
    	
	window.close_dialog = function () {$('.ZebraDialog_Button_0').click();}
});
</script>

<?php echo $this->load->view('common/footer');?>
<?php static_global('js/third_party/zebra_dialog.js');?>
