<?php $this->load->view('common/header');?>
<script language="javascript">
var preview_url = '';
var max_sort = <?=count($paper)?>;

function set_preview_url() {
   preview_url = "?exam_pid=<?=$exam['exam_id']?>&place_id=<?=$place_id?>";
   var paper_id = '';
   $("input[name^='paper_id']").each(function(){
	    if ($(this).prop("checked") == true)
	    {
		    var subject_id = $(this).attr('subject_id');
		    var p_id = $(this).val();
		    paper_id += subject_id +"_"+  p_id + ",";
	    }
   });

   paper_id = paper_id.substr(0, paper_id.length - 1);
   if (paper_id)
   {
	   preview_url += "&paper_id="+paper_id;
   }

   var paper_sort = '';
   var err = false;
   $("input[name^='paper_sort']").each(function(){
	    var subject_id = $(this).attr('subject_id');
	    var sort = $(this).val();
	    if (sort > max_sort)
	    {
	    	 err = true;
	    	 return false;
		}

	    paper_sort += subject_id +"_"+  sort + ",";
   });

   if (err)
   {
	   alert('排序数字不能大于'+max_sort);
  	   $('#preview_paper').attr('href', 'javascript:void(0);');
  	   $('#preview_paper_answer').attr('href', 'javascript:void(0);');
  	   $('#preview_paper').removeAttr('target');
	   $('#preview_paper_answer').removeAttr('target');
  	   return;
   }

   paper_sort = paper_sort.substr(0, paper_sort.length - 1);
   if (paper_sort)
   {
	   preview_url += "&paper_sort="+paper_sort;
   }

   $('#preview_paper').attr('href', '/admin/exam_paper/preview/'+preview_url);
   $('#preview_paper_answer').attr('href', '/admin/exam_paper/preview_answer/'+preview_url);
   $('#preview_paper').attr('target', '_blank');
   $('#preview_paper_answer').attr('target', '_blank');
}

$(function(){
	set_preview_url();

	$("input[name^='paper_id']").change(function(){ set_preview_url(); });
	$("input[name^='paper_sort']").blur(function(){ set_preview_url(); });
});

</script>
<div id="body">
  <div class="space">
    <div class="subtitle">
     	<?=$exam['exam_name']?> 成绩导入
    </div>
     <form name="frm_import" id="frm_import" method="POST" action="<?=site_url('admin/place_student/import_save');?>" enctype="multipart/form-data">
  <input type="hidden" name="place_id" value="<?php echo $place_id;?>" />
    <input type="hidden" name="exam_id" value="<?php echo $exam_pid;?>" />
    <table class="maintable" border="0" cellspacing="0" cellpadding="0">
    <tr class="altbg1">
        <td colspan="2" style="text-align:center;" class="altbg2">
         考试：<a href="/admin/exam_place/index/<?=$exam['exam_id']?>"><?=$exam['exam_name']?></a>
---> 场次：<?=$place['place_name']?> --->考试地点：<?=$place['address']?>
        </td>
      </tr>
    <?php if ($paper) {?>
        <?php foreach ($paper as $subject_id => $paper_list) {?>
          <tr class="altbg1">
            <td width="100" style="text-align:center;"><?=$subject[$subject_id]?></td>
            <td>
            <?php foreach ($paper_list as $key => $paper_id) {?>
            <input type="radio" value="<?=$paper_id?>" name="paper_id[<?=$subject_id?>]" id="paper_id_<?=$paper_id?>" subject_id="<?=$subject_id?>" <?php if (!$key) { echo "checked" ;}?>> <label for="paper_id_<?=$paper_id?>"><?=$subject[$subject_id]?>试卷<?=$key+1?></label>
            <?php }?>
            </td>
          </tr>
        <?php }?>
          <tr>
                <td class="altbg1">请选择文件</td>
                <td>
                    <input type="file" name="file" class="txtbox" />
                    <?php if (isset($error)): ?><span style="color:red;display: inline-block;"><?php echo $error; ?></span><?php endif ?>
                </td>
            </tr>
 <tr>
                <td class="altbg1">上传说明</td>
                <td style="padding:10px;">
                    <p>1.支持Excel 2003、Excel 2007、Excel 2010、Excel 2013 版本</p>
                    <p>2.最大文件上传尺寸为10Mb</p>
                    <p>3.准考证号，学生姓名不能为空</p>
                    <p>4.导入时如果当前行发生错误，将跳过当前行继续导入</p>
                    <p>5.重复导入时，如果已经存在面试结果，将覆盖之前的结果</p>
                </td>
            </tr>
            <tr>
                <td class="altbg1">导入模板下载</td>
                <td>
                    <a href="<?php echo base_url('file/changxing0225_175.xls'); ?>">点击下载</a>
                </td>
            </tr>

      <?php } else { ?>
      <tr>
        <td colspan="2">暂无记录！</td>
      </tr>
      <?php }?>
    </table>  <center>
            <input type="submit" value=" 提交 " class="btn" />
        </center>
    </form>
    <?php if ($paper) {?>
    <center>

    </center>
    <?php }?>
  </div>
</div>
<?php $this->load->view('common/footer');?>