<?php $this->load->view('common/header');?>
<script language="javascript">
function check_form(form) {                      
    if (checkbox_check('ids[]')) {
        var op = $('#batch_op').val();
        if (op == '') {
            alert('请选择操作类型');
            return false;
        } else {
            if (confirm('您确定要执行该操作么？')) {
                var action = $('#batch_op').find('option[value='+op+']').attr('op');
                form.action = action;
                return true;
            }
        }
    }
    return false;
}
</script>
<?
$CI = &get_instance();
$bPrivEdit = $CI->check_power_new('production_edit', false); 
$bPrivRemove = $CI->check_power_new('production_del', false);
$bPrivRemoveBatch = $CI->check_power_new('production_batch_delete', false);
$bPrivAdd = $CI->check_power_new('production_add', false);
$bPrivTrans = $CI->check_power_new('account_transactionp', false);
$bPrivAddPC = $CI->check_power_new('production_category_add', false);
?>
<div id="body">
  <form name="frm_cpuser_list" action="<?=site_url('admin/production/batch_delete')?>" method="POST" onsubmit="return check_form(this)">
  <div class="space">
    <div class="subtitle">
<span style="float:left">产品管理 </span>        <span style="float:right"> 
<a href="javascript:void(0)" onclick="fnShowDialog('id_qry_dlg')">查询</a>
<? if ($bPrivTrans) { ?><a href=<?php echo site_url('/admin/account/transactionw');?>>统计报表    </a><? } ?>
<? if ($bPrivAddPC) { ?><a href=<?php echo site_url('/admin/production_category/add');?>>添加产品类别</a><? } ?>
<? if ($bPrivAdd) { ?><a href=<?php echo site_url('/admin/production/add');?>> 添加新产品</a><? } ?>
</span>
    </div>  
    <table class="maintable" border="0" cellspacing="0" cellpadding="0">
      <tr class="altbg1">
        <td width="5%">ID</td>
        <td>产品名称</td>
    
        <td width="20%">产品类型</td>
      
        <td width="10%">创建人</td>
        <td width="10%">创建时间</td>
          <td width="10%">状态</td>
        <td width="15%">操作</td>
      </tr>
      <?php if($list):?>
      <?php foreach($list as $val):?>
      <tr>
        <td><? if ($bPrivRemoveBatch) {?><input type="checkbox" name="ids[]" value="<?=$val['p_id']?>"><? } ?>
        <?=$val['p_id']?></td>
        <td><?=$val['p_name']?></td>        
        <td><?=$val['pc_name']?></td>
        <td><?=$val['user_name']?></td> 
         <td><?=$val['p_c_time']?></td> 
         <td><? if($val['p_status']) echo '启用';else echo '禁用';?></td> 
       
        <td>          
          
        <? if ($bPrivEdit) { ?><a href="<?=site_url('admin/production/edit/'.$val['p_id'])?>">编辑</a><? } ?>
        <? if ($bPrivTrans) { ?><a href="<?=site_url('admin/account/transactionp/'.$val['p_id'])?>">查看交易数据</a><? } ?>
        <? if ($bPrivRemove) { ?>
          <?php if($val['pt_id_count']){
          ?>
            <font style="color:#999;text-decoration:line-through;" title="该产品存在交易记录,因此无法删除">删除</font>
            <?php }else{?>
           <a href="<?=site_url('admin/production/delete/'.$val['p_id'])?>">删除</a>
             <?php } ?>
        <? } ?>
        </td>
      </tr>

      <?php endforeach; ?>
      
      
       <tr class="altbg1">
        <td colspan="2">
          <?php if ($bPrivRemoveBatch) {?>
          <button type="button" class="btn2" onclick="checkbox_checked('ids[]');">全选</button>
          <select name="batch_op" id="batch_op">
           <option value="">-选择操作-</option>
          <option value="restore" op="<?=site_url('admin/production/batch_delete')?>">批量删除</option>
           
          </select>
          <?php } ?>
        </td>
        <td colspan="5" style="text-align:right"><?=$pagination?></td>
      </tr>
      
     
      <?php else: ?>
      <tr>
        <td colspan="7">暂无记录！</td>
      </tr>
      <?php endif; ?>
    </table>

          <?php if ($bPrivRemoveBatch) {?>
    <center><input type="submit" name="dosubmit" value=" 提交操作 " class="btn" /></center>
          <? } ?>
  </div>
  </form>

<div id="id_qry_dlg" style="display:none">
<div class="cls_title">搜索产品信息</div>
  <form method="get" name="search_form" action="<?=site_url('admin/production/index/')?>">
    <div class="space" style="margin:5px">
        <table class="maintable" border="0" cellspacing="0" cellpadding="0">
            <tr>
                <td class="altbg1">产品ID</td>
                <td>
                <input type="text" name="p_id" value="<?=($search['p_id']>0)?$search['p_id']:''?>"/>
                <font color="red">*注：根据产品ID搜索时，其他条件将失效</font>
                </td>
            </tr>  
   
            <tr>
                <td class="altbg1">产品类型</td>
                <td>
                  <select name="pc_id" id="pc_id">
                    <option value="0">--请选择--</option>
                    <?php foreach($pc_ids as $key => $val): ?>
                    <option value="<?=$key?>"<?=$key==$search['pc_id']?' selected="selected" ':''?>><?=$val?></option>
                    <?php endforeach; ?>
                  </select>  
                </td>
            </tr>
            <tr>
                <td class="altbg1">创建人</td>
                <td>                      
                  <select name="admin_id" id="admin_id">
                    <option value="0">--创建人--</option>
                      <?php foreach($admin_ids as $key => $val): ?>
                    <option value="<?=$key?>"<?=$key==$search['admin_id']?' selected="selected" ':''?>><?=$val?></option>
                    <?php endforeach; ?>
                  </select>
                </td>
            </tr> 
      
            <tr>
                <td class="altbg1">关键字</td>
                <td><input type="text" name="keyword" value="<?=$search['keyword']?>" class="txtbox" /></td>
            </tr>   
          
        </table>
        <center><input type="submit" value=" 搜索 " class="btn" /> <input type="button" value="重置 " class="btn" onclick="window.location.href='<?php echo site_url('admin/production');?>'"/></center>
    </div>
  </form>
</div>
</div>
<?php $this->load->view('common/footer');?>

