    <p class="cls_row">&nbsp;</p>
    <p class="cls_row font14">
            注：为表达更加简明扼要，部分数据进行了取整等简化处理，由此可能造成相关数据的误差不影响评价结果。
    </p>
    <h3 class="cls_row">附录一：</h3>
    <h5 class="cls_row">学习风格测评</h5>
    <p class="cls_row">1）理论背景</p>
    <p class="cls_row font14">&emsp;&emsp;本系统学习风格测评基于美国北卡罗来纳州立知名大学教授Richard M. Felder与Barbara A. Soloman的学习风格理论模型。1997年，二人在前人学习风格研究基础上发布了最新研究成果——学习风格研究及策略（Learning Styles and Strategies），以及所罗门学习风格量表（Index of Learning Styles）。该研究成果应用于国内外诸多教、学、测领域，已经逐渐成为全球通用的有数据支撑的学习风格理论测量模型。</p>
    <p class="cls_row">&nbsp;</p>
    <p class="cls_row">2）理论构架</p>
    <p class="cls_row font14">&emsp;&emsp;学习风格是指人们在学习时所具有的或偏爱的方式，换句话说，就是学习者在摄取、消化、解决学习任务时所表现出来的具有个人特色的方式。所罗门学习风格量表剖析了知识内化的过程，把它分为感知、输入、加工、理解四个环节，每一环节又通过二分法区分出两种典型的认知风格，如感知环节表现出具象型及抽象型两种不同的认知风格。每位学习者都必然经历这四个环节，每一环节上表现出不同程度的倾向。所罗门学习风格量表有助于全面地反映学习者的学习风格。</p>
    <p class="cls_row">&nbsp;</p>
    <p class="cls_row">
    <img src="<?php echo __GLOBAL_HTML_URL__;?>/images/zeming/report/learn_style_info.png">
    </p>
    <p class="cls_row">&nbsp;</p>
    <p class="cls_row">3）应用与延伸</p>
    <p class="cls_row font14">&emsp;&emsp;在Felder-Soloman学习风格理论基础上，本测评还做了学习风格与学科关联度的相关应用与延伸。不同学科对学习风格四个环节倾向各有差异。了解自身学习风格以及高中学科知识内化过程倾向的类别，有助于实现两者契合配对，优化选课组合。</p>
    <p class="cls_row">&nbsp;</p>
    <p class="cls_row">环节一：感知</p>
    <p class="cls_row font14">&emsp;&emsp;技术学科要求学习者关注具体、实际和过程性信息，较容易吸引具象型学习者；而物理学科覆盖较多概念及理论性信息，要求学习者具备抽象思维，表现出抽象性认知风格；相对而言，地理学科对具象与抽象能力要求比较均衡。</p>
    <p class="cls_row">&nbsp;</p>
    <p class="cls_row">环节二：输入</p>
    <p class="cls_row font14">&emsp;&emsp;技术学科涵盖了较多的图表信息或操作指示，图像型学习者学习这门学科加得心应手；政治学科文字素材较多，正合适文字型的学习，通过读写提高学习效率；相对而言，学习化学学科图文均有要求，两者认知风格较为均衡的人学起来会游刃有余。</p>
    <p class="cls_row">&nbsp;</p>
    <p class="cls_row">环节三：加工</p>
    <p class="cls_row font14">&emsp;&emsp;历史学科常常要求学习者之间多进行互动交流讨论，在知识加工环节主动型学习者更喜欢这类课程；物理学科崇尚独立的思考、反思推敲，更适合反思型学习者；而在生物学科的学习中，要求学习者能主动参与并积极思考，要求较为均衡。</p>
    <p class="cls_row">&nbsp;</p>
    <p class="cls_row">环节四：理解</p>
    <p class="cls_row font14">&emsp;&emsp;学习技术知识涉及面相对比较分散、强调细节，渐进型认知风格的学习者会比较喜欢这类学科；而如侧重整体理解、把握学习素材的政治学科，框架型学习风格者更加适用；而在化学学科的学习中，两种学习风格要求比较均衡。</p>
    <h3 class="cls_row">附录二：</h3>
    <h5 class="cls_row">学习风格论文索引</h5>
    <p class="cls_row font14">
    LEARNING STYLES AND STRATEGIES, Richard M. Felder Hoechst Celanese Professor of Chemical  Engineering North Carolina State University Barbara A. Soloman Coordinator of Advising,  First Year College North Carolina State University
    </p>
    <p class="cls_row">&nbsp;</p>
    <p class="cls_row font14" style="text-align:center">INDEX OF LEARNING STYLES (ILS)</p>
    <p class="cls_row">&nbsp;</p>
    <p class="cls_row font14">
    The Index of Learning Styles is an on-line instrument used to assess preferences on four dimensions (active/reflective, sensing/intuitive, visual/verbal, and sequential/global) of a learning style model formulated by Richard M. Felder and Linda K. Silverman. The instrument was developed by Richard M. Felder and Barbara A. Soloman of North Carolina State University.
    </p>
    <p class="cls_row">&nbsp;</p>
    <p class="cls_row font14">
    The ILS may be used at no cost for non-commercial purposes by individuals who wish to determine their own learning style profile and by educators who wish to use it for teaching, advising, or research. Consultants and companies who wish to use the ILS in their work may license it. (Click below on "Frequently Asked Questions" for details.)
    </p>
    <p class="cls_row">&nbsp;</p>
    <p class="cls_row font14">
    ILS users should be aware of two important points:
    </p>
    <p class="cls_row">&nbsp;</p>
    <p class="cls_row font14">
        The ILS results provide an indication of an individual's learning preferences and an even better indication of the preference profile of a group of students (e.g. a class), but they should not be over-interpreted. If someone does not agree with the ILS assessment of his or her preferences, trust that individual's judgment over the instrument results.
    </p>
    <p class="cls_row">&nbsp;</p>
    <p class="cls_row font14">
    A student's learning style profile provides an indication of possible strengths and possible tendencies or habits that might lead to difficulty in academic settings. The profile does not reflect a student's suitability or unsuitability for a particular subject, discipline, or profession. Labeling students in this way is at best misleading, and can be destructive if the student uses the label as justification for a major shift in curriculum or career goals. (A learning style preference also does not serve as an excuse for a bad grade on the student's last physics test.) 
    </p>
    <?php 
    if ($is_junior_high)
    {
        $profession = array_unique(array_merge(array_keys($clce_vocational_aptitude['profession']), array_keys($clce_vocational_interest['profession'])));
    }
    else
    {
        $profession = array_unique(array_intersect(array_merge(array_keys($clce_vocational_aptitude['profession']), array_keys($clce_vocational_interest['profession'])),
            array_keys($clce_comprehensive_selection['subject_related_profession'])));
        
    }
    $arr = array();
    if ($profession) 
    {
        $profession_info = $clce_vocational_aptitude['profession'];
        $profession_info2 = $clce_vocational_interest['profession'];
        foreach ($profession as $profession_id)
        {
            if (isset($profession_info[$profession_id]['profession_emerging'])
                && $profession_info[$profession_id]['profession_emerging'])
            {
                $arr[$profession_info[$profession_id]['profession_name']] = $profession_info[$profession_id]['profession_explain'];
            }
            else if (isset($profession_info2[$profession_id]['profession_emerging'])
                && $profession_info2[$profession_id]['profession_emerging'])
            {
                $arr[$profession_info2[$profession_id]['profession_name']] = $profession_info2[$profession_id]['profession_explain'];
            }
        }
    }
    ?>
    <?php if ($arr) {?>
    <h3 class="cls_row">附录三：</h3>
    <h5 class="cls_row">新兴职业说明</h5>
        <?php foreach ($arr as $key => $val) {?>
        <p class="cls_row font14"><b><?=$key?></b>——<?=$val?></p>
        <?php }?>
    <?php }?>
    
    <?php echo $this->load->view('report/table_auto_pager', array('g_real_page_height'=>1283));?>
    </div>
</body>
</html>