<?php echo $this->load->view('common/header');?>
<?php static_global('css/third_party/zebra_dialog/flat/zebra_dialog.css', 'css');?>
<style>
table th{
    text-align:right;
	font-size:14px;
	width: 10%;
}
.cls_footer {
	margin: 0 auto;
	width: 100%;
}
.cls_footer_pos {
	width: auto;
}
</style>
</head>
<body>
<?php echo $this->load->view('common/count_down.phtml');?>	
<div class="cls_body cls_login">
    <?php echo $this->load->view('common/copyright_system_name.phtml');?>
    <div class="cls_content">
        <div class="cls_time clearfix" style="width:500px;">
	        <i class="cls_time_ico fl_l"></i>
	        <p class="cls_time_text fl_l" id="id_statusbar_clock">正在初始化考试计时器...</p>
        </div>
        <table class="cls_top_content">
            <tbody><tr class="cls_instr_item">
                <th>考试期次：</th>
                <td class="cls_instr_text"><?php echo $current_exam['exam_name'];?></td>
                <th>考试场次：</th>
                <td class="cls_instr_text"><?php echo $current_exam['place_name'];?></td>
            </tr>
            <tr class="cls_instr_item">
                <th>考试时间：</th>
                <td class="cls_instr_text"><?php echo $current_exam['start_time'];?> ~ <?php echo $current_exam['end_time'];?></td>
                <th>考试科目：</th>
                <td class="cls_instr_text">
                	<?php $suject_name = trim($current_exam['subject_name']);?>
                	<?php echo $suject_name == '' ? '<font color="red">该场考试未分配科目，请联系监考老师</font>' : $suject_name;?></td>
            </tr>
            <tr class="cls_instr_item">
                <th>地&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;点：</th>
                <td colspan="3" class="cls_instr_text"><?php echo $current_exam['address'];?></td>
            </tr>
            </tbody></table>
        <div class="cls_login_containt clearfix">
            <div class="cls_login_main fl_l">
                <div class="cls_login_title">考生登录</div>
                    <ul class="cls_login_form">
                        <li class="cls_login_form_item clearfix">
                            <label class="fl_l" for="id_xwb_ticket">登录帐号:</label>
                            <input type="text" class="fl_l w-200 login_account" placeholder="Email/准考证号/身份证号" name="exam_ticket" id="txt_exam_ticket"/>
                        </li>
                        <li class="cls_login_form_item clearfix"><label class="fl_l" for="id_xwb_password">登录密码:</label>
                            <input type="password"  class="fl_l w-200 login_pwd" placeholder="请输入登录密码" name="password" id="txt_passwd"/>
                        </li>
                    </ul>
                    <div class="cls_login_button clearfix">
                        <span class="cls_login_btn_block"></span><input class="cls_login_btn cls_button " type="button" name="submit" id="btn_login" value="登录系统">
                        <?php if ($ref == 'index') {?>
                        &nbsp;&nbsp; <input class="cls_login_btn cls_button " type="button" name="submit" id="btn_login" value="返回上一步"  onclick="window.location.href='<?php echo site_url('exam/index/index/');?>'">
                          
						<?php } ?>
						<?php /*?>
                        <div class="cls_jiankao_btn cls_jiankao_pos ">
                            <?php //echo $this->load->view('common/call_teacher.phtml');?>
                        </div>
						<?php */?>
                    </div>
                    <p class="cls_login_msg_tixing "><i class="cls_imgpng"></i><span class="cls_login_msg_text"><strong>注意:</strong><em>忘记密码或无法登录请找监考老师处理</em></span></p>
            </div>
            <div class="cls_msg clearfix fl_l">
                <span class="cls_form_lable">[注意事项]:</span>
                <ul class="cls_form_text cls_form_textear">
                    <li><em><?php echo nl2br($current_exam['student_notice']);?></em></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<?php echo $this->load->view('common/copyright');?>

</body>
<?php static_js(array('front/count_down.js'));?>
<?php static_global('js/third_party/fullscreen.js');?>
<?php static_global('js/third_party/zebra_dialog.js');?>
<?php static_global('js/jquery/plugin/tiper.min.js');?>
<?php static_js(array('login.js'));?>
<script type="text/javascript">
	var check_login_url = '<?php echo site_url('exam/index/check_login/');?>';		
</script>
</html>
