<?php if (isset($sci_knowledge_group_type['extraction_ratio']['internal']) && count($sci_knowledge_group_type['extraction_ratio']['internal'])) {?>
	<?php 
		$sci_knowledge_group_type['extraction_ratio'] = isset($sci_knowledge_group_type['extraction_ratio']) ? $sci_knowledge_group_type['extraction_ratio'] : array();
		$sci_knowledge_group_type['exams'] = isset($sci_knowledge_group_type['exams']) ? $sci_knowledge_group_type['exams'] : array();
		$sci_knowledge_group_type['exam_names'] = array_keys($sci_knowledge_group_type['exams']);
	?>
    <h5 class="cls_row title_level_2"><?=$g_sort?>.<?=$c_sort?><?=$module_name?></h5>
    <table class="cls_row table_header indent_25" id="table_sci_er">
        <tr>
        	<?php $first_th_width = '20';?>
            <th width="<?php echo $first_th_width;?>%">内容所占分值\考试名称</th>
            <?php $count_data = count($sci_knowledge_group_type['exam_names']); ?>
            <?php $left_p_width = !$count_data ? 0 : round((100-$first_th_width)/count($sci_knowledge_group_type['exam_names']));?>
            <?php foreach ($sci_knowledge_group_type['exam_names'] as $exam_name) {?>
                <th width="<?=$left_p_width?>%"><?php echo $exam_name;?></th>
            <?php }?>
        </tr>
    </table>
    
    <?php $er_internal = isset($sci_knowledge_group_type['extraction_ratio']['internal']) ? $sci_knowledge_group_type['extraction_ratio']['internal'] : array(); ?>
    
    <?php if (count($er_internal)) {?>
        <!-- 内部信息提取方式 -->
        <?php $auto_key  = 0;?>
        <?php foreach ($er_internal as $er_name) {?>
            <?php $auto_key++;?>
            <table class="cls_row cls_table indent_25" <?php if (!$no_paging) {?>ref_title_id="table_sci_er"<?php }?>>
                <tr <?php echo $auto_key%2==0 ? 'class="bgc"' : '';?>>
                    <th width="<?=$first_th_width?>%"><?php echo $er_name . '(%)';?></th>
                    <?php foreach ($sci_knowledge_group_type['exam_names'] as $exam_name) {?>
                        <td width="<?=$left_p_width?>%"><?php echo isset($sci_knowledge_group_type['exams'][$exam_name]) && isset($sci_knowledge_group_type['exams'][$exam_name][$er_name]) ? round($sci_knowledge_group_type['exams'][$exam_name][$er_name]) : '0.00';?></td>
                    <?php } ?>
                </tr>
            </table>
        <?php } ?>
    <?php } ?>
<?php } ?>