<?php
/**
 * 考试信息对比
 */
?>
	<!-- 知识点模块 -->
	<?php 
		$sci_knowledge['knowledge'] = isset($sci_knowledge['knowledge']) ? $sci_knowledge['knowledge'] : array();
		$sci_knowledge['exams'] = isset($sci_knowledge['exams']) ? $sci_knowledge['exams'] : array();
		$sci_knowledge['exam_names'] = array_keys($sci_knowledge['exams']);
		
		//分解出我们考试名称
		$exam_names = $sci_knowledge['exam_names'];
		$count_exam_names = count($exam_names);
		$my_exam_name = $count_exam_names ? $exam_names[$count_exam_names-1] : '0';
		array_pop($exam_names);
	?>
    <h3 class="cls_row">1.考试信息对比:<?php echo implode('、', $exam_names);?> 与 <?php echo $my_exam_name;?> 的对比</h3>
    
    <?php $g_order_num = 0;?>
    <?php if (isset($sci_knowledge['knowledge']['internal']) && count($sci_knowledge['knowledge']['internal'])) {?>
    <?php $g_order_num++;?>
        <h5 class="cls_row"><?php echo $g_order_num;?>）	知识模块的对比：</h5>
        <table class="cls_row" id="table_sci_k">
            <tr>
            	<?php $first_th_width = '20';?>
                    <th width="<?=$first_th_width?>%">知识模块\考试名称</th>
                <?php $count_data = count($sci_knowledge['exam_names']); ?>
                <?php $left_p_width = !$count_data ? 0 : round((100-$first_th_width)/count($sci_knowledge['exam_names']));?>
                <?php foreach ($sci_knowledge['exam_names'] as $exam_name) {?>
                    <th width="<?php echo $left_p_width;?>%"><?php echo $exam_name;?></th>
                <?php }?>
            </tr>
        </table>
        <?php $k_internal = isset($sci_knowledge['knowledge']['internal']) ? $sci_knowledge['knowledge']['internal'] : array(); ?>
        <?php $k_external = isset($sci_knowledge['knowledge']['external']) ? $sci_knowledge['knowledge']['external'] : array(); ?>
        
        <?php if (count($k_internal)) {?>
        <?php 
            // 内部修正百分比
            $tmpInternalLast = array_pop($k_internal);

            if ($tmpInternalLast)
            {
                foreach ($sci_knowledge['exam_names'] as $exam_name)
                {
                    $tmpInternalLastPercent = 100;

                    foreach ($k_internal as $key => $value) {
                        $percent = isset($sci_knowledge['exams'][$exam_name][$value]) ? round($sci_knowledge['exams'][$exam_name][$value]) : '0';
                        $tmpInternalLastPercent = $tmpInternalLastPercent - $percent;
                    }

                    $sci_knowledge['exams'][$exam_name][$tmpInternalLast] = round($tmpInternalLastPercent);
                }
                
                array_push($k_internal,$tmpInternalLast);
            }
        ?>
            <!-- 内部知识点 -->
            <?php $auto_key  = 0;?>
            <?php foreach ($k_internal as $k_name) {?>
                <?php $auto_key++;?>
                <table class="cls_row cls_table" ref_title_id="table_sci_k">
                    <tr <?php echo $auto_key%2==0 ? 'class="bgc"' : '';?>>
                        <th width="<?=$first_th_width?>%"><?php echo $k_name . '(%)';?></th>
                        <?php foreach ($sci_knowledge['exam_names'] as $exam_name) {?>
                            <td width="<?php echo $left_p_width;?>%">
                                <?php echo isset($sci_knowledge['exams'][$exam_name]) && isset($sci_knowledge['exams'][$exam_name][$k_name]) ? round($sci_knowledge['exams'][$exam_name][$k_name]) : '0';?>
                            </td>
                        <?php } ?>
                    </tr>
                </table>
            <?php } ?>
        <?php } ?>
        
        <?php if (count($k_external)) {?>
        <?php
            // 外部修正百分比
            $tmpExternalLast = array_pop($k_external);

            if ($tmpExternalLast)
            {
                foreach ($sci_knowledge['exam_names'] as $exam_name)
                {
                    $tmpExternalLastPercent = 100;

                    foreach ($k_external as $key => $value) {
                        $percent = isset($sci_knowledge['exams'][$exam_name][$value]) ? round($sci_knowledge['exams'][$exam_name][$value]) : '0';
                        $tmpExternalLastPercent  = $tmpExternalLastPercent - $percent;
                    }

                    $sci_knowledge['exams'][$exam_name][$tmpExternalLast] = round($tmpExternalLastPercent);
                }

                array_push($k_external,$tmpExternalLast);
            }
         ?>
            <!-- 外部知识点 -->
            <?php foreach ($k_external as $k_name) {?>
                <?php $auto_key++;?>
                <table class="cls_row cls_table" ref_title_id="table_sci_k">
                    <tr <?php echo $auto_key%2==0 ? 'class="bgc"' : '';?>>
                        <th width="<?=$first_th_width?>%"><?php echo $k_name . '(%)';?></th>
                        <?php foreach ($sci_knowledge['exam_names'] as $exam_name) {?>
                            <td width="<?php echo $left_p_width;?>%">
                                <?php echo isset($sci_knowledge['exams'][$exam_name]) && isset($sci_knowledge['exams'][$exam_name][$k_name]) ? round($sci_knowledge['exams'][$exam_name][$k_name]) : '0';?>
                            </td>
                        <?php } ?>
                    </tr>
                </table>
            <?php } ?>
        <?php } ?>
        
        <!-- flash -->
        	<?php $auto_key = 0;?>
        	<?php foreach ($sci_knowledge['exam_names'] as $exam_name) {?>
        	<?php $auto_key++;?>
	        <div id="flash_container_sci_k_<?php echo $auto_key;?>"  class="cls_row"></div>
            <?php }?>
            <?php if (count($sci_knowledge['exam_names'])) {?>
	        <script type="text/javascript">
	        	$(function () {
	        		//考试信息对比--知识点模块 （饼状图）
		            <?php $auto_key = 0;
		             foreach ($sci_knowledge['exam_names'] as $exam_name) {
			             if (!isset($sci_knowledge['exams'][$exam_name])) {continue;}
			             $auto_key++;
			             $flash_exams = $sci_knowledge['exams'][$exam_name];
			             $tmp_arr = array();
			       //       foreach ($k_internal as $k_name) {
				      //       $tmp_arr[] = array(
										// 'name' 	=> $k_name,
										// 'y' 	=> isset($flash_exams[$k_name]) ? round($flash_exams[$k_name]) : 0,
				      //       );
			       //       }
                         //内部
                         $k_internal_tmp = array_values($k_internal);
                         $count = 100;
                         for ($i=0; $i < count($k_internal_tmp); $i++)
                         {
                            if ($i == (count($k_internal_tmp)-1))
                            {
                                $tmp_arr[] = array(
                                    'name'  => $k_internal_tmp[$i],
                                    'y'     => $count,
                                );
                            }
                            else{
                                $tmp_arr[] = array(
                                    'name'  => $k_internal_tmp[$i],
                                    'y'     => isset($flash_exams[$k_internal_tmp[$i]]) ? round($flash_exams[$k_internal_tmp[$i]]) : 0,
                                );
                                $precent = isset($flash_exams[$k_internal_tmp[$i]]) ? round($flash_exams[$k_internal_tmp[$i]]) : 0;
                                $count = $count - $precent;
                            }
                         }

			       //       foreach ($k_external as $k_name) {
				      //       $tmp_arr[] = array(
										// 'name' 	=> $k_name,
										// 'y' 	=> isset($flash_exams[$k_name]) ? round($flash_exams[$k_name]) : 0,
				      //       );
			       //       }
                         $k_external_tmp = array_values($k_external);
                         $count = 100;
                         for ($i=0; $i < count($k_external_tmp); $i++)
                         {
                            if ($i == (count($k_external_tmp)-1))
                            {
                                $tmp_arr[] = array(
                                    'name'  => $k_external_tmp[$i],
                                    'y'     => $count,
                                );
                            }
                            else
                            {
                                $tmp_arr[] = array(
                                    'name'  => $k_external_tmp[$i],
                                    'y'     => isset($flash_exams[$k_external_tmp[$i]]) ? round($flash_exams[$k_external_tmp[$i]]) : 0,
                                );
                                $precent = isset($flash_exams[$k_external_tmp[$i]]) ? round($flash_exams[$k_external_tmp[$i]]) : 0;
                                $count = $count - $precent;
                            }
                         }
		             ?>
		            
		            $('#flash_container_sci_k_<?php echo $auto_key;?>').highcharts({
		                chart: {
		                    plotBackgroundColor: null,
		                    plotBorderWidth: null,
		                    plotShadow: false
		                },
		                title: {
		                    text: '<?php echo $exam_name;?>',	//标题
		                    x: -20 //center
		                },
		                tooltip: {
		                    pointFormat: '{series.name}: <b>{point.percentage:.0f}%</b>'
		                },
		                plotOptions: {
		                    pie: {
		                        allowPointSelect: true,
		                        cursor: 'pointer',
		                        dataLabels: {
		                            enabled: true,
		                            color: '#000000',
		                            connectorColor: '#000000',
		                            format: '<b>{point.name}</b>: {point.percentage:.0f}%'
		                        },
		                        showInLegend: true
		                    }
		                },
		                legend: {
		                    layout: 'vertical',
		                    align: 'right',
		                    verticalAlign: 'middle',
		                    borderWidth: 0,
		                    useHTML:true
		                },
		                //colors: ['#000000','#000000','#000000','#000000'],	//线的颜色
		                series: [{
		                    type: 'pie',
		                    name: '',
		                    data: eval("("+'<?php echo json_encode($tmp_arr); ?>'+")")
		                    /*data: [
		                        {
		                            name: '一级知识点1',
		                            y: 25
		                        },
		                        {
		                            name: '一级知识点2',
		                            y: 15
		                        },
		                        {
		                            name: '一级知识点3',
		                            y: 45
		                        },
		                        {
		                            //color:'#000000',
		                            name: '外部新增知识点',
		                            y: 10
		                        }
		                    ]*/
		                }]
		            });
			        <?php } ?>
	            });
	        </script>
	        <?php } ?>
    <?php } ?>
    
    <?php if (isset($sci_group_type['group_type']['internal']) && count($sci_group_type['group_type']['internal'])) {?>
    <?php $g_order_num++;?>
    	<?php 
			$sci_group_type['group_type'] = isset($sci_group_type['group_type']) ? $sci_group_type['group_type'] : array();
			$sci_group_type['exams'] = isset($sci_group_type['exams']) ? $sci_group_type['exams'] : array();
			$sci_group_type['exam_names'] = array_keys($sci_group_type['exams']);
			
		?>
        <h5 class="cls_row"><?php echo $g_order_num;?>）信息提取方式的对比：</h5>
        <table class="cls_row" id="table_sci_gt">
        <tr>
        	<?php $first_th_width = '20';?>
            <th width="<?php echo $first_th_width;?>%">信息提取方式\考试名称</th>
            <?php $count_data = count($sci_group_type['exam_names']); ?>
            <?php $left_p_width = !$count_data ? 0 : round((100-$first_th_width)/count($sci_group_type['exam_names']));?>
            <?php foreach ($sci_group_type['exam_names'] as $exam_name) {?>
            <th width="<?=$left_p_width?>%"><?php echo $exam_name;?></th>
            <?php }?>
        </tr>
        </table>
        
        <?php $gt_internal = isset($sci_group_type['group_type']['internal']) ? $sci_group_type['group_type']['internal'] : array(); ?>
        
        <?php if (count($gt_internal)) {?>
        <!-- 内部信息提取方式 -->
        <?php $auto_key  = 0;?>
        <?php foreach ($gt_internal as $gt_name) {?>
        <?php $auto_key++;?>
        <table class="cls_row cls_table" ref_title_id="table_sci_gt">
        <tr <?php echo $auto_key%2==0 ? 'class="bgc"' : '';?>>
            <th width="<?=$first_th_width?>%"><?php echo $gt_name . '(%)';?></th>
            <?php foreach ($sci_group_type['exam_names'] as $exam_name) {?>
            <td width="<?=$left_p_width?>%">
            <?php echo isset($sci_group_type['exams'][$exam_name]) && isset($sci_group_type['exams'][$exam_name][$gt_name]) ? round($sci_group_type['exams'][$exam_name][$gt_name]) : '0';?>
            </td>
            <?php } ?>
        </tr>
        </table>
        <?php } ?>
        <?php } ?>
    <?php } ?>
    
    <?php if (isset($sci_extraction_ratio['extraction_ratio']['internal']) && count($sci_extraction_ratio['extraction_ratio']['internal'])) {?>
    <?php $g_order_num++;?>
    	<?php 
			$sci_extraction_ratio['extraction_ratio'] = isset($sci_extraction_ratio['extraction_ratio']) ? $sci_extraction_ratio['extraction_ratio'] : array();
			$sci_extraction_ratio['exams'] = isset($sci_extraction_ratio['exams']) ? $sci_extraction_ratio['exams'] : array();
			$sci_extraction_ratio['exam_names'] = array_keys($sci_extraction_ratio['exams']);
			
		?>
        <h5 class="cls_row"><?php echo $g_order_num;?>）知识点和信息提取方式比例：</h5>
        <table class="cls_row" id="table_sci_er">
        <tr>
        	<?php $first_th_width = '20';?>
            <th width="<?php echo $first_th_width;?>%">内容所占分值\考试名称</th>
            <?php $count_data = count($sci_extraction_ratio['exam_names']); ?>
            <?php $left_p_width = !$count_data ? 0 : round((100-$first_th_width)/count($sci_extraction_ratio['exam_names']));?>
            <?php foreach ($sci_extraction_ratio['exam_names'] as $exam_name) {?>
            <th width="<?=$left_p_width?>%"><?php echo $exam_name;?></th>
            <?php }?>
        </tr>
        </table>
        
        <?php $er_internal = isset($sci_extraction_ratio['extraction_ratio']['internal']) ? $sci_extraction_ratio['extraction_ratio']['internal'] : array(); ?>
        
        <?php if (count($er_internal)) {?>
        <!-- 内部信息提取方式 -->
        <?php $auto_key  = 0;?>
        <?php foreach ($er_internal as $er_name) {?>
        <?php $auto_key++;?>
        <table class="cls_row cls_table" ref_title_id="table_sci_er">
        <tr <?php echo $auto_key%2==0 ? 'class="bgc"' : '';?>>
            <th width="<?=$first_th_width?>%"><?php echo $er_name . '(%)';?></th>
            <?php foreach ($sci_extraction_ratio['exam_names'] as $exam_name) {?>
            <td width="<?=$left_p_width?>%"><?php echo isset($sci_extraction_ratio['exams'][$exam_name]) && isset($sci_extraction_ratio['exams'][$exam_name][$er_name]) ? round($sci_extraction_ratio['exams'][$exam_name][$er_name]) : '0.00';?></td>
            <?php } ?>
        </tr>
        </table>
        <?php } ?>
        <?php } ?>
    <?php } ?>
    
    <?php if (isset($sci_method_tactic['method_tactic']['internal']) && count($sci_method_tactic['method_tactic']['internal'])) {?>
    <?php $g_order_num++;?>
    	<?php 
			$sci_method_tactic['method_tactic'] = isset($sci_method_tactic['method_tactic']) ? $sci_method_tactic['method_tactic'] : array();
			$sci_method_tactic['exams'] = isset($sci_method_tactic['exams']) ? $sci_method_tactic['exams'] : array();
			$sci_method_tactic['exam_names'] = array_keys($sci_method_tactic['exams']);
			
		?>
        <h5 class="cls_row"><?php echo $g_order_num;?>）方法策略覆盖的对比：</h5>
        <table class="cls_row" id="table_sci_mt">
        <tr>
        	<?php $first_th_width = '20';?>
            <th width="<?php echo $first_th_width;?>%">方法策略\考试名称</th>
            <?php $count_data = count($sci_method_tactic['exam_names']); ?>
            <?php $left_p_width = !$count_data ? 0 : round((100-$first_th_width)/count($sci_method_tactic['exam_names']));?>
            <?php foreach ($sci_method_tactic['exam_names'] as $exam_name) {?>
            <th width="<?=$left_p_width?>%"><?php echo $exam_name;?></th>
            <?php }?>
        </tr>
        </table>
        
        <?php $mt_internal = isset($sci_method_tactic['method_tactic']['internal']) ? $sci_method_tactic['method_tactic']['internal'] : array(); ?>
        <?php $mt_external = isset($sci_method_tactic['method_tactic']['external']) ? $sci_method_tactic['method_tactic']['external'] : array(); ?>
        
        <?php if (count($mt_internal)) {?>
            <!-- 内部方法策略 -->
            <?php $auto_key  = 0;?>
            <?php foreach ($mt_internal as $mt_name) {?>
                <?php $auto_key++;?>
                <table class="cls_row cls_table" ref_title_id="table_sci_mt">
                    <tr <?php echo $auto_key%2==0 ? 'class="bgc"' : '';?>>
                        <th width="<?=$first_th_width?>%"><?php echo $mt_name . '(%)';?></th>
                        <?php foreach ($sci_method_tactic['exam_names'] as $exam_name) {?>
                            <td width="<?=$left_p_width?>%"><?php echo isset($sci_method_tactic['exams'][$exam_name]) && isset($sci_method_tactic['exams'][$exam_name][$mt_name]) ? round($sci_method_tactic['exams'][$exam_name][$mt_name]) : '0';?></td>
                        <?php } ?>
                    </tr>
                </table>
            <?php } ?>
        <?php } ?>
        
        <?php if (count($mt_external)) {?>
        <!-- 外部方法策略-->
            <?php foreach ($mt_external as $mt_name) {?>
                <?php $auto_key++;?>
                <table class="cls_row cls_table" ref_title_id="table_sci_mt">
                    <tr <?php echo $auto_key%2==0 ? 'class="bgc"' : '';?>>
                        <th width="<?php echo $first_th_width;?>%"><?php echo $mt_name . '(%)';?></th>
                        <?php foreach ($sci_method_tactic['exam_names'] as $exam_name) {?>
                            <td width="<?php echo $left_p_width;?>%"><?php echo isset($sci_method_tactic['exams'][$exam_name]) && isset($sci_method_tactic['exams'][$exam_name][$mt_name]) ? round($sci_method_tactic['exams'][$exam_name][$mt_name]) : '0';?></td>
                        <?php } ?>
                    </tr>
                </table>
            <?php } ?>
        <?php } ?>
        
        <?php /*?>
        <!-- flash -->
        	<?php $auto_key = 0;?>
        	<?php foreach ($sci_method_tactic['exam_names'] as $exam_name) {?>
        	<?php $auto_key++;?>
	        <div id="flash_container_sci_mt_<?php echo $auto_key;?>"  class="cls_row"></div>
            <?php }?>
            <?php if (count($sci_method_tactic['exam_names'])) {?>
	        <script type="text/javascript">
	        	$(function () {
	        		//考试信息对比--方法策略 （饼状图）
		            <?php $auto_key = 0;
		             foreach ($sci_method_tactic['exam_names'] as $exam_name) {
			             if (!isset($sci_method_tactic['exams'][$exam_name])) {continue;}
			             $auto_key++;
			             $flash_exams = $sci_method_tactic['exams'][$exam_name];
			             $tmp_arr = array();
			             foreach ($mt_internal as $mt_name) {
				            $tmp_arr[] = array(
										'name' 	=> $mt_name,
										'y' 	=> isset($flash_exams[$mt_name]) ? floatval($flash_exams[$mt_name]) : 0,
				            );
			             }
			             foreach ($mt_external as $mt_name) {
				            $tmp_arr[] = array(
										'name' 	=> $mt_name,
										'y' 	=> isset($flash_exams[$mt_name]) ? floatval($flash_exams[$mt_name]) : 0,
				            );
			             }
		            ?>
		             
		            $('#flash_container_sci_mt_<?php echo $auto_key;?>').highcharts({
		                chart: {
		                    plotBackgroundColor: null,
		                    plotBorderWidth: null,
		                    plotShadow: false
		                },
		                title: {
		                    text: '<?php echo $exam_name;?>',	//标题
		                    x: -20 //center
		                },
		                tooltip: {
		                    pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
		                },
		                plotOptions: {
		                    pie: {
		                        allowPointSelect: true,
		                        cursor: 'pointer',
		                        dataLabels: {
		                            enabled: true,
		                            color: '#000000',
		                            connectorColor: '#000000',
		                            format: '<b>{point.name}</b>: {point.percentage:.1f} %'
		                        },
		                        showInLegend: true
		                    }
		                },
		                legend: {
		                    layout: 'vertical',
		                    align: 'right',
		                    verticalAlign: 'middle',
		                    borderWidth: 0,
		                    useHTML:true
		                },
		                //colors: ['#000000','#000000','#000000','#000000'],	//线的颜色
		                series: [{
		                    type: 'pie',
		                    name: '',
		                    data: eval("("+'<?php echo json_encode($tmp_arr); ?>'+")")
		                    data: [
		                        {
		                            name: '一级知识点1',
		                            y: 25
		                        },
		                        {
		                            name: '一级知识点2',
		                            y: 15
		                        },
		                        {
		                            name: '一级知识点3',
		                            y: 45
		                        },
		                        {
		                            //color:'#000000',
		                            name: '外部新增知识点',
		                            y: 10
		                        }
		                    ]
		                }]
		            });
			        <?php } ?>
	            });
	        </script>
	        <?php } ?>
	        <?php */?>
    <?php } ?>
    
    <?php if (isset($sci_difficulty['difficulty']['internal']) && count($sci_difficulty['difficulty']['internal'])) {?>
    <?php $g_order_num++;?>
        <?php 
			$sci_difficulty['difficulty'] = isset($sci_difficulty['difficulty']) ? $sci_difficulty['difficulty'] : array();
			$sci_difficulty['exams'] = isset($sci_difficulty['exams']) ? $sci_difficulty['exams'] : array();
			$sci_difficulty['exam_names'] = array_keys($sci_difficulty['exams']);
		?>
        <h5 class="cls_row"><?php echo $g_order_num;?>）	题型和难易度覆盖的对比：</h5>
        <table class="cls_row" id="table_sci_diff">
        <tr>
        	<?php $first_th_width = '20';?>
        	<?php $count_data = count($sci_difficulty['exam_names']); ?>
            <?php $left_p_width = !$count_data ? 0 : round((100-$first_th_width)/count($sci_difficulty['exam_names']));?>
            <th width="<?=$first_th_width;?>%">题型和难易度\考试名称</th>
            <?php foreach ($sci_difficulty['exam_names'] as $exam_name) {?>
            <th width="<?=$left_p_width;?>%"><?php echo $exam_name;?></th>
            <?php }?>
        </tr>
        </table>
        
        <?php $diff_internal = isset($sci_difficulty['difficulty']['internal']) ? $sci_difficulty['difficulty']['internal'] : array(); ?>
        <?php $diff_external = isset($sci_difficulty['difficulty']['external']) ? $sci_difficulty['difficulty']['external'] : array(); ?>
        
        <?php if (count($diff_internal)) {?>
        <!-- 内部难易度和题型 -->
        <?php $auto_key  = 0;?>
            <?php foreach ($diff_internal as $q_type) {?>
                <?php $auto_key++;?>
                <table class="cls_row cls_table" ref_title_id="table_sci_diff">
                    <tr <?php echo $auto_key%2==0 ? 'class="bgc"' : '';?>>
                        <th width="<?=$first_th_width;?>%"><?php echo $q_type;?></th>
                        <?php foreach ($sci_difficulty['exam_names'] as $exam_name) {?>
                            <td width="<?=$left_p_width;?>%">
                                <?php echo isset($sci_difficulty['exams'][$exam_name]) && isset($sci_difficulty['exams'][$exam_name][$q_type]) ? round($sci_difficulty['exams'][$exam_name][$q_type]) : '0';?>
                            </td>
                        <?php } ?>
                    </tr>
                </table>
            <?php } ?>
        <?php } ?>
        
        <?php if (count($diff_external)) {?>
        <!-- 外部难易度和题型-->
            <?php foreach ($diff_external as $q_type) {?>
                <?php $auto_key++;?>
                <table class="cls_row cls_table" ref_title_id="table_sci_diff">
                    <tr <?php echo $auto_key%2==0 ? 'class="bgc"' : '';?>>
                        <th width="<?=$first_th_width;?>%"><?php echo $q_type;?></th>
                        <?php foreach ($sci_difficulty['exam_names'] as $exam_name) {?>
                            <td width="<?=$left_p_width;?>%">
                                <?php echo isset($sci_difficulty['exams'][$exam_name]) && isset($sci_difficulty['exams'][$exam_name][$q_type]) ? $sci_difficulty['exams'][$exam_name][$q_type]  : '0';?>
                            </td>
                        <?php } ?>
                    </tr>
                </table>
            <?php } ?>
        <?php } ?>
    <?php } ?>
    
    <h5 class="cls_row"><?php echo ++$g_order_num;?>）	本学科考试说明：</h5>
    <p class="mokuai-text cls_row"><?php echo $sci_exam_info;?></p>