<?php
/**
 * 试题分析及与之对应的评价 && 诊断及建议 
 */
?>
<style>
ul.k_ul li.line
{
	border-bottom:1px dotted #ccc;
}
ul.k_ul li
{
	height:30px;
	list-style:none;
	width:90%;
	padding:5px;
}

ul.k_ul li span
{
	padding-left:5px;
	display: block;
}

ul.k_ul li span.fl
{
	float:left;
	width:75%;
	text-align: center;
}

ul.k_ul li span.fr
{
	float: right;
	text-align: center;
	width: 20%;
}

.text_center{ text-align:center;}
.text_left{text-align: left;}
.ml5{ margin-left:5px;}
</style>







<!--试题分析及与之对应的评价start-->
       <h3 class="cls_row">3.试题分析及对应的评价</h3>
       <?php 
			$sq_all['fields'] = isset($sq_all['fields']) ? $sq_all['fields'] : array();
			$sq_all['data'] = isset($sq_all['data']) ? $sq_all['data'] : array();
			$sq_all['desc_data'] = isset($sq_all['desc_data']) ? $sq_all['desc_data'] : array();
		?>
		
	   <?php /*?>
       <table class="mb30 cls_row" id="table_sq_ss_0">
           <tr>
	           <?php $first_th_width = '15';?>
	           <?php $count_data = count($sq_all['fields']); ?>
               <?php $left_p_width = !$count_data ? 0 : round((100-$first_th_width)/count($sq_all['fields']));?>
	           <th width="<?=$first_th_width?>%">题目</th>
	           <?php foreach ($sq_all['fields'] as $field_name) {?>
	           <th width="<?=$left_p_width?>%"><?php echo $field_name;?></th>
	           <?php } ?>
           </tr>
        </table>
        
        
           <?php $auto_key  = 0;?>
	       <?php foreach ($sq_all['data'] as $name=>$item) {?>
	       <?php $auto_key++;?>
        <table class=" cls_row cls_table" ref_title_id="table_sq_ss_0">
	       <tr <?php echo $auto_key%2==0 ? 'class="bgc"' : '';?>>
	            <th width="<?=$first_th_width?>%"><?php echo $name;?></th>
	            <?php foreach ($sq_all['fields'] as $field_name) {?>
	            <td width="<?=$left_p_width?>%"><?php echo isset($item[$field_name]) ? $item[$field_name] : '--';?></td>
	            <?php } ?>
	       </tr>
       </table>
	       <?php } ?>
       <?php */?>
       
       <?php if (count($sq_all['data'])) {?>
       <?php 
       		$flash_data = array();
       		foreach ($sq_all['fields'] as $field_name)
       		{
       			if ($field_name == '总分') continue;

       			$tmp_arr = array();
       			foreach ($sq_all['data'] as $key=>$item)
	       		{
	       			$tmp_arr[] = isset($item[$field_name]) ? floatval($item[$field_name]) : 0;
	       		}
	       			
	       		$field_name = $field_name == '得分' ? '我' : $field_name;
	       		$flash_data[] = array('name'=>$field_name, 'data' => $tmp_arr);
       		}
       		
       		$max_score = 0;
       		foreach ($sq_all['data'] as $data)
       		{
       		    $data = array_values($data);
       		    foreach ($data as $key => $score)
       		    {
       		        if ($key < 1)
       		        {
       		            continue;
       		        }
       		        if ($score > $max_score)
       		        {
       		            $max_score = $score;
       		        }
       		    }
       		}
       		if ($max_score > 0)
       		{
       		    $max_score = ceil($max_score) + 1;
       		}
       ?>
           <div id="flash_container_sq"  class="cls_row"></div>
           <script type="text/javascript">
           $(function () {
			    //试题分析及与之对应的评价 曲线图
			    $('#flash_container_sq').highcharts({
			    	chart: {
			    		height: '1200',
			            type: 'line',
			            inverted: true
			        },
			        title: {
			            text: '试题得分折线图'
			        },
			        plotOptions: {
			            line: {
			                dataLabels: {
			                //    enabled: true
			                },
			                enableMouseTracking: false	//关闭动画特效,使其在pdf中线条不会变粗
			            }
			        },
			        xAxis: {
			            categories: eval("("+'<?php echo json_encode(array_keys($sq_all['data'])); ?>'+")"),
			            labels: {
			            	rotation : 0.5,//坐标旋转角度 为0：表示横放置
			            	align : 'right'
			            }
			        },
			        yAxis:[{
			            title:'',
			            <?php if($max_score > 0) {?>
			            max:<?=$max_score?>, // 定义Y轴 最大值  
		                min:0 // 定义最小值 
		                <?php } else {?>
		                tickPositions: [0]
		                <?php } ?>
        			    },
        			    {
			            title:'',
			            <?php if($max_score > 0) {?>
			            max:<?=$max_score?>, // 定义Y轴 最大值  
		                min:0, // 定义最小值
		                <?php } else {?>
		                tickPositions: [0],
		                <?php }?>
			            opposite:true
    			    }],
			        tooltip: {
			            valueSuffix: ''
			        },
			        legend: {
			            layout: 'vertical',
			            align: 'right',
			            verticalAlign: 'middle',
			            borderWidth: 0
			        },
			        //colors: ['#000000','#000000','#000000'],	//线的颜色
			        series: eval("("+'<?php echo json_encode($flash_data); ?>'+")")
			        /*
			        series: [{
			            name: '我',
			            data: [4.5, 2.5, 3.5, 4.5]
			        }, {
			            name: '总体1',
			            data: [2.5, 4.5, 1.5, 2.5]
			        }, {
			            name: '总体2',
			            data: [2.0, 2.0, 3.0, 5.0]
			        }]*/
			    });
		    });
		    </script>
       <?php } ?>

       <?php if (count($sq_all['desc_data'])) {?>
       <table class="mb10 cls_row" id="table_sq_ss_1">
           <tr>
               <th width="20%">题号</th>
               <!--  
               <th width="35%">知识点</th>
               <th width="15%">认知过程</th>
               -->
               <th width="20%">难易度</th>
               <th width="20%">分值</th>
               <th width="20%">得分</th>
               <th width="20%">期望得分</th>
           </tr>
        </table>
        
           <?php $auto_key  = 0;?>
	       <?php foreach ($sq_all['desc_data'] as $item) {?>
	       <?php $auto_key++;?>
        <table class=" cls_row cls_table" ref_title_id="table_sq_ss_1">
	       <tr <?php echo $auto_key%2==0 ? 'class="bgc"' : '';?>>
	            <th width="20%"><?php echo $item['id'];?></th>
	            
	            <?php /*?>
	            <?php $i_knowledge = $item['knowledge'];?>
	            <?php $count_k = count($i_knowledge);?>
	            <td width="35%">
	            	<ul <?php echo $count_k > 1 ? 'class="k_ul"' : '';?>>
	            	<?php foreach ($i_knowledge as $val) {?>
	           			<li <?php echo $count_k > 1 ? 'class="line text_left"' : 'class="text_left ml5"';?>>
	           				<?php echo isset($val['knowledge']) ? $val['knowledge'] : '--';?>
	           			</li>
           			<?php } ?>
	            	</ul>
            	</td>
	            <td width="15%">
	            	<ul <?php echo $count_k > 1 ? 'class="k_ul"' : '';?>>
	            	<?php foreach ($i_knowledge as $val) {?>
	           			<li <?php echo $count_k > 1 ? 'class="line text_center"' : 'class="text_center"';?>>
	           				<?php echo isset($val['know_process']) ? $val['know_process'] : '--';?>
	           			</li>
	            	<?php } ?>
	            	</ul>
            	</td>
            	<?php */?>
            	
	            <td width="20%"><?php echo $item['difficulty'];?></td>
	            <td width="20%"><?php echo $item['full_score'];?></td>
	            <td width="20%"><?php echo $item['test_score'];?></td>
	            <td width="20%"><?php echo $item['expect_score'];?></td>
	       </tr>
       </table>
	       <?php } ?>
       <?php } ?>
       
       <h3 class="cls_row">4.诊断及建议：</h3>
       <?php $g_o_n = 0;?>
       <?php if (count($ss_summary)) {?>
       <h5 class="cls_row"><?php echo ++$g_o_n;?>）总体水平等级和排名</h5>
       <ul class="cls_row">
           <li>参加考试的总体人数：<span><?php echo isset($ss_summary['total']) ? $ss_summary['total'] : '0';?>人</span></li>
           <?php if (count($ss_summary['summary'])) {?>
           <?php foreach ($ss_summary['summary'] as $k=>$v) {?>
           <li><?php echo $k;?> ：<span><?php echo $v;?>人</span></li>
           <?php } ?>
           <?php } ?>
           <?php if (isset($ss_summary['win_percent'])) {?>
           <?php if (!$ss_summary['is_last_rank']) {?>
           <li>恭喜，你的测试成绩比 <strong><?php echo isset($ss_summary['win_percent']) ? $ss_summary['win_percent'] : 0;?> %</strong> 的学生更出色！<?php echo str_repeat("★", $ss_summary['level']);?></li>
           <?php } else {?>
           <li>你的测试成绩比 0%的学生更出色！请再接再厉！</li>
           <?php }?>
           <?php } ?>
       </ul>
       <?php }?>
       <?php if (count($ss_application_situation)) {?>
       <h5 class="cls_row"><?php echo ++$g_o_n;?>) 强弱点分布情况：</h5>
       
       <table class="cls_row" id="table_sq_ss_2">
           <tr>
           	   <th class="w168" width="30%">知识点\认知过程</th>
	           <th width="10%">记忆</th>
	           <th width="10%">理解</th>
	           <th width="10%">应用</th>
	           <th width="40%">评语</th>
           </tr>
        </table>
        
           <?php $auto_key = 0;?>
	       <?php foreach ($ss_application_situation as $k_name=>$item) {?>
	       <?php $auto_key++;?>
        <table class="cls_row cls_table" ref_title_id="table_sq_ss_2">
	       <tr <?php echo $auto_key%2==0 ? 'class="bgc"' : '';?>>
	            <td class="w168" width="30%"><?php echo $k_name;?></td>
	            <td width="10%"><span class="level level<?php echo $item['kp_1']?>"></span></td>
	            <td width="10%"><span class="level level<?php echo $item['kp_2']?>"></span></td>
	            <td width="10%"><span class="level level<?php echo $item['kp_3']?>"></span></td>
	            <td width="40%"><?php echo $item['comment'];?></td>
	       </tr>
       </table>
	       <?php } ?>
       <?php } ?>
       
       <?php if (count($ss_match_percent)) {?>
       <h5 class="cls_row"><?php echo ++$g_o_n;?>) 目标匹配度：<?php echo $ss_match_percent['percent'];?>%</h5>
       <?php if (isset($ss_match_percent['data'])):?>
        <?php $count_num = 1; ?>
       <?php foreach ($ss_match_percent['data'] as $keys=>$item): ?>
	       <table class="cls_row cls_table" <?php if($count_num == 1): ?>id="table_match_percent"<?php else: ?>ref_title_id="table_match_percent"<?php endif; ?>>
	           <tr>
	           <?php foreach ($item as $key=>$val):?>
			   <th width="20%" <?php if ( is_numeric($val)):?>style="background-color:#FFF;"<?php endif; ?>><?php echo  $val;?></th>
			   <?php endforeach;?>	           
	           </tr>
	        </table>
	        <?php $count_num++; ?>
        <?php endforeach;?>
        <?php endif;?>
       <?php } ?>
       <br>
       <p class="mokuai-text cls_row">
                注：为表达更加简明扼要，部分数据进行了取整等简化处理，由此可能造成相关数据的误差不影响评价结果。
       </p>
<!--试题分析及与之对应的评价end-->
