<?php
/**
 * 后台管理->素质相关管理->职业能力倾向管理
 */
$this->load->view('common/header');?>
<script language="javascript">
function check_form(form) {                      
    if (checkbox_check('pr_ids[]')) {
        return confirm('确定要删除么？');
    }
    
    return false;
} 

</script>

<div id="body">
  <form name="frm_list" action="<?=site_url('admin/vocational_aptitude/remove')?>" method="GET" onsubmit="return check_form(this)">
  <div class="space">
    <div class="subtitle">
    <?php if ($priv_edit) {?>
    <a class="menu" href="<?=site_url('admin/vocational_aptitude/edit')?>">添加职业能力倾向</a>
    <?php }?>
    <a class="menu" href="javascript:void(0)" onclick="fnShowDialog('id_qry_dlg')">查询</a> 
            职业能力倾向管理
   </div>  
    <table class="maintable" border="0" cellspacing="0" cellpadding="0">
      <tr class="altbg1">
        <td width="2%">删?</td>
        <td width="5%">ID</td>
        <td width="15%">职业能力倾向</td>
        <td width="34%">说明</td>
        <td width="34%">关联职业</td>
        <td width="10%">操作</td>
      </tr>
      <?php if($list):?>
      <?php foreach($list as $val):?>
      <tr>
        <td><input type="checkbox" name="pr_ids[]" value="<?=$val['pr_id']?>"></td>
        <td><?=$val['pr_id']?></td>
        <td><?=$val['knowledge_name']?></td>
        <td><?=$val['pr_explain']?></td>
        <td>
        <?php $profession_name = array();?>
        <?php foreach ($val['pr_professionid'] as $professionid) {?>
        <? $profession_name[] = $profession[$professionid]['profession_name'];?> 
        <?php }?>
        <?=implode('、', $profession_name)?>
        </td>
        <td>
          <?php if ($priv_edit) {?>
          <a href="<?=site_url('admin/vocational_aptitude/edit/'.$val['pr_id'])?>">编辑</a>
          <?php } ?>
          <?php if ($priv_delete) {?>
          <a href="<?=site_url('admin/vocational_aptitude/remove/'.$val['pr_id'])?>" onclick="return confirm('确定要删除么？');"><?php if ($val['pr_flag'] == -1) {?>彻底<?php }?>删除</a>
          <?php } ?>
        </td>
      </tr>
      <?php endforeach; ?>
      <tr class="altbg1">
        <td colspan="2"><button type="button" class="btn2" onclick="checkbox_checked('pr_ids[]');">全选</button></td>
        <td colspan="7" style="text-align:right">
          <?=$pagination?>
        </td>
      </tr>
      <?php else: ?>
      <tr>
        <td colspan="8">暂无记录！</td>
      </tr>
      <?php endif; ?>
    </table>
    <?php if ($priv_delete) {?>
    <center><input type="submit" value=" 批量删除 " class="btn" /></center>
    <?php }?>
  </div>
  </form>
</div>

<div id="id_qry_dlg" style="display:none">
<div class="cls_title">搜索职业能力倾向</div>
  <form method="get" name="search_form" action="<?=site_url('admin/vocational_aptitude/index/')?>">
    <div class="space" style="margin:5px">
        <table class="maintable" border="0" cellspacing="0" cellpadding="0">
            <tr>
                <td class="altbg1">职业能力倾向</td>
                <td><input type="text" name="knowledge_name" value="<?=$search['knowledge_name']?>" class="txtbox" /></td>
            </tr>
        </table>
        <center><input type="submit" value=" 搜索 " class="btn" /> <input type="button" value="取消 " class="btn" onclick="fnCloseDialog('id_qry_dlg')"/></center>
    </div>
  </form>
</div>
</div>
<?php $this->load->view('common/footer');?>
