<?php $this->load->view('common/header');?>
<?php static_global('js/flexigrid/css/flexigrid.css', 'css'); ?>
<?php static_global('js/flexigrid/js/flexigrid.js'); ?>
<?php 
    static_js(array('common/address.js', 
                    'common/region.js'));
?>
<script type="text/javascript">
$(function(){
    fnInitGrid('#id_grid');
});

function fnSelItem()
{
    var param = new Array();
    $("#id_grid input[name='tc_id']:checked").each(function(){
        var tcid = this.value;
        var tcname = $("#id_tr_" + tcid + " td.tc_name").text();
        var tcprovid = $("#id_tr_" + tcid + " input[name='tc_provid']").attr('value');
        var tccityid = $("#id_tr_" + tcid + " input[name='tc_cityid']").attr('value');
        var tcareaid = $("#id_tr_" + tcid + " input[name='tc_areaid']").attr('value');
        var tcctcaddr = $("#id_tr_" + tcid + " td.tc_ctcaddr").text();
        var tcctcperson = $("#id_tr_" + tcid + " td.tc_ctcperson").text();
        var tcctcphone = $("#id_tr_" + tcid + " td.tc_ctcphone").text();
        param[param.length] = {
                "tc_id" : tcid, 
                "tc_name" : tcname, 
                "tc_provid" : tcprovid,
                "tc_cityid" : tccityid,
                "tc_areaid" : tcareaid,
                "tc_ctcaddr" : tcctcaddr,
                "tc_ctcperson" : tcctcperson,
                "tc_ctcphone" : tcctcphone};
    });
    return param;
}

function fnClearSelection()
{
    $("#id_grid input[name='tc_id']:checked").removeAttr('checked');
}
</script>
<div id="body">
  <div class="space">
  <div class="subtitle">培训机构校区列表<?if ($ti_info) { ?>(<? Func::echo_s($ti_info['ti_name']); ?>)<? } ?>
        
      <div class="cls_toolbar">
      <button type="button" onclick="location.reload()">刷新</button>
      </div>
    </div>
    <table class="cls_table" border="0" cellspacing="0" cellpadding="0" id="id_grid">
      <tr class="cls_title">
      <td width="20"><? if ($_GET['multisel']) { ?><input type="checkbox" onchange="fnSelAll('id_grid', 'tc_id', this.checked)"/><? } ?></td>
        <td width="40">ID</td>
        <td width="80">名称</td>
        <? if ($ti_info) {} else { ?>
        <td width="100">所属培训机构</td>
        <? } ?>
        <td width="120">省/市/区</td>
        <td width="100" id="id_td_tc_ctcaddr">联系地址</td>
        <td width="100" id="id_td_tc_ctcperson">联系人员</td>
        <td width="100" id="id_td_tc_ctcphone">联系电话</td>
        <td width="35" align="right">环境指数</td>
        <td width="35">状态</td>
      </tr>
      <? if(!empty($tc_list)) { ?>
      <? foreach($tc_list as $v) { ?>
      <tr id="id_tr_<?=$v['tc_id']?>">
        <td><input type="<?=$_GET['multisel'] ? 'checkbox' : 'radio'?>" name="tc_id" value="<?=$v['tc_id']?>"/></td>
        <td><?=$v['tc_id']?></td>
        <td class="tc_name"><? Func::echo_s($v['tc_name']); ?></td>
        <? if ($ti_info) {} else { ?>
        <td><? Func::echo_s($v['ti_name']); ?></td>
        <? } ?>
        <td>
        <input type="hidden" name="tc_provid" value="<?=$v['tc_provid']?>"/>
        <input type="hidden" name="tc_cityid" value="<?=$v['tc_cityid']?>"/>
        <input type="hidden" name="tc_areaid" value="<?=$v['tc_areaid']?>"/>
        <? Func::echo_s($v['tc_provname']); ?> /
        <? Func::echo_s($v['tc_cityname']); ?> /
        <? Func::echo_s($v['tc_areaname']); ?></td>
        <td class="tc_ctcaddr"><? Func::echo_s($v['tc_ctcaddr']); ?></td>
        <td class="tc_ctcperson"><? Func::echo_s($v['tc_ctcperson']); ?></td>
        <td class="tc_ctcphone"><? Func::echo_s($v['tc_ctcphone']); ?></td>
        <td><?=$v['tc_environ']?></td>
        <td><?  if ($v['tc_flag'] < 0) echo('已删'); 
                else if ($v['tc_flag'] == '0') echo('禁用'); 
                else if ($v['tc_flag'] == 1) echo('启用'); 
                else if ($v['tc_flag'] > 1) echo('待审'); ?></td>
      </tr>
      <? } ?>
      <? } ?>
    </table>
    <? $this->load->view('common/paginator', Fn::paginator($tc_list_count));?>
  </div>
</div>
<?php $this->load->view('common/footer');?>
