<? $this->load->view('common/header');?>
<? static_global(array('js/common/address.js', 'js/common/region.js')); ?>
<script type="text/javascript">
function fnSaveTCInfo()
{
    var param = fnGetFormData('id_tc_form');
    if ($.trim(param['tc_name']) == '')
    {
        alert('培训校区名称不可为空');
        return;
    }
    if (($("#selProvinces option").size() > 1 && $("#selProvinces").get(0).value == '0')
        || ($("#selCities option").size() > 1 && $("#selCities").get(0).value == '0')
        || ($("#selAreas option").size() > 1 && $("#selAreas").get(0).value == '0'))
    {
        alert('请选择校区所在省市区！');
        return;
    }
    if ($.trim(param['tc_ctcaddr']) == '')
    {
        alert('联系地址不可为空');
        return;
    }
    if ($.trim(param['tc_ctcphone']) == '')
    {
        alert('联系电话不可为空');
        return;
    }

    var tc_environ = parseInt(param['tc_environ']);
    if (isNaN(tc_environ))
    {
        alert('请写环境指数');
        return;
    }
    ajax_setTC(param);
}
</script>
<div id="body">
  <div class="space">
    <div class="subtitle"><?=$tc_info['tc_id'] ? '编辑': '新增'?>培训机构校区<? if ($tc_info['tc_id']) echo('(ID:' . $tc_info['tc_id'] . ')'); ?>
      <div class="cls_toolbar">
        <button type="button" onclick="fnSaveTCInfo()">保存</button>
        <button type="button" onclick="location.href='<?=site_url('admin/traininginstitution/tilist')?>'">返回校区列表</button>
        <button type="button" onclick="location.href='<?=site_url('admin/traininginstitution/tilist')?>'">返回机构列表</button>
        <button type="button" onclick="location.reload()">重新载入</button>
      </div>
    </div>
    <div id="id_tc_form">
    <table class="maintable" id="id_tc_table" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td class="altbg1" width="15%">培训机构名称</td>
        <td width="35%"><? Func::echo_s($tc_info['ti_name']); ?></td>
        <td class="altbg1" width="15%">培训校区名称</td> 
        <td>
            <input type="hidden" name="tc_id" value="<?=$tc_info['tc_id']?>" class="cls_field"/>
            <? if ($tc_info['tc_id'] == 0) { ?>
            <input type="hidden" name="tc_tiid" value="<?=$tc_info['tc_tiid']?>" class="cls_field"/>
            <? } ?>
            <input type="text" name="tc_name" value="<? Func::echo_s($tc_info['tc_name']); ?>" class="cls_field txtbox"/>
            <span style="color:#f00">*</span>
        </td>
      </tr>

        <tr>
            <td class="altbg1">校区所属省市</td>
            <td colspan="3">
              <select name="tc_provid" id="selProvinces" onchange="region.changed(this, 2, 'selCities');region.changed(document.getElementById('selCities'), 2, 'selAreas');" class="cls_field">
                <option value="0">--请选择省--</option>
                <? foreach($province_list as $val) { ?>
                <option value="<?=$val['region_id']?>"<?=$val['region_id']==$tc_info['tc_provid']?' selected="selected"':''?>><?=$val['region_name']?></option>
                <? } ?>
              </select>
              <select name="tc_cityid" id="selCities" onchange="region.changed(this, 3, 'selAreas')" class="cls_field">
                <option value="0">--请选择市--</option>
                <? foreach($city_list as $val) { ?>
                <option value="<?=$val['region_id']?>"<?=$val['region_id']==$tc_info['tc_cityid']?' selected="selected"':''?>><?=$val['region_name']?></option>
                <? } ?>
              </select>
              <select name="tc_areaid" id="selAreas" class="cls_field">
                <option value="0">--请选择区县--</option>
                <? foreach($area_list as $val) { ?>
                <option value="<?=$val['region_id']?>"<?=$val['region_id']==$tc_info['tc_areaid']?' selected="selected"':''?>><?=$val['region_name']?></option>
                <? } ?>
              </select>
               <span style="color:#f00">*</span>
            </td>
        </tr>


        <tr>
           <td class="altbg1">联系地址</td>
           <td><input type="text" name="tc_ctcaddr" value="<? Func::echo_s($tc_info['tc_ctcaddr']); ?>" class="txtbox cls_field" />
               <span style="color:#f00">*</span>
           </td>
           <td class="altbg1">联系人员</td>
           <td><input type="text" name="tc_ctcperson" value="<? Func::echo_s($tc_info['tc_ctcperson']); ?>" class="txtbox cls_field" />
               <span style="color:#f00"></span>
           </td>
       </td>

        <tr>
           <td class="altbg1">联系电话</td>
           <td><input type="text" name="tc_ctcphone" value="<? Func::echo_s($tc_info['tc_ctcphone']); ?>" class="txtbox cls_field" />
               <span style="color:#f00">*</span>
           </td>
           <td class="altbg1">环境指数</td>
           <td><input type="text" name="tc_environ" value="<?=intval($tc_info['tc_environ'])?>" class="txtbox cls_field" />
               <span style="color:#f00">*</span>
           </td>
       </td>

        <tr>
           <td class="altbg1">状态</td>
           <td colspan="3">
                 <label><input type="radio" name="tc_flag" class="cls_field" value="1" <?=$tc_info['tc_flag'] == 1 ? 'checked="checked"' : ''?>/>启用</label>
                 <label><input type="radio" name="tc_flag" class="cls_field" value="0" <?=$tc_info['tc_flag'] == '0' ? 'checked="checked"' : ''?>/>禁用</label>
                 <? if ($tc_info['tc_id']) { ?>
                 <label><input type="radio" name="tc_flag" class="cls_field" value="-1" <?=$tc_info['tc_flag'] == -1 ? 'checked="checked"' : ''?>/>已删</label>
                 <? } ?>
                 <? if ($tc_info['tc_flag'] > 1) { ?>
                 <label><input type="radio" name="tc_flag" class="cls_field" value="<?=$tc_info['tc_flag']?>" checked="checked">待审</label>
                 <? } else { ?>
                 <label><input type="radio" name="tc_flag" class="cls_field" value="<?=time()?>">待审</label>
                 <? } ?>
            </td>
        </tr>
      </table>
    </div>
  </div>
</div>
<?php $this->load->view('common/footer');?>
