<? $this->load->view('common/header');?>
<?
$CI = &get_instance();
$bPrivEdit = $CI->check_power_new('traininginstitution_settcinfo', false); 
?>
<div id="body">
  <div class="space">
    <div class="subtitle">查看培训机构校区(ID:<?=$tc_info['tc_id']?>)
      <div class="cls_toolbar">
<? if ($bPrivEdit) { ?>
      <button type="button" onclick="location.href='<?=site_url('admin/traininginstitution/settcinfo/' . $tc_info['tc_id'])?>'">编辑</button>
<? } ?>
        <button type="button" onclick="location.href='<?=site_url('admin/traininginstitution/tclist/' . $tc_info['tc_tiid'])?>'">返回校区列表</button>
        <button type="button" onclick="location.href='<?=site_url('admin/traininginstitution/tilist')?>'">返回机构列表</button>
        <button type="button" onclick="location.reload()">刷新</button>
      </div>
    </div>
    <div id="id_tc_form">
    <table class="maintable" id="id_tc_table" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td class="altbg1" width="15%">培训机构名称</td>
        <td width="35%"><? Func::echo_s($tc_info['ti_name']); ?></td>
        <td class="altbg1" width="15%">培训校区名称</td>
        <td width="35%"><? Func::echo_s($tc_info['tc_name']); ?></td>
      </tr>

        <tr>
            <td class="altbg1">校区所在省市</td>
            <td><?=$tc_info['tc_provname']?> / <?=$tc_info['tc_cityname']?> / <?=$tc_info['tc_areaname']?></td>
            <td class="altbg1">联系地址</td>
            <td><? Func::echo_s($tc_info['tc_ctcaddr']); ?></td>
        </tr>

        <tr>
          <td class="altbg1">联系人员</td>
          <td><? Func::echo_s($tc_info['tc_ctcperson']); ?></td>
          <td class="altbg1">联系电话</td>
          <td><? Func::echo_s($tc_info['tc_ctcphone']); ?></td>
        </tr>

        <tr>
          <td class="altbg1">环境指数</td>
          <td><?=$tc_info['tc_environ']?></td>
           <td class="altbg1">状态</td>
           <td><? if ($tc_info['tc_flag'] > 1) echo('待审'); else if ($tc_info['tc_flag'] == '0') echo('禁用'); else if ($tc_info['tc_flag'] == 1) echo('启用'); else if ($tc_info['tc_flag'] == -1) echo('已删'); ?></td>
        </tr>

        <tr>
          <td class="altbg1">添加人</td>
          <td><?=$tc_info['tc_adduname']?></td>
           <td class="altbg1">添加时间</td>
          <td><?=$tc_info['tc_addtime']?></td>
        </tr>
      </table>
    </div>
  </div>
</div>
<?php $this->load->view('common/footer');?>
