<?php $this->load->view('common/header');?>
<div id="body">
  <form name="Frm_info" method="POST" action="<?=site_url('admin/region/create')?>">
  <input type="hidden" name="parent_id" value="<?=$parent['region_id']?>">
  <div class="space">
    <div class="subtitle">添加地区</div>
    <table class="maintable" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="16%" class="altbg1">上级地区</td>        
        <td>
            <?=$parent['region_name']?>
        </td>
      </tr>
      <tr>
        <td width="16%" class="altbg1">地区名称</td>        
        <td>
            <input type="text" id="region_name" name="region_name" class="txtbox" value="">
        </td>
      </tr>
      <tr>
        <td width="16%" class="altbg1">是否显示</td>        
        <td>
            <input type="checkbox" name="status" value="1" checked="checked">
            是否在下拉菜单中显示
        </td>
      </tr>
    </table>
  </div>
  <center> 
    <input type="submit" name="dosubmit" value=" 提交 " class="btn" />
    &nbsp;&nbsp;
    <input type="button" name="" value=" 返回 " onclick="history.go(-1);" class="btn" />
  </center>   
  </form>
</div>
<?php $this->load->view('common/footer');?>