<? $this->load->view('common/header'); ?>
<?php static_global('js/flexigrid/css/flexigrid.css', 'css'); ?>
<?php static_global('js/flexigrid/js/flexigrid.js'); ?>
<?php 
    static_js(array('common/address.js', 
                    'common/region.js'));
?>
<script type="text/javascript">
$(function(){
    fnInitGrid('#id_grid');
});

function fnSelItem()
{
    var param = new Array();
    $("#id_grid input[name='cc_id']:checked").each(function(){
        var ccid = this.value;
        var tiname = $("#id_tr_ccid_" + ccid + " input[name='ti_name']").val();
        var tcname = $("#id_tr_ccid_" + ccid + " input[name='tc_name']").val();
        var corsname = $("#id_tr_ccid_" + ccid + " input[name='cors_name']").val();
        param[param.length] = {
                "cc_id" : ccid, 
                "tc_name" : tcname, 
                "ti_name" : tiname,
                "cors_name" : corsname
                };
    });
    return param;
}


function fnClearSelection()
{
    $("#id_grid input[name='cc_id']:checked").removeAttr('checked');
}
</script>
<style type="text/css">
.gray {
    color:gray;
}
</style>
<div id="body">
  <div class="space">
    <div class="subtitle">课程校区列表
      <div class="cls_toolbar">
        <button type="button" onclick="fnShowDialog('id_qry_dlg')">查询</button>
        <button type="button" onclick="location.reload()">刷新</button>
      </div>
    </div>
    <table class="cls_table" id="id_grid" border="0" cellspacing="0" cellpadding="0">
      <tr class="cls_title">
      <td width="20"><? if ($_GET['multisel']) { ?><input type="checkbox" onchange="fnSelAll('id_grid', 'cc_id', this.checked)"/><? } ?></td>
        <td width="100">课程/校区</td>
        <td width="120">机构/来源</td>
        <td width="160">授课模式/上课时间</td>
        <td width="170">年级/开课周期</td>
        <td width="160">学科/(省/市/区)</td>
        <td width="160">类型/地址</td>
        <td width="40" align="right">状态/课时</td>
        <td width="60" align="right">价格</td>
      </tr>
      <? if(!empty($cors_list)) { ?>
      <? foreach($cors_list as $v) { ?>
      <? if (isset($cors_campus_map[$v['cors_id']])) { ?>
      <tr>
        <td></td>
        <td><span class="gray"><? Func::echo_s($v['cors_name']); ?></span></td>
        <td><span class="gray"><? Func::echo_s($v['ti_name']); ?></span></td>
        <td><span class="gray"><? Func::echo_s($v['cm_name']); ?></span></td>
        <td><span class="gray"><? if (isset($cors_gradeid[$v['cors_id']])) foreach ($cors_gradeid[$v['cors_id']] as $v1) { ?>
            &nbsp;<?=$grade_map[$v1['cg_gradeid']]?>
            <? } ?></span>
        </td>
        <td><span class="gray"><? if (isset($cors_subjectid[$v['cors_id']])) foreach ($cors_subjectid[$v['cors_id']] as $v2) { ?>
            &nbsp;<?=$subject_map[$v2['cs_subjectid']]?>
            <? } ?></span>
        </td>
        <td><span class="gray"><? if (isset($cors_classid[$v['cors_id']])) foreach ($cors_classid[$v['cors_id']] as $v3) { ?>
            &nbsp;<?=$v3['class_name']?>
            <? } ?></span>
        </td>
        <td><span class="gray"><?  if ($v['cors_flag'] < 0) echo('已删'); 
                else if ($v['cors_flag'] == '0') echo('禁用'); 
                else if ($v['cors_flag'] == 1) echo('启用'); 
                else if ($v['cors_flag'] > 1) echo('待审'); ?></span></td>
        <td></td>
      </tr>
      <? foreach ($cors_campus_map[$v['cors_id']] as $vv) { ?>
      <tr id="id_tr_ccid_<?=$vv['cc_id']?>">
        <td><input type="<?=$_GET['multisel'] ? 'checkbox' : 'radio'?>" name="cc_id" value="<?=$vv['cc_id']?>"/>
        <input type="hidden" name="tc_name" value="<? Func::echo_s($vv['tc_name']); ?>"/>
        <input type="hidden" name="ti_name" value="<? Func::echo_s($v['ti_name']); ?>"/>
        <input type="hidden" name="cors_name" value="<? Func::echo_s($v['cors_name']); ?>"/></td>
        <td>校区: <? Func::echo_s($vv['tc_name']); ?></td>
        <td><? Func::echo_s($vv['ctf_name']); ?></td>
        <td><? Func::echo_s($vv['cc_classtime']); ?></td>
        <td><? if ($vv['cc_startanytime']) { ?>随时开课<? } else if ($vv['cc_begindate']) { ?>从<b><?=$vv['cc_begindate']?></b>到<b><?=$vv['cc_enddate']?></b><? } ?></td>
        <td><?=$vv['cc_provname']?> / <?=$vv['cc_cityname']?> / <?=$vv['cc_areaname']?></td>
        <td><? Func::echo_s($vv['cc_addr']); ?></td>
        <td><?=$vv['cc_hours']?></td>
        <td><?=$vv['cc_price']?></td>
      </tr>
      <? } ?>
      <? } ?>
      <? } ?>
      <? } ?>
    </table>
    <? $this->load->view('common/paginator', Fn::paginator($cors_list_count));?>
  </div>
</div>

<div id="id_qry_dlg" style="display:none">
<div class="cls_title">搜索课程信息</div>
  <form method="GET" id="id_qry_form" name="search_form" action="<?=site_url('admin/course/selcorscampuslist')?>">
    <div class="space" style="margin:5px">
        <table class="maintable" border="0" cellspacing="0" cellpadding="0">
            <tr>
                <td class="altbg1">课程名称</td>
                <td><input type="text" name="cors_name" value="<? Func::echo_s($param['cors_name']); ?>" class="txtbox"/>
                <input type="hidden" name="multisel" value="<?=$_GET['multisel'] ? '1' : ''?>"/></td>
            </tr>  
            <tr>
                <td class="altbg1">来源机构</td>
                <td><input type="text" name="ti_name" value="<? Func::echo_s($param['ti_name']); ?>" class="txtbox"/></td>
            </tr>
            <tr>
                <td class="altbg1">授课模式</td>
                <td>                      
                    <select name="cors_cmid">
                    <option value="">[不限]</option>
                    <? foreach ($mode_list as $val) { ?>
                    <option value="<?=$val['cm_id'];?>" <? if ($param['cors_cmid'] == $val['cm_id']) echo('selected="selected"'); ?>><?=$val['cm_name'];?></option>
                    <? } ?>
                    </select>
                </td>
            </tr> 
            <tr>
                <td class="altbg1">年级</td>
                <td>
                    <select name="grade_id_str">
                    <option value="">[不限]</option>
                    <? foreach ($grade_map as $key =>$val) if ($key > 0) { ?>
                    <option value="<?=$key?>" 
<? if ($key == $param['grade_id_str']) echo('selected="selected"'); ?>
><? Func::echo_s($val);?></option>
                    <? } ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td class="altbg1">学科</td>
                <td>
                    <select name="subject_id_str">
                    <option value="">[不限]</option>
                    <? foreach ($subject_map as $key =>$val) if ($key > 0) { ?>
                    <option value="<?=$key?>" 
<? if ($key == $param['subject_id_str']) echo('selected="selected"'); ?>
><? Func::echo_s($val);?></option>
                    <? } ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td class="altbg1">考试类型</td>
                <td>
                    <select name="class_id_str">
                    <option value="">[不限]</option>
                  <? foreach ($classid_map as $key =>$val) { ?>
                    <option value="<?=$key?>"
<? if ($key == $param['class_id_str']) echo('selected="selected"'); ?>
><? Func::echo_s($val);?></option>
                    <? } ?>
                    </select>
                 </td>
            </tr>    
        </table>
      </div>
  </form>
<div class="cls_dialog_buttons">
<button type="submit" onclick="document.getElementById('id_qry_form').submit()">确定</button>
<button type="button" onclick="fnCloseDialog('id_qry_dlg')">取消</button>
</div>
</div>

<? $this->load->view('common/footer'); ?>

