<div id="id_setcminfo_dlg" style="width:400px">
<div class="cls_title"><?=$cm_info['cm_id'] ? '编辑' : '新增'?>培训课程授课模式<? if ($cm_info['cm_id']) echo('(ID:' . $cm_info['cm_id'] . ')'); ?></div>
<table class="maintable" id="id_setcminfo_table" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td class="altbg1" width="35%">培训课程授课模式ID</td>
    <td>
      <input type="text" name="cm_id" value="<?=$cm_info['cm_id']?>" class="cls_field txtbox" style="width:100px"/>
       <span style="color:#f00">*</span>
    </td>
  </tr>
  <tr>
    <td class="altbg1">培训课程授课模式名称</td>
    <td>
      <input type="text" name="cm_name" value="<? Func::echo_s($cm_info['cm_name']); ?>" class="txtbox cls_field" style="width:100px"/>
       <span style="color:#f00">*</span>
    </td>
  </tr>
</table>
<div class="cls_dialog_buttons">
<button type="button" onclick="ajax_setCM(<?=$cm_id?>, fnGetFormData('id_setcminfo_dlg'))">确定</button>
<button type="button" onclick="fnCloseDialog('id_setcminfo_dlg')">取消</button>
</div>
</div>
