<?php $this->load->view('common/header');?>
<?php static_global('js/flexigrid/css/flexigrid.css', 'css'); ?>
<?php static_global('js/flexigrid/js/flexigrid.js'); ?>


<?php 
    static_js(array('common/address.js', 
                    'common/region.js'));
?>

<?php $this->load->view('recycle/recycle.phtml');?>

<?php static_global('css/third_party/zebra_dialog/flat/zebra_dialog.css', 'css');?>
<?php static_global('js/third_party/zebra_dialog.js');?>
<script language="javascript">
$(function(){
    fnInitGrid('#id_grid');
});
function check_form(form) {                      
    if (checkbox_check('ids[]')) {
        var op = $('#batch_op').val();
        if (op == '') {
            alert('请选择操作类型');
            return false;
        } else {
            if (confirm('您确定要执行该操作么？')) {
                var action = $('#batch_op').find('option[value='+op+']').attr('op');
                form.action = action;
                return true;
            }
        }
    }
    return false;
}

function set_schools() {
   // if (grade_id == 0) return;
	var area=$('#selAreas option:selected').val();
	if (area == 0) return;
	   var school_id=<?php echo $search['school_id'];?>;
    $.post(
        '<?=site_url('admin/common/schools')?>',
        {grade_id:$('#grade_id option:selected').val(),province:$('#selProvinces option:selected').val(),city:$('#selCities option:selected').val(),area:$('#selAreas option:selected').val()},
        function(data){
            var str = '<option value="0">--请选择学校--</option>';
            for (var i=0; i<data.length; i++) {
                if(data[i]['school_id']==school_id){
                    str += '<option value="'+data[i]['school_id']+'" selected>'+data[i]['school_name']+'</option>';
                } 
                else{
              str += '<option value="'+data[i]['school_id']+'" >'+data[i]['school_name']+'</option>'; 
                }
                               
            }
            $('#school_id').html(str);
        },
        'json'
    );
}

function set_schools_onload() {
	   // if (grade_id == 0) return;

	var area=$('#selAreas option:selected').val();
	if (area == 0) return;
	   
		   var school_id=<?php echo $search['school_id'];?>;
		   
	    $.post(
	        '<?=site_url('admin/common/schools')?>',
	        {grade_id:$('#grade_id option:selected').val(),province:$('#selProvinces option:selected').val(),city:$('#selCities option:selected').val(),area:$('#selAreas option:selected').val()},
	        function(data){
	            var str = '<option value="0">--请选择学校--</option>';
	            for (var i=0; i<data.length; i++) {
	                if(data[i]['school_id']==school_id){
	                    str += '<option value="'+data[i]['school_id']+'" selected>'+data[i]['school_name']+'</option>';
	                } 
	                else{
	              str += '<option value="'+data[i]['school_id']+'" >'+data[i]['school_name']+'</option>'; 
	                }
	                               
	            }
	            $('#school_id').html(str);
	        },
	        'json'
	    );
	}

function test() {
var str = '<option value="0">--请选择区县--</option>';
$('#selAreas').html(str);
}
$(document).ready(function(){
	set_schools_onload();
});


</script>

<div id="body">
  <form name="frm_cpuser_list" action="<?=site_url('admin/student/batch_delete')?>" method="POST" onsubmit="return check_form(this)">
  <div class="space">
    <div class="subtitle">

      <?php if($mode=='trash'):?>
      学生回收站
      <?php else:?>
      <?php if ($priv_manage) {?>
        <a class="menu" href="<?=site_url('admin/student/del_batch')?>">批量删除学生(自动添加)</a>&nbsp;
      	<a class="menu" href="<?=site_url('admin/student/add_batch')?>">批量添加学生</a>&nbsp;
	<a class="menu" href="<?=site_url('admin/student/add')?>">添加学生</a>
	<a class="menu" href="<?=site_url('admin/student/info_check')?>">学生报名信息核对</a>学生信息管理
      <?php } ?>
      <?php endif;?>
       <a class="menu" href="javascript:void(0)" onclick="fnShowDialog('id_qry_dlg')">查询</a>
    </div>  
    <table class="cls_table" border="0" cellspacing="0" cellpadding="0" id="id_grid">
      <tr class="cls_title">
        <td width="60">ID</td>
        <td width="60">姓名</td>
        <td width="100">准考证</td>
        <td width="160">学校</td>
        <td width="50">年级</td>
        <td width="100">联系方式</td>
        <td width="120">登记时间</td>
        <td width="240">操作</td>
      </tr>
      <?php if($list):?>
      <?php foreach($list as $val):?>
      <tr>
        <td><?php if ($priv_manage) {?><input type="checkbox" name="ids[]" value="<?=$val['uid']?>"><?php } ?><?=$val['uid']?></td>
        <td><?=$val['last_name']?><?=$val['first_name']?></td>        
        <td><?=$val['exam_ticket']?></td> 
        <td><?=$val['school_name']?></td>
        <td><?=$val['grade']?></td> 
        <td><?=$val['mobile']?></td> 
        <td><?=$val['addtime']?></td> 
        <td>          
          <a href="<?=site_url('admin/student/preview/'.$val['uid'])?>">预览信息</a>
          <?php if ($priv_manage) {?>
          <a href="<?=site_url('admin/student/edit/'.$val['uid'])?>">编辑</a>
          <a href="###" i_name="<?php echo $val['last_name']?> <?=$val['first_name'];?>" class="reset_password" rel="<?php echo $val['uid'];?>">重置密码</a> 
          <?php if($mode=='trash'):?>
          <a href="<?=site_url('admin/student/restore/'.$val['uid'])?>" onclick="return confirm('确定要还原么？');">还原</a>
          <a href="<?=site_url('admin/student/remove/'.$val['uid'])?>" onclick="return confirm('确定要删除么？');">移除</a>
          <?php elseif($priv_delete):?>
          <?php $remove_id = $val['uid'];?>
          <a href="javascript:void(0)" onclick="fnShowDialog('delete_box_<?=$remove_id?>')">删除</a>
          <?php endif;?>
          <?php } ?>
        </td>
      </tr>
      <?php if($mode == 'trash'):?>
      <?php $recycles = $val['recycle'];?>
      <?php if (count($recycles)) {?>
      <tr>
      	  <td colspan="8">
      	  		<strong>删除原因:</strong>
      	  		<ul class="recycle">
      	  			<?php foreach ($recycles as $k=>$recycle) {?>
      	  			<li><?php echo $k+1;?>、<?php echo $recycle['reason'] . '  <font color="red">' . $recycle['ctime'] . '</font>';?></li>
      	  			<?php }?>
      	  		</ul>
      	  </td>
      </tr>
      <?php }?>
      <?php endif;?>
      <?php endforeach; ?>
      <tr class="altbg1">
        <td colspan="8">
<table class="cls_box">
<tr><td>
          <?php if ($priv_manage) {?>
          <button type="button" class="btn2" onclick="checkbox_checked('ids[]');">全选</button>
          <select name="batch_op" id="batch_op">
           <option value="">-选择操作-</option><option value="">暂无！</option>
           <?php if($mode=='trash'):?>
           <option value="restore" op="<?=site_url('admin/student/batch_restore')?>">批量还原</option>
           <option value="remove" op="<?=site_url('admin/student/batch_remove')?>">批量移除</option>
           <?php else:?>
           <?php /*?><option value="restore" op="<?=site_url('admin/student/batch_delete')?>">批量删除</option><?php */?>
           <?php endif;?>
          </select>
          <?php } ?>
          </td><td style="text-align:right">
          <?=$pagination?>
</td></tr></table>          
</td>
      </tr>
      <?php else: ?>
      <tr>
        <td colspan="8">暂无记录！</td>
      </tr>
      <?php endif; ?>
    </table>
    <center><input type="submit" name="dosubmit" value=" 提交操作 " class="btn" /></center>
  </div>
  </form>


<?php if($list) { ?>
<?php foreach($list as $val) { ?>
  <?php if ($priv_manage && $priv_delete) {?>
  <?php $remove_id = $val['uid'];?>
  <div id="delete_box_<?php echo $remove_id;?>" style="display:none">
<div class="cls_title">请输入删除(<?=$val['last_name']?><?=$val['first_name']?>)原因</div>
<div class="space" style="margin:5px">
                        <textarea title="请输入 删除原因" placeholder="请输入 删除原因" name="note" id="txt_reason_<?php echo $remove_id;?>"></textarea><br/><center>
                        <input type="button" value="保存" class="btn btn_submit_delete" delete_id="<?php echo $remove_id;?>" post_url="<?=site_url('admin/student/delete/'.$remove_id)?>" rel="<?php echo $remove_id;?>" id="btn_submit_<?php echo $remove_id;?>" style="margin-top:4px;"/>
                        <input type="button" class="btn" onclick="fnCloseDialog('delete_box_<?=$remove_id?>')" value="取消"/></center>
</div>
          </div> 
  <?php } ?>
<?php } ?>
<?php } ?>



<div id="id_qry_dlg" style="display:none">
<div class="cls_title">搜索学生信息</div>
  <form method="get" name="search_form" action="<?=site_url('admin/student/index/'.$mode)?>">
    <div class="space" style="margin:5px">
        <table class="maintable" border="0" cellspacing="0" cellpadding="0">
            <tr>
                <td class="altbg1">学生ID</td>
                <td>
                <input type="text" name="uid" value="<?=$search['uid']?>"/>
                <font color="red">*注：根据学生ID搜索时，其他条件将失效</font>
                </td>
            </tr>  
        
            <tr>
                <td class="altbg1">所属地区</td>
                <td>
                  <select name="province" id="selProvinces" onchange="region.changed(this, 2, 'selCities');set_schools();$('#selAreas').html('<option value=0>--请选择区县--</option>');">
                    <option value="0">--请选择省--</option>
                    <?php foreach($province_list as $val): ?>
                    <option value="<?=$val['region_id']?>" <?=$val['region_id']==$search['province']?' selected="selected" ':''?>><?=$val['region_name']?></option>
                    <?php endforeach; ?>
                  </select>
                  <select name="city" id="selCities" onchange="region.changed(this, 3, 'selAreas');set_schools();">
                    <option value="0">--请选择市--</option>
                    <?php foreach($city_list as $val): ?>
                    <option value="<?=$val['region_id']?>" <?=$val['region_id']==$search['city']?' selected="selected" ':''?>><?=$val['region_name']?></option>
                    <?php endforeach; ?>
                  </select>
                  <select name="area" id="selAreas" onchange="set_schools();">
                    <option value="0">--请选择区县--</option>
                    <?php foreach($area_list as $val): ?>
                    <option value="<?=$val['region_id']?>" <?=$val['region_id']==$search['area']?' selected="selected" ':''?>><?=$val['region_name']?></option>
                    <?php endforeach; ?>
                  </select>
                </td>
            </tr>
            <tr>
                <td class="altbg1">年级</td>
                <td>
                  <select name="grade_id" onchange="set_schools()" id="grade_id">
                    <option value="0">--请选择--</option>
                    <?php foreach($grades as $key => $val): ?>
                    <option value="<?=$key?>"<?=$key==$search['grade_id']?' selected="selected" ':''?>><?=$val?></option>
                    <?php endforeach; ?>
                  </select>  
                </td>
            </tr>
            <tr>
                <td class="altbg1">所在学校</td>
                <td>                      
                  <select name="school_id" id="school_id">
                    <option value="0">--请选择学校--</option>
                  </select>
                </td>
            </tr> 
            <tr>
                <td class="altbg1">学生来源</td>
                <td>                      
                  <select name="from" id="from">
                    <option value="-1">--请选择--</option>
                    <?php foreach ($from as $key => $item) {?>
                    <option value="<?=$key;?>" <?=(isset($search['from']) && $key == $search['from'] ? ' selected="selected" ':'')?>><?=$item?></option>
                    <?php }?>
                  </select>
                </td>
            </tr> 
            <tr>
                <td class="altbg1">关键字(姓/名/身份证)</td>
                <td><input type="text" name="keyword" value="<?=$search['keyword']?>" class="txtbox" /></td>
            </tr>   
            <tr>
                <td class="altbg1">准考证</td>
                <td><input type="text" name="exam_ticket" value="<?=$search['exam_ticket']?>" class="txtbox" /></td>
            </tr>
            <tr>
                <td class="altbg1">邮箱</td>
                <td><input type="text" name="email" value="<?=$search['email']?>" class="txtbox" /></td>
            </tr>      
            <tr>
                <td class="altbg1">联系方式</td>
                <td><input type="text" name="mobile" value="<?=$search['mobile']?>" /></td>
            </tr>
        </table>
        <center><input type="submit" value=" 搜索 " class="btn" /> <input type="button" value="重置 " class="btn" onclick="window.location.href='<?php echo site_url('admin/student') . "/index/$mode";?>'"/></center>
    </div>
  </form>
</div>
</div>

<script type="text/javascript">
  $(document).ready(function () {
      //重置密码
      $('a.reset_password').unbind('click').bind('click', function () {
            var uid = $(this).attr('rel'),
            	uname = $(this).attr('i_name');
			new $.Zebra_Dialog('', {
			    'source':  {'ajax': '<?php echo site_url('admin/student/load_reset_password');?>/' + uid},
			    'type':     '',
			    width: 890,
			    'title': '修改 学生 (<font color="red" style="font-size:16px;">' + uname + '</font>) 的密码'
			});

			setTimeout(function () {
				$('div.ZebraDialog_Buttons').hide();
			}, 500);
	});
    	
	window.close_dialog = function () {$('.ZebraDialog_Button_0').click();}
});
</script>

<?php $this->load->view('common/footer');?>

