<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>
<?php if(!empty($exam['exam_id'])){ ?>
<?=$exam['exam_name']?>
<?php } else {?>
<?=C('webconfig/site_name')?>
<?php }?>
</title>
<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<meta http-equiv="x-ua-compatible" content="ie=7" />

<?php static_css('index/login.css');?>

<script type="text/javascript">
var siteurl = "<?=site_url()?>";
if(self.parent.frames.length != 0)
{
    self.parent.location=document.location;
}
</script>
<?=C('tongji_script')?>
</head>
<body>
<p>&nbsp;</p><p>&nbsp;</p>
<?php if(!empty($exam['exam_id'])){ ?>
<div id="zeming_logo_new"></div>
<?php }else{ ?>
<div id="zeming_logo"></div>
<?php } ?>
<?php /*if(!empty($exam['exam_id'])){ ?>
<div style="text-align:center;"><?=$exam['exam_name']?></div>
<?php } */?>
<table width="600" border="0" cellpadding="8" cellspacing="0" class="login_table">
<!--<tr>
    <td colspan="3" class="table_title"><?/*=C('webconfig/site_name')*/?></td>
</tr>-->
<tr>
    <td colspan="2" height="10"></td>
</tr>
<tr>
    <td width="50%" align="center">
    <a href="<?=site_url('student/profile/basic/'.(isset($exam['exam_id']) ? $exam['exam_id'] : ''))?>"><img src="<?=__HTML_URL__?>images/index/reg.gif" border="0"/></a>
    </td>
    <td style="width:1px;background:#dedede;padding:0px;"> </td>
    <td align="center">
       <a href="<?=site_url('student/index/login/'.(isset($exam['exam_id']) ? $exam['exam_id'] : ''))?>"><img src="<?=__HTML_URL__?>images/index/edit.gif"  border="0"/></a>
    </td>
</tr>

<tr>
    <td colspan="3" align="center" height="50" class="cls_posr">
        Powered by <?php if(!empty($exam['exam_id'])){ ?><a href="http://www.ruida-edu.com/" target="_blank"><?=C('webconfig/rd_name')?><i class="cls_copyright_tm"></i></a>&nbsp;<?php }else{ ?><a href="<?=site_url()?>" target="_blank"><?=C('webconfig/site_name')?><i class="cls_copyright_tm"></i></a>&nbsp;<?php } ?><span class="cls_copyright_main"><?php echo date('Y');?>&nbsp;&nbsp;<?=C('version')?></span>
    </td>
</tr>
</table>
</body>
</html>
