<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN">
<html><head>
<title>
<?php if(!empty($exam['exam_id'])){ ?>
<?=$exam['exam_name']?>
<?php } else {?>
<?=C('webconfig/site_name')?>
<?php }?>
</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body style="padding: 0;margin: 0;">
    <div style="height:101px;width: 100%">
        <iframe frameborder="0" id="header" name="header" src="<?=site_url('student/teacher_download/top/')?>"
        scrolling="no" style="height:101px; visibility: inherit; width: 100%; ">
        </iframe>
    </div>
    <div class="clearfix cls_iframe_height" style="position: relative;">
        <div class="cls_iframe_left fl_l" style="position: absolute;top: 0;left: 0;width: 12%;top: 3px;height: 710px;">
            <iframe frameborder="0" id="menu_iframe" name="menu_iframe" src="<?=site_url('student/teacher_download/left/')?>"
                    scrolling="no" style="height:100%; visibility: inherit; width: 100%;overflow: auto;">
            </iframe>
        </div>
       <div class="cls_iframe_right fl_l" style="float: right;clear: both;width: 88%;height: 710px;margin-top:3px;*margin-top:-6px;">
            <iframe frameborder="0" id="main_iframe" name="main_iframe" src="<?=site_url('student/teacher_download/teacher_info/')?>"
                    style="height:100%; visibility: inherit; width: 100%; z-index: 1;">
            </iframe>
        </div>
    </div>
</body>
</html>
