<?php $this->load->view('common/header');?>
<?php static_global(array('js/common/common.js'));?>
<script>
    $(function(){
        $('#form').submit(function(){
            // 旧密码不能为空
            if($('input[name="old_password"]').val() == '') {
                alert('密码不能为空！');
                return false;
            }

            // 新密码规则验证
            pwd = $('input[name="new_password"]').val()

            if(pwd == '') {
                alert('新密码不能为空！');
                return false;
            }

            if ('string' === typeof(passwd_msg = is_password(pwd))) {
                alert(passwd_msg);
                $('input[name="new_password"]').focus();
                return false;
            }

            if ($('input[name="repeat_password"]').val() != pwd) {
                alert('两次密码输入不一致！');
                $('input[name="repeat_password"]').focus();
                return false;
            }

        });
    });
    
</script>

<div id="body">
    <div class="space">
        <div class="subtitle">修改密码</div>
        <form  id="form" method="post" action="<?=site_url('student/teacher_download/reset_password_deal')?>" enctype="multipart/form-data">
            <table class="maintable" id="table_basic" border="0" cellspacing="0" cellpadding="0">
                <tr>
                    <td style="border:none;height:10px;"></td>
                </tr>
                <tr>
                    <td colspan="2" class="altbg2" style="text-align: left;">
                        <span class="altbg2-bg">修改密码</span>
                        <i class="altbg2-r"></i>
                    </td>
                </tr>
                <tr>
                    <td width="16%" class="altbg1">原密码</td>
                    <td>
                        <input type="password" name="old_password">
                        <span><i style="color:red;">*</i> 请输入旧密码</span>
                    </td>
                </tr>
                <tr>
                    <td width="16%" class="altbg1">新密码</td>
                    <td>
                        <input type="password" name="new_password">
                        <span><i style="color:red;">*</i> 密码长度必须为6~20个字符</span>
                    </td>
                </tr>
                <tr>
                    <td width="16%" class="altbg1">确认新密码</td>
                    <td>
                        <input type="password" name="repeat_password">
                        <span><i style="color:red;">*</i> 请再次输入密码</span>
                    </td>
                </tr>
                <tr>
                    <td colspan="2" style="text-align:center;border:none;">
                        <center>
                            <input type="submit" name="dosubmit"  value=" 提交  " class="btn" />
                        </center>
                    </td>
                </tr>
                <tr>
                    <td class="altbg1" colspan="2" style="border-bottom:2px solid #045eab;"></td>
                </tr>
            </table>
        </form>
    </div>
</div>