
<h4>亲爱的会员：<?=$student['email']?>，您好！</h4>

<p>您于<?=date('Y-m-d H:i')?>提交了验证邮箱有效性申请,请在半个小时内点击下面的链接完成验证</p>
<p>
<a href="<?=site_url('student/index/validate/').'?code='.$hash?>" target="_blank">点击验证Email地址</a>


<p>
如果上述文字点击无效，请把下面网页地址复制到浏览器地址栏中打开：<a href="<?=site_url('student/index/validate/').'?code='.$hash?>" target="_blank"><?=site_url('student/index/validate/').'?code='.$hash?></a>
</p>
<br/>
<br/>
<div align="right" style="font-size:14px;">
杭州择明教育科技<br/>
择明，为你架起人和教育的链接！
</div>
