<?php if (count($ttd_match_percent['data'])) {?>
	<h5 class="cls_row title_level_2"><?=$g_sort?>.<?=$c_sort?><?=$module_name?>
	：<span class="cr"><?php echo ($ttd_match_percent['percent'] > 100 ? 100 : $ttd_match_percent['percent']);?>%</span>
	</h5>
	<?php $count_num = 1; ?>
	<?php foreach ($ttd_match_percent['data'] as $keys => $item) {?>
	   	<table class="cls_row indent_25 cls_table <?php if($count_num == 1){ echo 'table_header';} ?>" <?php if($count_num == 1): ?>id="table_clss_match_percent"<?php else: ?><?php if (!$no_paging) {?>ref_title_id="table_clss_match_percent"<?php }?><?php endif; ?>>
	       	<tr>
		       	<?php foreach ($item as $key => $val) {?>
			   		<<?=is_numeric($val) ? 'td' : 'th'?> width="20%" <?php if ($keys == 1 && is_numeric($val) && $val > -1 && $val != $ttd_match_percent['data'][3][$key]) {?>style="color:<?=$val > $ttd_match_percent['data'][3][$key] ? 'green' : 'red'?>"<?php }?>>
			   		<?php if (is_numeric($val)) {?>
			   		<?=$val > -1 ? round($val) : '-'?>
			   		<?php } else {?>
			   		<?=$val?>
			   		<?php }?>
			   		</<?=is_numeric($val) ? 'td' : 'th'?>>
			   	<?php }?>	           
	       	</tr>
	    </table>
	    <?php $count_num++; ?>
	<?php }?>
<?php } ?>
