<?php if ($clss_rank_factor['data']) {?>
<h5 class="cls_row title_level_2"><?=$g_sort?>.<?=$c_sort?><?=$module_name?></h5>
<table class="cls_row indent_25 cls_table">
<?php $title = array('排名系数', '班级', '全校');?>
<?php foreach ($clss_rank_factor['data'] as $key => $item) {?>
    <?php $width = 100 / (count($item) + 1);?>
   	<tr>
        <th width="<?=$width?>%"><?=$title[$key]?></th>
       	<?php foreach ($item as $val) {?>
   		<<?=!$val || is_numeric($val) ? 'td' : 'th'?> width="<?=$width?>%">
   		<?=$val ? $val : '-'?>
   		</<?=!$val || is_numeric($val) ? 'td' : 'th'?>>
	   	<?php }?>	           
   	</tr>
<?php }?>
</table>

<?php 
    $prev_rate = 0;
    $text = array();
    $end_name = end(array_keys($clss_rank_factor['proportion']));
    foreach ($clss_rank_factor['proportion'] as $name => $rate) 
    {
        if ($prev_rate && $end_name != $name)
        {
            $text[] = "前{$prev_rate}%-{$rate}%为{$name}";
        }
        else if ($prev_rate && $end_name == $name)
        {
            $text[] = "后" . (100 - $prev_rate) ."%为{$name}";
        }
        else
        {
            $text[] = "前{$rate}%为{$name}";
        }
   
        $prev_rate = $rate;
    }
?>
<?php if ($text) {?>
<p class="cls_row">&nbsp;</p>
<p class="mokuai-text cls_row font12">&emsp;&emsp;注：定义学校<?=implode('，', $text)?>；排名系数代表各分数段学生平均名次。</p>
<?php }?>
<?php }?>