<?php
/**
 * 诊断及建议 --相同知识点强弱点分布情况
 */
?>
<?php if (count($clss_contrast_knowledge['data'])) {?>
<?php 
$data = $clss_contrast_knowledge['data'];
?>
    <h5 class="cls_row title_level_2"><?=$g_sort?>.<?=$c_sort?><?=$module_name?></h5>
        <?php if ($data) {?>
            <?php $last_k = end(array_keys($data));?>
            <?php foreach ($data as $k_name => $item) {?>
            <table class="cls_row table_header indent_25">
                <tr>
                <th width="25%"><?=$k_name?></th>
                <th width="25%">记忆(%)</th>
                <th width="25%">理解(%)</th>
                <th width="25%">应用(%)</th>
                </tr>
                <?php foreach ($item as $key => $val) {?>
                <tr>
                    <?php foreach ($val as $k => $v) {?>
                    <<?=is_numeric($v) ? 'td' : 'th'?> width="25%" <?php if(is_numeric($v) && $key == 0 && $v > -1 && $item[1][$k] > -1 && $v != $item[1][$k]) {?>style="position:relative;"<?php }?>>
                    <?php if ($v > -1) {?>
                    <?=$v?>
                    <?php } else {?>
                    -
                    <?php }?>
                    
                    <?php if (is_numeric($v) && $key == 0 && $v > -1 && $item[1][$k] > -1 && $v != $item[1][$k]) {?>
				   	<div class="<?php if ($v > $item[1][$k]){?>cls_sort cls_up<?php } else {?>cls_sort cls_down<?php }?>"></div>
        		   	<?php }?>
                    </<?=is_numeric($v) ? 'td' : 'th'?>>
                    <?php }?>
                </tr>
                <?php }?>
            </table>
            <?php if ($k_name != $last_k) {?>
            <p class="cls_row">&nbsp;</p>
            <?php }?>
            <?php }?>
        <?php }?>
<?php } ?>