<?php $this->load->view('common/header');?>
<?php static_global('js/datepicker/wdatepicker.js');?>

<script language="javascript">
function check_form(form) {                      
    if (checkbox_check('ids[]')) {
        var op = $('#batch_op').val();
        if (op == '') {
            alert('请选择操作类型');
            return false;
        } else {
            if (op == 'relate') {
                var relate_ques_id = parseInt($('#relate_ques_id').val());
                if (isNaN(relate_ques_id)) {
                    alert('请填写被关联试题ID.');
                    return false;
                }
            }
            if (confirm('您确定要执行该操作么？')) {
                var action = $('#batch_op').find('option[value='+op+']').attr('op');
                form.action = action;
                return true;
            }
        }
    }
    return false;
}

$(document).ready(function(){
    set_batch_option();
    $('.ques_title').find('div').dblclick(function(){
        $(this).toggleClass('line_18');
    });
    $('#batch_op').change(function(){
        set_batch_option();
    });
});

function set_batch_option() {
    var op = $('#batch_op').val();
    if (op == 'relate') {
        $('#batch_extend').show();
    } else {
        $('#batch_extend').hide();
    }
}

</script>
<div id="body">
  <form name="frm_info" action="<?=site_url('admin/interview_question/batch_delete')?>" method="POST" onsubmit="return check_form(this)">
  <div class="space">
    <div class="subtitle">
    <?php if($mode=='trash'):?>
    面试题回收站
    <?php else:?>
    <?php if ($priv_manage) {?>
    <a class="menu" href="<?=site_url('admin/interview_question/add')?>">添加面试题</a>
    <?php } ?>
    <a class="menu" href="javascript:void(0)" onclick="fnShowDialog('id_qry_dlg')">查询</a>


    面试题管理
    <?php endif;?>
    </div>  
    <table class="maintable" border="0" cellspacing="0" cellpadding="0">
      <tr class="altbg1">
        <td width="5%">ID</td>
        <td>题目</td>
        <td width="10%">年段</td>
        <td width="10%">类型</td>
        <td width="5%">语言</td>
        <td width="10%">考点</td>
        <td width="10%">录入时间</td>
        <td width="8%">录入人员</td>
        <td width="15%">操作</td>
      </tr>
      <?php if($list):?>
      <?php foreach($list as $val):?>
      <tr>
        <td><?php if ($priv_manage) {?><input type="checkbox" name="ids[]" value="<?=$val['id']?>"/><?php } ?><?php echo $val['id'];?></td>
        <td class="ques_title"><div class="line_18"><?=$val['content']?></div></td>
        <td><?=$val['period_name']?></td> 
        <td><?=$val['class_name']?></td>
        <td><?=$val['language']?></td>
        <td><?=$val['type_name']?></td>        
        <td><?=$val['addtime']?></td> 
        <td><?=$val['realname']?></td> 
        <td>
          <a href="<?=site_url('admin/interview_question/preview/'.$val['id'])?>">预览</a>
          <?php if ($priv_manage) {?>
          <a href="<?=site_url('admin/interview_question/edit/'.$val['id'])?>">编辑</a>

          <?php if($mode=='trash'):?>
          <a href="<?=site_url('admin/interview_question/restore/'.$val['id'])?>" onclick="return confirm('您确定要还原么？');">还原</a>
          <a href="<?=site_url('admin/interview_question/remove/'.$val['id'])?>" onclick="return confirm('您确定要移除么？');">移除</a>
          <?php else:?>
          <?php if($priv_delete):?>
          <a href="<?=site_url('admin/interview_question/delete/'.$val['id'])?>" onclick="return confirm('您确定要删除么？');">删除</a>
          <?php endif;?>
          <?php endif;?>

          <?php if($val['group_id']):?>
          <a href="<?=site_url('admin/relate_group/group/'.$val['group_id'])?>">关联组[<?=$val['group_id']?>]</a>
          <?php endif;?>
          <?php } ?>
        </td>
      </tr>
      <?php endforeach; ?>
      <?php else: ?>
      <tr>
        <td colspan="9">暂无记录！</td>
      </tr>
      <?php endif; ?>
      <tr class="altbg1">
        <td colspan="2">
          <?php if ($priv_manage) {?>
          <button type="button" class="btn2" onclick="checkbox_checked('ids[]');">全选</button>
          <?php if($mode=='trash'):?>
          <select name="batch_op" id="batch_op">
           <option value="">-选择操作-</option>
           <option value="restore" op="<?=site_url('admin/interview_question/batch_restore')?>">批量还原</option>
           <option value="remove" op="<?=site_url('admin/interview_question/batch_remove')?>">批量移除</option>
          </select>
          <?php else:?>
          <select name="batch_op" id="batch_op">
           <option value="">-选择操作-</option>
           <option value="relate" op="<?=site_url('admin/interview_question/batch_relate')?>">关联试题</option>
           <option value="unrelate" op="<?=site_url('admin/interview_question/batch_unrelate')?>">取消关联</option>
           <option value="delete" op="<?=site_url('admin/interview_question/batch_delete')?>">批量删除</option>
          </select>
          <span style="display:none;" id="batch_extend">
          关联试题ID（<font class="font_4">机考试题</font>）:
          <input type="text" class="txtbox5" name="relate_ques_id" id="relate_ques_id" />
          </span>
          <?php endif;?>
          <?php } ?>
        </td>
        <td colspan="7" style="text-align:right"><?=$pagination?></td>
      </tr>
    </table>
    <center><input type="submit" name="dosubmit" value=" 提交操作 " class="btn" /></center>
  </div>
  </form>


<div id="id_qry_dlg" style="display:none;min-width:500px">
        <div class="cls_title">搜索面试试题</div>
  <form method="get" name="search_form" action="<?=site_url('admin/interview_question/index/'.$mode)?>">
    <div class="space" style="margin:5px">
        <table class="maintable" border="0" cellspacing="0" cellpadding="0">
            <tr>
                <td class="altbg1">管理员</td>
                <td>
                  <select name="admin_id">
                  <option value="">=录入人员=</option>
                  <?php foreach($admin_list as $admin):?>
                  <option value="<?=$admin['admin_id']?>"<?=$search['admin_id']==$admin['admin_id']?' selected':''?>><?=$admin['admin_user']?><?=$admin['realname']?'['.$admin['realname'].']':''?></option>
                  <?php endforeach;?> 
                  </select>
                </td>
            </tr>
            <tr>
                <td class="altbg1">录入时间</td>
                <td>
                    <input type="text" id="begin_time" name="begin_time" class="txtbox4" value="<?=$search['begin_time']?>" onclick="WdatePicker({dateFmt:'yyyy-MM-dd',startDate:'2013-09-01'});"> - 
                    <input type="text" id="end_time" name="end_time" class="txtbox4" value="<?=$search['end_time']?>" onclick="WdatePicker({dateFmt:'yyyy-MM-dd',startDate:'2013-09-01'});">
                </td>
            </tr>
            <tr>
                <td class="altbg1">年段</td>
                <td>
                  <?php foreach($periods as $k => $v):?>
                  <input type="checkbox" name="period[]" value="<?=$k?>" id="period<?=$k?>" <?php if(in_array($k, $search['period'])) echo 'checked';?>/> <label for="period<?=$k?>"><?=$v?></label>
                  <?php endforeach;?>
                </td>
            </tr>
            <tr>
                <td class="altbg1">类型</td>
                <td>
                  <?php foreach($class_list as $v):?>
                  <input type="checkbox" name="class_id[]" value="<?=$v['class_id']?>" id="class<?=$v['class_id']?>" <?php if(in_array($v['class_id'], $search['class_id'])) echo ' checked';?>/> <label for="class<?=$v['class_id']?>"><?=$v['class_name']?></label>
                  <?php endforeach;?> 
                </td>
            </tr>
            <tr>
                <td class="altbg1">语言</td>
                <td>
                  <select name="lang">
                  <option value="">=语言=</option>
                  <?php foreach($langs as $k => $v):?>
                  <option value="<?=$k?>"<?=$k==$search['lang']?' selected':''?>><?=$v?></option>
                  <?php endforeach;?> 
                  </select>
                </td>
            </tr>
            <tr>
                <td class="altbg1">考点</td>
                <td>
                  <select name="interview_type">
                  <option value="">=考点=</option>
                  <?php foreach($types as $k => $v):?>
                  <option value="<?=$k?>"><?=$v['pid']?'　':''?><?=$v['type_name']?></option>
                  <?php endforeach;?> 
                  </select>
                </td>
            </tr>
            <tr>
                <td class="altbg1">关键字</td>
                <td><input type="text" name="keyword" value="<?=$search['keyword']?>" class="txtbox" /></td>
            </tr>         
        </table>
        <center>
        <input type="submit" value=" 搜索 " class="btn" />
        <input type="button" value=" 重置 " class="btn" onclick="window.location.href='<?php echo site_url('admin/interview_question/index') . '/' .$mode;?>' "/>
        </center>
    </div>
  </form>
</div>

</div>
<?php $this->load->view('common/footer');?>
