<?php if (!empty($std_method_tactic['data'])) {?>
    <h5 class="cls_row title_level_2"><?=$g_sort?>.<?=$c_sort?><?=$module_name?></h5>
    <?php 
		$std_method_tactic['fields'] = isset($std_method_tactic['fields']) ? $std_method_tactic['fields'] : array();
		$std_method_tactic['data'] = isset($std_method_tactic['data']) ? $std_method_tactic['data'] : array();
		$std_method_tactic['comment_data'] = isset($std_method_tactic['comment_data']) ? $std_method_tactic['comment_data'] : array();
	?>
	
	<?php if (isset($std_method_tactic['flash_data']['data']) && count($std_method_tactic['flash_data']['data'])) {?>
            <?php
                $flash_titles = array();
                //flash_data
                $flash_data = array();
                foreach ($std_method_tactic['flash_data']['field'] as $name)
                {
                    $tmp_arr = array();
                    foreach ($std_method_tactic['flash_data']['data'] as $mt_name=>$item)
                    {
                        $tmp_arr[] = isset($item[$name]) ? floatval($item[$name]) : 0;
                        $flash_titles[] = $mt_name;
                    }
                    $flash_data[] = array(
                                            'name'  => $name,
                                            'data'  => $tmp_arr,
                                );
                }
                $std_method_tactic['flash_data']['data'] = $flash_data;
                $flash_titles = array_unique($flash_titles);
            ?>
            <div id="flash_container_std_mt_<?=$t_subject_id?>" class="cls_row indent_25"></div>
            <script type="text/javascript">
                $(function () {
                   //方法策略柱状图1
                   $('#flash_container_std_mt_<?=$t_subject_id?>').highcharts({
                   chart: {
                       type: 'column',
                       height: '410'
                   },
                   title: {
                       text: '  方法策略柱状图'
                   },
                   xAxis: {
                       categories: eval("("+'<?php echo json_encode($flash_titles); ?>'+")"),
                       labels: {
                            rotation : -45,//坐标旋转角度 为0：表示横放置
                            align : 'right'
                            /* style: {
                                fontSize: '13px',
                                fontFamily: 'Verdana, sans-serif'
                            } */
                        }   
                   },
                   yAxis: {
                        title: {
                            text: ''
                        }
                    },  
                   plotOptions : {
                       column : {
                            //pointWidth: 2,    //柱子的大小(会影响到柱子的大小)
                           pointPadding: 0  //柱子之间的间隔(会影响到柱子的大小)
                       }
                   },
                   legend: {
                       layout: 'vertical',
                       align: 'right',
                       verticalAlign: 'middle',
                       borderWidth: 0
                   },
                   colors: ['#4F81BD','#F15A24','#8CC63F','#93489B','#FBB03B','#00A99D','#4C5260','#959FB1','#90B9EA','#F7AA8E','#B9E881','#DE98E5','#F5CB8E','#67D8CE','#A0B7F2'],
                   series: eval("("+'<?php echo json_encode($std_method_tactic['flash_data']['data']); ?>'+")")
                   /*
                   series: [{
                       name: '我-总体1',
                       data: [4, -3, 3]
                   }, {
                       name: '我-总体2',
                       data: [2, 4, 1.5]
                   }]*/
                   });
               });
            </script>
            <?php if (isset($std_method_tactic['flash_comment'])) {?>
                <p class="mokuai-text cls_row indent_25">
                    <?php if (empty($std_method_tactic['flash_comment'])) :?>
                        你对方法策略的理解使用已经游刃有余，继续努力使自己的领悟更加精进。
                    <?php else :?>
                        你对<?=$std_method_tactic['flash_comment']?>已经摸着门路，要登堂入室、举一反三还需继续努力。
                    <?php endif;?>
                </p>
            <?php } ?>
        <?php } ?>
        <p class="cls_row">&nbsp;</p>
        <?php if (count($std_method_tactic['comment_data'])) {?>
           <table class="mb10 cls_row table_header indent_25" id="table_std_mt_c">
                <tr>
                    <th width="15%">方法策略</th>
                    <th width="15%">得分率(%)</th>
                    <th width="15%">掌握等级</th>
                    <th width="55%">评价</th>
                </tr>
            </table>
            <?php $auto_key = 0;?>
            <?php foreach ($std_method_tactic['comment_data'] as $item) {?>
                <?php $auto_key++;?>
                <table class=" cls_row cls_table indent_25" <?php if (!$no_paging) {?>ref_title_id="table_std_mt_c"<?php }?>>
                    <tr <?if ($auto_key%2==0) { ?>class="bgc_level<?=Fn::judgmentBelongsLevel($item['percent'])?>"<?}?>>
                        <th width="15%">
                        <?if ($zmcat_studyplus_enabled) {?><a href="/student/index/studyplus?<?=http_build_query(array('ms_name'=>$item['name'], 'subject_name'=>$subject_name))?>" target="_blank"><?=$item['name']?></a><?}else{?><?=$item['name']?><?}?>
                        </th>
                        <td width="15%"><?php echo $item['percent'];?></td>
                        <td width="15%"><?php echo str_repeat("★", $item['level']);?></td>
                        <td width="55%" style="text-align:left;"><?php echo $item['comment'];?></td>
                    </tr>
                </table>
            <?php } ?>
        <?php } ?>
<?php } ?>