<?php if (count($std_knowledge['comment_data'])) {?>
    <h5 class="cls_row title_level_2"><?=$g_sort?>.<?=$c_sort?><?=$module_name?></h5>
    
    <?php if (isset($std_knowledge['flash_data']['data']) && count($std_knowledge['flash_data']['data'])) {?>
        <?php
            $flash_titles = array();
            //flash_data
            $flash_data = array();
            foreach ($std_knowledge['flash_data']['field'] as $name)
            {
                $tmp_arr = array();
                foreach ($std_knowledge['flash_data']['data'] as $k_name=>$item)
                {
                    $tmp_arr[] = isset($item[$name]) ? floatval($item[$name]) : 0;
                    $flash_titles[] = $k_name;
                }
                $flash_data[] = array(
                                        'name'  => $name,
                                        'data'  => $tmp_arr,
                            );
            }
            $std_knowledge['flash_data']['data'] = $flash_data;
            $flash_titles = array_unique($flash_titles);
        ?>

        <div id="flash_container_std_k_<?=$t_subject_id?>"  class="cls_row indent_25"></div>
        <script type="text/javascript">
            $(function () {
               //柱状图1
                $('#flash_container_std_k_<?=$t_subject_id?>').highcharts({
                    chart: {
                        type: 'column',
                        height: '400'
                    },
                    title: {
                        text: ' 知识模块柱状图'
                    },
                    xAxis: {
                        categories: eval("("+'<?php echo json_encode($flash_titles); ?>'+")"),
                        labels: {
                            rotation : -45,//坐标旋转角度 为0：表示横放置
                            align : 'right'
                            /* style: {
                                fontSize: '13px',
                                fontFamily: 'Verdana, sans-serif'
                            } */
                        }           
                    },
                    yAxis: {
                        title: {
                            text: ''
                        }
                    },      
                    plotOptions : {
                        column : {
                            //pointWidth: 2,    //柱子的大小(会影响到柱子的大小)
                            pointPadding: 0 //柱子之间的间隔(会影响到柱子的大小)
                        }
                    },
                    legend: {
                        layout: 'vertical',
                        align: 'right',
                        verticalAlign: 'middle',
                        borderWidth: 0
                    },
                    colors: ['#4F81BD','#F15A24','#8CC63F','#93489B','#FBB03B','#00A99D','#4C5260','#959FB1','#90B9EA','#F7AA8E','#B9E881','#DE98E5','#F5CB8E','#67D8CE','#A0B7F2'],
                    series: eval("("+'<?php echo json_encode($std_knowledge['flash_data']['data']); ?>'+")")
                       /*
                       series: [{
                           name: '我-总体1',
                           data: [4, -3, 3]
                       }, {
                           name: '我-总体2',
                           data: [2, 4, 1.5]
                       }]*/
                });
            });         
        </script>
    <?php } ?>

    <?php if (isset($std_knowledge['flash_comment'])) {?>
        <p class="mokuai-text cls_row indent_25">
            <?php if (empty($std_knowledge['flash_comment'])) :?>
                知识点掌握全面、理解透彻，会当凌绝顶，一览众山小。
            <?php else :?>
                你对<?=$std_knowledge['flash_comment']?>的理解已经略有心得，想要更上一层楼，还需再接再厉。
            <?php endif;?>
        </p>
    <?php }?>
    
    <p class="cls_row">&nbsp;&nbsp;</p>
    
    <table class="mb10 cls_row table_header indent_25" id="table_std_k_c">
        <tr>
            <th width="15%">知识模块</th>
            <th width="15%">得分率(%)</th>
            <th width="15%">掌握等级</th>
            <th width="55%">评价</th>
        </tr>
    </table>
    
    <?php $auto_key  = 0;?>
    <?php foreach ($std_knowledge['comment_data'] as $item) {?>
        <?php $auto_key++;?>
        <table class="cls_row cls_table indent_25" <?php if (!$no_paging) {?>ref_title_id="table_std_k_c"<?php }?>>
            <tr <?if ($auto_key%2==0) { ?>class="bgc_level<?=Fn::judgmentBelongsLevel($item['percent'])?>"<?}?>>
                <th width="15%"><?if ($zmcat_studyplus_enabled) {?><a href="/student/index/studyplus?k_zmtekpid=<?=$std_knowledge['knowledges'][$item['name']]?>" target="_blank"><?=$item['name']?></a><?}else{?><?=$item['name']?><?}?></th>
                <td width="15%"><?php echo $item['percent'];?></td>
                <td width="15%"><?php echo str_repeat("★", $item['level']);?></td>
                <td width="55%" style="text-align:left;"><?php echo $item['comment'];?></td>
             </tr>
        </table>
    <?php } ?>
<?php } ?>