<?php if (count($std_contrast_difficulty['contrast_qtype'])) {?>
    <h5 class="cls_row title_level_2"><?=$g_sort?>.<?=$c_sort?><?=$module_name?></h5>
    <?php 
		$contrast_qtype = isset($std_contrast_difficulty['contrast_qtype']) ? $std_contrast_difficulty['contrast_qtype'] : array();
		$new_qtype = isset($std_contrast_difficulty['new_qtype']) ? $std_contrast_difficulty['new_qtype'] : array();
	?>

	<?php foreach ($contrast_qtype as $index => $vals) {?>
	   <table class="cls_row table_header indent_25">
	   <?php foreach ($vals as $key => $val) {?>
            <tr>
                <?php foreach ($val as $k => $v) {?>
                    <<?=is_numeric($v) || empty($v) ? 'td' : 'th'?> width="25%" <?php if ($key == 1 && is_numeric($vals[2][$k]) && $v != $vals[2][$k]) {?>style="position:relative;"<?php }?>>
                    <?php if (!$key && !$k) {?>
                    <?if ($zmcat_studyplus_enabled) {?><a href="/student/index/studyplus?<?=http_build_query(array('subject_name'=>$subject_name,'questype_name'=>$v))?>" target="_blank"><?=$v?></a><?}else{?><?=$v?><?}?>
                    <?php } else {?>
                    <?=strlen($v) ? $v : '-'?><?=is_numeric($v) ? '%' : ''?>
                    <?php }?>
                    <?php if ($key == 1 && is_numeric($v) && is_numeric($vals[2][$k]) && $v != $vals[2][$k]) {?>
    		   		     <div class="<?php if ($v > $vals[2][$k]){?>cls_sort cls_up<?php } elseif ($v < $vals[2][$k]) {?>cls_sort cls_down<?php }?>"></div>
    		   		 <?php }?>
                    </<?=is_numeric($v) || empty($v) ? 'td' : 'th'?>>
                <?php }?>
            </tr>
        <?php }?>
        </table>
        <?php if ($index != count($contrast_qtype) - 1) {?>
        <p class="cls_row indent_25 font12">&nbsp;</p>
        <?php }?>
	<?php }?>
	
	<?php if ($new_qtype) {?>
	<p class="cls_row indent_25 font12">&nbsp;</p>
    <p class="cls_row indent_25 font12">新题型：</p>
    <p class="cls_row indent_25 font12">&nbsp;</p>
	<?php }?>

    <?php $std_difficulty_key  = 0;?>
    <?php $count_std_difficulty_key = count($new_qtype['data']);?>
    <?php foreach ($new_qtype['data'] as $q_type=>$item) {?>
        <?php $std_difficulty_key++;?>
        <table class="cls_row table_header indent_25" id="table_std_diff_<?echo $std_difficulty_key?>">
            <tr>
                <?php $first_th_width = '15';?>
                <?php $count_data = count($new_qtype['fields']); ?>
                <?php $left_p_width = !$count_data ? 0 : round((100-$first_th_width)/count($new_qtype['fields']));?>
                <th width="<?=$first_th_width?>%">
                <?if ($zmcat_studyplus_enabled) {?><a href="/student/index/studyplus?<?=http_build_query(array('subject_name'=>$subject_name,'questype_name'=>$q_type))?>" target="_blank"><?=$q_type;?></a><?}else{?><?=$q_type;?><?}?>
                </th>
                <?php foreach ($new_qtype['fields'] as $field_name) {?>
                    <th width="<?=$left_p_width?>%"><?php echo $field_name;?></th>
                <?php } ?>
            </tr>
        </table>
        
        <?php $auto_key  = 0;?>
        <?php foreach ($item as $name=>$val) {?>
           <?php $auto_key++;?>
            <table class="cls_row cls_table indent_25" <?php if (!$no_paging) {?>ref_title_id="table_std_diff_<?echo $std_difficulty_key?>"<?php }?>>
                <tr <?php echo $auto_key%2==0 ? 'class="bgc"' : '';?>>
                    <th width="<?=$first_th_width?>%"><?php echo $name;?></th>
                    <?php foreach ($new_qtype['fields'] as $field_name) {?>
                       <?php if ($val[$new_qtype['fields'][0]]) {?>
                      <td width="<?=$left_p_width?>%" <?php if ($field_name == $new_qtype['fields'][2] && $val[$field_name] != $val[$new_qtype['fields'][3]]) {?>style="color:<?=$val[$field_name] > $val[$new_qtype['fields'][3]] ? 'green' : 'red'?>"<?php }?>><?php echo isset($val[$field_name]) ? $val[$field_name] : '-';?></td>
                       <?php } else {?>
                       <td width="<?=$left_p_width?>%">-</td>
                       <?php }?>
                    <?php } ?>
                </tr>
            </table>
        <?php } ?>

        <?php if ($std_difficulty_key != $count_std_difficulty_key):?>
            <hr class="cls_row indent_25"/>
        <?php endif;?>
    <?php } ?>
<?php } ?>