<?php $this->load->view('common/header');?>
<script language="javascript">
function check_form(form) {                      
    if (checkbox_check('ids[]')) {
        var op = $('#batch_op').val();
        if (op == '') {
            alert('请选择操作类型');
            return false;
        } else {
            if (confirm('您确定要执行该操作么？')) {
                var action = $('#batch_op').find('option[value='+op+']').attr('op');
                form.action = action;
                return true;
            }
        }
    }
    return false;
}
</script>
<?
$CI = &get_instance();
$bPrivEdit = $CI->check_power_new('production_category_edit', false); 
$bPrivRemove = $CI->check_power_new('production_category_delete', false);
$bPrivRemoveBatch = $CI->check_power_new('production_category_batch_delete', false);
$bPrivAdd = $CI->check_power_new('production_category_add', false);
$bPrivAddP = $CI->check_power_new('production_add', false);
$bPrivTrans = $CI->check_power_new('account_transactionw', false);
?>
<div id="body">
  <form name="frm_cpuser_list" action="<?=site_url('admin/production_category/batch_delete')?>" method="POST" onsubmit="return check_form(this)">
  <div class="space">
    <div class="subtitle">
<span style="float:left">产品类别管理 </span>        
<span style="float:right"> 
<a href="javascript:void(0)" onclick="fnShowDialog('id_qry_dlg')">查询</a>
<? if ($bPrivTrans) { ?><a href=<?php echo site_url('/admin/account/transactionw');?>>统计报表    </a> <? } ?>
<? if ($bPrivAdd) { ?><a href=<?php echo site_url('/admin/production_category/add');?>>添加产品类别</a><? } ?>
<? if ($bPrivAddP) { ?><a href=<?php echo site_url('/admin/production/add');?>> 添加新产品</a><? } ?>
</span>
    </div>  
    <table class="maintable" border="0" cellspacing="0" cellpadding="0">
      <tr class="altbg1">
        <td width="50">ID</td>
        <td width="100">产品分类名称</td>
        <td>备注</td>
        <td width="100">操作</td>
      </tr>
      <?php if($list):?>
      <?php foreach($list as $val):?>
      <tr>
        <td><?php if ($bPrivRemoveBatch) {?><input type="checkbox" name="ids[]" value="<?=$val['pc_id']?>"><?php } ?><?=$val['pc_id']?></td>
        <td><?=$val['pc_name']?></td>        
        <td><? Func::echo_s($val['pc_memo']); ?></td> 
        <td>          
          
          <?php if ($bPrivEdit) {?>
          <a href="<?=site_url('admin/production_category/edit/'.$val['pc_id'])?>">编辑</a>
          <? } ?>
     
          <? if ($bPrivRemove) { ?>
          <?php if($val['p_id_count']){
          ?>
            <font style="color:#999;text-decoration:line-through;" title="该产品存在交易记录,因此无法删除">删除</font>
            <?php }else{?>
           <a href="<?=site_url('admin/production_category/delete/'.$val['pc_id'])?>">删除</a>
             <?php } ?>
           <? } ?>
        </td>
      </tr>

      <?php endforeach; ?>
      <tr class="altbg1">

 <td colspan="2">
          <?php if ($bPrivRemoveBatch) {?>
          <button type="button" class="btn2" onclick="checkbox_checked('ids[]');">全选</button>
          <select name="batch_op" id="batch_op">
           <option value="">-选择操作-</option>
          <option value="restore" op="<?=site_url('admin/production_category/batch_delete')?>">批量删除</option>
           
          </select>
          <?php } ?>
        </td>
        <td colspan="2" style="text-align:right"><?=$pagination?></td>
      </tr>
      <?php else: ?>
      <tr>
        <td colspan="4">暂无记录！</td>
      </tr>
      <?php endif; ?>
    </table>
<? if ($bPrivRemoveBatch) { ?>
    <center><input type="submit" name="dosubmit" value=" 提交操作 " class="btn" /></center>
<? } ?>
  </div>
  </form>

<div id="id_qry_dlg" style="display:none">
        <div class="cls_title">搜索产品类别信息</div>
  <form method="get" name="search_form" action="<?=site_url('admin/production_category/index/')?>">
    <div class="space">
        <table class="maintable" border="0" cellspacing="0" cellpadding="0">
            <tr>
                <td class="altbg1">产品类别ID</td>
                <td>
                <input type="text" name="pc_id" value="<?=($search['pc_id']>0)?$search['pc_id']:''?>"/>
                <font color="red">*注：根据产品类别ID搜索时，其他条件将失效</font>
                </td>
            </tr>  
   

      
            <tr>
                <td class="altbg1">关键字</td>
                <td><input type="text" name="keyword" value="<?=$search['keyword']?>" class="txtbox" /></td>
            </tr>   
          
        </table>
        <center><input type="submit" value=" 搜索 " class="btn" /> <input type="button" value="重置 " class="btn" onclick="window.location.href='<?php echo site_url('admin/production_category') . "/index";?>'"/></center>
    </div>
  </form>
</div>
</div>
<?php $this->load->view('common/footer');?>
