<?php $this->load->view('common/header');?>

<?php $this->load->view('recycle/recycle.phtml');?>
<script language="javascript">
function check_form(form) {
    if (checkbox_check('ids[]', form.id)) {
        var op = $('#'+form.id+" select").val();
        var action =  $('#'+form.id+" select option:selected").attr('op');
        if (op == '') {
            alert('请选择操作类型');
            return false;
        } else if (op == 'relate') {
            var relate_ques_id = parseInt($('#'+form.id).find('input[name=relate_ques_id]').val());
            if (isNaN(relate_ques_id)) {
                alert('请填写被关联试题ID.');
                return false;
            }
        }
        form.action = action;
        return true;
    }
    return false;
}

$(document).ready(function(){
    $('.ques_title').find('div').dblclick(function(){
        $(this).toggleClass('line_18');
    });
    $('#grade_id').change(function(){
        set_question_class();
    });
    $('.batch_op').change(function(){
        set_batch_option($(this));
    });
});

function set_batch_option(obj) {
    var op = obj.val();
    if (op == 'relate') {
        obj.parent().find('.batch_extend').show();
    } else {
        obj.parent().find('.batch_extend').hide();
    }
}

</script>
<div id="body">
  <form name="frm_list" id="frm_list" action="<?=site_url('admin/question/batch_delete')?>" method="POST" onsubmit="return check_form(this)">
  <div class="space">
    <div class="subtitle">
    <?php if ($has_edit_power) {?>
    <a class="menu" href="<?=site_url('admin/question/add_group/?group='.$group_id)?>">添加关联题组</a>
    <a class="menu" href="<?=site_url('admin/question/add/?group='.$group_id)?>">添加关联试题</a>
    <?php } ?>
    关联组试题</div>
    <table class="maintable" border="0" cellspacing="0" cellpadding="0">
      <tr class="altbg1">
        <td width="7%">&nbsp;&nbsp;ID</td>
        <td>题目（双击展开/收缩）</td>
        <td width="5%">题型</td>
        <td width="5%">学科</td>
        <td width="10%">类型</td>
        <td width="10%">年级</td>
        <td width="15%">录入时间</td>
        <td width="8%">录入人员</td>
        <td width="15%">操作</td>
      </tr>
      <?php if($list_ques):?>
      <?php foreach($list_ques as $val):?>
      <tr>
        <td><?php if ($val['has_edit_power']) {?><input type="checkbox" name="ids[]" value="<?=$val['ques_id']?>" /><?php } ?><?=$val['ques_id']?></td>
        <td title="双击展开" class="ques_title"><div class="line_18" style="">  <?=$val['title']?></div></td>
        <td>
          <?php if($val['qtype']=='题组'):?>
          <font class="font_4">题组</font>
          <?php else:?>
          <?=$val['qtype']?>
          <?php endif;?>
        </td>
        <td><?=$val['subject_name']?></td>
        <td><?=$val['class_name']?></td>
        <td>[<?=$val['start_grade']?>] - [<?=$val['end_grade']?>]</td>
        <td><?=$val['addtime']?></td>
        <td><?=$val['cpuser']?></td>
        <td>
          <?php if ($val['be_tested']) {?>
          <?php if ($val['has_edit_power']) {?>
          <?php if($val['is_parent']):?>
          <font style="color:#999;text-decoration:line-through;" title="该试题已经被考生考过 或者 正在被考中,因此无法操作">管理</font>
	      <font style="color:#999;text-decoration:line-through;" title="该试题已经被考生考过 或者 正在被考中,因此无法操作">编辑</font>
          <?php else:?>
	      <font style="color:#999;text-decoration:line-through;" title="该试题已经被考生考过 或者 正在被考中,因此无法操作">编辑</font>
          <?php endif;?>

          <?php if($priv['delete_question']):?>
	      <font style="color:#999;text-decoration:line-through;" title="该试题已经被考生考过 或者 正在被考中,因此无法操作">删除</font>
          <?php endif;?>

          <?php } else {?>
          <a href="<?=site_url('admin/question/preview/'.$val['ques_id'])?>" target="_blank">预览</a>
          <?php } ?>

          <?php } else {?>

          <?php if ($val['has_edit_power']) {?>

          <?php if($val['is_parent']):?>
          <a href="<?=site_url('admin/question/group/'.$val['ques_id'])?>">管理</a>
          <a href="<?=site_url('admin/question/edit_group/'.$val['ques_id'])?>">编辑</a>
          <?php else:?>
          <a href="<?=site_url('admin/question/edit/'.$val['ques_id'])?>">编辑</a>
          <?php endif;?>

<!--
          <?php if($priv['delete_question']):?>
          <a href="<?=site_url('admin/question/delete/'.$val['ques_id'])?>" onclick="return confirm('您确定要删除么？');">删除</a>
          <?php endif;?>
-->
	           <?php if($priv['delete_question']):?>
		          <?php if ($val['be_tested']) {?>
		          <?php } else {?>
		          <?php $remove_id = $val['ques_id'];?>
		          <a class="a_delete" rel="<?php echo $remove_id;?>" id="a_delete_<?php echo $remove_id;?>" href="###">删除</a>
		          <div class="delete_box display_none" id="delete_box_<?php echo $remove_id;?>">
		        			<textarea title="请输入 删除原因" placeholder="请输入 删除原因" name="note" id="txt_reason_<?php echo $remove_id;?>"></textarea>
		        			<input type="button" value="保存" class="btn btn_submit_delete" delete_id="<?php echo $remove_id;?>" post_url="<?=site_url('admin/question/delete/'.$remove_id)?>" rel="<?php echo $remove_id;?>" id="btn_submit_<?php echo $remove_id;?>" style="margin-top:4px;"/>
		        			<input type="button" rel="<?php echo $remove_id;?>" id="btn_cancle_<?php echo $remove_id;?>" value="取消" class="btn btn_cancle_delete" />
				  </div>
		          <?php } ?>
	          <?php endif;?>
          <?php } ?>
          <a href="<?=site_url('admin/question/preview/'.$val['ques_id'])?>" target="_blank">预览</a>
          <?php } ?>
        </td>
      </tr>
      <?php endforeach; ?>
      <tr class="altbg1">
        <td colspan="2">
          <?php if ($has_edit_power) {?>
          <button type="button" class="btn2" onclick="checkbox_checked('ids[]', 'frm_list');">全选</button>
          <select name="batch_op" class="batch_op">
           <option value="">-选择操作-</option>
           <option value="relate" op="<?=site_url('admin/question/batch_relate')?>">关联试题</option>
           <option value="unrelate" op="<?=site_url('admin/question/batch_unrelate')?>">取消关联</option>
           <option value="delete" op="<?=site_url('admin/question/batch_delete')?>">批量删除</option>
          </select>
          <span style="display:none;" class="batch_extend">
          关联试题ID:
          <input type="text" class="txtbox5" name="relate_ques_id" />
          </span>
          <?php } ?>
        </td>
        <td colspan="7" style="text-align:right"></td>
      </tr>
      <?php else: ?>
      <tr>
        <td colspan="8">暂无记录！</td>
      </tr>
      <?php endif; ?>
    </table>
    <center><input type="submit" name="dosubmit" value=" 提交操作 " class="btn" /></center>
  </div>
  </form>
<?php if ($has_interview_question_manage) {?>
  <form name="frm_list2" id="frm_list2" action="<?=site_url('admin/interview_question/batch_delete')?>" method="POST" onsubmit="return check_form(this)">
  <div class="space">
    <div class="subtitle">
    <a class="menu" href="<?=site_url('admin/interview_question/add?group='.$group_id)?>">添加关联面试题</a>
    关联组面试题</div>
    <table class="maintable" border="0" cellspacing="0" cellpadding="0">
      <tr class="altbg1">
        <td width="8%">ID</td>
        <td>题目</td>
        <td width="10%">年段</td>
        <td width="10%">类型</td>
        <td width="5%">语言</td>
        <td width="10%">考点</td>
        <td width="15%">录入时间</td>
        <td width="8%">录入人员</td>
        <td width="15%">操作</td>
      </tr>
      <?php if($list_interview):?>
      <?php foreach($list_interview as $val):?>
      <tr>
        <td><input type="checkbox" name="ids[]" value="<?=$val['id']?>"/><?=$val['id']?></td>
        <td class="ques_title"><div class="line_18"><?=$val['content']?></div></td>
        <td><?=$val['period_name']?></td>
        <td><?=$val['class_name']?></td>
        <td><?=$val['language']?></td>
        <td><?=$val['type_name']?></td>
        <td><?=$val['addtime']?></td>
        <td><?=$val['cpuser']?></td>
        <td>
          <a href="<?=site_url('admin/interview_question/edit/'.$val['id'])?>">编辑</a>
          <?php if($priv['delete_interview_question']):?>
          <a href="<?=site_url('admin/interview_question/delete/'.$val['id'])?>" onclick="return confirm('您确定要删除么？');">删除</a>
          <?php endif;?>
        </td>
      </tr>
      <?php endforeach; ?>
      <tr class="altbg1">
        <td colspan="2">
          <button type="button" class="btn2" onclick="checkbox_checked('ids[]', 'frm_list2');">全选</button>
          <select name="batch_op" class="batch_op">
           <option value="">-选择操作-</option>
           <option value="relate" op="<?=site_url('admin/interview_question/batch_relate')?>">关联试题</option>
           <option value="unrelate" op="<?=site_url('admin/interview_question/batch_unrelate')?>">取消关联</option>
           <option value="delete" op="<?=site_url('admin/interview_question/batch_delete')?>">批量删除</option>
          </select>
          <span style="display:none;" class="batch_extend">
          关联试题ID（机考试题）:
          <input type="text" class="txtbox5" name="relate_ques_id" />
          </span>
        </td>
        <td colspan="7" style="text-align:right"></td>
      </tr>
      <?php else: ?>
      <tr>
        <td colspan="9">暂无记录！</td>
      </tr>
      <?php endif; ?>
    </table>
    <center><input type="submit" name="dosubmit" value=" 提交操作 " class="btn" /></center>
  </div>
  </form>
<?php }?>
</div>
<?php $this->load->view('common/footer');?>
