<?php

/*
 * 权限菜单
 */

$config['roles'] = array(
        array(
                'label'=>'学生信息管理',
                'code'=>'group_student',
                'priv'=>array(
                        array(
                                'label'=>'学生列表',

                                'code'=>'student_index',

                                'priv'=>array(

                                        array(
                                                'label'=>'预览信息',
                                                'code'=>'student_preview'
                                        ),
                                        array(
                                                'label'=>'编辑',
                                                'code'=>'student_edit'
                                        ),
                                        array(
                                                'label'=>'重置密码',
                                                'code'=>'student_load_reset_password,student_reset_password'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'student_delete,student_del_batch'
                                        ),
                                        array(
                                                'label'=>'学生报名信息核对',
                                                'code'=>'student_info_check,student_down'
                                        ),
                                        array(
                                                'label'=>'添加学生',
                                                'code'=>'student_add,student_add_batch,student_test'
                                        ),
                                         array(
                                                'label'=>'移除',
                                                'code'=>'student_remove,student_batch_remove'
                                        ),
                                        array(
                                                'label'=>'还原',
                                                'code'=>'student_restore,student_batch_restore'
                                        )
                                )
                        ),


                        array(
                                'label'=>'学生帐号管理',
                                'code'=>'account_index',
                                'priv'=>array(

                                        array(
                                                'label'=>'编辑帐号',
                                                'code'=>'account_edit'
                                        ),
                                        array(
                                                'label'=>'查看交易明细',
                                                'code'=>'account_transaction'
                                        ),
                                        array(
                                                'label'=>'修改帐号余额',
                                                'code'=>'account_load_reset_account,account_reset_account'
                                        ),
                                        array(
                                                'label'=>'修改帐号状态',
                                                'code'=>'account_reset_account_status'
                                        )
                                )
                        ),
                        array(
                                'label'=>'学校管理',
                                'code'=>'school_index',
                                'priv'=>array(

                                        array(
                                                'label'=>'编辑',
                                                'code'=>'school_edit,school_update'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'school_delete,school_delete_batch'
                                        ),
                                        array(
                                                'label'=>'添加学校',
                                                'code'=>'school_add,school_create,common_regions'
                                        ),
                                        array(
                                                'label'=>'添加/编辑班级',
                                                'code'=>'school_classlist,school_editclass,school_updateclass'
                                        ),
                                        array(
                                                'label'=>'删除班级',
                                                'code'=>'school_classlist,school_deleteclass'
                                        ),
                                        array(
                                                'label'=>'添加/编辑老师',
                                                'code'=>'school_teacherlist,school_editteacher,school_importteacher'
                                        ),
                                        array(
                                                'label'=>'删除老师',
                                                'code'=>'school_teacherlist,school_deleteteacher'
                                        )
                                )
                        ),
                        array(
                                'label'=>'地区管理',
                                'code'=>'region_index',
                                'priv'=>array(

                                        array(
                                                'label'=>'编辑',
                                                'code'=>'region_edit,region_update'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'region_delete,region_delete_batch'
                                        ),
                                        array(
                                                'label'=>'添加下级地区',
                                                'code'=>'region_add,region_create'
                                        ),
                                        array(
                                                'label'=>'更新地区下拉框',
                                                'code'=>'region_export'
                                        )
                                )
                        )
                )
        ),

        /* 产品管理 */
        array(
                'label'=>'产品管理',
                'code'=>'group_product',
                'priv'=>array(
                        array(
                                'label'=>'产品列表',
                                'code'=>'production_index',
                                'priv'=>array(
                                        array(
                                                'label'=>'编辑',
                                                'code'=>'production_edit'
                                        ),
                                        array(
                                                'label'=>'查看交易数据',
                                                'code'=>'account_transactionp,account_report'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'production_del,production_batch_delete'
                                        ),
                                        array(
                                                'label'=>'添加',
                                                'code'=>'production_add'
                                        )
                                )
                        ),
                        array(
                                'label'=>'产品分类',
                                'code'=>'production_category_index',
                                'priv'=>array(
                                        array(
                                                'label'=>'编辑',
                                                'code'=>'production_category_edit'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'production_category_delete,production_category_batch_delete'
                                        ),
                                        array(
                                                'label'=>'添加',
                                                'code'=>'production_category_add'
                                        )
                                )
                        ),
                        array(
                                'label'=>'统计报表',
                                'code'=>'account_transactionw',
                                'priv'=>array(
                                        array(
                                                'label'=>'导出',
                                                'code'=>'account_report'
                                        )
                                )
                        )
                )
        ),

        /* 课程管理 */
        array(
                'label'=>'课程管理',
                'code'=>'group_course',
                'priv'=>array(
                        array(
                                'label'=>'课程列表',
                                'code'=>'course_index,course_corslist,course_corsinfo',
                                'priv'=>array(
                                        array(
                                                'label'=>'新增',
                                                'code'=>'course_addcorsinfo,traininginstitution_seltilist'
                                        ),
                                        array(
                                                'label'=>'编辑',
                                                'code'=>'course_setcorsinfo,traininginstitution_seltclist,cteacher_selctlist,course_setcorsinfo_campus'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'course_removecors'
                                        ),
                                        array(
                                                'label'=>'导入',
                                                'code'=>'course_import_cors_excel'
                                        )
                                )
                        ),
                        array(
                                'label'=>'课程授课模式',
                                'code'=>'course_cmlist',
                                'priv'=>array(
                                        array(
                                                'label'=>'新增',
                                                'code'=>'course_addcminfo'
                                        ),
                                        array(
                                                'label'=>'编辑',
                                                'code'=>'course_setcminfo'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'course_removecm'
                                        )
                                )
                        ),
                        array(
                                'label'=>'课程授课人数类别',
                                'code'=>'course_csntlist',
                                'priv'=>array(
                                        array(
                                                'label'=>'新增',
                                                'code'=>'course_addcsntinfo'
                                        ),
                                        array(
                                                'label'=>'编辑',
                                                'code'=>'course_setcsntinfo'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'course_removecsnt'
                                        )
                                )
                        ),
                        array(
                                'label'=>'课程授课教师来源',
                                'code'=>'course_ctflist',
                                'priv'=>array(
                                        array(
                                                'label'=>'新增',
                                                'code'=>'course_addctfinfo'
                                        ),
                                        array(
                                                'label'=>'编辑',
                                                'code'=>'course_setctfinfo'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'course_removectf'
                                        )
                                )
                        ),
                        array(
                                'label'=>'课程授课教师列表',
                                'code'=>'cteacher_index,cteacher_ctlist,cteacher_ctinfo',
                                'priv'=>array(
                                        array(
                                                'label'=>'新增',
                                                'code'=>'cteacher_addctinfo,course_selcorscampuslist'
                                        ),
                                        array(
                                                'label'=>'编辑',
                                                'code'=>'cteacher_setctinfo,course_selcorscampuslist'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'cteacher_removect'
                                        ),
                                        array(
                                                'label'=>'导入',
                                                'code'=>'cteacher_import_cteacher_excel'
                                        )
                                )
                        )
                )
        ),

        /* 培训机构管理 */
        array(
                'label'=>'培训机构管理',
                'code'=>'group_traininginstitution',
                'priv'=>array(
                        array(
                                'label'=>'培训机构列表',
                                'code'=> 'traininginstitution_index,traininginstitution_tilist,traininginstitution_tiinfo,traininginstitution_tclist,traininginstitution_tcinfo',
                                'priv'=>array(
                                        array(
                                                'label'=>'新增机构',
                                                'code'=>'traininginstitution_addtiinfo'
                                        ),
                                        array(
                                                'label'=>'编辑机构',
                                                'code'=>'traininginstitution_settiinfo'
                                        ),
                                        array(
                                                'label'=>'删除机构',
                                                'code'=>'traininginstitution_removeti'
                                        ),
                                        array(
                                                'label'=>'新增校区',
                                                'code'=>'traininginstitution_addtcinfo'
                                        ),
                                        array(
                                                'label'=>'编辑校区',
                                                'code'=>'traininginstitution_settcinfo'
                                        ),
                                        array(
                                                'label'=>'删除校区',
                                                'code'=>'traininginstitution_removetc'
                                        ),
                                        array(
                                                'label'=>'导入机构和校区',
                                                'code'=>'traininginstitution_import_titc_excel'
                                        )
                                )
                        ),
                        array(
                                'label'=>'培训机构类型',
                                'code'=>'traininginstitution_titlist',
                                'priv'=>array(
                                        array(
                                                'label'=>'新增',
                                                'code'=>'traininginstitution_addtitinfo'
                                        ),
                                        array(
                                                'label'=>'编辑',
                                                'code'=>'traininginstitution_settitinfo'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'traininginstitution_removetit'
                                        )
                                )
                        ),
                        array(
                                'label'=>'培训机构优先类别',
                                'code'=>'traininginstitution_tiptlist',
                                'priv'=>array(
                                        array(
                                                'label'=>'新增',
                                                'code'=>'traininginstitution_addtiptinfo'
                                        ),
                                        array(
                                                'label'=>'编辑',
                                                'code'=>'traininginstitution_settiptinfo'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'traininginstitution_removetipt'
                                        )
                                )
                        )
                )
        ),


    /* 教师信息管理 */
    array(
                'label'=>'教师信息管理',
                'code'=>'group_teacher',
                'priv'=>array(
                        array(
                                'label'=>'监考教师管理',
                                'code'=>'invigilate_index',
                                'priv'=>array(
                                        array(
                                                'label'=>'编辑',
                                                'code'=>'invigilate_edit,invigilate_do_action'
                                        ),
                                        array(
                                                'label'=>'添加',
                                                'code'=>'invigilate_add'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'invigilate_delete,invigilate_batch_delete'
                                        ),
                                        array(
                                                'label'=>'重置密码',
                                                'code'=>'invigilate_load_reset_password,invigilate_reset_password'
                                        )
                                )
                        )
                        ,
                        array(
                                'label'=>'评估报告教师管理',
                                'code'=>'teacher_download_index',
                                'priv'=>array(
                                        array(
                                                'label'=>'编辑',
                                                'code'=>'teacher_download_edit,teacher_download_select_exams'
                                        ),
                                        array(
                                                'label'=>'添加',
                                                'code'=>'teacher_download_add,teacher_download_select_exams'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'teacher_download_delete,teacher_download_batch_delete,teacher_download_do_action'
                                        ),
                                        array(
                                                'label'=>'重置密码',
                                                'code'=>'teacher_download_load_reset_password,teacher_download_reset_password'
                                        )
                                )
                        )

                )
        ),
        // 学科管理
        array(
                'label'=>'学科管理',
                'code'=>'group_subject',
                'priv'=>array()
        ),
        // 年级管理
        array(
                'label'=>'年级管理',
                'code'=>'group_grade',
                'priv'=>array()
        ),
        // 考试类型管理
        array(
                'label'=>'考试类型管理',
                'code'=>'group_q_type',
                'priv'=>array()
        ),
        array(
                'label'=>'机考题库管理',
                'code'=>'group_question',
                'priv'=>array(
                        array(
                                'label'=>'试题列表',
                                'code'=>'question_index,question_group,question_combination,question_cloze,question_match,question_diction,question_blank,question_showSentence,question_listening,question_correct,relate_group_group',
                                'priv'=>array(
                                        array(
                                                'label'=>'编辑',
                                                'code'=>'question_edit,question_edit_group,question_update_group,question_edit_group_question,question_update_group_question,question_edit_cloze,question_update_colze,question_edit_cloze_question,question_update_cloze_question,question_edit_match,question_update_match,question_edit_match_question,question_update_match_question,question_edit_diction,question_edit_diction_question,question_update_diction_question,question_update_diction,question_edit_blank,question_update_blank,question_edit_blank_question,question_update_blank_question,question_editSentence,question_updateSentence,question_edit_listening,question_update_listening,question_edit_listening_question,question_update_listening_question,question_edit_correct,question_update_correct,question_edit_correct_question,question_update_correct_question,question_answer,question_edit_answer,question_update_answer,question_edit_answer_question,question_update_answer_question,question_count_method_tactics,question_edit_combination,question_update_combination'
                                        ),
                                        array(
                                                'label'=>'添加',
                                                'code'=>'question_add,question_add_group,question_update_group,question_add_group_question,question_update_group_question,question_add_cloze,question_update_colze,question_add_cloze_question,question_update_cloze_question,question_add_match,question_update_match,question_add_match_question,question_update_match_question,question_add_diction,question_add_diction_question,question_update_diction_question,question_update_diction,question_add_blank,question_update_blank,question_add_blank_question,question_update_blank_question,question_addSentence,question_updateSentence,question_add_listening,question_update_listening,question_add_listening_question,question_update_listening_question,question_add_correct,question_update_correct,question_add_correct_question,question_update_correct_question,question_answer,question_add_answer,question_update_answer,question_add_answer_question,question_update_answer_question,question_count_method_tactics,question_add_combination,question_update_combination'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'question_delete,question_batch_delete,question_remove,question_batch_remove,question_restore,question_batch_restore,question_batch_relate,question_batch_unrelate'
                                        ),
                                        array(
                                                'label'=>'预览',
                                                'code'=>'question_preview'
                                        ),
                                        array(
                                                'label'=>'复制',
                                                'code'=>'question_add'
                                        ),
                                        array(
                                                'label'=>'审核',
                                                'code'=>'question_check'
                                        ),
                                        array(
                                                'label'=>'设置真题',
                                                'code'=>'question_update_original'
                                        )
                                )
                        )
                        ,
                        array(
                                'label'=>'试题统计',
                                'code'=>'question_count',
                                'priv'=>array()
                        ),

                        array(
                                'label'=>'试题审核',
                                'code'=>'question_audit_index',
                                'priv'=>array(

                                        array(
                                                'label'=>'预览',
                                                'code'=>'question_preview'
                                        ),
                                        array(
                                                'label'=>'审核',
                                                'code'=>'question_audit_audit'
                                        ),
                                        array(
                                                'label'=>'查看审核日志',
                                                'code'=>'question_audit_log'
                                        )
                                )
                        )
                        ,
                        array(
                                'label'=>'信息提取方式统计',
                                'code'=>'question_count_tz',
                                'priv'=>array()
                        ),

                        array(
                                'label'=>'试题难易度查看',
                                'code'=>'relate_class_index',
                                'priv'=>array(

                                        array(
                                                'label'=>'更新',
                                                'code'=>'relate_class_recover_difficulty,relate_class_update_difficulty,relate_class_update_difficulty,relate_class_recover_default_difficulty'
                                        )
                                )
                        )
                        ,
                        array(
                                'label'=>'学科查看',
                                'code'=>'subject_index',
                                'priv'=>array(

                                        array(
                                                'label'=>'编辑',
                                                'code'=>'subject_edit,subject_update'
                                        ),
                                        array(
                                                'label'=>'添加',
                                                'code'=>'subject_add,subject_create'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'subject_delete,subject_delete_batch'
                                        )
                                )
                        )
                        ,
                        array(
                            'label'=>'学科四维管理',
                            'code'=>'subject_subject_dimension_list',
                            'priv'=>array(
                        
                                array(
                                    'label'=>'新增/编辑',
                                    'code'=>'subject_edit_subject_dimension,subject_save_subject_dimension'
                                ),
                                array(
                                    'label'=>'删除',
                                    'code'=>'subject_remove_subject_dimension'
                                )
                            )
                        )
                        ,
                        array(
                                'label'=>'考试类型',
                                'code'=>'question_class_index,question_class_ajax_class_list',
                                'priv'=>array(

                                        array(
                                                'label'=>'编辑',
                                                'code'=>'question_class_edit,question_class_update'
                                        ),
                                        array(
                                                'label'=>'添加',
                                                'code'=>'question_class_add,question_class_create'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'question_class_delete,question_class_delete_batch'
                                        )
                                )
                        )
                        ,
                        array(
                                'label'=>'方法策略管理',
                                'code'=>'subject_category_index',
                                'priv'=>array(

                                        array(
                                                'label'=>'编辑',
                                                'code'=>'subject_category_edit'
                                        ),
                                        array(
                                                'label'=>'添加',
                                                'code'=>'subject_category_add'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'subject_category_delete,,subject_category_delete_batch'
                                        )
                                )
                        )
                        ,
                        array(
                                'label'=>'知识点管理',
                                'code'=>'knowledge_index',
                                'priv'=>array(

                                        array(
                                                'label'=>'编辑',
                                                'code'=>'knowledge_edit,knowledge_update'
                                        ),
                                        array(
                                                'label'=>'添加',
                                                'code'=>'knowledge_add,knowledge_update'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'knowledge_delete,knowledge_delete_batch'
                                        ),
                                        array(
                                                'label'=>'在线学习知识点同步',
                                                'code'=>'knowledge_synclist'
                                        )
                                )
                        )
                        ,
                        array(
                                'label'=>'信息提取方式管理',
                                'code'=>'group_type_index',
                                'priv'=>array(

                                        array(
                                                'label'=>'编辑',
                                                'code'=>'group_type_edit'
                                        ),
                                        array(
                                                'label'=>'添加',
                                                'code'=>'group_type_add'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'group_type_delete,group_type_delete_batch'
                                        )
                                )
                        )

                )
        )
        ,
        array(
            'label'=>'素质测试相关管理',
            'code'=>'diathesis_manage',
            'priv'=>array(
                array(
                    'label'=>'职业能力倾向管理',
                    'code'=>'vocational_aptitude_index',
                    'priv'=>array(
                        array(
                            'label'=>'新增/编辑',
                            'code'=>'vocational_aptitude_edit,vocational_aptitude_save'
                        ),
                        array(
                            'label'=>'删除',
                            'code'=>'vocational_aptitude_remove'
                        )
                    )
                ),
                array(
                    'label'=>'学习风格管理',
                    'code'=>'learn_style_index',
                    'priv'=>array(
                        array(
                            'label'=>'新增/编辑',
                            'code'=>'learn_style_edit,learn_style_save'
                        ),
                        array(
                            'label'=>'删除',
                            'code'=>'learn_style_remove'
                        ),
                        array(
                            'label'=>'学习风格属性管理',
                            'code'=>'learn_style_attribute_list'
                        ),
                        array(
                            'label'=>'学习风格属性新增/编辑',
                            'code'=>'learn_style_edit_attribute,learn_style_save_attribute'
                        ),
                        array(
                            'label'=>'学习风格属性删除',
                            'code'=>'learn_style_remove_attribute'
                        )
                    )
                ),
                array(
                    'label'=>'职业兴趣管理',
                    'code'=>'vocational_interest_index',
                    'priv'=>array(
                        array(
                            'label'=>'新增/编辑',
                            'code'=>'vocational_interest_edit,vocational_interest_save'
                        ),
                        array(
                            'label'=>'删除',
                            'code'=>'vocational_interest_remove'
                        )
                    )
                ),
                array(
                    'label'=>'职业管理',
                    'code'=>'profession_index',
                    'priv'=>array(
                        array(
                            'label'=>'新增/编辑',
                            'code'=>'profession_edit,profession_save'
                        ),
                        array(
                            'label'=>'导入',
                            'code'=>'profession_import,profession_save_import'
                        ),
                        array(
                            'label'=>'删除',
                            'code'=>'profession_remove'
                        )
                    )
                )
            )
        ),
        array(
                'label'=>'机考试卷管理',
                'code'=>'group_exam_paper',
                'priv'=>array(
                        array(
                                'label'=>'考试期次',
                                'code'=>'exam_index',
                                'priv'=>array(
                                        array(
                                            'label'=>'查看',
                                            'code'=>'exam_index'
                                        ),
                                        array(
                                            'label'=>'添加考试期次',
                                            'code'=>'exam_add,exam_update,exam_add_subject,exam_update_subject'
                                        ),
                                        array(
                                            'label'=>'编辑考试期次',
                                                'code'=>'exam_edit,exam_update,exam_edit_subject,exam_update_subject,exam_edit_index,exam_change_status,exam_update_questions_cache,exam_update_questions_cache,exam_invigilator_index,exam_invigilator_add,exam_invigilator_save,exam_invigilator_edit'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'exam_delete,exam_invigilator_batch_delete'
                                        ),
                                        array(
                                            'label'=>'添加考试学科',
                                            'code'=>'exam_add_subject,exam_update_subject'
                                        ),
                                        array(
                                            'label'=>'编辑考试学科',
                                            'code'=>'exam_edit_subject,exam_update_subject'
                                        ),
                                        array(
                                            'label' => '公布成绩',
                                            'code'  => 'exam_exam_result_publish',
                                        ),
                                        array(
                                            'label'=>'师生关联管理',
                                            'code'=>'teacher_student_index,teacher_student_import'
                                        ),
                                        array(
                                                'label'=>'成绩下载',
                                                'code'=>'exam_down_exam'
                                        )
                                )
                        )
                        ,
                        array(
                            'label'=>'成绩同步',
                            'code'=>'zmoss_index',
                            'priv'=>array(
                                array(
                                    'label'=>'设置考试对应关系',
                                    'code'=>'zmoss_index,zmoss_setexamrelate,zmoss_saveexamrelate'
                                ),
                                array(
                                    'label'=>'设置试题对应关系',
                                    'code'=>'zmoss_index,zmoss_setexamrelatequestion,zmoss_saveexamrelatequestion'
                                ),
                                array(
                                    'label'=>'同步成绩',
                                    'code'=>'zmoss_index,zmoss_sync'
                                ),
                                array(
                                    'label'=>'删除',
                                    'code'=>'zmoss_index,zmoss_remove'
                                )
                            )
                        )
                        ,
                        array(
                                'label'=>'组题规则',
                                'code'=>'exam_rule_index',
                                'priv'=>array(
                                        array(
                                                'label'=>'添加',
                                                'code'=>'exam_rule_add'
                                        ),
                                        array(
                                                'label'=>'编辑',
                                                'code'=>'exam_rule_edit'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'exam_rule_delete,exam_rule_restore,exam_rule_remove'
                                        ),
                                        array(
                                                'label'=>'生成试卷',
                                                'code'=>'exam_rule_gen,exam_rule_generate'
                                        )
                                )
                        )
                        ,
                        array(
                            'label'=>'试卷管理',
                            'code'=>'paper_index',
                            'priv'=>array(
                                array(
                                    'label'=>'编辑',
                                    'code'=>'paper_edit,paper_update,paper_update_s'
                                ),
                                array(
                                    'label'=>'试卷详情',
                                    'code'=>'paper_detail'
                                ),
                                array(
                                    'label'=>'删除',
                                    'code'=>'paper_delete,paper_batch_delete,paper_restore,paper_batch_restore,paper_remove,paper_batch_remove'
                                ),
                                array(
                                    'label'=>'试卷对比',
                                    'code'=>'paper_compare'
                                ),
                                array(
                                    'label'=>'试卷预览',
                                    'code'=>'paper_preview'
                                ),
                                array(
                                    'label'=>'试卷更新',
                                    'code'=>'paper_batch_renew,paper_renew'
                                ),
                                array(
                                    'label'=>'试卷试题管理',
                                    'code'=>'exam_question_index,exam_question_index2,exam_question_index3,exam_question_add,exam_question_insert,exam_question_delete,exam_question_batch_delete,exam_question_search'
                                )
                            )
                        )
                        ,
                        array(
                                'label'=>'答案录入',
                                'code'=>'exam_answer_entry_index,exam_answer_entry_exam_sheet,exam_answer_entry_insert_student_sheet',
                                'priv'=>array()
                        ),

                        array(
                                'label'=>'手动组卷',
                                'code'=>'paper_diy_index',
                                'priv'=>array(

                                        array(
                                                'label'=>'添加',
                                                'code'=>'paper_diy_add_paper'
                                        ),
                                        array(
                                                'label'=>'编辑',
                                                'code'=>'paper_diy_edit_paper'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'paper_diy_delete_batch,paper_diy_remove_paper'
                                        ),
                                        array(
                                                'label'=>'预览',
                                                'code'=>'paper_diy_preview_paper,paper_diy_question_manage,paper_diy_select_question,paper_diy_update_question'
                                        ),
                                        array(
                                                'label'=>'试卷详情',
                                                'code'=>'paper_diy_detail,paper_diy_detail2'
                                        )
                                )
                        )

                )

        ),
        array(
                'label'=>'机考评估管理',
                'code'=>'group_evaluate',
                'priv'=>array(
                        array(
                                'label'=>'外部对比信息类型',
                                'code'=>'comparison_type_index',
                                'priv'=>array(

                                        array(
                                                'label'=>'添加',
                                                'code'=>'comparison_type_add'
                                        ),
                                        array(
                                                'label'=>'编辑',
                                                'code'=>'comparison_type_edit'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'comparison_type_do_batch'
                                        ),
                                        array(
                                                'label'=>'禁用',
                                                'code'=>'comparison_type_do_action'
                                        )
                                )
                        )
                        ,
                        array(
                                'label'=>'外部对比信息',
                                'code'=>'comparison_info_index',
                                'priv'=>array(

                                        array(
                                                'label'=>'添加',
                                                'code'=>'comparison_info_add'
                                        ),
                                        array(
                                                'label'=>'编辑',
                                                'code'=>'comparison_info_edit'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'comparison_info_do_action,comparison_info_do_batch,comparison_info_ajax_check_year'
                                        )
                                )
                        )
                        ,
                        array(
                                'label'=>'评估规则',
                                'code'=>'evaluate_rule_index',
                                'priv'=>array(

                                        array(
                                                'label'=>'添加',
                                                'code'=>'evaluate_rule_add,evaluate_rule_get_exams,evaluate_rule_get_exam_places,evaluate_rule_get_exam_place_subjects,evaluate_rule_get_exam_place_subject_knowledge,evaluate_rule_get_exam_place_subject_method_tactic,evaluate_rule_get_exam_place_subject_group_type,evaluate_rule_get_comparison_info,evaluate_rule_get_exam_areas,evaluate_rule_save'
                                        ),
                                        array(
                                                'label'=>'编辑',
                                                'code'=>'evaluate_rule_edit'
                                        ),
                                        array(
                                                'label'=>'回收站',
                                                'code'=>'evaluate_rule_do_action'
                                        ),
                                        array(
                                                'label'=>'生成报告',
                                                'code'=>'evaluate_rule_general,evaluate_rule_general_template'
                                        ),
                                        array(
                                                'label'=>'下载考试排名',
                                                'code'=>'evaluate_rule_get_exam_rank'
                                        ),
                                        array(
                                            'label'=>'查看报告',
                                            'code'=>'report_index,report_interview'
                                        ),
                                        array(
                                            'label'=>'下载报告',
                                            'code'=> 'report_down_file'
                                            
                                        ),
                                        array(
                                            'label'=>'执行生成报告相关命令',
                                            'code'=> 'report_command_index'
                                            
                                        )
                                )
                        )
                        ,
                        array(
                                'label'=>'评估模板',
                                'code'=>'evaluate_template_index',
                                'priv'=>array(

                                        array(
                                                'label'=>'添加',
                                                'code'=>'evaluate_template_edit,evaluate_template_update'
                                        ),
                                        array(
                                                'label'=>'编辑',
                                                'code'=>'evaluate_template_edit,evaluate_template_update'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'evaluate_template_delete'
                                        )
                                )
                        )
                        ,
                        array(
                                'label'=>'评估模块',
                                'code'=>'evaluate_module_index',
                                'priv'=>array(

                                        array(
                                                'label'=>'添加',
                                                'code'=>'evaluate_module_add,evaluate_module_add_module'
                                        ),
                                        array(
                                                'label'=>'编辑',
                                                'code'=>'evaluate_module_edit,evaluate_module_edit_module'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'evaluate_module_do_action'
                                        ),
                                        array(
                                                'label'=>'禁用',
                                                'code'=>'evaluate_module_do_action'
                                        )
                                )
                        )

                )
        )
        ,
        array(
                'label'=>'官网MINI测管理',
                'code'=>'demo_paper_report',
                'priv'=>array(
                        array(
                                'label'=>'MINI测配置管理',
                                'code'=>'demo_config_index',
                                'priv'=>array(

                                        array(
                                                'label'=>'添加',
                                                'code'=>'demo_config_edit,demo_config_save_config'
                                        ),
                                        array(
                                                'label'=>'编辑',
                                                'code'=>'demo_config_edit,demo_config_save_config'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'demo_config_delete'
                                        ),
                                        array(
                                                'label'=>'更新试卷',
                                                'code'=>'demo_config_update_demo_paper'
                                        ),
                                        array(
                                                'label'=>'更新配置缓存',
                                                'code'=>'demo_config_update_cache'
                                        )
                                )
                        )
                        ,

                        array(
                                'label'=>'MINI测报告查看',
                                'code'=>'demo_paper_index,demo_paper_show_paper',
                                'priv'=>array(
                                        array(
                                                'label'=>'删除',
                                                'code'=>'demo_paper_remove_report,demo_paper_show_report'
                                        )
                                )
                        )
                )
        )
        ,
        array(
                'label'=>'面试题库管理',
                'code'=>'group_interview',
                'priv'=>array(
                        array(
                                'label'=>'面试试题',
                                'code'=>'interview_question_index',
                                'priv'=>array(
                                        array(
                                                'label'=>'编辑',
                                                'code'=>'interview_question_edit'
                                        ),
                                        array(
                                                'label'=>'添加',
                                                'code'=>'interview_question_add'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'interview_question_delete'
                                        ),
                                        array(
                                                'label'=>'预览',
                                                'code'=>'interview_question_preview'
                                        )
                                )
                        ),
                        array(
                                'label'=>'面试题回收站',
                                'code'=>'interview_question_index',
                                'priv'=>array(
                                        array(
                                                'label'=>'编辑',
                                                'code'=>'interview_question_edit'
                                        ),
                                        array(
                                                'label'=>'移除',
                                                'code'=>'interview_question_remove'
                                        ),
                                        array(
                                                'label'=>'还原',
                                                'code'=>'interview_question_restore'
                                        ),
                                        array(
                                                'label'=>'预览',
                                                'code'=>'interview_question_preview'
                                        )
                                )
                        ),
                        array(
                                'label'=>'面试考点',
                                'code'=>'interview_type_index',
                                'priv'=>array(
                                        array(
                                                'label'=>'添加',
                                                'code'=>'interview_type_add,interview_type_create'
                                        ),
                                        array(
                                                'label'=>'编辑',
                                                'code'=>'interview_type_edit,interview_type_update'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'interview_type_delete,interview_type_delete_batch'
                                        )
                                )
                        ),
                        array(
                                'label'=>'面试组题',
                                'code'=>'interview_rule_index',
                                'priv'=>array(
                                        array(
                                                'label'=>'添加',
                                                'code'=>'interview_rule_add'
                                        ),
                                        array(
                                                'label'=>'编辑',
                                                'code'=>'interview_rule_edit'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'interview_rule_delete'
                                        ),
                                        array(
                                                'label'=>'匹配试题',
                                                'code'=>'interview_rule_search_question'
                                        )
                                )
                        ),
                        array(
                                'label'=>'评分项管理',
                                'code'=>'evaluation_option_index',
                                'priv'=>array(
                                        array(
                                                'label'=>'添加',
                                                'code'=>'evaluation_option_add,evaluation_option_add_save'
                                        ),
                                        array(
                                                'label'=>'编辑',
                                                'code'=>'evaluation_option_update,evaluation_option_update_save'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'evaluation_option_delete'
                                        ),
                                        array(
                                                'label'=>'禁用',
                                                'code'=>'evaluation_option_enabled,evaluation_option_disabled'
                                        )
                                )
                        ),
                        array(
                                'label'=>'评分标准管理',
                                'code'=>'evaluation_standard_index',
                                'priv'=>array(
                                        array(
                                                'label'=>'添加',
                                                'code'=>'evaluation_standard_add,evaluation_standard_add_save'
                                        ),
                                        array(
                                                'label'=>'编辑',
                                                'code'=>'evaluation_standard_update,evaluation_standard_update_save'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'evaluation_standard_delete'
                                        ),
                                        array(
                                                'label'=>'禁用',
                                                'code'=>'evaluation_standard_enabled,evaluation_standard_disabled'
                                        )
                                )
                        ),
                        array(
                                'label'=>'面试结果导入',
                                'code'=>'interview_result_import',
                                'priv'=>array()
                        ),
                        array(
                                'label'=>'睿达杯结果导入',
                                'code'=>'ruidabei_import_import',
                                'priv'=>array()
                        )
                )
        ),
        array(
                'label'=>'权限管理',
                'code'=>'group_role',
                'priv'=>array(
                        array(
                                'label'=>'管理员列表',
                                'code'=>'cpuser_index',
                                'priv'=>array(
                                        array(
                                                'label'=>'添加',
                                                'code'=>'cpuser_add,cpuser_create'
                                        ),
                                        array(
                                                'label'=>'编辑',
                                                'code'=>'cpuser_edit,cpuser_update,cpuser_priv'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'cpuser_delete,cpuser_restore'
                                        ),
                                        array(
                                                'label'=>'重置密码',
                                                'code'=>'cpuser_load_reset_password,cpuser_reset_password'
                                        ),
                                        array(
                                                'label'=>'批量导入',
                                                'code'=>'cpuser_import,cpuser_set_import_priv,cpuser_import_save'
                                        )
                                )
                        ),
                        array(
                                'label'=>'角色列表',
                                'code'=>'role_index',
                                'priv'=>array(
                                        array(
                                                'label'=>'添加',
                                                'code'=>'role_add,role_create'
                                        ),
                                        array(
                                                'label'=>'编辑',
                                                'code'=>'role_edit,role_update'
                                        ),
                                        array(
                                                'label'=>'删除',
                                                'code'=>'role_delete'
                                        ),
                                        array(
                                                'label'=>'权限设置',
                                                'code'=>'role_priv'
                                        ),
                                        array(
                                                'label'=>'相关人员',
                                                'code'=>'role_index'
                                        )
                                )
                        ),
                        array(
                                'label'=>'管理员回收站',
                                'code'=>'cpuser_index',
                                'priv'=>array(

                                        array(
                                                'label'=>'还原',
                                                'code'=>'cpuser_restore'
                                        ),
                                        array(
                                                'label'=>'移除',
                                                'code'=>'cpuser_remove'
                                        )
                                )
                        )
                        ,
                        array(
                                'label'=>'操作日志',
                                'code'=>'admin_log_index',
                                'priv'=>array(

                                        array(
                                                'label'=>'删除',
                                                'code'=>'admin_log_batch_delete'
                                        )
                                )
                        )

                )
        )
        ,
        array(
                'label'=>'系统设置',
                'code'=>'group_system',
                'priv'=>array(
                        array(
                                'label'=>'网站设置',
                                'code'=>'system_config,setting_index',
                                'priv'=>array()
                        ),
/*
                array(
                'label' => '模板选择',
                'code'  => 'setting_template',
            ),
            array(
                'label' => '邮件设置',
                'code'  => 'setting_mail',
            ),
            */
        )
        ),
        // 站点监控
        array(
                'label'=>'站点监控',
                'code'=>'cron_schedule_index',
                'priv'=>array(
                        array(
                                'label'=>'计划任务',
                                'code'=>'cron_schedule_list,cron_schedule_index',
                                'priv'=>array()
                        )
                )
        )
);
