<?php $this->load->view('common/header');?>
<script language="javascript">
function check_form(form) {                      
    if (checkbox_check('ids[]')) {
        return confirm('确定要删除么？');
    }
    return false;
} 

</script>

<div id="body">
  <form name="frm_list" action="<?=site_url('admin/interview_type/delete_batch')?>" method="POST" onsubmit="return check_form(this)">
  <div class="space">
    <div class="subtitle"><a class="menu" href="<?=site_url('admin/interview_type/add')?>">添加面试考点</a>面试考点管理</div>  
    <table class="maintable" border="0" cellspacing="0" cellpadding="0">
      <tr class="altbg1">
        <td width="5%">删?</td>
        <td width="15%">ID</td>
        <td>考点名称</td>
        <td width="35%">操作</td>
      </tr>
      <?php if($list):?>
      <?php foreach($list as $val):?>
      <?php $level_space = $val['pid'] ? '&nbsp;&nbsp;' : '';?>
      <tr>
        <td><input type="checkbox" name="ids[]" value="<?=$val['type_id']?>"></td>
        <td><?=$val['type_id']?></td>
        <td><?= $val['pid'] ? '&nbsp;&nbsp;└' : ''?> <?=$val['type_name']?></td>
        <td>
          <a href="<?=site_url('admin/interview_type/edit/'.$val['type_id'])?>">编辑</a>
          <a href="<?=site_url('admin/interview_type/delete/'.$val['type_id'])?>" onclick="return confirm('确定要删除么？');">删除</a>
        </td>
      </tr>
      <?php endforeach; ?>
      <tr class="altbg1">
        <td colspan="3"><button type="button" class="btn2" onclick="checkbox_checked('ids[]');">全选</button></td>
        <td colspan="7" style="text-align:right"></td>
      </tr>
      <?php else: ?>
      <tr>
        <td colspan="8">暂无记录！</td>
      </tr>
      <?php endif; ?>
    </table>
    <center><input type="submit" name="dosubmit" value=" 批量删除 " class="btn" /></center>
  </div>
  </form>

</div>
<?php $this->load->view('common/footer');?>