<?php $this->load->view('common/header');?>
<script language="javascript">
function check_form(form) {
    if (checkbox_check('ids[]')) {
        var op = $('#batch_op').val();
        if (op == '') {
            alert('请选择操作类型');
            return false;
        } else {
            if ( ! confirm('确定要执行该操作么？')) {
                return false;
            }
        }
        var action = $('#batch_op').find('option[value='+op+']').attr('op');
        form.action = action;
        return true;
    }
    return false;
}
</script>
<div id="body">
  <div class="space">
    <form name="frm_list" action="<?=site_url('admin/subject_paper/insert')?>" method="POST" onsubmit="return check_form(this)">
    <input type="hidden" name="exam_id" value="<?=$exam['exam_id']?>" />
    <div class="subtitle">
      <a class="menu" href="<?=site_url('admin/subject_paper/index/'.$exam['exam_id'])?>">已添加的试卷列表</a>
     		 添加科目试卷
    </div>
    <table class="maintable" border="0" cellspacing="0" cellpadding="0">
    	<tr>
	        <td colspan="10" class="altbg2" style="text-align: center;color:blue;">
	          考试期次：<?=$exam['exam_name']?>
	          --->
	          科目：<?=$exam['subject_name']?>
	        </td>
	  </tr>
      <tr class="altbg1">
        <td width="70">ID</td>
        <td>试卷名称</td>
        <td>试卷类型</td>
        <td width="260">试题数量</td>
        <td width="150">难易度</td>
        <td width="280">操作</td>
      </tr>
      <?php if($paper_list):?>
      <?php foreach($paper_list as $val):?>
      <tr>
        <td>
          <input type="checkbox" name="ids[]" value="<?=$val['paper_id']?>" />
          <?=$val['paper_id']?>
        </td>
        <td><?=$val['paper_name']?></td>
        <td>
          <?php if ($val['admin_id'] > 0): ?>
            <span>手动添加</span>
          <?php else: ?>
            <span>系统生成</span>
          <?php endif ?>
        </td>
        <td>
          <?=$val['ques_num']?>[
          <?php foreach(C('qtype') as $k=>$v):?><?=$k?',':''?><?=$v?>:<?=isset($val['qtype_ques_num'][$k])?$val['qtype_ques_num'][$k]:0?>          
          <?php endforeach;?>
          ]
        </td>
        <td><?=$val['difficulty']?></td>
        <td>
          <?php if ($val['admin_id'] > 0): ?>
            <a href="<?=site_url('admin/paper_diy/preview_paper/'.$val['paper_id'])?>" target="_blank">预览</a>  
          <?php else: ?>
            <a href="<?=site_url('admin/paper/preview/'.$val['paper_id'])?>" target="_blank">预览</a>
            <a href="<?=site_url('admin/paper/detail/'.$val['paper_id'])?>" target="_blank">试卷详情</a>
          <?php endif ?>
        </td>
      </tr>
      <?php endforeach; ?>
      <?php else: ?>
      <tr>
        <td colspan="10">暂无记录！</td>
      </tr>
      <?php endif; ?>
      <?php if(!empty($pagination)):?>
      <tr class="altbg1">
        <td colspan="3">
          <button type="button" class="btn2" onclick="checkbox_checked('ids[]');">全选</button>
          <select name="batch_op" id="batch_op">
           <option value="">-选择操作-</option>
           <option value="delete" op="<?=site_url('admin/subject_paper/insert')?>">添加试卷</option>
          </select>
        </td>
        <td colspan="10" style="text-align:right"><?=$pagination?></td>
      </tr>
      <?php endif;?>
    </table>
    <center><input type="submit" name="dosubmit" value=" 提交操作 " class="btn" /></center>
    </form>
  </div>
</div>
<?php $this->load->view('common/footer');?>