<?php $this->load->view('common/header');?>
<div id="body">
  <form name="Frm_cpuser_info" method="POST" action="<?=site_url('admin/cpuser/create')?>">
  <input type="hidden" name="id" value="{$id}" />
  <div class="space">
    <div class="subtitle">添加后台用户</div>
    <table class="maintable" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="16%" class="altbg1">用户名</td>        
        <td><input type="text" name="admin_user" class="txtbox"> <span style="color:#f00">*</span></td>
      </tr>
      <tr>
        <td class="altbg1">真实姓名</td>        
        <td><input type="text" id="realname" name="realname" class="txtbox"><span style="color:#f00">*</span></td>
      </tr>
	  <tr>
        <td class="altbg1">角色选择</td>        
        <td>
		<?php foreach ($role_list as $v):?>
 			<input type="checkbox" name="roleIds[]" value="<?php echo $v['role_id'];?>" id="roles_list_<?php echo $v['role_id'];?>" /><label for="roles_list_<?php echo $v['role_id'];?>"><?php echo $v['role_name'];?></label>
        <?php endforeach;?>
        </td>
      </tr>
      <tr>
        <td class="altbg1">Email</td>        
        <td><input type="text" name="email" class="txtbox"><span style="color:#f00">*</span></td>
      </tr>
      <tr>
        <td class="altbg1">密码</td>        
        <td><input type="password" name="password"  class="txtbox"> <span style="color:#f00">*</span><span class="notice">密码长度必须为6~20个字符</span></td>
      </tr>
      <tr>
        <td class="altbg1">确认密码</td>        
        <td><input type="password" name="password_confirm" class="txtbox"> <span style="color:#f00">*</span></td>
      </tr>
    </table>
  </div>
  <center> 
    <input type="submit" name="dosubmit" value=" 提交 " class="btn" />
    &nbsp;&nbsp;
    <input type="button" name="" value=" 返回 " onclick="history.go(-1);" class="btn" />
  </center>   
  </form>
</div>
<?php $this->load->view('common/footer');?>