<?php $this->load->view('common/header');?>
<script language="javascript">
function check_form(form) {                      
    if (checkbox_check('ids[]')) {
        return confirm('确定要删除么？');
    }
    return false;
}
</script>

<?php static_global('css/third_party/zebra_dialog/flat/zebra_dialog.css', 'css');?>
<?php static_global('js/third_party/zebra_dialog.js');?>
<div id="body">
  <form name="frm_cpuser_list" action="<?=site_url('admin/cpuser/index')?>" method="POST" onsubmit="return check_form(this)">
  <div class="space">
    <div class="subtitle">
    	<a class="menu" href="<?=site_url('admin/cpuser/add')?>">添加管理员</a>后台用户管理 [<?php if($search['trash']):?><a href="<?=site_url('admin/cpuser/index')?>">管理员</a><?php else:?><a href="<?=site_url('admin/cpuser/index').'?trash=1'?>">回收站</a><?php endif;?>]
    	<?php if ($priv_import_cpuser) {?><a class="menu" href="<?=site_url('admin/cpuser/import')?>">批量导入</a><?php } ?>
	</div>  
    <table class="maintable" border="0" cellspacing="0" cellpadding="0">
      <tr class="altbg1">
        <td width="5%">删?</td>
        <td width="10%">用户名</td>
        <td width="7%">姓名</td>
        <td width="20%">邮箱</td>
        <td width="12%">最后登录</td>
        <td width="10%">登录IP</td>
        <td width="12%">创建时间</td>
        <td width="7%">来源</td>
        <td width="5%">状态</td>
        <td>管理</td>
      </tr>
      <?php if($list):?>
      <?php foreach($list as $val):?>
      <tr>
        <td><input type="checkbox" name="ids[]" value="<?=$val['admin_id']?>" <?=$val['admin_id']==1?'disabled':''?>></td>
        <td><?=$val['admin_user']?></td>
        <td><?=$val['realname']?></td> 
        <td><?=$val['email']?></td> 
        <td><?=$val['last_login']?></td> 
        <td><?=$val['last_ip']?></td> 
        <td><?=$val['addtime']?></td> 
        <td><?=$val['from'] == '1' ? '后台添加' : '批量导入';?></td> 
        <td>
            <img src="<?=__HTML_URL__?>images/<?=$val['is_delete']?'no':'yes'?>.gif" />
        </td> 
        <td>
            <a href="<?=site_url('admin/cpuser/edit/'.$val['admin_id'])?>">编辑</a>
            <?php if($val['admin_id'] != 1):?>
            <?php if($priv_role):?>
            <a href="###" i_name="<?php echo $val['realname']?>" class="reset_password" rel="<?php echo $val['admin_id'];?>">重置密码</a>
            <?php endif;?>
            <?php if($priv_delete):?>
            <?php if($search['trash']):?>
            <a href="<?=site_url('admin/cpuser/restore/'.$val['admin_id'])?>">还原</a>
            <a href="<?=site_url('admin/cpuser/delete/'.$val['admin_id'])?>" onclick="return confirm('确定要彻底删除么？');">彻底删除</a>
            <?php else:?>
            <a href="<?=site_url('admin/cpuser/delete/'.$val['admin_id'])?>" onclick="return confirm('确定要删除么？');">删除</a>
            <?php endif;?>
            <?php endif;?>
            <?php endif;?>
        </td>
      </tr>
      <?php endforeach; ?>
      <tr class="altbg1">
        <td colspan="2"><button type="button" class="btn2" onclick="checkbox_checked('ids[]');">全选</button></td>
        <td colspan="8" style="text-align:right"><?=$pagination?></td>
      </tr>      
      <?php else: ?>
      <tr>
        <td colspan="10">暂无记录！</td>
      </tr>
      <?php endif; ?>
    </table>
    <!--<center><input type="submit" name="dosubmit" value=" 提交操作 " class="btn" /></center>-->
  </div>
  </form>
</div>
<?php $this->load->view('common/footer');?>


<script type="text/javascript">
  $(document).ready(function () {
      //重置密码
      $('a.reset_password').unbind('click').bind('click', function () {
            var uid = $(this).attr('rel'),
            	uname = $(this).attr('i_name');
			new $.Zebra_Dialog('', {
			    'source':  {'ajax': '<?php echo site_url('admin/cpuser/load_reset_password');?>/' + uid},
			    'type':     '',
			    width: 890,
			    'title': '修改 管理员 (<font color="red" style="font-size:16px;">' + uname + '</font>) 的密码'
			});

			setTimeout(function () {
				$('div.ZebraDialog_Buttons').hide();
			}, 500);
	});
    	
	window.close_dialog = function () {$('.ZebraDialog_Button_0').click();}
});
</script>
