<?php $this->load->view('common/header');?>
<div id="body">
  <div class="space">
    <div class="subtitle">    

    <?php if($mode=='trash'):?>
    回收站 - [<a href="<?=site_url('admin/exam_rule/index')?>">组题规则</a>]
    <?php else:?>
    <a class="menu" href="<?=site_url('admin/exam_rule/add')?>">添加组题规则</a>
    组题规则 - [<a href="<?=site_url('admin/exam_rule/index/trash')?>">回收站</a>]
    <?php endif;?>

<a style="float:right" href="javascript:void(0)" onclick="fnShowDialog('id_qry_dlg')">查询</a>


    </div>
    <table class="maintable" border="0" cellspacing="0" cellpadding="0">
      <tr class="altbg1">
        <td width="3%">选</td>
        <td width="5%">ID</td>
        <td>规则名称</td>
        <td width="10%">学科</td>
        <td width="10%">年级</td>
        <td width="5%">类型</td>
        <td width="10%">难易度</td>
        <td width="15%">录入时间</td>
        <td width="15%">操作</td>
      </tr>
      <?php if($list):?>
      <?php foreach($list as $val):?>
      <tr>
        <td><input type="checkbox" name="ids[]" value="<?=$val['rule_id']?>" /></td>
        <td><?=$val['rule_id']?></td>
        <td><?=$val['rule_name']?></td>
        <td><?=$val['subject']?></td> 
        <td><?=$val['grade_name']?></td>
        <td><?=$val['class_name']?></td>        
        <td><?=$val['difficulty']?></td>        
        <td><?=$val['addtime']?></td> 
        <td>
          <?php if($mode=='trash'):?>
          <a href="<?=site_url('admin/exam_rule/restore/'.$val['rule_id'])?>">还原</a>
          <a href="<?=site_url('admin/exam_rule/remove/'.$val['rule_id'])?>" onclick="return confirm('您确定要彻底删除么？');">移除</a>
          <?php else:?>
          <a href="<?=site_url('admin/exam_rule/edit/'.$val['rule_id'])?>">编辑</a>          
          <a href="<?=site_url('admin/exam_rule/generate/'.$val['rule_id'])?>">生成试卷</a>
          <a href="<?=site_url('admin/exam_rule/delete/'.$val['rule_id'])?>" onclick="return confirm('您确定要删除么？');">删除</a>
          <?php endif;?>
        </td>
      </tr>
      <?php endforeach; ?>
      <?php else: ?>
      <tr>
        <td colspan="9">暂无记录！</td>
      </tr>
      <?php endif; ?>
      <?php if($pagination):?>
      <tr class="altbg1">
        <td colspan="2">
        </td>
        <td colspan="7" style="text-align:right"><?=$pagination?></td>
      </tr>
      <?php endif;?>
    </table>
  </div>

<div id="id_qry_dlg" style="display:none">
            <div class="cls_title">搜索</div>
    <form method="get" name="search_form" action="<?=site_url('admin/exam_rule/index/'.$mode)?>">
        <div class="space" style="margin:5px">
            <table class="maintable" border="0" cellspacing="0" cellpadding="0">
                <tr>
                    <td class="altbg1" width="15%">学科</td>
                    <td>
                      <select name="subject">
                      <option value="">=学科=</option>
                      <?php foreach($subjects as $k => $v):?>
                      <option value="<?=$k?>"<?=$search['subject']==$k?' selected':''?>><?=$v?></option>
                      <?php endforeach;?> 
                      </select>
                    </td>
                </tr>
                <tr>
                    <td class="altbg1">年级</td>
                    <td>
                      <select name="grade">
                      <option value="">=年级=</option>
                      <?php foreach($grades as $k => $v):?>
                      <option value="<?=$k?>"<?=$search['grade']==$k?' selected':''?>><?=$v?></option>
                      <?php endforeach;?> 
                      </select>
                    </td>
                </tr>
                <tr>
                    <td class="altbg1">类型</td>
                    <td>
                      <select name="class">
                      <option value="">=类型=</option>
                      <?php foreach($class_list as $val):?>
                      <option value="<?=$val['class_id']?>"<?=$search['class']==$val['class_id']?' selected':''?>><?=$val['class_name']?></option>
                      <?php endforeach;?> 
                      </select>
                    </td>
                </tr>
                <tr>
                    <td class="altbg1">名称</td>
                    <td><input type="text" name="keyword" value="<?=$search['keyword']?>" class="txtbox" /></td>
                </tr>         
            </table>
            <center><input type="submit" value=" 搜索 " class="btn" /> <input type="button" value=" 重置 " class="btn" onclick="window.location.href='<?php echo site_url('admin/exam_rule/index');?>'"/></center>
        </div>
    </form>
  </div>
</div>
<?php $this->load->view('common/footer');?>
