<?php 


$this->load->view('common/header');?>
<script language="javascript">
function check_form(form) {                      
    if (checkbox_check('ids[]')) {
        return confirm('确定要删除么？');
    }
    return false;
} 

</script>

<div id="body">
  <form name="frm_list" action="<?=site_url('admin/method_tactic/delete_batch')?>" method="POST" onsubmit="return check_form(this)">
  <div class="space">
    <div class="subtitle">
    	<a class="menu" href="<?=site_url('admin/method_tactic/add/' . $subject_category_id)?>">添加方法策略</a>方法策略管理
	</div>  
    <table class="maintable" border="0" cellspacing="0" cellpadding="0">
      <tr>
      	<td class="altbg2" colspan="5" style="text-align:center;">
      		方法策略分类：<a href="<?php echo site_url('admin/subject_category/index');?>"><?php echo $subject_category['name'];?></a> -> 方法策略 
      	</td>
      </tr>
      <tr class="altbg1">
        <td width="5%">删?</td>
        <td width="15%">ID</td>
        <td>方法策略名称</td>
        <td>方法策略分类</td>
        <td width="35%">操作</td>
      </tr>
      <?php if($list):?>
      <?php foreach($list as $val):?>
      <tr>
        <td><?php if (!$val['has_relate_info']) {?><input type="checkbox" name="ids[]" value="<?=$val['id']?>"><?php } ?></td>
        <td><?=$val['id']?></td>
        <td><?=$val['name']?></td>
        <td><?=$subject_category['name']?></td>
        <td>
          <?php if ($priv_manage) {?>
          <a href="<?=site_url('admin/method_tactic/edit/'.$val['id'])?>">编辑</a>
          <?php } ?>
          <?php if ($priv_delete) {?>
          <?php if (!$val['has_relate_info']) {?>
          <a href="<?=site_url('admin/method_tactic/delete/'.$val['id'])?>" onclick="return confirm('确定要删除么？');">删除</a>
          <?php } else {?>
          <font color="#999" title="该方法策略有关联的试题，无法删除">删除</font>
          <?php } ?>
          <?php }?>
        </td>
      </tr>
      <?php endforeach; ?>
      <tr class="altbg1">
        <td colspan="2"><button type="button" class="btn2" onclick="checkbox_checked('ids[]');">全选</button></td>
        <td colspan="3" style="text-align:right"><!--<?=$pagination?>--></td>
      </tr>
      <?php else: ?>
      <tr>
        <td colspan="5">暂无记录！</td>
      </tr>
      <?php endif; ?>
    </table>
    <?php if ($priv_delete) {?>
    <center><input type="submit" name="dosubmit" value=" 批量删除 " class="btn" />&nbsp;<input type="button" name="dosubmit" value=" 返回 " class="btn"  onclick="history.go(-1);"/></center>
    <?php } ?>
  </div>
  </form>

</div>
<?php $this->load->view('common/footer');?>
