<?php $this->load->view('common/header');?>
<?php $this->load->view('common/mathjax');?>
<?php $this->load->view('common/ueditor_parse');?>

<script language="javascript">
function check_form(form) {
    var op = $('#'+form.id+" select").val();
    var action =  $('#'+form.id+" select option:selected").attr('op');
    if (checkbox_check('ids[]', form.id)) {
        if (op == '') {
            alert('请选择操作类型');
            return false;
        } else {
            if (confirm('您确定要执行该操作么？')) {
                form.action = action;
                return true;
            }
        }

    }
    return false;
}

$(document).ready(function(){
    $('.ques_title').find('div').dblclick(function(){
        $(this).toggleClass('line_18');
    });
});
</script>
<style type="text/css">
    .maiev
    {
    	line-height:30px;
    	/*text-indent:25px;*/
    	display:block;

    	background:#a6cbe7;
    	font-weight:700;
    	font-size:18px;
    }
    body,td {
    	margin: 0px;
    	font: 16px Cambria;
    	text-align: left;
    }

    .maintable tr.bg td {
    	background:#E5E5E5;
    }

    .cls_table tbody tr td{
	    //padding-left:20px;
        padding-right:20px;
        border:0px;
        background:#A6CBE7;
        font-weight:bold;
        font-size:18px;
    }
</style>
<div id="body">
  <form name="frm_list" id="frm_list" action="<?=site_url('admin/question/batch_delete')?>" method="POST" onsubmit="return check_form(this)">
  <div class="space">
    <div class="subtitle">
    <?php if ($parent['be_tested']) {?>
    <a class="menu" href="###" style="color:#999;text-decoration:line-through;" title="该试题已经被考生考过 或者 正在被考,因此无法操作">添加子题</a>
    <?php } else {?>
    <a class="menu" href="<?=site_url('admin/question/add_diction_question/'.$parent['ques_id'])?>">添加子题</a>
    <?php } ?>
    选词填空管理
    </div>
    <table class="maintable" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td colspan="8" class="altbg2" style="text-align: center;">
        	题干信息 [
        	<?php if ($priv_manage) {?>
        	<?php if ($parent['be_tested']) {?>
		    <a href="###" style="color:#999;text-decoration:line-through;" title="该试题已经被考生考过 或者 正在被考,因此无法操作">编辑</a>
		    <?php } else {?>
        	<a href="<?=site_url('admin/question/edit_diction/'.$parent['ques_id'])?>">编辑</a>
		    <?php } ?>
		    <?php }?>
        	]</td>
      </tr>
      <tr><td colspan="8" class="altbg1">
        <table class="subtable">
          <tr>
            <td width="10%" class="altbg1">学科</td>
            <td width="30%" ><?=$parent['subject_name']?></td>

            <td width="10%" class="altbg1">年级</td>
            <td>[<?=$parent['start_grade']?>] - [<?=$parent['end_grade']?>]</td>
          </tr>
          <tr>
            <td width="10%" class="altbg1">类型</td>
            <td>
                <?php foreach($parent['class_names'] as $grade_id => $arr):?>
                <?=$grades[$grade_id]?>:<?=implode(' , ', $arr)?><br/>
                <?php endforeach;?>
            </td>
            <td width="10%" class="altbg1">标签</td>
            <td><?=$q_tags[$parent['tags']]?></td>
          </tr>
          <tr>
            <td width="10%" class="altbg1">试题ID</td>
            <td  colspan="3"><?=$parent["ques_id"]?></td>
          </tr>
          <tr>
            <td width="10%" class="altbg1">题目类型(真题、原创、模拟题)</td>
            <td colspan="3">
                <?php if ($parent['is_original'] == 1): ?>
                    <span>原创</span>
                <?php elseif($parent['is_original'] == 2): ?>
                    <span>真题</span>
                 <?php elseif($parent['is_original'] == 3): ?>
                    <span>模拟题</span>
                <?php endif; ?>
            </td>
          </tr>
          <?php if ($parent['is_original'] == 2): ?>
            <tr>
                <td width="10%" class="altbg1">附加信息</td>
                <td colspan="3">
                    <?php if (isset($parent['exam_year']) && $parent['exam_year'] > 0): ?>
                        <p>年份: <?php echo $parent['exam_year']; ?>   </p><br/>
                    <?php endif ?>
                    <?php if (isset($parent['remark']) && !empty($parent['exam_year'])): ?>
                        <p>备注: <?php echo $parent['remark']; ?></p><br/>
                    <?php endif ?>
                    <?php if (isset($parent['relateds']) && !empty($parent['relateds'])): ?>
                        <p>衍生题目: </p>
                        <?php foreach ($parent['relateds'] as $key => $value): ?>
                            <p>
                                <a href="<?php echo site_url('admin/question/preview/' . $value['ques_id']) ?>"><?php echo $value['ques_id']; ?></a>
                            </p>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </td>
            </tr>
          <?php elseif ($parent['is_original'] == 1): ?>
              <tr>
                  <td width="10%" class="altbg1">附加信息</td>
                  <td colspan="3">
                      <?php if (isset($parent['related']) && !empty($parent['related'])): ?>
                          <p>真题路径: <a href="<?php echo site_url('admin/question/preview/' . $parent['related']) ?>"><?php echo $parent['related']; ?></a></p>
                      <?php endif; ?>
                      <p>&nbsp;</p>
                      <?php if (isset($parent['relateds']) && !empty($parent['relateds'])): ?>
                        <p>衍生题目: </p>
                        <?php foreach ($parent['relateds'] as $key => $value): ?>
                            <p>
                                <a href="<?php echo site_url('admin/question/preview/' . $value['ques_id']) ?>"><?php echo $value['ques_id']; ?></a>
                            </p>
                        <?php endforeach; ?>
                    <?php endif; ?>
                  </td>
              </tr>



               <?php elseif ($parent['is_original'] ==3): ?>
          <tr>
                <td width="10%" class="altbg1">附加信息</td>
                <td colspan="3">
                    <?php if (isset($parent['simulation']) ): ?>
                        <p>来源: <?php echo $parent['simulation']; ?>   </p><br/>
                    <?php endif ?>

                    <?php if (isset($parent['relateds']) && !empty($parent['relateds'])): ?>
                        <p>衍生题目: </p>
                        <?php foreach ($parent['relateds'] as $key => $value): ?>
                            <p>
                                <a href="<?php echo site_url('admin/question/preview/' . $value['ques_id']) ?>"><?php echo $value['ques_id']; ?></a>
                            </p>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endif; ?>
        </table>
      </td>
    </tr>

    <!-- =========================== 题目 ============================== -->
          <?php
                $info = explode('&nbsp;<br/>&nbsp;',$parent['title']);
				$search = array('<p>', '<br/></p>','；');
				$replace = array('', '', ';');
				$info[1] = str_replace($search, $replace, $info[1]);
				$info[1] = strip_tags($info[1]);
				$info[1] = trim($info[1]);

                $info1 = explode(';', $info[1]);


				foreach($info1 as $key => $val)
				{
					if (!$val)
					{
						unset($info1[$key]);
					}
					else
					{
						$info1[$key] = trim(strip_tags($val));
					}
				}


                $info1_1 = array();
                $info1_2 = array();

                if (count($info1) == 15)
                {
                    for ($i=0; $i<7; $i++)
                    {
                        $info1_1[] = $info1[$i];
                    }

                    for ($i=7; $i<15; $i++)
                    {
                        $info1_2[] = $info1[$i];
                    }
                }
                else
                {
                    for ($i=0; $i < (int)(count($info1)/2); $i++)
                    {
                        $info1_1[] = $info1[$i];
                    }

                    for ($i=count($info1)/2; $i<count($info1); $i++)
                    {
                        $info1_2[] = $info1[$i];
                    }
                }
            ?>
      <tr>
        <td colspan="8" class="altbg2" style="text-align: center;">题目</td>
      </tr>
      <tr>
        <td colspan="8" class="preview_content">
         <div class="maiev">
           <table class="cls_table">
               <tbody>
                   <tr>
                   <?foreach($info1_1 as $val){?>
                       <td><?=$val?>;</td>
                   <?}?>
                   </tr>
                   <tr>
                   <?foreach($info1_2 as $val){?>
                       <td><?=$val?>;</td>
                   <?}?>
                   </tr>
               </tbody>
           </table>
         </div>
         <div><?php echo $info[0];?></div>
          <?php if($parent['picture']):?>
          <div><br/><img src="<?=__IMG_ROOT_URL__?><?=$parent['picture']?>" /><br/></div>
          <?php endif;?>
          <div>
          <?php
          if (isset($list))
          {
            foreach ($list as $key => $val)
            {
              $val['answer'] = explode("\n", $val['answer']);

              foreach ($val['answer'] as $k => $v)
              {
                echo '<span>第' . ($key+1) . '题、</span>';
                echo '<input type="text" value="'.$v.'"/>　';
                if (($key+1)%5 == 0) echo "<br/><br/>";
              }
            }
          }
        ?>
        </div>
        </td>
      </tr>
    <!-- =========================== 附加信息 ============================== -->

       <tr>
        <td colspan="8" class="altbg2" style="text-align: center;">
        	附加信息 [
        		<?php if ($priv_manage) {?>
        		<?php if ($parent['be_tested']) {?>
			    <a href="###" style="color:#999;text-decoration:line-through;" title="该试题已经被考生考过 或者 正在被考,因此无法操作">添加</a>
			    <?php } else {?>
        		<a href="<?=site_url('admin/question/add_diction_question/'.$parent['ques_id'])?>">添加</a>
			    <?php } ?>
			    <?php } ?>
        	]</td>
      </tr>
      <tr class="altbg1">
        <td>序号</td>
        <td width="7%">题目ID</td>
        <td width="6%">题型</td>
        <td></td>
        <td width="15%">录入时间</td>
        <td width="10%">录入人员</td>
        <td width="15%">操作</td>
      </tr>
      <?php if($list):?>
      <?php foreach($list as $key => $val):?>
      <tr>
        <td><?php echo $key+1; ?></td>
        <td><?php if ($priv_manage && !$parent['be_tested']) {?><input type="checkbox" name="ids[]" value="<?=$val['ques_id']?>"><?php } ?><?=$val['ques_id']?></td>
        <td><?=$qtypes[$val['type']]?></td>
        <td>
        <td><?=$val['addtime']?></td>
        <td><?=$val['cpuser']?></td>
        <td>
          <?php if ($priv_manage) {?>
          <?php if ($parent['be_tested']) {?>

	      <a href="###" style="color:#999;text-decoration:line-through;" title="该试题已经被考生考过 或者 正在被考,因此无法操作">编辑</a>
          <?php if($priv_delete):?>
	      <a href="###" style="color:#999;text-decoration:line-through;" title="该试题已经被考生考过 或者 正在被考,因此无法操作">删除</a>
          <?php endif;?>

	      <?php } else {?>

          <a href="<?=site_url('admin/question/edit_diction_question/'.$val['ques_id'])?>">编辑</a>
	      <?php } ?>
	      <?php } ?>

        </td>
      </tr>
      <tr class="bg">
        <td colspan="2">知识点</td>
        <td colspan="5">
            <?php echo $val['knowledge_name'];?>
        </td>
      </tr>
      <?php endforeach; ?>
      <tr class="altbg1">
        <td colspan="7">
          <?php if ($priv_manage) {?>
          <button type="button" class="btn2" onclick="checkbox_checked('ids[]','frm_list');">全选</button>
          <?php if ($parent['be_tested']) {?>
          <select name="batch_op" style="color:#999;text-decoration:line-through;">
           <option value="">该试题已经被考生考过 或者 正在被考,因此无法操作</option>
          </select>
          <?php } else {?>
          <select name="batch_op">
           <option value="">-选择操作-</option>
           <option value="delete" op="<?=site_url('admin/question/batch_delete')?>">批量删除</option>
          </select>
          <?php } ?>
          <?php } ?>
        </td>
      </tr>
      <?php else: ?>
      <tr>
        <td colspan="8">暂无记录！</td>
      </tr>
      <?php endif; ?>
    </table>
    <center><input type="submit" name="dosubmit" value=" 提交操作 " class="btn" />&nbsp;<input type="button" name="dosubmit" value=" 返回 " class="btn"  onclick="history.go(-1)"/></center>
  </div>
  </form>

  <?php if($list2):?>
  <form name="frm_list2" id="frm_list2" action="<?=site_url('admin/question/batch_remove')?>" method="POST" onsubmit="return check_form(this)">
  <div class="space">
    <table class="maintable" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td colspan="8" class="altbg2" style="text-align: center;">子题回收站</td>
      </tr>
      <tr class="altbg1">
        <td width="7%">&nbsp;&nbsp;ID</td>
        <td width="5%">题型</td>
        <td>题目</td>
        <td width="15%">录入时间</td>
        <td width="10%">录入人员</td>
        <td width="15%">操作</td>
      </tr>
      <?php foreach($list2 as $val):?>
      <tr>
        <td><?php if ($priv_manage && !$parent['be_tested']) {?><input type="checkbox" name="ids[]" value="<?=$val['ques_id']?>"><?php } ?><?=$val['ques_id']?></td>
        <td><?=$qtypes[$val['type']]?></td>
        <td>
        <div><?=$val['title']?></div>
          <?php if($val['picture']):?>
          <div style="text-align:center;"><img src="<?=__IMG_ROOT_URL__?><?=$val['picture']?>" /></div>
          <?php endif;?>
        </td>
        <td><?=$val['addtime']?></td>
        <td><?=$val['cpuser']?></td>
        <td>
          <?php if ($priv_manage) {?>
          <?php if ($parent['be_tested']) {?>
          <a href="###" style="color:#999;text-decoration:line-through;" title="该试题已经被考生考过 或者 正在被考,因此无法操作">编辑</a>
          <a href="<?=site_url('admin/question/restore/'.$val['ques_id'])?>" onclick="return confirm('您确定要还原么？');">还原</a>
          <a href="###" style="color:#999;text-decoration:line-through;" title="该试题已经被考生考过 或者 正在被考,因此无法操作">移除</a>

          <?php } else {?>

          <a href="<?=site_url('admin/question/edit_diction_question/'.$val['ques_id'])?>">编辑</a>
          <?php if($priv_delete):?>
          <a href="<?=site_url('admin/question/restore/'.$val['ques_id'])?>" onclick="return confirm('您确定要还原么？');">还原</a>
          <a href="<?=site_url('admin/question/remove/'.$val['ques_id'])?>" onclick="return confirm('您确定要移除么？');">移除</a>
          <?php endif;?>

          <?php } ?>
          <?php } ?>
        </td>
      </tr>
      <tr class="bg">
        <td colspan="2">知识点</td>
        <td colspan="5">
            <?php echo $val['knowledge_name'];?>
        </td>
      </tr>
      <?php endforeach; ?>
      <tr class="altbg1">
        <td colspan="7">
          <?php if ($priv_manage) {?>
          <button type="button" class="btn2" onclick="checkbox_checked('ids[]','frm_list2');">全选</button>
          <?php if ($parent['be_tested']) {?>
          <select name="batch_op" style="color:#999;text-decoration:line-through;">
           <option value="">该试题已经被考生考过 或者 正在被考,因此无法操作</option>
          </select>
          <?php } else {?>
          <select name="batch_op">
           <option value="">-选择操作-</option>
           <option value="restore" op="<?=site_url('admin/question/batch_restore')?>">批量还原</option>
           <option value="remove" op="<?=site_url('admin/question/batch_remove')?>">批量移除</option>
          </select>
          <?php } ?>
          <?php } ?>
        </td>
      </tr>
    </table>
    <?php if ($priv_manage) {?>
    <center><input type="submit" name="dosubmit" value=" 提交操作 " class="btn" />&nbsp;<input type="button" name="dosubmit" value=" 返回 " class="btn"  onclick="history.go(-1)"/></center>
    <?php } ?>
  </div>
  </form>
  <?php endif;?>
</div>
<?php $this->load->view('common/footer');?>
