<?php $this->load->view('common/header');?>
<?php $this->load->view('common/question_js');?>
<?php $this->load->view('question/js/question_type');?>

<script>
var paper_diy=0;
var dirName = "question/<?=$question['ques_id'] ? $question['ques_id'] : microtime(true);?>";
var is_question_mode = 1;//用于区分知识点选择框中的认知过程
var is_group  = false;
var class_ids = [<?=trim($question['class_id'],',')?>];
var skill_ids = [<?=trim($question['skill'],',')?>];
var knowledge_ids = [<?=trim($question['knowledge'],',')?>];
var knowledge_know_process = eval("("+'<?php echo json_encode($know_processes); ?>'+")");

var ajax_url_class = '<?=site_url('admin/common/question_class')?>';
var ajax_url_skill = '<?=site_url('admin/common/skill')?>';
var ajax_url_knowledge = '<?=site_url('admin/common/knowledge_all')?>';
var ajax_url_knowledge_select = '<?=site_url('admin/common/knowledge_select')?>';
var ajax_url_knowledge_init = '<?=site_url('admin/common/knowledge_init')?>';

</script>
<style>
    .height_light {
        border:1px solid #f00;
        padding:2px 0 2px 0;
        margin:2px 0 2px 0;
    }
    .div_option{
        border-bottom:1px solid #CCCCFF;
        padding:5px;
    }
    .gray_input {
        color:#ccc;
    }
</style>
<div id="body">
  <form name="Frm_info" class="validate" id="question_form" method="POST" action="<?=site_url('admin/question/updateSentence')?>" enctype="multipart/form-data" onsubmit="return false;">
  <?php if($act == 'add'):?>
  <input type="hidden" name="relate_group" value="<?=$relate_group?>" />
  <input type="hidden" name="relate_ques_id" value="<?=$relate_ques_id?>" />
  <input type="hidden" name="file_save_path" value="<?=$question['ques_id']?>">
  <?php else:?>
  <input type="hidden" name="ques_id" value="<?=$question['ques_id']?>" />
  <input type="hidden" name="relate_group" value="<?=$question['group_id']?>" />
  <?php endif;?>
  <input type="hidden" name="back_url" value="<?=$back_url?>" />
  <input type="hidden" name="act" id="act" value="<?=$act?>" />
  <input type="hidden" name="qtype" id="qtype" value="<?php echo $question['type']; ?>">

  <div style="position:absolute;top:-1000px;">
    <input type="checkbox" id="class_id_validate" name="class_id_validate" value="1" />
  </div>

  <div class="space">
    <div class="subtitle">
      <?php if($act=='edit'):?>
      <a class="menu" href="<?=site_url('admin/question/add/'.$question['ques_id'])?>">添加相关试题</a>
      <?php endif;?>
      <?=$act=='add'?'添加':'修改'?>连词成句
    </div>
    <table class="maintable" border="0" cellspacing="0" cellpadding="0">
      <tbody>
        <tr>
            <td colspan="2" class="altbg2" style="text-align: center;">题目信息</td>
        </tr>
        <tr>
            <td width="10%" class="altbg1">学科</td>
            <td>
              <select name="subject_id" id="subject_id">
                <option value="">--请选择--</option>
                <?php foreach($subjects as $key => $val): ?>
                <option value="<?=$key?>" selected><?=$val?></option>
                <?php endforeach; ?>
              </select>
              <span style="color:#f00">*</span>
              <label for="subject_id" class="error" style="display:none"></label>
            </td>
        </tr>
        <tr>
            <td class="altbg1">年级</td>
            <td>
              <select name="start_grade" id="start_grade">
                <option value="">--请选择--</option>
                <?php foreach($grades as $key => $val): ?>
                <option value="<?=$key?>"<?=$question['start_grade']==$key?' selected':''?>><?=$val?></option>
                <?php endforeach; ?>
              </select>
              -
              <select name="end_grade" id="end_grade">
                <option value="">--请选择--</option>
                <?php foreach($grades as $key => $val): ?>
                <option value="<?=$key?>"<?=$question['end_grade']==$key?' selected':''?>><?=$val?></option>
                <?php endforeach; ?>
              </select>
              <span style="color:#f00">*</span>
              <label for="grade_id" class="error" style="display:none"></label>
            </td>
        </tr>
        <?php if ($act=='edit' && trim($question['skill']) != '') {?>
        <tr>
            <td class="altbg1">技能</td>
            <td>
              <span style="color:red;">*注意：因考虑到后续将移除技能项，请将该处已勾选的技能全部去除。</span>
              <br/>
              <br/>
              <div style="position:absolute;top:-1000px;left:200px;"><input type="checkbox" name="skill_id[]" value="" /></div>
              <span id="skill_list"></span>
              <label for="skill_id[]" class="error" style="display:none"></label>
            </td>
        </tr>
        <?php } ?>
        <tr>
            <td class="altbg1">知识点</td>
            <td>
             <div style="position:absolute;top:-1000px;left:200px;"><input type="checkbox" name="knowledge_id[]" value="" /></div>
             <div id="knowledge_list"></div>
             <input type="hidden" name="knowledge_ids" id="knowledge_ids" value="<?=trim($question['knowledge'],',')?>" />
             <button id="knowledge_select" class="btn2" type="button">点击选择</button>
             <label for="knowledge_id[]" class="error" style="display:none"></label>
            </td>
        </tr>
        <?php /* 考试类型 */ ?>
        <?php $this->load->view('question/property/exam_type'); ?>
        <?php /* 考试方式 */ ?>
        <?php $this->load->view('question/property/exam_way'); ?>
        <?php /* 试题类型 */ ?>
        <?php $this->load->view('question/property/question_type'); ?>
        <tr>
            <td class="altbg1">题目</td>
            <td>
				<script id="question_title" name="title" type="text/plain" style="width:700px;height:320px;"><?=$question['title']?><?php if($act=='edit' && $question['picture']):?><img src="<?=__IMG_ROOT_URL__?><?=$question['picture']?>" /><?php endif;?></script>
                <div id="input_answer_notice">
                填空题说明：<br/>
                1, 在需要设置填空项的地方，输入【中文括号加数字】，例如：（1），（2）。<br/>
                2, 多个填空项，请按数字顺序填写；只有一个填空项，可以不填写数字。
                </div>
            </td>
        </tr>
      </tbody>

      <tbody>
        <tr id="input_answer_tr">
            <td class="altbg1">答案</td>
            <td>
                <textarea id="input_answer" name="input_answer" style="width:500px;height:150px;" required title="请填写答案"><?php echo $question['answer']; ?></textarea>

                <label for="input_answer" class="error" style="display:none"></label>
                <div>请输入填空题的答案；每一行代表一个填空项答案，直接填写答案，不要填写题目中对应的数字。</div>
            </td>
        </tr>
      </tbody>
    </table>
  </div>
  <center>
    <input type="submit" id="dosubmit" name="dosubmit" value=" 提交 " class="btn" />
    &nbsp;&nbsp;
    <input type="button" name="back" value=" 返回 " onclick="history.go(-1);" class="btn" />
  </center>
  </form>
</div>
<?php $this->load->view('common/footer');?>
