<?php  if ( ! defined('BASEPATH')) die;?>
<style>
.ZebraDialog .ZebraDialog_Icon {
	padding-left: 24px;
}
.ZebraDialog .ZebraDialog_Body {
	padding: 10px 40px 40px 40px;
}
.info {
	border:1px dotted #ccc;
	padding:8px;
	margin:0 auto; 
	display:none;
	text-align:center;
}
.info p {
	text-indent: 26px;
	line-height: 10px;
	height: 10px;
}
.form_data span.f_label {
	width: 178px;
}
</style>
<div class="form_data">
	<p><span class="f_label">考生 准考证号/拼音简写：</span><input type="text" id="txt_student_account" class="student_account" value=""/><font class="error"></font></p>
	<p><span class="f_label">请输入新密码：</span><input type="password" id="txt_password" value=""/><span style="color:#f00" class="notice">*<i style="color:#333;font-size:12px;">密码长度必须为6~20个字符</i></span><font class="error"></font></p>
	<p><span class="f_label">请重新输入密码：</span><input type="password" id="txt_confirm_password" value=""/><font class="error"></font></p>
	<p class="tool_bar"><input type="button" id="btn_submit" value="保存修改"/></p>
	<div class="info error" id="font_form"></div>
</div>

<script>
$(document).ready(function () {
	set_ticket_autocomplete(1);
	$('#txt_student_account').focus();
	
	$('#txt_student_account, #txt_password, #txt_confirm_password')
	    .bind('keyup', function(e) {
	      var  keycode = e.keyCode;
	      if (keycode == '13') {
	    	  $('#btn_submit').click();
	          return false;
	      }
    });

	$('#btn_submit').unbind('click').bind('click', function () {
		var $thiz = $(this),
			$txt_account = $('#txt_student_account'),
			$txt_password = $('#txt_password'),
			$txt_confirm_password = $('#txt_confirm_password'),
			$font_form = $('#font_form');
		
		var account = $txt_account.val(),
			password = $txt_password.val(),
			confirm_password = $txt_confirm_password.val();

		var is_success = true,
        	objs = [];
		
		if (!$.trim(account).length) {
			is_success = false;
			objs.push({msg:'考生中帐号不能为空', obj:$txt_account});
		}

		//验证密码规则
        if ('string' === typeof (passwd_msg = is_password(password))) {
        	is_success = false;
			objs.push({msg:passwd_msg, obj:$txt_password});
        }
		
		if (!$.trim(confirm_password).length) {
			is_success = false;
			objs.push({msg:'确认密码不能为空', obj:$txt_confirm_password});
		}
		
		if (password != confirm_password) {
			is_success = false;
			objs.push({msg:'两次密码输入不一致', obj:$txt_confirm_password});
		}
		
		if (!is_success) {
			show_form_error(objs);
            return false;
        }
        
		$thiz.attr('disabled', 'disabled');
		$.ajax({
			url : '<?php echo site_url('exam/invigilate/reset_student_password/'); ?>',
			dataType : 'json',
			type : 'post',
			data : {
				account : account,
				password : password,
				confirm_password : confirm_password
			},
			timeout : 5000,
			error: function (a, b, c) {
				//alert(a + b + c);
				$thiz.removeAttr('disabled');
				$font_form.removeClass('success').addClass('error').html('考生密码修改失败，如有问题，请联系系统管理员.').hide().fadeIn();
			},
			success : function (response) {
				var code = response.code,
					msg	= response.msg,
					data = response.data;

				$thiz.removeAttr('disabled');
				if (code < 0) {
					$font_form.removeClass('success').addClass('error').html(msg).hide().fadeIn();
					if (response.callback) {
						window.location.href = response.callback;
						return;
					}
					return false;
				}

				$font_form.removeClass('error').addClass('success').html(msg).hide().fadeIn();
				return true;
			}
		});
	});
});
</script>
