<?php  if ( ! defined('BASEPATH')) die;?>
<?php static_global(array('js/common/common.js'));?>
<style>
.ZebraDialog .ZebraDialog_Icon {
	padding-left: 24px;
}
.ZebraDialog .ZebraDialog_Body {
	padding: 10px 40px 40px 40px;
}
.info {
	border:1px dotted #ccc;
	padding:8px;
	margin:0 auto; 
	display:none;
	text-align:center;
}
</style>
<div class="form_data">
	<p><span class="f_label">请输入旧密码：</span><input type="password" id="txt_old_password" value=""/><font class="error"></font></p>
	<p><span class="f_label">请输入新密码：</span><input type="password" id="txt_new_password" value=""/><span style="color:#f00" class="notice">*<i style="color:#333;font-size:12px;">密码长度必须为6~20个字符</i></span><font class="error"></font></p>
	<p><span class="f_label">请重新输入密码：</span><input type="password" id="txt_new_confirm_password" value=""/><font class="error"></font></p>
	<p class="tool_bar"><input type="button" id="btn_submit" value="保存修改"/></p>
	<div class="info error" id="font_form"></div>
	<input type="hidden" id="txt_hidden_uid" value="<?php echo $uid;?>"/>
</div>

<script>
$(document).ready(function () {
	$('#txt_old_password').focus();
	
	$('#txt_old_password, #txt_new_password, #txt_new_confirm_password')
	    .bind('keyup', function(e) {
	      var  keycode=e.keyCode;
	      if (keycode == '13') {
	    	  $('#btn_submit').click();
	          return false;
	      }
    });

	$('#btn_submit').unbind('click').bind('click', function () {
		var $thiz = $(this),
			$txt_old_password = $('#txt_old_password'),
			$txt_new_password = $('#txt_new_password'),
			$txt_new_confirm_password = $('#txt_new_confirm_password'),
			$txt_hidden_uid = $('#txt_hidden_uid'),
			$font_form = $('#font_form');
		
		var old_password = $txt_old_password.val(),
			new_password = $txt_new_password.val(),
			new_confirm_password = $txt_new_confirm_password.val(),
			hidden_uid = $txt_hidden_uid.val();

		var is_success = true,
        	objs = [];
		
		if (!$.trim(old_password).length) {
			is_success = false;
			objs.push({msg:'旧密码不能为空', obj:$txt_old_password});
		}

		//验证密码规则
        if ('string' === typeof (passwd_msg = is_password(new_password))) {
        	is_success = false;
			objs.push({msg:passwd_msg, obj:$txt_new_password});
        }
        
		if (!$.trim(new_confirm_password).length) {
			is_success = false;
			objs.push({msg:'确认密码不能为空', obj:$txt_new_confirm_password});
		}
		
		if (new_password != new_confirm_password) {
			is_success = false;
			objs.push({msg:'两次密码输入不一致', obj:$txt_new_confirm_password});
		}
		
		if (!is_success) {
			show_form_error(objs);
            return false;
        }
        
		$thiz.attr('disabled', 'disabled');
		$.ajax({
			url : '<?php echo site_url('exam/invigilate/reset_password/'); ?>',
			dataType : 'json',
			type : 'post',
			data : {
				uid : hidden_uid,
				old_password : old_password,
				new_password : new_password,
				confirm_password : new_confirm_password
			},
			timeout : 5000,
			error: function (a, b, c) {
				//alert(a + b + c);
				$thiz.removeAttr('disabled');
				$font_form.removeClass('success').addClass('error').html('密码修改失败，如有问题，请联系系统管理员.').hide().fadeIn()	;
			},
			success : function (response) {
				var code = response.code,
					msg	= response.msg,
					data = response.data;

				$thiz.removeAttr('disabled');
				if (code < 0) {
					$font_form.removeClass('success').addClass('error').html(msg).hide().fadeIn();
					if (response.callback) {
						window.location.href = response.callback;
						return;
					}
					return false;
				}

				$font_form.removeClass('error').addClass('success').html(msg).hide().fadeIn();
				setTimeout(function () {window.location.href='<?php echo site_url('exam/invigilate/logout/?act=force'); ?>';}, 1000);
				return true;
			}
		});
	});
});
</script>