<?php $this->load->view('common/header');?>

<?php static_global('js/jquery/plugin/validate/jquery.validate.min.js');?>
<?php static_js('admin/exam_rule/exam_rule.js');?>

<script>
var js_grade_id = '<?=$exam['grade_id']?>';
var js_class_id = '<?=$exam['class_id']?>';
var ajax_url_class = '<?=site_url('admin/common/question_class')?>';

$(document).ready(function(){
    $("#exam_form").validate({
        submitHandler:function(form){
            form.submit();
        },
        rules: {            
            exam_name: "required",
            grade_id: "required",
            class_id: "required",
            	cheat_num:{
                    required:true,
                    range:[1,10]
                },
        },
        messages: {
            exam_name: "请填写考试名称",
            grade_id: "请选择年级",
            class_id: "请选择类型",
            cheat_num: "请选择可作弊次数"
        }
    });

    $('#grade_id').change(function(){
        set_question_class_option();
    });

    set_question_class_option();
});

</script>
<div id="body">

  <form name="exam_form" class="validate" id="exam_form" method="POST" action="<?=site_url('admin/exam/update')?>" onsubmit="return false;">
  <input type="hidden" name="act" value="<?=$act?>" />
  <input type="hidden" name="exam_id" value="<?=$exam['exam_id']?>" />
  <input type="hidden" name="referer" value="<?=$referer?>" />
  <div class="space">
    <div class="subtitle"><?=$act=='add'?'添加':'修改'?>考试期次</div> 
    <table class="maintable" border="0" cellspacing="0" cellpadding="0">
        <tr>
            <td colspan="2" class="altbg2" style="text-align: center;">
			考试信息
            </td>
        </tr>
        <tr>
            <td class="altbg1"  width="15%">考试名称<font class="notice">*</font></td>
            <td>
              <input type="text" name="exam_name" class="txtbox" value="<?=$exam['exam_name']?>" />
              <label for="exam_name" class="error" style="display:none"></label>
            </td>
        </tr>
        <tr>
            <td class="altbg1"  width="15%">考试时间<font class="notice">*</font></td>
            <td>
            <?php if ($exam['exam_id']) {?>
              <input type="radio" value="1" disabled <?php if ($exam['exam_isfree'] == 1) {?>checked<?php }?>/>随时开考
              <input type="radio" value="0" disabled <?php if ($exam['exam_isfree'] == 0) {?>checked<?php }?>/>固定时间
              <input type="hidden" value="<?=$exam['exam_isfree']?>" name="exam_isfree">
            <?php } else {?>
              <input type="radio" id="exam_isfree_1" name="exam_isfree" value="1"/><label for="exam_isfree_1">随时开考</label>
              <input type="radio" id="exam_isfree_0" name="exam_isfree" value="0"/><label for="exam_isfree_0">固定时间</label>
            <?php }?>
            </td>
        </tr>
        <tr>
            <td class="altbg1">年级<font class="notice">*</font></td>
            <td>
              <?php if ($act == 'edit') {?>
              <input type="hidden" name="grade_id" value="<?php echo $exam['grade_id']?>" />
              <?php echo $grades[$exam['grade_id']];?>
              <?php } else {?>
              <select name="grade_id" id="grade_id">
              <option value="">=年级=</option>
              <?php foreach($grades as $k => $v):?>
              <option value="<?=$k?>"<?=$k==$exam['grade_id']?' selected':''?>><?=$v?></option>
              <?php endforeach;?> 
              </select>
              <?php } ?>
            </td>
        </tr>
        <tr>
            <td class="altbg1">类型<font class="notice">*</font></td>
            <td>
              <?php if ($act == 'edit') {?>
              <input type="hidden" name="class_id" value="<?php echo $exam['class_id']?>" />
              <?php echo $class_list[$exam['class_id']]['class_name'];?>
              <?php } else {?>
	              <select name="class_id" id="class_id">
	              <option value="">=类型=</option>
	              <?php foreach($class_list as $val):?>
	              <option value="<?=$val['class_id']?>"><?=$val['class_name']?></option>
	              <?php endforeach;?>
              <?php }?>
              </select>
            </td>
        </tr>        
        
         <tr>
            <td class="altbg1">准考证转换规则</td>
            <td>
              <select name="exam_ticket_maprule" id="exam_ticket_maprule">
              <?php foreach ($exam_ticket_maprule as $key => $val) {?>
                <option value="<?=$key?>" <?php if ($key == $exam['exam_ticket_maprule']) echo "selected"?>><?=$val['title']?></option>
                <?php }?>
              </select>
            </td>
        </tr>
        
        <tr>
            <td class="altbg1">可作弊次数<font class="notice">*</font></td>
            <td>
              <select name="cheat_num" id="cheat_num">
                <option value="0">--请选择--</option>
                <?php for($i = 1; $i < 11; $i++) {?>
                <option value="<?=$i?>"  <?php if ($exam['cheat_number'] == $i):?>selected<?php endif;?>><?=$i?></option>
                <?php }?>
              </select>
            </td>
        </tr>


        <tr>
            <td class="altbg1">是否立即踢出<font class="notice">*</font></td>
            <td>
            
            <?php if( isset($exam['kickornot']) ):?>
            
              <input type="radio" name="kick" value="1" <?php if($exam['kickornot']=='1'):?>checked="checked"<?php endif;?>/>是
              <input type="radio" name="kick" value="0" <?php if($exam['kickornot']=='0'):?>checked="checked"<?php endif;?>/>否
              <?php else:?>
              
              <input type="radio" name="kick" value="1" />是
              <input type="radio" name="kick" value="0" checked="checked"/>否
              
              <?php endif;?>
              
              
            </td>
        </tr>

        <?php /*
        <tr>
            <td class="altbg1"  width="15%">考试时长</td>
            <td>
              <input type="text" name="exam_minute" class="txtbox5" value="<?=$exam['exam_minute']?>" /> 分钟 
              <label for="exam_minute" class="error" style="display:none"></label>
            </td>
        </tr>
        */?>
        <?php /*?>
        <tr>
            <td class="altbg1">考试模式</td>
            <td>
              <?php $exam_type = $exam['exam_type']; ?>
              <input type="radio" name="exam_type" value="1" <?php echo $exam_type == '1' ? 'checked="checked"' : '';?> id="exam_type_1"/>
              <label for="exam_type_1">单题模式(<font color="red">“上一题”、“下一题”</font>)</label>
              <input type="radio" name="exam_type" value="2" <?php echo $exam_type == '2' ? 'checked="checked"' : '';?> id="exam_type_2"/>
              <label for="exam_type_2">全篇模式(<font color="red">一份试卷一次性考</font>)</label>
            </td>
        </tr>
        <?php */?>
        <tr style="display: none;">
            <td class="altbg1">考试介绍</td>
            <td>
              <textarea name="introduce" style="width:600px;height:60px;"><?=$exam['introduce']?></textarea>
              <label for="introduce" class="error" style="display:none"></label>
            </td>
        </tr>
        <tr>
            <td class="altbg1">考生须知</td>
            <td>
              <textarea name="student_notice" style="width:600px;height:60px;"><?=$exam['student_notice']?></textarea>
              <label for="student_notice" class="error" style="display:none"></label>
            </td>
        </tr>
        <tr>
            <td class="altbg1">监考人员须知</td>
            <td>
              <textarea name="invigilate_notice" style="width:600px;height:60px;"><?=$exam['invigilate_notice']?></textarea>
              <label for="invigilate_notice" class="error" style="display:none"></label>
            </td>
        </tr>
        <tr>
            <td class="altbg1">考试学生</td>
            <td>
              <textarea name="student_name" style="width:600px;height:100px;"><?=$student_name?></textarea>
              <label for="invigilate_notice" class="error" style="display:none"></label>
              <br/>
              <span class="cls_red">学生姓名与准考证号以','分开（例：王小二,10000100001），每行一个学生</span>
              <style type="text/css">
                  .cls_red{
                    color:#ff0000;
                  }
              </style>
            </td>
        </tr>
        <tr>
            <td class="altbg1">状态</td>
            <td>
              <?php 
              	$status = $exam['status'];
              ?>
              <?php foreach ($exam_status as $k=>$v) {?>
              <input type="radio" name="status" value="<?=$k?>" <?=$status == $k ? 'checked="checked"' : '';?> id="status_<?=$k?>"/>
              <label for="status_<?=$k?>" ><?=$v?></label>
              <?php }?>
            </td>
        </tr>
        <tr>
            <td class="altbg1">期次管理员</td>
            <td>
              <?php if (!empty($creator)) {?>
              <input type="checkbox" checked disabled><?=$creator['realname']?>&nbsp;
              <?php }?>
              <?php foreach ($admin_list as $item) {?>
              <?php if (in_array($item['admin_id'], $admin_list2)) continue;?>
              <input type="checkbox" name="managers[]" id="managers_<?=$item['admin_id']?>" value="<?=$item['admin_id']?>" <?php if (in_array($item['admin_id'], $exam['managers'])) {?>checked<?php }?>><label for="managers_<?=$item['admin_id']?>"><?=$item['realname']?></label>&nbsp;
              <?php }?>
            </td>
        </tr>
    </table>
  </div>
  <center> 
    <input type="submit" name="dosubmit" value=" 提交 " class="btn" />

  </center>   
  </form>
</div>
<?php $this->load->view('common/footer');?>
