<?php $this->load->view('common/header');?>
<div id="body">
  <div class="space">
    <div class="subtitle">
    <a class="menu" href="<?=site_url('admin/exam/add_subject/'.$parent['exam_id'])?>">添加考试学科</a>
    考试学科管理</div>  
    <table class="maintable" border="0" cellspacing="0" cellpadding="0">
      <tr><td class="altbg2" colspan="10" style="text-align:center;"><?=$parent['exam_name']?></td></tr>
      <tr class="altbg1">
        <td width="50">ID</td>
        <td width="80">学科</td>
        <td width="80">年级</td>
        <td width="80">类型</td>
        <td width="120">录入时间</td>
        <td width="200">操作</td>
      </tr>
      <?php if($list):?>
      <?php foreach($list as $k => $val):?>
      <tr>
        <td><?=$val['exam_id']?></td>
        <td><?=$val['subject']?></td> 
        <td><?=$val['grade_name']?></td>
        <td><?=$val['class_name']?></td>   
        <td><?=$val['addtime']?></td> 
        <td>
          <a href="<?=site_url('admin/exam/edit_subject/'.$val['exam_id'])?>">编辑</a>
          <a href="<?=site_url('admin/paper/index/'.$val['exam_id'])?>">试卷列表</a>
          <a href="<?=site_url('admin/exam/delete/'.$val['exam_id'])?>" onclick="return confirm('您确定要删除么？');">删除</a>
          [
          <?php if($k):?>
          <a href="<?=site_url('admin/exam/edit_index/'.$val['exam_id'].'/forward')?>">向上移</a>
          <?php else:?>
          <font style="color:#ccc">向上移</font>
          <?php endif;?>

          <?php if($k < count($list)-1):?>
          <a href="<?=site_url('admin/exam/edit_index/'.$val['exam_id'].'/backward')?>">向下移</a>
          <?php else:?>
          <font style="color:#ccc">向下移</font>
          <?php endif;?>
          ]
        </td>
      </tr>
      <?php endforeach; ?>
      <tr class="altbg1">
        <td colspan="2">
        </td>
        <td colspan="7" style="text-align:right"><?=$pagination?></td>
      </tr>
      <?php else: ?>
      <tr>
        <td colspan="9">暂无记录！</td>
      </tr>
      <?php endif; ?>
    </table>
  </div>
</div>
<?php $this->load->view('common/footer');?>