<?php $this->load->view('common/header', array('load_dialog_css' => true));?>
<div id="body">
  <div class="space">
    <div class="subtitle">
    <?php if (!in_array($parent['exam_id'], $demo_exams)) {?>
        <!-- 外部考试可以导入学生考试成绩 -->
        <?php if ($parent['exam_ticket_maprule'] && $parent['max_end_time']['end_time'] <= time()){?>
        <a class="menu ajax_loader" href="###" ajax="<?=site_url('admin/place_student/import/'.$parent['exam_id'])?>">成绩导入</a>
        <?php }?>
        <a class="menu" href="<?=site_url('admin/teacher_student/index/'.$parent['exam_id'])?>">师生关联管理</a>
        <a class="menu" href="<?=site_url('admin/exam_place/add/'.$parent['exam_id'])?>">添加考场</a>
    <?php } ?>
    考场管理</div>
    <table class="maintable" border="0" cellspacing="0" cellpadding="0">
      <tr><td class="altbg2" colspan="10" style="text-align:center;"><?=$parent['exam_name']?></td></tr>
      <tr class="altbg1">
        <td width="30">ID</td>
        <td width="150">场次名称</td>
        <?php /*?><td width="50">场次</td><?php */?>
        <td width="150">学校</td>
        <td width="150">班级</td>
        <td width="100">考场地址</td>
        <td width="120">考场IP</td>
        <td width="140">时间</td>
        <td width="50">人数</td>
        <td width="200">操作</td>
      </tr>
      <?php if($list):?>
      <?php foreach($list as $val):?>
      <tr>
        <td><?=$val['place_id']?></td>
        <td><?=$val['place_name']?></td>
        <?php /*?><td><?=$val['place_index']?></td><?php */?>
        <td><?=$val['school_name']?></td>
        <td><?=$val['schcls_name']?></td>
        <td><?=$val['address']?></td>
        <td><?=str_replace(",", " ", $val['ip'])?></td>
        <td><?=$val['start_time']?><br/> - <br/><?=$val['end_time']?></td>
        <td><?=$val['student_num']?></td>
        <td>
              <?php if ($priv_manage) {?>
                  <a href="<?=site_url('admin/exam_place/edit/'.$val['place_id'])?>">编辑</a>
                  <?php if (!$val['has_relate_info']) {?>
                  <a href="<?=site_url('admin/exam_place/delete/'.$val['place_id'])?>" onclick='return confirm("您确定要删除该场次吗？");'>删除</a>
                  <?php } else {?>
                  <font style="color:#999;text-decoration:line-through;" title="该考场有关联的其他信息,因此无法删除">删除</font>
                  <?php } ?>
              <?php } ?>

              <?php if (!in_array($val['exam_pid'], $demo_exams)) {?>
                  <a href="<?=site_url('admin/place_subject/index/' . $val['exam_pid'] . '/' .$val['place_id'])?>">学科</a>
                  <a href="<?=site_url('admin/place_student/index/'.$val['place_id'])?>">考生</a>
                  <a href="<?=site_url('admin/place_invigilator/index/'.$val['place_id'])?>">监考</a>
              <?php }?>

              <a href="###" class="ajax_loader" ajax="<?=site_url('admin/exam_student_result/index/?exam_pid='.$val['exam_pid'] . '&place_id=' . $val['place_id'])?>">考生成绩</a>
              <?php if ($priv_manage && !in_array($val['exam_pid'],$demo_exams)) {?>
                   <br/>
                   <?php if ($has_preview_manage) {?>
                     <a href="<?=site_url('admin/exam_paper/index/'.$val['exam_pid'] . "/" .$val['place_id'])?>">试卷打印</a>
                  <?php }?>
                  <a href="<?=site_url('admin/exam_place/check_status/'.$val['place_id'])?>" style="color:red;">一键检查配置</a>
                  <?php if ($is_super_user 
                      && $parent['exam_ticket_maprule'] 
                      && strtotime($val['end_time']) > time()) {?>
                  <br/>
                  <a href="<?=site_url('admin/exam_place/init_place_student/'.$val['place_id'])?>" style="color:red;">一键初始化</a>
                  <?php }?>
              <?php } ?>
        </td>
      </tr>
      <?php endforeach; ?>
      <tr class="altbg1">
        <td colspan="2"></td>
        <td colspan="8" style="text-align:right"><?=$pagination?></td>
      </tr>
      <?php else: ?>
      <tr>
        <td colspan="8">暂无记录！</td>
      </tr>
      <?php endif; ?>
    </table>
  </div>
</div>
<?php $this->load->view('common/footer', array('load_dialog_js' => true));?>
