<?php
/**
 * 后台管理->素质相关管理->学习风格管理
 */
$this->load->view('common/header');?>
<script language="javascript">
function check_form(form) {                      
    if (checkbox_check('learnstyle_ids[]')) {
        return confirm('确定要删除么？');
    }
    
    return false;
} 

</script>

<div id="body">
  <form name="frm_list" action="<?=site_url('admin/learn_style/remove')?>" method="GET" onsubmit="return check_form(this)">
  <div class="space">
    <div class="subtitle">
    <?php if ($priv_edit) {?>
    <a class="menu" href="<?=site_url('admin/learn_style/edit')?>">添加内化过程</a>
    <?php }?>
            学习风格管理
   </div>  
    <table class="maintable" border="0" cellspacing="0" cellpadding="0">
      <tr class="altbg1">
        <td width="2%">删?</td>
        <td width="5%">ID</td>
        <td width="10%">内化过程</td>
        <td width="60%">说明</td>
        <td width="10%">操作</td>
      </tr>
      <?php if($list):?>
      <?php foreach($list as $val):?>
      <tr>
        <td><input type="checkbox" name="learnstyle_ids[]" value="<?=$val['learnstyle_id']?>"></td>
        <td><?=$val['learnstyle_id']?></td>
        <td><?=$val['knowledge_name']?></td>
        <td><?=$val['learnstyle_explain']?></td>
        <td>
          <?php if ($priv_edit) {?>
          <a href="<?=site_url('admin/learn_style/edit/'.$val['learnstyle_id'])?>">编辑</a>
          <?php } ?>
          <?php if ($priv_attr_manage) {?>
          <a href="<?=site_url('admin/learn_style/attribute_list/'.$val['learnstyle_id'])?>">学习风格</a>
          <?php }?>
          <?php if ($priv_delete) {?>
          <a href="<?=site_url('admin/learn_style/remove/'.$val['learnstyle_id'])?>" onclick="return confirm('确定要删除么？');"><?php if ($val['learnstyle_flag'] == -1) {?>彻底<?php }?>删除</a>
          <?php } ?>
        </td>
      </tr>
      <?php endforeach; ?>
      <tr class="altbg1">
        <td colspan="2"><button type="button" class="btn2" onclick="checkbox_checked('learnstyle_ids[]');">全选</button></td>
        <td colspan="7" style="text-align:right">
          <?=$pagination?>
        </td>
      </tr>
      <?php else: ?>
      <tr>
        <td colspan="8">暂无记录！</td>
      </tr>
      <?php endif; ?>
    </table>
    <?php if ($priv_delete) {?>
    <center><input type="submit" value=" 批量删除 " class="btn" /></center>
    <?php }?>
  </div>
  </form>
</div>

<?php $this->load->view('common/footer');?>
