<?php if ($clstd_contrast_group_type['contrast_group_type']) {?>
    <h5 class="cls_row title_level_2"><?=$g_sort?>.<?=$c_sort?><?=$module_name?></h5>
    <?php $contrast_group_type = $clstd_contrast_group_type['contrast_group_type'];?>
    <?php $tr_name = array('相同信息提取方式', '本班本次考试', '本班上次考试');?>
    
    <?php foreach ($contrast_group_type as $keys => $item) {?>
        <?php foreach ($item as $key => $value) {?>
        <?php $width = 80 / count($value)?>
            <? if ($key !== 2) { ?>
            <table class="cls_row cls_table indent_25 <?php if($key === 0){ echo 'table_header';} ?>">
            <? } ?>
               	<tr>
               	    <th width="20%"><?php echo $tr_name[$key];?></th>
               	    <?php foreach ($value as $k => $val) {?>
               	        <?php if ($key > 0) {?>
        		   		 <td width="<?=$width?>%" <?php if ($key == 1 && $val != $item[2][$k]) {?>style="position:relative"<?php }?>>
        		   		 <?php echo $val;?>%
        		   		 <?php if ($key == 1 && is_numeric($val) && $val != $item[2][$k]) {?>
        		   		     <div class="<?php if ($val > $item[2][$k]){?>cls_sort cls_up<?php } elseif ($val < $item[2][$k]) {?>cls_sort cls_down<?php }?>"></div>
        		   		 <?php }?>
        		   		 </td>
        		   		 <?php } else {?>
        		   		 <th width="<?=$width?>%"><?php echo $val;?></th>
        		   		 <?php }?>
        		   	<?php }?>
               	</tr>
            <? if ($key !== 1) { ?>
            </table>
            <? } ?>
        <?php }?>
        <?php if (!$keys) {?><p class="cls_row">&nbsp;</p><?php }?>
    <?php }?>
    
    <p class="mokuai-text cls_row font12" style="padding-left:25px">注：表中数据为得分率对比。</p>
    
    <?php
        $clstd_group_type = array(); 
        if (isset($clstd_contrast_group_type['new_group_type']))
        {
            $clstd_group_type = $clstd_contrast_group_type['new_group_type'];
        }
    ?>
    
    <?php if (!empty($clstd_group_type['data'])) {?>
    		<table class="mb10 cls_row table_header indent_25" id="table_contrast_clstd_gt_c">
	        <tr>
	        	<th width="25%">新的信息提取方式</th>
	        	<?php foreach ($clstd_group_type['fields'] as $val) {?>
	        	<th width="25%"><?=$val?></th>
	        	<?php }?>
	        </tr>
	    </table>
	        
		<?php $auto_key  = 0;?>
	    <?php foreach ($clstd_group_type['data'] as $key => $item) {?>
	    	<?php $auto_key++;?>
	        <table class=" cls_row cls_table indent_25" <?php if (!$no_paging) {?>ref_title_id="table_contrast_clstd_gt_c"<?php }?>>
	        	<tr <?php echo $auto_key%2==0 ? 'class="bgc"' : '';?>>
		            <th width="25%"><?=$key?></th>
		            <?php ?>
		            <?php foreach ($item as $k => $val) {?>
                    <td width="25%" <?if ($k == 0 && $val != end($item)) {?>style="color:<?=$val > end($item) ? 'green' : 'red'?>"<?php }?>><?=$val?></td>
                    <?php }?>
		        </tr>
	        </table>
	    <?php } ?>
    <?php } ?>
<?php }?>
