<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<meta http-equiv="x-ua-compatible" content="ie=7" />
<?php static_css(array('admin.css','treeview.css'));?>
<?php static_global(array('js/jquery/jquery.js','js/jquery/plugin/treeview1.5.js'));?>
<script type="text/javascript">
	$(document).ready(function(){
        $("#left_menu").treeview();
    });
</script>
</head>
<body>
<div class="tvborder">
<ul id="left_menu" class="filetree">
    <?php echo $showmenu;?>
</ul>
</div>
</body>
</html>