<?php
/**
 * 后台管理->考试相关管理->教师关联学生
 */
$this->load->view('common/header');?>
<?php static_global('js/flexigrid/css/flexigrid.css', 'css'); ?>
<?php static_global('js/flexigrid/js/flexigrid.js'); ?>

<script language="javascript">
$(function(){
    fnInitGrid('#id_grid');
});
</script>
<div id="body">
  <div class="space">
    <div class="subtitle">
    <a class="menu" href="<?=site_url('admin/teacher_student/import/'. $exam['exam_id'])?>">导入</a>
    <a class="menu" href="javascript:void(0)" onclick="fnShowDialog('id_qry_dlg')">查询</a>
    师生关联管理</div>  
    <table class="cls_table" border="0" cellspacing="0" cellpadding="0" id="id_grid">
      <tr class="cls_title">
        <td width="200">学生姓名</td>
        <td width="200">学科</td>
        <td width="200">学科教师</td>
      </tr>
      <?php if($list):?>
      <?php foreach($list as $val):?>
      <tr>
        <td><?=$val['last_name'].$val['first_name']?></td>
        <td><?=$subject[$val['tstu_subjectid']]?></td>
        <td><?=$val['ct_name']?></td>
      </tr>
      <?php endforeach; ?>
      <tr>
        <td colspan="8" style="text-align:right"><?=$pagination?></td>
      </tr>
      <?php else: ?>
      <tr>
        <td colspan="8">暂无记录！</td>
      </tr>
      <?php endif; ?>
    </table>
  </div>
</div>

<div id="id_qry_dlg" style="display:none">
<div class="cls_title">搜索信息</div>
  <form method="get" name="search_form" action="?">
    <div class="space" style="margin:5px; width:400px;">
        <table class="maintable" border="0" cellspacing="0" cellpadding="0">
            <tr>
                <td class="altbg1">教师姓名</td>
                <td>
                <input type="text" name="ct_name" value="<?=$search['ct_name']?>"/>
                </td>
            </tr>
            <tr>
                <td class="altbg1">学生姓名</td>
                <td>
                <input type="text" name="stu_name" value="<?=$search['stu_name']?>"/>
                </td>
            </tr>  
            <tr>
                <td class="altbg1">学科</td>
                <td>
                  <select name="subject_id" id="subject_id">
                    <option value="0">--请选择--</option>
                    <?php foreach($subject as $key => $val): ?>
                    <option value="<?=$key?>"<?=$key==$search['subject_id']?' selected="selected" ':''?>><?=$val?></option>
                    <?php endforeach; ?>
                  </select>  
                </td>
            </tr>
        </table>
        <center><input type="submit" value=" 搜索 " class="btn" /> <input type="button" value="重置 " class="btn" onclick="window.location.href='<?php echo site_url('admin/teacher_student') . "/index/{$exam['exam_id']}";?>'"/></center>
    </div>
  </form>
</div>
</div>


<?php $this->load->view('common/footer');?>
