<script type='text/javascript' src='/js/third_party/MathJax/MathJax.js?config=TeX-MML-AM_HTMLorMML&locale=zh-hans'></script>
<script type='text/x-mathjax-config'>
MathJax.Hub.Config({
    showMathMenu: true,
    showMathMenuMSIE: true,
    tex2jax: { inlineMath: [['$','$'],['\\(','\\)']] },
    MathMenu: {showLocale: false},
    menuSettings: {
        zoom: "Hover",        //  when to do MathZoom
        CTRL: false,         //    require CTRL for MathZoom?
        ALT: false,          //    require Alt or Option?
        CMD: false,          //    require CMD?
        Shift: false,        //    require Shift?
        zscale: "200%",      //  the scaling factor for MathZoom
        font: "Auto",        //  what font HTML-CSS should use
        context: "MathJax",  //  or "Browser" for pass-through to browser menu
        mpContext: false,    //  true means pass menu events to MathPlayer in IE
        mpMouse: false,      //  true means pass mouse events to MathPlayer in IE
        texHints: true       //  include class names for TeXAtom elements
    }
});
</script>
