<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title><?=C('webconfig/site_name')?>管理中心</title>
<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<meta http-equiv="x-ua-compatible" content="ie=7" />
<?php static_css('login.css');?>
<?php if($url_forward):?>
<script type="text/javascript">
window.onload = function() {
    setTimeout(do_location, <?=$redirect_time?>);
}

function do_location() {
    document.location.href = '<?=$url_forward?>';
}
</script>
<?php endif;?>
</head>
<body>
<div id="body">
    <center>
    <table cellspacing="0" cellpadding="0" align="center" style="border: 1px solid #CCCCCC;background:#FFF;width:600px;height:150px;margin:50px 0">
        <tr><td align="center"><center><?=$message?> <?php if($url_forward):?><br /><br /><a href="<?=$url_forward?>">如果您的浏览器没有自动跳转，请点击这里。</a><?php endif;?></center></td></tr>
    </table>
    </center>
</div>
</body>
</html>