<!-- 版权说明 -->
<style>
.cls_copyright {
	font-family: '\5fae\8f6f\96c5\9ed1',"Microsoft YaHei";
}
</style>
<div class="cls_footer clearfix">
    <div class="cls_footer_pos">
        <div class="cls_copyright">&copy; <?php echo date('Y');?> <?=C('company_shortname')?><i class="cls_copyright_tm"></i> <span class="cls_copyright_main">保留所有权利</span>&nbsp;&nbsp;<?=C('version') ?></div>
    </div>
</div>
