<?php echo $this->load->view('common/header.phtml', array('render_simple' => true, 'page_title' => '哦哦~，出错了'));?>
<style>
body{background:#fff;}
*{padding:0;margin:0;}
.cls_notice{
    margin: 100px auto 0;
    padding: 50px;
    background-color: #ffc;
    border: 1px solid #dedede; 
	font-size:14px;
	font-family: "微软雅黑";
	text-align: center;
	overflow: hidden;
}
h1{
	font-size:16px;
	margin-bottom:10px;
}
.cls_copyright{
    text-align: center;
    margin-top: 20px;
}
.cls_notice_pos{
    width: 750px;
    margin: 0 auto;
}
.cls_notice_ico{
    background: url("/source/images/zeming/exam/notice.png") no-repeat;
    _background:none;
    _filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(enabled=true,src='/source/images/zeming/exam/notice.png',sizingMethod='scale');
    width: 146px;
    height: 130px;
    margin-right: 30px;
}
.fl_l {
	display: inline-block;
	float: left;
	padding-top: 30px;
}
.cls_copyright{
    text-align: center;
    margin-top: 20px;
	position: relative;
}
.cls_copyright_main {
    margin-left: 16px;
}
.cls_copyright_tm{
    font-size: 10px;
    position: absolute;
    font-style: normal;
    font-family:tahoma;
}
</style>
<?php if($url_forward):?>
<script type="text/javascript">
window.onload = function() {
    setTimeout(do_location, <?=$redirect_time?>);
}

function do_location() {
    document.location.href = '<?=$url_forward?>';
}
</script>
<?php endif;?>
</head>
<body>
<div class="cls_notice">
	<div class="cls_notice_pos">
		<i class="cls_notice_ico fl_l"></i>
		<div class="fl_l">
		    <h1><?=$message?> </h1>
		    <?php if($url_forward):?>
		    <div>
			 	<a href="<?=$url_forward?>">如果您的浏览器没有自动跳转，请点击这里。</a>
		    </div>
		    <?php endif;?>
	    </div>
    </div>
</div>
<?php echo $this->load->view('common/copyright');?>
</body>
</html>
