<?php $this->load->view('common/header');?>
<script language="javascript">
function check_form(form) {                      
    if (checkbox_check('ids[]')) {
        return confirm('确定要删除么？');
    }
    return false;
} 

</script>

<div id="body">
  <form name="frm_list" action="<?=site_url('admin/subject_category/delete_batch')?>" method="POST" onsubmit="return check_form(this)">
  <div class="space">
    <div class="subtitle"><a class="menu" href="<?=site_url('admin/subject_category/add')?>">添加方法策略分类</a>方法策略管理</div>  
    <table class="maintable" border="0" cellspacing="0" cellpadding="0">
      <tr class="altbg1">
        <td width="5%">删?</td>
        <td width="15%">ID</td>
        <td>方法策略分类名称</td>
        <td>关联学科</td>
        <td width="35%">操作</td>
      </tr>
      <?php if($list):?>
      <?php foreach($list as $val):?>
      <tr>
        <td><?php if (!$val['has_relate_info']) {?><input type="checkbox" name="ids[]" value="<?=$val['id']?>"><?php } ?></td>
        <td><?=$val['id']?></td>
        <td><?=$val['name']?></td>
        <td><?=$val['subject']?></td>
        <td>
          <?php if ($priv_manage) {?>
          <a href="<?=site_url('admin/subject_category/edit/'.$val['id'])?>">编辑</a>
          <?php } ?>
          <?php if ($priv_delete) {?>
          <?php if (!$val['has_relate_info']) {?>
          <a href="<?=site_url('admin/subject_category/delete/'.$val['id'])?>" onclick="return confirm('确定要删除么？');">删除</a>
          <?php } else {?>
          <font color="#999" title="该方法策略分类有关联的方法策略，无法删除">删除</font>
          <?php } ?>
          <?php } ?>
          
          <a href="<?=site_url('admin/method_tactic/index/'.$val['id'])?>">方法策略</a>
        </td>
      </tr>
      <?php endforeach; ?>
      <tr class="altbg1">
        <td colspan="2"><button type="button" class="btn2" onclick="checkbox_checked('ids[]');">全选</button></td>
        <td colspan="3" style="text-align:right"><!--<?=$pagination?>--></td>
      </tr>
      <?php else: ?>
      <tr>
        <td colspan="5">暂无记录！</td>
      </tr>
      <?php endif; ?>
    </table>
    <?php if ($priv_delete) {?>
    <center><input type="submit" name="dosubmit" value=" 批量删除 " class="btn" /></center>
    <?php } ?>
  </div>
  </form>

</div>
<?php $this->load->view('common/footer');?>