<?php $this->load->view('common/header');?>
<script language="javascript">
function check_form(form) {
    if (checkbox_check('ids[]')) {
        var op = $('#batch_op').val();
        if (op == '') {
            alert('请选择操作类型');
            return false;
        } else {
            if ( ! confirm('确定要执行该操作么？')) {
                return false;
            }
        }
        var action = $('#batch_op').find('option[value='+op+']').attr('op');
        form.action = action;
        return true;
    }
    return false;
}

function isPlusInteger(str){
	var patrn=/^([+]?)(\d+)$/;
	return patrn.test(str);	
}

function apply(){
	var page_size = $("#page_size").val();
	
	if (!isPlusInteger(page_size) || page_size==0){
		alert("格式错误，请输入大于0的整数");
		return false;	
	}
	
	var place_id = $("#place_id").val();
	var href = "<?=site_url('admin/place_student/add/manual/"+place_id+"/"+page_size+"')?>";
	
	$('#search_form').attr('action', href).submit();
}
</script>
<div id="body">
  <div class="space">
    <form name="frm_list" id="add_form" action="<?=site_url('admin/place_paper/insert')?>" method="POST" onsubmit="return check_form(this)">
    <input id="place_id" type="hidden" name="place_id" value="<?=$place['place_id']?>" />
    <div class="subtitle">
      <a class="menu" href="<?=site_url('admin/place_student/index/'.$place['place_id'])?>">考生列表</a>
      添加考场学生
    </div>
    <table class="maintable" border="0" cellspacing="0" cellpadding="0">
<tr>
        <td colspan="10" class="altbg2" style="text-align: center;">
          考试：<a href="<?=site_url('admin/exam_place/index/'.$place['exam_id'])?>"><?=$place['exam_name']?></a>
          --->
          场次：<?=$place['place_name']?> 
          考试地点：<?=$place['address']?>
        </td>
      </tr>
      <tr class="altbg1">
        <td width="70">ID</td>
        <td width="100">姓名</td>
        <td width="80">性别</td>
        <td width="200">Email</td>
        <td width="150">准考证</td>
        <td width="250">学校</td>
        <td>操作</td>
      </tr>
      <?php if($list):?>
      <?php foreach($list as $val):?>
      <tr>
        <td><input type="checkbox" name="ids[]" value="<?=$val['uid']?>" /><?=$val['uid']?></td>
        <td><?=$val['last_name'].$val['first_name']?></td>
        <td><?=$val['sex']==1?'男':'女'?></td>
        <td><?=$val['email']?></td>
        <td><?=$val['exam_ticket']?></td>
        <td><?=$val['school_name']?></td>
        <td>
          <a href="<?=site_url('admin/student/preview/'.$val['uid'])?>" target="_blank">详细信息</a>    
        </td>
      </tr>
      <?php endforeach; ?>
      <?php else: ?>
      <tr>
        <td colspan="10">该学校暂无学生 或 该学校的学生均已分配考场, <font color="blue">您可以搜索并 添加其他学校的学生！</font></td>
      </tr>
      <?php endif; ?>
      <?php if(!empty($pagination)):?>
      <tr class="altbg1">
        <td colspan="2">
          <button type="button" class="btn2" onclick="checkbox_checked('ids[]');">全选</button>
          <select name="batch_op" id="batch_op">
           <option value="">-选择操作-</option>
           <option value="delete" op="<?=site_url('admin/place_student/insert')?>">添加考生</option>
          </select>
        </td>
        <td colspan="2">
        每页显示条数:<input id="page_size" style="width:30px" type="text" name="page_sizw" value="<?php echo $page_size?>"/>
        &nbsp;&nbsp;<a id="apply" href="javascript:void(0);" onclick="apply();">应用</a>
        </td>
        <td colspan="9" style="text-align:right"><?=$pagination?></td>
      </tr>
      <?php endif;?>
    </table>
    <center><input type="submit" name="dosubmit" value=" 提交操作 " class="btn" /></center>
    <input type="hidden" id="select_school_id" name="school_id" value="<?php echo $school['school_id'];?>"/>
    </form>
  </div>
  
  <div class="space">
    <form method="post" id="search_form" name="search_form" action="#">
    	<input type="hidden" class="hidden_school_id" name="school_id" value="<?php echo $school['school_id'];?>"/>
        <div class="space">
            <div class="subtitle">搜索</div>
            <table class="maintable" border="0" cellspacing="0" cellpadding="0">
                <tr>
                    <td class="altbg1" width="6%">学校：</td>
                    <td>
                        <input type="text" value="<?php echo $school['school_name'];?>" class="txtbox" readonly="readonly" id="select_school" style="width:400px;height:40px;"/>       
                    </td>
                </tr>
                <tr>
                    <td class="altbg1" width="6%">姓名：</td>
                    <td>
                        <textarea class="txtbox" name="student_name" rows="8"><?=$student_name?></textarea> 
                        <span>每行一个学生姓名</span>    
                    </td>
                </tr>
            </table>
            <center><input type="submit" value=" 搜索学生 " class="btn" /></center>
        </div>
    </form>
    <input type="hidden" id="hidden_province" value="<?php echo $school['province'];?>"/>
    <input type="hidden" id="hidden_city" value="<?php echo $school['city'];?>"/>
    <input type="hidden" id="hidden_area" value="<?php echo $school['area'];?>"/>
    <input type="hidden" id="hidden_grade_period" value="<?php echo $school['grade_period'];?>"/>
    </div>
</div>
<?php $this->load->view('school/ajax_select_school.phtml');?>
<?php $this->load->view('common/footer');?>