<?php $this->load->view('common/header');?>

<div id="body">
  <form name="frm_import" id="frm_import" method="POST" action="<?=site_url('admin/place_student/import_save_hierarchy');?>" enctype="multipart/form-data">
    <input type="hidden" name="place_id" value="<?php echo $place_id;?>" />
    <input type="hidden" name="exam_id" value="<?php echo $exam_id;?>" />
    <div class="space">
        <div class="subtitle">学生分数更新</div>
        <table class="maintable" border="0" cellspacing="0" cellpadding="0">
		<tr>
                <td class="altbg1">请选择学科</td>
                <td>
              <select name="subject_id" id="subject_id">
                        <?php if (count($place_subjects) >= 1): ?>
                            <?php foreach ($place_subjects as $key => $value): ?>
                                <option value="<?php echo $value['subject_id'] ?>" ><?php echo $subjects[$value['subject_id']]; ?></option>
                            <?php endforeach ?>
                        <?php else: ?>
                            <option>--暂无考试学科--</option>
                        <?php endif ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td class="altbg1">请选择文件</td>
                <td>
                    <input type="file" name="file" class="txtbox" />
                    <?php if (isset($error)): ?><span style="color:red;display: inline-block;"><?php echo $error; ?></span><?php endif ?>
                </td>
            </tr>
            <tr>
                <td class="altbg1">上传说明</td>
                <td style="padding:10px;">
                    <p>1.支持Excel 2003、Excel 2007、Excel 2010、Excel 2013 版本</p>
                    <p>2.最大文件上传尺寸为10Mb</p>
                    <p>3.准考证号，学生姓名不能为空</p>
                    <p>4.导入时如果当前行发生错误，将跳过当前行继续导入</p>
                    <p>5.重复导入时，如果已经存在结果，将覆盖之前的结果</p>
                </td>
            </tr>
        </table>
        <center>
            <input type="submit" value=" 提交 " class="btn" />
            <input type="button" name="back" value=" 返回 " onclick="history.go(-1);" class="btn" />
        </center>
    </div>
  </form>

</div>
<?php $this->load->view('common/footer');?>