<?php $this->load->view('common/header');?>
<?php static_global('css/third_party/zebra_dialog/flat/zebra_dialog.css', 'css');?>
<?php static_global('js/third_party/zebra_dialog.js');?>
<script language="javascript">
function check_form(form) {
    if (checkbox_check('ids[]')) {
        var op = $('#batch_op').val();
        if (op == '') {
            alert('请选择操作类型');
            return false;
        } else {
            if ( ! confirm('确定要执行该操作么？')) {
                return false;
            }
        }
        var action = $('#batch_op').find('option[value='+op+']').attr('op');
        form.action = action;
        return true;
    }
    return false;
}

</script>
<div id="body">
  <div class="space">
    <form name="frm_list" action="<?=site_url('admin/place_student/batch_delete')?>" method="POST" onsubmit="return check_form(this)">
    <input type="hidden" name="place_id" value="<?=$place['place_id']?>" />
    <div class="subtitle">
      <?php if ($priv_manage) {?>
      <?php if (!$place['no_start']) {?>
           <a class="menu" href="###" style="color:#999;text-decoration:line-through;" title="该考场正在考试或已结束，无法做此操作">手动添加</a>
	  <?php } else {?>
	      <a class="menu" href="<?=site_url('admin/place_student/add/manual/'.$place['place_id'])?>">手动添加</a>
	  <?php } ?>


	  <?php if (!$place['no_start']) {?>
	       <a class="menu" href="###" style="color:#999;text-decoration:line-through;" title="该考场正在考试或已结束，无法做此操作">导入学生</a>
	  <?php } else {?>
	       <a class="menu" href="<?=site_url('admin/place_student/import_student/'.$place['place_id'])?>">导入学生</a>
	  <?php }?>

      <?php /*?><a class="menu" href="<?=site_url('admin/place_student/add/auto/'.$place['place_id'])?>">自动添加</a><?php */?>
      <?php } ?>
      场次考生列表
    </div>
    <table class="maintable" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td colspan="10" class="altbg2" style="text-align: center;">
          考试：<a href="<?=site_url('admin/exam_place/index/'.$place['exam_id'])?>"><?=$place['exam_name']?></a>
          --->
          场次：<?=$place['place_name']?>
          考试地点：<?=$place['address']?>
        </td>
      </tr>
      <tr class="altbg1">
        <td width="70">UID</td>
        <td width="100">姓名</td>
        <td width="80">性别</td>
        <td width="200">Email</td>
        <td width="150">准考证</td>
        <td>学校</td>
        <td width="280">操作</td>
      </tr>
      <?php if($list):?>
      <?php foreach($list as $val):?>
      <tr>
        <td><?php if ($priv_manage) {?><input type="checkbox" name="ids[]" value="<?=$val['id']?>" /><?php } ?><?=$val['uid']?></td>
        <td><?=$val['last_name'].$val['first_name']?></td>
        <td><?=$val['sex']==1?'男':'女'?></td>
        <td><?=$val['email']?></td>
        <td><?=$val['exam_ticket']?></td>
        <td><?=$val['school_name']?></td>
        <td>
          <a href="<?=site_url('admin/student/preview/'.$val['uid'])?>" target="_blank">详细信息</a>

         <a href="###" i_name="<?php echo $val['last_name']?> <?=$val['first_name'];?>" class="out_student" rel="<?php echo $val['exam_ticket'];?>">踢出/恢复学生</a>

        </td>
      </tr>
      <?php endforeach; ?>
      <?php else: ?>
      <tr>
        <td colspan="10">暂无记录！</td>
      </tr>
      <?php endif; ?>
      <?php if($pagination):?>
      <tr class="altbg1">
        <td colspan="4">
          <?php if ($priv_manage) {?>
          <button type="button" class="btn2" onclick="checkbox_checked('ids[]');">全选</button>
          <?php if ($place['no_start']) {?>
          <select name="batch_op" id="batch_op">
           <option value="">-选择操作-</option>
           <option value="delete" op="<?=site_url('admin/place_student/batch_delete')?>">批量删除</option>
          </select>
          <?php } else {?>
          <!--
          <select name="batch_op" id="batch_op" style="color:#999;text-decoration:line-through;">
             <option value="">该考场正在考试或已结束，无法做此操作</option>
          </select>
          -->
          <?php } ?>
          <?php } ?>
          每页显示条数:<input id="page_size" style="width:30px" type="text" name="page_size" value="<?php echo $page_size;?>"/>
        <input type="button" value="应用" onclick="window.location.href='<?=site_url('/admin/place_student/index/'.$place_id)?>/'+$('#page_size').val();">
        </td>
        <td colspan="9" style="text-align:right"><?=$pagination?></td>
      </tr>
      <?php endif;?>
    </table>
    <center><input type="submit" name="dosubmit" value=" 提交操作 " class="btn" />    &nbsp;&nbsp;
    <input type="button" name="back" value=" 返回 " onclick="history.go(-1);" class="btn" /></center>
    </form>
  </div>
</div>

 <form method="get" name="search_form" id="search_form" action="<?=site_url('admin/place_student/index/'.$place_id)?>">
    <div class="space">
        <div class="subtitle">搜索考生</div>
        <table class="maintable" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td class="altbg1">姓/名</td>
                <td><input type="text" name="keyword" value="<?php echo $search['keyword'];?>" id="keyword" class="txtbox" /></td>
            </tr>


            <tr>
                <td class="altbg1">考生准考证号</td>
                <td><input type="text" name="ticket" value="<?php echo $search['ticket'];?>" id="txt_ticket" class="txtbox" /></td>
            </tr>
                <td style="text-align:center" class="altbg1" colspan="2">
                    <input type="submit" value=" 搜索 " class="btn" />
                    <input type="button" value=" 重置" class="btn"
                        onclick="window.location.href='<?=site_url('/admin/place_student/index/' .$place_id)?>' "/>
                </td>
            </tr>
        </table>
    </div>
  </form>
<?php $this->load->view('common/footer');?>
<script type="text/javascript">
  $(document).ready(function () {
      //重置密码
      $('a.out_student').unbind('click').bind('click', function () {
            var uid = $(this).attr('rel'),
            	uname = $(this).attr('i_name'),
            	place_id =<?=$place['place_id']?>,
            	exam_id =<?=$place['exam_id']?>
            	;
			new $.Zebra_Dialog('', {
			    'source':  {'ajax': '<?php echo site_url('admin/place_student/load_out_student');?>/?uid=' + uid +'&place_id='+place_id+'&exam_id='+exam_id},
			    'type':     '',
			    width: 890,
			    'title': '踢出/恢复 学生 (<font color="red" style="font-size:16px;">' + uname + '</font>) 的状态'
			});

			setTimeout(function () {
				$('div.ZebraDialog_Buttons').hide();
			}, 500);
	});

	window.close_dialog = function () {$('.ZebraDialog_Button_0').click();}
});
</script>
