<?php if ($ts_new_method_tactic['data'] || $ts_new_method_tactic['qualified_method_tactic']) {?>
    <h5 class="cls_row title_level_2"><?=$g_sort?>.<?=$c_sort?><?=$module_name?></h5>
    <?php if ($ts_new_method_tactic['qualified_method_tactic']) {?>
    <p class="cls_row indent_25">经过前一阶段的教学，您所任教的学生在方法策略—“<?=implode("“、”" ,$ts_new_method_tactic['qualified_method_tactic'])?>” 上掌握情况较好。</p>
    <?php }?>
    <p class="cls_row">&nbsp;</p>
    <?php if ($ts_new_method_tactic['data']) {?>
        <p class="cls_row indent_25">以下方法策略的掌握情况有待提高：</p>
        <p class="cls_row">&nbsp;</p>
        <?php foreach ($ts_new_method_tactic['data'] as $item) {?>
            <table class="cls_row cls_table indent_25">
            <?php foreach ($item as $key => $val) {?>
                <tr>
                <?php 
                $width = 100 / count($val);
                $kk = count($val) - 2;
                ?>
                <?php foreach ($val as $k => $v) {?>
                <<?=($key == 0 || $k == 0) ? "th" : 'td'?> width="<?=$width?>%">
                <?php if (is_numeric($v)) {?>
                <span style="<?php if ($v < 0) {?>color:red;<?} else if ($k < $kk && $v > end($val)){?>color:green;<?php }?> font-weight: unset;"><?=abs(intval($v))?>%</span>
                <?php } else {?>
                <?=$v?>
                <?php }?>
                </<?=($key == 0 || $k == 0) ? "th" : 'td'?>>
                <?php }?>
                </tr>
            <?php } ?>
            </table>
            <p class="cls_row">&nbsp;</p>
        <?php } ?>
    <?php } else {?>
    <p class="cls_row indent_25">所有方法策略都表现较好。</p>
    <?php }?>
<?php } ?>