<?php $this->load->view('common/header');?>

<?php
    // 根路径
    echo "<script>root_url = '".rtrim(site_url(''),'/')."';</script>";

    static_js(array('common/schools.js'));

    static_global(array('js/jquery/plugin/validate/jquery.validate.min.js',
    					'js/jquery/plugin/tiper.min.js',
    					'js/jquery/plugin/jquery.form.js',
    					'js/jquery/plugin/jquery.charsleft.min.js',
    					'js/datepicker/wdatepicker.js'
    ));
?>

<style>
.score_rank_td div{
	line-height:30px;
	height:30px;
	padding-top:6px;
}
</style>
<?php static_global('css/third_party/zebra_dialog/flat/zebra_dialog.css', 'css');?>
<?php static_global('js/third_party/zebra_dialog.js');?>

<div id="body">

  <input type="hidden" name="act" value="<?=$act?>" />
  <div class="space">
    <div class="subtitle">学生帐号管理</div>
    <div>
    
       
    </div>
    <div>    
    <table class="maintable" id="table_basic" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td colspan="2" class="altbg2" style="text-align: center;">
            帐号信息
        </td>
      </tr>
    
      <tr>
        <td class="altbg1">帐号余额</td>
        <td>                      
          <?=$student['account']?><?=C('virtual_currency')['name']?>     <a class="reset_account" href="#" rel="<?=$student['uid']?>"
          i_name="<?php echo $student['last_name']?> <?=$student['first_name'];?>"><span style="color:red;">修改余额</span></a> 
        </td>
        </tr>
      <tr>
        <td class="altbg1">帐号状态</td>        
        <td>
        	<input type="radio" <?php if(!$student['account_status']):?>checked<?php endif;?> name="status" id="status_0" value="0" class="status" rel="<?=$student['uid']?>"><label for="status_0">启用</label> 
        	<input  type="radio" <?php if($student['account_status']):?>checked<?php endif;?> name="status" id="status_1" value="1" class="status" rel="<?=$student['uid']?>"><label for="status_1">冻结</label>
		</td>
      </tr>

  
      <tr>
        <td colspan="2" class="altbg2" style="text-align: center;">
          帐号交易记录
        </td>
      </tr>
            <tr>
        <td colspan="4" class="altbg2" style="text-align: center;">
         <form method="get" name="search_form" action="<?=site_url('/admin/account/edit/'.$uid)?>">
        <table class="maintable" border="0" cellspacing="0" cellpadding="0">
            <tr>
               
              
               <td style="text-align: center;">
                            <input type="text" id="begin_time" name="begin_time" class="txtbox3" value="<?=$search['begin_time']?>" onclick="WdatePicker({dateFmt:'yyyy-MM-dd',startDate:'%y-%M-%d %h:%m:%s'});"> -
                            <input type="text" id="end_time" name="end_time" class="txtbox3" value="<?=$search['end_time']?>" onclick="WdatePicker({dateFmt:'yyyy-MM-dd',startDate:'%y-%M-%d %h:%m:%s'});">
                       <input type="submit" value=" 查询 " class="btn" /> </td>
                <td></td>
            </tr>  
        </table>
        
          <table class="maintable" border="0" cellspacing="0" cellpadding="0">
      <tr class="altbg1">
        <td width="10%">交易类型</td>
        <td width="10%">充值时间</td>
        <td width="10%">充值金额</td>
        <td width="10%">充值后余额</td>
        <td width="10%">充值管理员</td>
        <td width="20%">备注</td>
      </tr>
      <?php if($list):?>
      <?php $trade_type = C('trade_type')?>
      <?php foreach($list as $val):?>
      <tr>
        <td><?=$trade_type[$val['tr_type']]?></td>
        <td><?=date('Y-m-d H:i', $val['tr_createtime'])?></td> 
        <td><?=$val['tr_trade_amount']?></td> 
        <td><?=$val['tr_money']?></td> 
        <td><?=$val['admin_user']?></td> 
        <td><?=$val['tr_comment']?></td> 
      </tr>
      <?php endforeach; ?>
      <tr class="altbg1">
        <td colspan="6" style="text-align:right"><?=$pagination?></td>
      </tr>
      <?php else: ?>
      <tr>
        <td colspan="8">暂无记录！</td>
      </tr>
      <?php endif; ?>
    </table>
      
      </td>
      </tr>
     <tr>
      	<td colspan="4">
      		 <!-- 下一步 -->
		     <center> 
			    <input type="button" name="" value=" 返回 " onclick="window.history.go(-1)" class="btn next_step" />
			  </center> 
      	</td>
      </tr>
    </table>
    </div>
    <div id="auto_school_list"></div>
  </div>

</div>
<script type="text/javascript">
  $(document).ready(function () {
	  $('.status').unbind('click').bind('click', function () {

		if (!confirm('确定执行此操作吗？'))
		{
			return false;
		}
		
		var $thiz = $(this);
	
		var status = $thiz.val();
		var hidden_uid = $thiz.attr('rel');
		
		$.ajax({
			url : '<?php echo site_url('admin/account/reset_account_status/'); ?>',
			dataType : 'json',
			type : 'post',
			data : {
				uid:hidden_uid,
				status : status,
				
			},
			timeout : 5000,
			error: function (a, b, c) {
				//alert(a + b + c);
				$thiz.removeAttr('disabled');
				$font_form.removeClass('success').addClass('error').html('帐号修改失败.').hide().fadeIn()	;
			},
			success : function (response) {
				var code = response.code,
					msg	= response.msg,
					data = response.data;

				window.location.reload();
				return true;
			}
		});
		});

	  
      //充值
      $('a.reset_account').unbind('click').bind('click', function () {
            var uid = $(this).attr('rel'),
            	uname = $(this).attr('i_name');
			new $.Zebra_Dialog('', {
			    'source':  {'ajax': '<?php echo site_url('admin/account/load_reset_account');?>/' + uid},
			    'type':     '',
			    width: 890,
			    'title': '帐号充值（学生： <font color="red" style="font-size:16px;">' + uname + '</font>）'
			});

			setTimeout(function () {
				$('div.ZebraDialog_Buttons').hide();
			}, 500);
	});
    	
	window.close_dialog = function () {$('.ZebraDialog_Button_0').click();}
});
</script>
<?php $this->load->view('common/footer');?>
