<?php $this->load->view('common/header');?>
<?php static_global('js/flexigrid/css/flexigrid.css', 'css'); ?>
<?php static_global('js/flexigrid/js/flexigrid.js'); ?>

<?php 
    static_js(array('common/address.js', 
                    'common/region.js'));
?>

<?php $this->load->view('recycle/recycle.phtml');?>

<?php static_global('css/third_party/zebra_dialog/flat/zebra_dialog.css', 'css');?>
<?php static_global('js/third_party/zebra_dialog.js');?>

<script language="javascript">
$(function(){
    fnInitGrid("#id_grid");
});
function check_form(form) {                      
    if (checkbox_check('ids[]')) {
        var op = $('#batch_op').val();
        if (op == '') {
            alert('请选择操作类型');
            return false;
        } else {
            if (confirm('您确定要执行该操作么？')) {
                var action = $('#batch_op').find('option[value='+op+']').attr('op');
                form.action = action;
                return true;
            }
        }
    }
    return false;
}

function set_schools() {
   // if (grade_id == 0) return;
	var area=$('#selAreas option:selected').val();
	if (area == 0) return;
	   var school_id=<?php echo $search['school_id'];?>;
    $.post(
        '<?=site_url('admin/common/schools')?>',
        {grade_id:$('#grade_id option:selected').val(),province:$('#selProvinces option:selected').val(),city:$('#selCities option:selected').val(),area:$('#selAreas option:selected').val()},
        function(data){
            var str = '<option value="0">--请选择学校--</option>';
            for (var i=0; i<data.length; i++) {
                if(data[i]['school_id']==school_id){
                    str += '<option value="'+data[i]['school_id']+'" selected>'+data[i]['school_name']+'</option>';
                } 
                else{
              str += '<option value="'+data[i]['school_id']+'" >'+data[i]['school_name']+'</option>'; 
                }
                               
            }
            $('#school_id').html(str);
        },
        'json'
    );
}



function set_schools_onload() {
	   // if (grade_id == 0) return;

	var area=$('#selAreas option:selected').val();
	if (area == 0) return;
	   
		   var school_id=<?php echo $search['school_id'];?>;
		   
	    $.post(
	        '<?=site_url('admin/common/schools')?>',
	        {grade_id:$('#grade_id option:selected').val(),province:$('#selProvinces option:selected').val(),city:$('#selCities option:selected').val(),area:$('#selAreas option:selected').val()},
	        function(data){
	            var str = '<option value="0">--请选择学校--</option>';
	            for (var i=0; i<data.length; i++) {
	                if(data[i]['school_id']==school_id){
	                    str += '<option value="'+data[i]['school_id']+'" selected>'+data[i]['school_name']+'</option>';
	                } 
	                else{
	              str += '<option value="'+data[i]['school_id']+'" >'+data[i]['school_name']+'</option>'; 
	                }
	                               
	            }
	            $('#school_id').html(str);
	        },
	        'json'
	    );
	}


function test() {
var str = '<option value="0">--请选择区县--</option>';
$('#selAreas').html(str);
}
$(document).ready(function(){
	set_schools_onload();
});


</script>


<div id="body">
  <form name="frm_cpuser_list" action="<?=site_url('admin/student/batch_delete')?>" method="POST" onsubmit="return check_form(this)">
  <div class="space">
    <div class="subtitle">
      <?php if($mode=='trash'):?>
      学生回收站
      <?php else:?>
      <?php if ($priv_manage) {?>
      
学生帐号管理
      <?php } ?>
      <?php endif;?>

     <span style="float:right">
<a href="javascript:void(0)" onclick="fnShowDialog('id_qry_dlg')">查询</a>
&nbsp;&nbsp;
</span>
    </div>  
    <table id="id_grid" border="0" cellspacing="0" cellpadding="0">
      <tr class="cls_title">
        <td width="60">ID</td>
        <td width="60">学生姓名</td>
        <td width="160">学校</td>
        <td width="100">联系方式</td>
        <td width="40">状态</td>
        <td width="160">帐号余额</td>
        <td width="240">操作</td>
      </tr>
      <?php if($list):?>
      <?php foreach($list as $val):?>
      <tr>
        <td><?=$val['uid']?></td>
        <td><?=$val['last_name']?><?=$val['first_name']?></td>        
        <td><?=$val['school_name']?></td>
        <td><?=$val['mobile']?></td> 
         <td><? if($val['account_status']) echo '禁用';else echo '正常';?></td> 
         <td><?=$val['account']?><?=C('virtual_currency')['fullname']?></td> 
        <td>          
          
          <?php if ($priv_manage) {?>
          <a href="<?=site_url('admin/account/edit/'.$val['uid'])?>">帐号管理</a>
          <a href="<?=site_url('admin/account/transaction/'.$val['uid'])?>">查看交易明细</a>
        
          <?php } ?>
        </td>
      </tr>

      <?php endforeach; ?>
      <tr class="altbg1">


        <td colspan="7" style="text-align:right"><?=$pagination?></td>
      </tr>
      <?php else: ?>
      <tr>
        <td colspan="7">暂无记录！</td>
      </tr>
      <?php endif; ?>
    </table>
    
  </div>
  </form>

<div id="id_qry_dlg" style="display:none">
        <div class="cls_title">搜索学生信息</div>
  <form method="get" name="search_form" action="<?=site_url('admin/account/index/')?>">
    <div class="space" style="margin:5px">
        <table class="maintable" border="0" cellspacing="0" cellpadding="0">
            <tr>
                <td class="altbg1">学生ID</td>
                <td>
                <input type="text" name="uid" value="<?=$search['uid']?>"/>
                <font color="red">*注：根据学生ID搜索时，其他条件将失效</font>
                </td>
            </tr>  
        
            <tr>
                <td class="altbg1">所属地区</td>
                <td>
                  <select name="province" id="selProvinces" onchange="region.changed(this, 2, 'selCities');set_schools();$('#selAreas').html('<option value=0>--请选择区县--</option>');">
                    <option value="0">--请选择省--</option>
                    <?php foreach($province_list as $val): ?>
                    <option value="<?=$val['region_id']?>" <?=$val['region_id']==$search['province']?' selected="selected" ':''?>><?=$val['region_name']?></option>
                    <?php endforeach; ?>
                  </select>
                  <select name="city" id="selCities" onchange="region.changed(this, 3, 'selAreas');set_schools();">
                    <option value="0">--请选择市--</option>
                    <?php foreach($city_list as $val): ?>
                    <option value="<?=$val['region_id']?>" <?=$val['region_id']==$search['city']?' selected="selected" ':''?>><?=$val['region_name']?></option>
                    <?php endforeach; ?>
                  </select>
                  <select name="area" id="selAreas" onchange="set_schools();">
                    <option value="0">--请选择区县--</option>
                    <?php foreach($area_list as $val): ?>
                    <option value="<?=$val['region_id']?>" <?=$val['region_id']==$search['area']?' selected="selected" ':''?>><?=$val['region_name']?></option>
                    <?php endforeach; ?>
                  </select>
                </td>
            </tr>
            <tr>
                <td class="altbg1">年级</td>
                <td>
                  <select name="grade_id" onchange="set_schools()" id="grade_id">
                    <option value="0">--请选择--</option>
                    <?php foreach($grades as $key => $val): ?>
                    <option value="<?=$key?>"<?=$key==$search['grade_id']?' selected="selected" ':''?>><?=$val?></option>
                    <?php endforeach; ?>
                  </select>  
                </td>
            </tr>
            <tr>
                <td class="altbg1">所在学校</td>
                <td>                      
                  <select name="school_id" id="school_id">
                    <option value="0">--请选择学校--</option>
                  </select>
                </td>
            </tr> 
            <tr>
                <td class="altbg1">学生来源</td>
                <td>                      
                  <select name="from" id="from">
                    <option value="-1">--请选择--</option>
                    <?php foreach ($from as $key => $item) {?>
                    <option value="<?=$key;?>" <?=(isset($search['from']) && $key == $search['from'] ? ' selected="selected" ':'')?>><?=$item?></option>
                    <?php }?>
                  </select>
                </td>
            </tr> 
            <tr>
                <td class="altbg1">关键字(姓/名/身份证)</td>
                <td><input type="text" name="keyword" value="<?=$search['keyword']?>" class="txtbox" /></td>
            </tr>   
          
        </table>
        <center><input type="submit" value=" 搜索 " class="btn" /> <input type="button" value="重置 " class="btn" onclick="window.location.href='<?php echo site_url('admin/account');?>'"/></center>
    </div>
  </form>
</div>
</div>
<?php $this->load->view('common/footer');?>
