<?php $this->load->view('common/header', array('load_dialog_css' => true));?>

<?php
    // 根路径
    echo "<script>root_url = '".rtrim(site_url(''),'/')."';</script>";

    static_js(array('common/schools.js'));

    static_global(array('js/jquery/plugin/validate/jquery.validate.min.js',
    					'js/jquery/plugin/tiper.min.js',
    					'js/jquery/plugin/jquery.form.js',
    					'js/jquery/plugin/jquery.charsleft.min.js',
    					'js/datepicker/wdatepicker.js'
    ));
    $vc = C('virtual_currency');
?>

<style>
.score_rank_td div{
	line-height:30px;
	height:30px;
	padding-top:6px;
}
</style><?php static_global(array('js/datepicker/wdatepicker.js','js/jquery/plugin/blockUi.js'));?>
<?php static_global('css/third_party/zebra_dialog/flat/zebra_dialog.css', 'css');?>
<?php static_global('js/third_party/zebra_dialog.js');?>

<div id="body">
 
  <div class="space">
    <div class="subtitle">交易明细(<?php echo $p_name?>)</div>
    <div>
       
    </div>
    <div>    
    <table class="maintable" id="table_basic" border="0" cellspacing="0" cellpadding="0">


   <tr>
        <td colspan="2" class="altbg2" style="text-align: center;">
          产品统计数据
        </td>
      </tr>
    
      <tr>
        <td class="altbg1">产品统计</td>
        <td>                      
        交易总次数：<?php echo $p_id_count;?>    &nbsp;&nbsp;&nbsp;&nbsp;交易总额：<?php echo $p_money_count;?><?=$vc['fullname']?>
        </td>
        </tr>
   
  

   <tr>
        <td colspan="2" class="altbg2" style="text-align: center;">
          交易明细
        </td>
      </tr>
    
            <tr>
        <td colspan="4" class="altbg2" style="text-align: center;">
      
          <table class="maintable" border="0" cellspacing="0" cellpadding="0">
      <tr class="altbg1">

        <td width="10%">交易ID</td>
    
        <td width="20%">产品名称</td>
      
        <td width="20%">产品类型</td>
        <td width="20%">测评人</td>
         <td width="20%">测评时间</td>
           <td width="20%">交易金额</td>
      </tr>
      <?php if($list):?>
      <?php foreach($list as $val):?>
      <tr>
      
        <td><?=$val['pt_id']?></td>        
        <td><?=$val['p_name']?></td>
        <td><?=$val['pc_name']?></td> 
       <td><?=$val['a_name']?></td>
       <td><?=$val['start_time']?>~<?=$val['end_time']?></td>
      
       <td><?=$val['pt_money']?><?=$vc['fullname']?></td> 
      </tr>

      <?php endforeach; ?>
      <tr class="altbg1">


        <td colspan="6" style="text-align:right"><?=$pagination?></td>
      </tr>
      <?php else: ?>
      <tr>
        <td colspan="8">暂无记录！</td>
      </tr>
      <?php endif; ?>
    </table>
      
      </td>
      </tr>
      
      
      
      
     <tr>
      	<td colspan="4">
      		 <!-- 下一步 -->
		     <center> 
			    <input type="button" name="" value=" 返回 " onclick="window.history.go(-1)" class="btn next_step" />
			  </center> 
      	</td>
      </tr>
    </table>


    
     
    </div>
    <div id="auto_school_list"></div>
  </div>
   
   <form method="get" name="search_form" action="<?=site_url('/admin/account/transactionp/'.$p_id)?>">
    <div class="space">
        <div class="subtitle">搜索产品信息</div>
        <table class="maintable" border="0" cellspacing="0" cellpadding="0">
            <tr>
                <td class="altbg1">交易时间</td>
              
               <td>
                            <input type="text" id="begin_time" name="begin_time" class="txtbox3" value="<?=$search['begin_time']?>" onclick="WdatePicker({dateFmt:'yyyy-MM-dd',startDate:'%y-%M-%d %h:%m:%s'});"> -
                            <input type="text" id="end_time" name="end_time" class="txtbox3" value="<?=$search['end_time']?>" onclick="WdatePicker({dateFmt:'yyyy-MM-dd',startDate:'%y-%M-%d %h:%m:%s'});">
                        </td>
        
            </tr>  
   
           
          
        </table>
        <center><input type="submit" value=" 搜索 " class="btn" /> <input type="button" value="重置 " class="btn" onclick="window.location.href='<?php echo site_url('admin/student') . "/account";?>'"/></center>
    </div>
  </form>
</div>

<?php $this->load->view('common/footer');?>

