<?php
    $this->load->view('common/header');
    static_js(array('third_party/layer/layer.min.js'));
?>

<div id="space">
    <div class="subtitle">
    </div>
    <div class="space">
        <table class="maintable" border="0" cellspacing="0" cellpadding="0">
            <tr class="altbg1">
                <td style="padding:15px;">
                    <?php if (count($logs) >= 1): ?>
                        <ul>
                            <?php foreach ($logs as $key => $value): ?>
                                <li>
                                    <p>
                                        <?php echo date('Y-m-d H:i:s', $value['time']); ?>&nbsp;&nbsp;
                                        <span>审核人：<?php echo $value['admin_name']; ?></span>&nbsp;&nbsp;
                                        <?php if ($value['flag'] == -1): ?>
                                            <span style="color:red;">审核未通过</span>&nbsp;&nbsp;
                                            <span><?php echo $value['comment']; ?></span>
                                        <?php else: ?>
                                            <span style="color:green;">审核通过</span>
                                        <?php endif ?>
                                    </p>
                                    <hr/>
                                </li>
                            <?php endforeach ?>
                        </ul>
                    <?php else: ?>
                        <p>暂无记录！</p>
                    <?php endif ?>
                </td>
            </tr>
        </table>
        <table class="maintable" border="0" cellspacing="0" cellpadding="0">
            <tr>
                <td style="text-align: center;color:#f00">
                    <input type="button" value=" 确定 " id="close_button" />
                </td>
            </tr>
        </table>
    </div>
</div>

<script>
    $(document).ready(function(){

        // 关闭当前窗口
        var index = parent.layer.getFrameIndex(window.name); //获取当前窗体索引
        $('#close_button').on('click', function(){
            parent.layer.close(index); //执行关闭
        });
    });
</script>

<?php $this->load->view('common/footer', array('load_dialog_js' => true));?>