<?php $this->load->view('common/header', array('load_dialog_css' => true));?>

<?php static_global(array('js/datepicker/wdatepicker.js','js/jquery/plugin/blockUi.js'));?>
<?php static_js(array('admin/question/question.js', 'admin/question/question_list.js', 'admin/exam_rule/exam_rule.js', 'third_party/layer/layer.min.js'));?>
<?php $this->load->view('recycle/recycle.phtml');?>

<script language="javascript">
    var class_ids = [<?=implode(',',$search['class_id'])?>];
    var skill_ids = [<?=implode(',',$search['skill_id'])?>];
    var knowledge_ids = [<?php echo $search['knowledge_ids'];?>];
    var method_tactic_ids = [<?php echo $search['method_tactic_ids'];?>];

    var ajax_url_class = '<?=site_url('admin/common/question_class')?>';
    var ajax_url_skill = '<?=site_url('admin/common/skill')?>';
    var ajax_url_knowledge = '<?=site_url('admin/common/knowledge')?>';
    var ajax_url_knowledge_select = '<?=site_url('admin/common/knowledge_select')?>';
    var ajax_url_knowledge_init = '<?=site_url('admin/common/knowledge_init')?>';

    var ajax_url_method_tactic = '<?=site_url('admin/common/method_tactic_all')?>';
    var ajax_url_method_tactic_select = '<?=site_url('admin/common/method_tactic_select')?>';
    var ajax_url_method_tactic_init = '<?=site_url('admin/common/method_tactic_init')?>';

    function check_form(form) {
        if (checkbox_check('ids[]')) {
            var op = $('#batch_op').val();
            if (op == '') {
                alert('请选择操作类型');
                return false;
            } else if (op == 'relate') {
                var relate_ques_id = parseInt($('#relate_ques_id').val());
                if (isNaN(relate_ques_id)) {
                    alert('请填写被关联试题ID.');
                    return false;
                }
            }
            var action = $('#batch_op').find('option[value='+op+']').attr('op');
            form.action = action;
            return true;
        }
        return false;
    }

    $(document).ready(function(){
        $('.ques_title').dblclick(function(){
            $(this).find('div').first().toggleClass('line_18');
        });

        $('.ques_handle_td').click(function(e){
            var is_hidden = true;
            $(this).find('div[class=ques_handle] > a').each(function(){
                if ($(this).css('display') == 'none')
                {
                	is_hidden = false;
                    return;
                }
            });
            
            is_hidden && $(this).find('div').first().toggleClass('line_18');
        });
        
        $('#start_grade,#end_grade').change(function(){
            //set_question_class();
            //联动类型
            set_question_class_checkbox();
        });
        $('#subject_id').change(function(){
            set_skill();
            set_knowledge_cascade(0, 'knowledge_pid');

            //联动类型
            set_question_class_checkbox();
        });
        set_question_class_checkbox();

        $('#knowledge_pid').change(function(){
            set_knowledge_cascade($(this).val(), 'knowledge_id');
        });
        $('#batch_op').change(function(){
            set_batch_option();
        });

        $('#knowledge_select').click(function(){
            knowledge_select();
        });

        // 试题类型（真题、原创）
        $('#is_original').change(function(){
            origin_toggle();
        });

        // 对已选择的知识点操作，调整隐藏项knowledge_ids的值
        $('#knowledge_list').on('click', 'input:checkbox', function(){
            var objs = $('#knowledge_list').find('input:checkbox');
            var ids = '';
            for (var i=0; i<objs.length; i++) {
                if (objs[i].checked) {
                    ids += (ids ? ',' : '') + objs[i].value;
                }
            }
            $('#knowledge_ids').val(ids);
        });

        //方法策略
        $('#method_tactic_select').click(function(){
        	method_tactic_select();
        });
        // 对已选择的方法策略操作，调整隐藏项knowledge_ids的值
        $('#method_tactic_list').on('click', 'input:checkbox', function(){
            var objs = $('#method_tactic_list').find('input:checkbox');
            var ids = '';
            for (var i=0; i<objs.length; i++) {
                if (objs[i].checked) {
                    ids += (ids ? ',' : '') + objs[i].value;
                }
            }
            $('#method_tactic_ids').val(ids);
        });

        $('#subject_id').change(function(){
        	var subject_id = $('#subject_id').val();
        	if (subject_id == 11)
        	{
        		$("#subject_id_list input[name='subject_str[]']").removeAttr('disabled');
        	    $('#subject_id_list').show();
        	}
        	else
        	{
        		$('#subject_id_list').hide();
        		$("#subject_id_list input[name='subject_str[]']").attr('disabled', 'disabled');
        	}
        });

        set_batch_option();
        init_knowledge();
        init_method_tactic();
        origin_toggle();
    });

    function origin_toggle ()
    {
        val = $('#is_original').val();
        if (val == 2)
        {
            $('#container_exam_year').show();
            $('#container_remark').show();
        }
        else
        {
            $('#container_exam_year').hide();
            $('#container_remark').hide();
        }
    }

    function set_knowledge_cascade(pid, target) {
        var subject_id = $('#subject_id').val();
        if (subject_id == '') return;
        if (pid.length == 0) {
            $('#'+target)[0].length = 1;
            return;
        }
        $.post(
            ajax_url_knowledge,
            {subject_id:subject_id, pid:pid},
            function(data){
                var target_obj = $('#'+target)[0];
                if (document.all) {
                    target_obj.fireEvent("onchange")
                } else {
                    var evt = document.createEvent("HTMLEvents");
                    evt.initEvent('change', true, true);
                    target_obj.dispatchEvent(evt)
                }

                var str = '<option value="">=请选择=</option>';
                for (var i=0; i<data.length; i++) {
                    str += '<option value="'+data[i]['id']+'">'+data[i]['knowledge_name']+'('+data[i]['ques_num']+')</option>';
                }
                $('#'+target).html(str);
            },
            'json'
        );
    }

    function set_batch_option() {
        var op = $('#batch_op').val();
        if (op == 'relate') {
            $('#batch_extend').show();
        } else {
            $('#batch_extend').hide();
        }
    }

    //年级跟类型联动
    function set_question_class_option() {
        var start_grade = $('#start_grade').val();
        var end_grade = $('#end_grade').val();
        if ( !start_grade ) return;
        $.post(
            ajax_url_class,
            {grade_id:grade_id},
            function(data){
                if (typeof(class_id) == 'undefined') class_id = 0;
                var str = '';
                for (var i=0; i<data.length; i++) {
                    var selected = js_class_id==data[i]['class_id'] ? ' selected' : '';
                    str += '<option value="'+data[i]['class_id']+'"'+selected+'>'+data[i]['class_name']+'</option>';
                }
                $('#class_id')[0].length = 1;
                $('#class_id').append(str);
            },
            'json'
        );
    }

    function set_disable(ques_id, status)
    {
    	if (!ques_id) return;

    	if (!confirm('您确定要执行操作？'))
    	{
    	    return;
    	}

    	$.getJSON('/admin/question/set_ques_status',{ques_id:ques_id,'status':status},function(data){
    	    if (data.status == true)
    	    {
    	        $('#set_ques_status_'+ques_id).attr('onclick',"set_disable("+ques_id+", "+Math.abs(status - 2)+");");
    	        $('#set_ques_status_'+ques_id).html(((status == 2) ? "解禁" : "禁用"));
    		}
    	});
    }

    function audit(ques_id) {
        if (ques_id == '') {
            alert('未选中试题！');
            return;
        };

        $.layer({
            type: 2,
            border: [0],
            title: '试题审核',
            shadeClose: true,
            closeBtn:  [0, true],
            iframe: {src : '<?=site_url("admin/question_audit/audit/")?>' + '/'+ ques_id},
            area: ['900px', '450px']
        });
    }

    function audit_log(ques_id) {
        if (ques_id == '') {
            alert('未选中试题！');
            return;
        };

        $.layer({
            type: 2,
            border: [0],
            title: '试题审核日志',
            shadeClose: true,
            closeBtn:  [0, true],
            iframe: {src : '<?=site_url("admin/question_audit/log/")?>' + '/'+ ques_id},
            area: ['900px', '450px']
        });
    }


</script>

<div id="body">
    <form name="frm_cpuser_list" action="#" method="POST" onsubmit="return check_form(this)">
        <div class="space">
            <div class="subtitle">试题审核</div>
            <table class="maintable" border="0" cellspacing="0" cellpadding="0">
                <tr class="altbg1">
                    <td width="50">&nbsp;&nbsp;ID</td>
                    <td width="400">题目（双击展开/收缩）</td>
                    <td width="60">题型</td>
                    <td width="80">审核状态</td>
                    <td width="50">学科</td>
                    <td width="140">类型</td>
                    <td width="120">年级</td>
                    <td width="120">录入时间</td>
                    <td width="80">录入人员</td>
                    <td width="195">操作（单击空白展开/收缩）</td>
                </tr>
                <?php if($list):?>
                    <?php foreach($list as $val):?>
                        <?php $q_type = '';?>
                        <tr>
                            <td><?php if ($priv_manage) {?><input type="checkbox" name="ids[]" value="<?=$val['ques_id']?>" /><?php } ?><?=$val['ques_id']?></td>
                            <td title="双击展开" class="ques_title">
                                <div class="line_18" style="width: 400px;">
                                    <?=strip_tags($val['title'])?>
                                </div>
                            </td>
                            <td>
                                <?=$val['qtype']?>
                                <?php $q_type = $val['qtype'];?>
                            </td>
                            <td>
                                <?php if ($val['check'] == 0): ?>
                                    <span style="color:blue;">未审核</span>
                                <?php elseif($val['check'] == 1): ?>
                                    <span style="color:green;">审核通过</span>
                                <?php else: ?>
                                    <span style="color:red;">审核未通过</span>
                                <?php endif ?>
                            </td>
                            <td><?=$val['subject_name']?></td>
                            <td><?=$val['class_name']?></td>
                            <td>[<?=$val['start_grade']?>] - [<?=$val['end_grade']?>]</td>
                            <td><?=$val['addtime']?></td>
                            <td><?=$val['realname']?></td>
                            <td class="ques_handle_td">
                                <div class="ques_handle line_18">
                                    <a href="<?=site_url('admin/question/preview/'.$val['ques_id'])?>" target="_blank">预览</a>
                                    <a href="javascript:void(0);" onclick="javascript:audit(<?php echo $val['ques_id']; ?>);">审核</a>
                                    <a href="javascript:void(0);" onclick="javascript:audit_log(<?php echo $val['ques_id']; ?>);">查看审核日志</a>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php else: ?>
                    <tr>
                        <td colspan="10">暂无记录！</td>
                    </tr>
                <?php endif; ?>
                <tr class="altbg1">
                    <td colspan="3">
                        <button type="button" class="btn2" onclick="checkbox_checked('ids[]');">全选</button>
                        <select name="batch_op" id="batch_op">
                            <option value="">-选择操作-</option>
                            <option value="shenhe" op="<?=site_url('admin/question_audit/batch_audit')?>">批量审核通过</option>
                            <option value="unshenhe" op="<?=site_url('admin/question_audit/batch_unaudit')?>">取消审核通过</option>
                        </select>
                        <span style="display:none;" id="batch_extend">关联试题ID:<input type="text" class="txtbox5" name="relate_ques_id" id="relate_ques_id" /></span>
                    </td>
                    <td colspan="7" style="text-align:right"><?=$pagination?></td>
                </tr>
            </table>
            <center><input type="submit" name="dosubmit" value=" 提交操作 " class="btn" /></center>
        </div>
    </form>
</div>

<script>
  function test()
  {
       	 var start_grade = parseInt($('#start_grade').val());
 	    var end_grade = parseInt($('#end_grade').val());
  	    var begin_time =$('#begin_time').val();
    	  var end_time = $('#end_time').val();
    	  var start_difficulty =$('#start_difficulty').val();
    	  var end_difficulty = $('#end_difficulty').val();

 	    if (isNaN(start_grade) || isNaN(end_grade) || start_grade > end_grade) {
 	        alert('年级段选择错误，开始年级不能大于结束年级！');
 	        return false;
            }

 	   else if(!duibi(begin_time, end_time))
            {
                alert('开始时间不能大于结束时间！');
 	        return false;
            }


  	  else if (isNaN(start_difficulty )  ) {

	       alert('难度系数填写错误，不是数字！');
	       return false;
        }

   	 else if (isNaN(end_difficulty  ) ) {

	       alert('难度系数填写错误，不是数字！');
	       return false;
        }

   	 else  if ( Number(start_difficulty)>100||Number(start_difficulty)<0)
	    {
	    	   alert('难易度填写错误，范围应为[0-100]！');
	       return false;
	    }

   	 else  if ( Number(end_difficulty)>100||Number(end_difficulty)<0)
	    {
	    	   alert('难易度填写错误，范围应为[0-100]！');
	       return false;
	    }

   	 else  if (start_difficulty!=''&&Number(start_difficulty)  > Number(end_difficulty)&&end_difficulty!='' ) {

	 	       alert('难度系数填写错误，开始区间大于结束区间！');
	 	       return false;
	         }
   	 else
   	 {

                $('#search_form').submit();
   	 }


 }

  function duibi(a, b) {
	    var arr = a.split("-");
	    var starttime = new Date(arr[0], arr[1], arr[2]);
	    var starttimes = starttime.getTime();

	    var arrs = b.split("-");
	    var lktime = new Date(arrs[0], arrs[1], arrs[2]);
	    var lktimes = lktime.getTime();

	    if (starttimes > lktimes) {

	       // alert('开始时间大于离开时间，请检查');
	        return false;
	    }
	    else
	        return true;

	}	
</script>

  <div class="space">
    <form method="get" name="search_form" class="validate" id="search_form" action="<?=site_url('admin/question_audit/index/'.$mode)?>" onsubmit="return test();">
        <div class="space">
            <div class="subtitle">搜索试题</div>
            <table class="maintable" border="0" cellspacing="0" cellpadding="0">
                <tr>
                    <td class="altbg1" width="15%">试题ID</td>
                    <td>
                    	<input type="text" value="<?php echo isset($search['ques_id']) ? $search['ques_id'] : '';?>" name="ques_id"/>
                    	<font color="red">*注：根据试题ID搜索时，其他条件将失效</font>
                    </td>
                </tr>
                <tr>
                    <td class="altbg1" width="15%">管理员</td>
                    <td>
                      <select name="admin_id">
                      <option value="">=录入人员=</option>
                      <?php foreach($admin_list as $admin):?>
                      <option value="<?=$admin['admin_id']?>"<?=$search['admin_id']==$admin['admin_id']?' selected':''?>><?=$admin['admin_user']?><?=$admin['realname']?'['.$admin['realname'].']':''?></option>
                      <?php endforeach;?>
                      </select>
                    </td>
                </tr>
                <tr>
                    <td class="altbg1">录入时间</td>
                    <td>
                        <input type="text" id="begin_time" name="begin_time" class="txtbox4" value="<?=$search['begin_time']?>" onclick="WdatePicker({dateFmt:'yyyy-MM-dd',startDate:'2013-09-01'});"> -
                        <input type="text" id="end_time" name="end_time" class="txtbox4" value="<?=$search['end_time']?>" onclick="WdatePicker({dateFmt:'yyyy-MM-dd',startDate:'2013-09-01'});">
                    </td>
                </tr>
                <tr>
                    <td class="altbg1">题型</td>
                    <td>
                      <select name="qtype">
                        <option value="">-请选择-</option>
                        <?php foreach($qtypes as $k => $v):?>
                        <option value="<?=$k?>" <?=$search['type']===$k?'selected':''?>><?=$v?></option>
                        <?php endforeach;?>
                      </select>
                    </td>
                </tr>
				<tr>
                    <td class="altbg1">考试方式</td>
                    <td>
                      <select name="test_way">
                        <option value="">-请选择-</option>
                        <?php $test_way = C('test_way')?>
                        <?php foreach($test_way as $k => $v):?>
                        <option value="<?=$k?>" <?=$search['test_way'] === $k ? 'selected' : '' ?>><?=$v?></option>
                        <?php endforeach;?>
                      </select>
                    </td>
                </tr>
                <tr>
                    <td class="altbg1">审核状态</td>
                    <td>
                    <select name="check">
                        <option value="">-请选择-</option>

                        <option value="0" <?=$search['check']===0?'selected':''?>>未审</option>
                     <option value="1" <?=$search['check']===1?'selected':''?>>已审</option>
                      </select>
                    </td>
                </tr>

                <tr>
                    <td class="altbg1">标签</td>
                    <td>
                    <SELECT name="tags">
                    <option value="">-请选择-</option>
                    <?php foreach ($q_tags as $k => $q_tag) {?>
                        <?php foreach ($q_tag as $key => $item) {?>
                            <option value="<?=$k?>-<?=$key?>" <?=$search['tags']===$k.'-'.$key?'selected':''?>><?=$item?></option>
                        <?php }?>
                    <?php }?>
                    </SELECT>
                    </td>
                </tr>
                <tr>
                    <td class="altbg1">学科</td>
                    <td>
                      <select name="subject_id" id="subject_id">
                        <option value="">--请选择--</option>
                        <?php foreach($subjects as $key => $val): ?>
                        <option value="<?=$key?>"<?=$key==$search['subject_id']?' selected="selected" ':''?>><?=$val?></option>
                        <?php endforeach; ?>
                      </select>

                      <?php $subject_ids = explode(',', $search['subject_id_str']);?>
                      <span id="subject_id_list" <?if ($search['subject_id'] != 11): ?> style="display: none;" <?php endif;?>>
                          <?php foreach($all_subjects as $key => $val): ?>
                              <?php if ($key != 11):?>
                                <input type="checkbox" name="subject_str[]" value="<?=$key?>" <? echo in_array($key, $subject_ids) ? 'checked': '';?>><?=$val?>
                              <?php endif;?>
                          <?php endforeach; ?>
                      </span>
                    </td>
                </tr>
                <tr>
                    <td class="altbg1">知识点</td>
                    <td>
		             <div id="knowledge_list"></div>
		             <input type="hidden" name="knowledge_ids" id="knowledge_ids" value="<?php echo $search['knowledge_ids'];?>" />
		             <button id="knowledge_select" class="btn2" type="button">点击选择</button>
                    </td>
                </tr>
                <tr>
                    <td class="altbg1">认知过程</td>
                    <td>
                    	<div id="kp_box">
                    		<?php $search_kp = is_array($search['know_process']) ? $search['know_process'] : array();?>
			             	<?php foreach ($know_processes as $k=>$v) {?>
			             	<input type="checkbox" name="know_process[]" value="<?php echo $k;?>" id="kp_<?php echo $k;?>" <?php echo in_array($k, $search_kp) ? 'checked="checked"' : '';?>/><label for="kp_<?php echo $k;?>"><?php echo $v;?></label>
			             	<?php } ?>
                    	</div>
                    </td>
                </tr>
                <tr>
                    <td class="altbg1">方法策略：</td>
                    <td>
		             <div id="method_tactic_list"></div>
		             <input type="hidden" name="method_tactic_ids" id="method_tactic_ids" value="<?php echo $search['method_tactic_ids'];?>" />
		             <button id="method_tactic_select" class="btn2" type="button">点击选择</button>
                    </td>
                </tr>

                <tr style="display:none;">
                    <td class="altbg1">技能</td>
                    <td>
                      <span id="skill_list"></span>
                    </td>
                </tr>
                <tr>
                    <td class="altbg1">年级</td>
                    <td>
                      <select name="start_grade" id="start_grade">
                        <option value="0">--请选择--</option>
                        <?php foreach($grades as $key => $val): ?>
                        <option value="<?=$key?>"<?=$key==$search['start_grade']?' selected="selected" ':''?>><?=$val?></option>
                        <?php endforeach; ?>
                      </select>
                      -
                      <select name="end_grade" id="end_grade">
                        <option value="0">--请选择--</option>
                        <?php foreach($grades as $key => $val): ?>
                        <option value="<?=$key?>"<?=$key==$search['end_grade']?' selected="selected" ':''?>><?=$val?></option>
                        <?php endforeach; ?>
                      </select>

                    </td>
                </tr>
                <tr>
                    <td class="altbg1">题目类型（真题、原创、模拟题）</td>
                    <td>
                        <select name="is_original" id="is_original">
                            <option value="0">--请选择--</option>
                            <option value="1" <?=$search['is_original']=='1'?'selected="selected" ':''?>>原创</option>
                            <option value="2" <?=$search['is_original']=='2'?'selected="selected" ':''?>>真题</option>
                             <option value="3" <?=$search['is_original']=='3'?'selected="selected" ':''?>>模拟题</option>
                        </select>

                        <span id="container_exam_year" style="display: none;">
                            <span>&nbsp;&nbsp;&nbsp;&nbsp;</span>
                            <label for="exam_year">真题年份</label>
                            <input type="text" id="exam_year" name="exam_year" value="<?php echo $search['exam_year']; ?>">
                            <span>（选填-题目类型为真题时生效）</span>
                        </span>

                        <span id="container_remark" style="display: none;">
                            <span>&nbsp;&nbsp;&nbsp;&nbsp;</span>
                            <label for="remark">关键词（备注内检索）</label>
                            <input type="text" id="remark" name="remark" value="<?php echo $search['remark']; ?>">
                            <span>（选填-题目类型为真题时生效）</span>
                        </span>
                    </td>
                </tr>
                <tr>
                    <td class="altbg1">类型</td>
                    <td>
                    	<input type="hidden" value="<?php echo implode('_', $search['class_id']);?>" id="search_class_id"/>
                      <div id="class_list">
                        <?php /*foreach($class_list as $val):?>
                        <input type="checkbox" name="class_id[]" id="class_id<?=$val['class_id']?>" value="<?=$val['class_id']?>" <?=in_array($val['class_id'],$search['class_id'])?' checked':''?>/><label for="class_id<?=$val['class_id']?>"><?=$val['class_name']?></label>
                        <?php endforeach;*/?>
                      </div>
                      <div style="display:none;" id="hidden_class_list">
		                <?php foreach($grades as $key => $val):?>
		                <div id="grade<?=$key?>_class" <?php if(empty($relate_class[$key])):?>style="display:none;"<?php endif;?>>
			                <?php $class_list = isset($all_grade_class[$key])?$all_grade_class[$key]:array();?>
			                <?php $class_list_ids = array();?>
			                <?php foreach($class_list as $cid => $class):?>
			                <?php $class_list_ids[$cid] = $class['class_name'];?>
			                <?php if($key>=11 && in_array($cid,array(2,3))):?>
							<span class="subject_type_box">
							<?php $subject_type_ids = array();?>
			                <?php foreach(array_filter($subject_types) as $k => $v):?>
			                <?php $subject_type_ids[$k] = $v;?>
			                <?php endforeach;?>
			                <?php echo json_encode($subject_type_ids);?>
			                </span>
			                <?php endif;?>
			                <?php endforeach;?>
			                <span class="class_id_box"><?php echo json_encode($class_list_ids);?></span>
		                </div>
		                <?php endforeach;?>
                    </td>
                </tr>
                <tr>
                    <td class="altbg1">文理科:</td>
                    <td>
                      <div id="subject_type_list"></div>
                      <input type="hidden" value="<?php echo $search['subject_type'];?>" id="search_subject_type"/>
                    </td>
                </tr>
                <tr>
                    <td class="altbg1">难易度</td>
                    <td>
                        <input type="text" name="start_difficulty" id="start_difficulty" class="txtbox4" value="<?=$search['start_difficulty']?>"/> -
                        <input type="text" name="end_difficulty" id="end_difficulty" class="txtbox4" value="<?=$search['end_difficulty']?>" /> <span style="color:red">请按难易度数值区间搜索，范围为[0-100]</span>
                    </td>
                </tr>
                <tr>
                    <td class="altbg1">关键字</td>
                    <td><input type="text" name="keyword" value="<?=$search['keyword']?>" class="txtbox" /></td>
                </tr>
            </table>
            <center><input type="submit" value=" 搜索 " class="btn" /> <input type="button" value="重置 " class="btn" onclick="window.location.href='/admin/question/index/<?php echo $mode;?>'"/></center>
        </div>
    </form>
  </div>
</div>
<?php $this->load->view('common/footer', array('load_dialog_js' => true));?>