<div class="cls_footer clearfix" id="tool_bar_box">
	<div class="cls_footer_page bar_menu" id="tool_bar_menu">
        <a class="cls_footer_prv disabled visibility_hide" href="###" id="btn_prev_question" >上一题</a>
		<a class="cls_footer_next visibility_hide" href="###" id="btn_next_question">下一题</a>
    </div>
    <div class="cls_footer_bg">
		<div class="cls_footer_pos">
			<div class="cls_footer_left fl_l clearfix">
                <div class="cls_jilu fl_l" id="cheat_span" style="display:none;">本场考试你的作弊行为已经达到 <em class="cls_jilu_strong" id="cheat_count"></em>次，超过<em id="cheat_total"></em>次系统将自动提交试卷!</div>
			</div>
	      <!--   <div class="cls_ques_buttons fl_r clearfix">
	            <a href="###" id="btn_finish" class="cls_submit_btn cls_button fl_r">提交试卷</a>
	        </div> -->
		</div>
	</div>
</div>
